traefik/traefik

.gitignore, Dockerfile, Makefile, build.Dockerfile, circle.yml, configuration.go, docker.go, file_test.go, middlewares/logger.go, middlewares/routes.go, script/.validate, script/binary, script/generate, script/make.sh, script/test-integration, script/test-unit, script/validate-gofmt, traefik.go
This mainly change the ``Dockerfile`` and the ``Makefile`` and its targets to use `docker` for building. 🐧
This also updates the `circleci.yml` file to make the continuous integration to work with it.
The list of the current targets :
- `validate` (`validate-gofmt`) : validates the projects files ; for now just checking on `gofmt` but could be used with other tooling (`go vet`, `golint`, …) — probably following PRs to come :wink:.
- `binary` : build `traefik` using `gox` and but the result in `dist` (just like now, but using volumes).
- `test` (`test-unit`, `test-integration`) : run tests (there is none for now but will be :stuck_out_tongue_closed_eyes:).
- `image` : make the final image that will be deployed on the docker hub (with just the binary in it).
This looks like :
```bash
λ make …
```
=> Refactor toolchain

Makefile, script/validate-govet
Adds a `go tool vet` check on changed files for `make validate`. It's possible to run the targe `make validate-govet` to check for it.
Because of `go-logging`, I had to put a `-printf=false` :sweat_smile:.
Rationale (taken from docker/docker#14756) : 
> - We want to improve code quality
> - We need objective filters on quality to help us discriminate bad pull requests
This is one of them :stuck_out_tongue:.
=> Add govet target and script

docs/index.md, marathon.go, providerTemplates/marathon-prefix.tmpl
Marathon label traefik.prefixes can be used to specify what
prefixes to use.
New example marathon-prefix.tmpl to take advantage of this new
mechanism.
=> Add getPrefixes to get string array of PathPrefixes

consul.go, docker.go, docs/index.md, file.go, marathon.go, provider.go, templates/configuration.tmpl, traefik.go, web.go
Configurations are now cached from each provider separately so that
we can merge them together when one provider has changed config.
The Web module also returns full config info through the HTML call,
but REST API is working on a separate web configuration that is
sent in just like any other.
=> Adding caching and merging of configurations

circle.yml
The idea is to have releases tagged with v1.0.alpha.$CIRCLE_BUILD_NUM.
=> Corrects release management with build number in tags

configuration.go, docs/index.md, integration/marathon_test.go, traefik.go, traefik.sample.toml
Closes #48.
Closes #46.
> This PR adds a backend throttle duration. It resolves #46
Backends throttle duration is the minimum duration between 2 events from providers before applying a new configuration. It avoids unnecessary reloads if multiples events are sent in a short amount of time.
=> Carry Add backend throttle duration #48

.dockerignore
Ignoring `vendor/` and `dist/`
=> Add .dockerignore to lightweight build context

configuration.go, docker.go, docs/index.md, marathon.go, static/app/sections/providers/frontend-monitor/frontend-monitor.html, templates/docker.tmpl, templates/marathon.tmpl, traefik.go, traefik.sample.toml
This PR:
- adds `passHostHeader` in frontend configuration
- adds `passHostHeader` in UI
- adds `traefik.frontend.passHostHeader` label in docker and marathon
Fixes #86
=> Add passhostheader in frontends configuration 

traefik.go, version.go
Just because.. why not ? I would even think we should move it to a `version` package. @emilevauge WDYT ?
=> Move version info in its own file.

README.md, build.Dockerfile, generate.go
This mades the build impossible offline (as when doing a go generate it was trying to go get something)
Probably needs some documentation updates too (like do a `go get …`).. But I found it kinda bad to not be able to build `traefik` while offline, in the train :sweat_smile:.
=> Remove go get go-bindata from generate.go

configuration.go, file_test.go, generate.go, provider.go, provider/boltdb.go, provider/consul.go, provider/docker.go, provider/etcd.go, provider/file.go, provider/file_test.go, provider/kv.go, provider/marathon.go, provider/provider.go, provider/zk.go, script/binary, script/crossbinary, script/test-unit, traefik.go, types/types.go, web.go
Split a bit traefik into package. The idea behind this refactor is to start move inter-dependencies away and do some DRY or SRP or both :stuck_out_tongue_closed_eyes: . 🐙
- Adds a `provider` package, with providers except `web.go`
- Adds a `types` package with common struct.
- Move `gen.go` to an `autogen` package
The 2nd commit is *optional*, but will be needed at some point :see_no_evil:.
To test heavily as it might breaks things that are not covered yet :smile_cat:.
🐸
=> Refactor traefik with package

middlewares/cbreaker.go, middlewares/logger.go, middlewares/routes.go, middlewares/websocket.go, provider/boltdb.go, provider/consul.go, provider/docker.go, provider/etcd.go, provider/file.go, provider/kv.go, provider/marathon.go, provider/provider.go, provider/zk.go, types/types.go
Following #88, *lint* some packages : `middlewares`, `provider` and `types` 🐼. 
This will ease the soon to be coming `script/validate-golint` script 😇.
🐸
=> Linting some packages

.gitignore, integration/basic_test.go, integration/consul_test.go, integration/file_test.go, integration/fixtures/simple_web.toml, integration/integration_test.go, integration/marathon_test.go
- Use `defer` to kill traefik process (to fix the still running traefik binaries if the given tests is failing before the kill)
- Add `TestWithWebConfig`
- Add *.test to gitignore to ignore the test binaries generated by go.
After each *next* pass on the integration suite, I'll move the definition (`DockerSuite`, etc..) in their own files :wink:.
=> Updates and additions on some integration tests

Makefile, integration/docker_test.go, integration/integration_test.go, provider/docker.go
Using Docker provider, you can specify `traefik.frontend.rule` and `traefik.frontend.value` labels. If they are not both provided, there is a default behavior. On the current master, if they are not defined, the container is filtered (and thus the default behavior is broken).
- Fixes this behavior.
- Add integration tests for it, and some helper function for DockerSuite.
- For now, using the `swarm` image as test image (and download nginx too, why not ?) to test against. `swarm` because it's small :stuck_out_tongue_closed_eyes:.
=> Fix docker labels (frontend.*) non-presence

provider/docker.go
Refs #98 - TOML doesn't allow `[` and `]` to be used in table names. This replaces them with empty strings.
=> Replace [ and ] in frontend names

integration/file_test.go, provider/boltdb.go, provider/consul.go, provider/docker.go, provider/docker_test.go, provider/etcd.go, provider/file.go, provider/kv.go, provider/kv_test.go, provider/marathon.go, provider/marathon_test.go, provider/provider.go, provider/provider_test.go, provider/zk.go
Another refactor for the *great and good* 🐙.
- Add a `baseProvider` struct with common stuff.
- Refactor docker, kv(s) and marathon providers (spliting into small pieces), easier to unit-test.
- Add unit tests for…
```bash
+ go test -cover -coverprofile=cover.out ./provider
ok      github.com/emilevauge/traefik/provider  0.005s  coverage: 58.3% of statements
```
This is a big one :wink:.
Fixes #115
🐸
=> Refactor providers and add unit tests

glide.yaml, provider/marathon.go, provider/marathon_test.go
Newer version of go-marathon allows to get only `running` tasks.
https://github.com/gambol99/go-marathon/pull/82
Fixes #81
=> Add filter task by running status in marathon

templates/marathon.tmpl
Fixes #136, the included Marathon tmpl should convert multiple slashes in Marathon app names to dashes when creating route/backend.
Otherwise, apps such as /hello/world will cause Traefic to fail on startup.
```
time="2015-12-04T22:20:08Z" level=debug msg="Creating frontend frontend-helloworld"
time="2015-12-04T22:20:08Z" level=debug msg="Creating route route-host-helloworld Host: helloworld.mydomain"
time="2015-12-04T22:20:08Z" level=debug msg="Creating backend "
time="2015-12-04T22:20:08Z" level=error msg="Error loading new configuration, aborted Backend not found: "
```
After this change:
```
time="2015-12-05T18:07:36Z" level=debug msg="Creating frontend frontend-hello-world" 
time="2015-12-05T18:07:36Z" level=debug msg="Creating route route-host-hello-world Host:helloworld.mydomain" …
```
=> Marathon tmpl converts slashes in Marathon app names to dashes

docs/index.md, provider/marathon.go, provider/marathon_test.go, templates/marathon.tmpl
The "traefik.port" label value is not used when selecting which port to use. Instead, the Marathon provider always uses the first possible port.
The Marathon provider should honor the "traefik.port" label supplied by the Marathon app.  If no "traefik.port" label is specified, then the first possible port us used.
=> Marathon provider uses port from label.

docs/index.md
Traefik automatically adds it. If you specify it, it causes an error.
=> Consul config doesn't need "http://"

contrib/systemd/traefik.service
The super simple traefik service I'm using. It assumes the binary has been installed as /usr/bin/traefik
=> Add minimal systemd service file

README.md, build.Dockerfile, glide.yaml
This PR add `--quick` to `glide up`.
Fixes the issue during `glide up`:
```
[INFO] Setting version for github.com/codegangsta/inject to 33e0aa1cb7c019ccc3fbe049a8262a6403d30504.
[ERROR] Dependency /go/src/github.com/emilevauge/traefik/vendor/github.com/docker/docker/autogen/dockerversion failed to resolve: lstat /go/src/github.com/emilevauge/traefik/vendor/github.com/docker/docker/autogen/dockerversion: no such file or directory.
[ERROR] Failed to retrieve a list of dependencies: lstat /go/src/github.com/emilevauge/traefik/vendor/github.com/docker/docker/autogen/dockerversion: no such file or directory
The command '/bin/sh -c glide up' returned a non-zero code: 1
make: *** [build] Error 1
```
cc @vdemeester @ldez
=> Glide up quick

provider/provider.go
We already decided to convert all slashes to dashes for marathon deployments, now I'm updating the frontend rule value to also match that.
Currently docker and marathon providers use `getEscapedName`.
Similar effort to #137 
Before:
```
time="2016-02-03T01:01:06Z" level=info msg="Creating frontend frontend-prod-foosvc"
time="2016-02-03T01:01:06Z" level=info msg="Creating route route-host-prod-foosvc Host:prodfoosvc.docker.local"
```
After
```
time="2016-02-03T20:18:55Z" level=info msg="Creating frontend frontend-prod-foosvc"
time="2016-02-03T20:18:55Z" level=info msg="Creating route route-host-prod-foosvc Host:prod-foosvc.docker.local"
```
=> Updated getEscapedName with slash to dash instead of space

cmd.go, configuration.go, docs/index.md, traefik.sample.toml
This PR adds an option `MaxIdleConnsPerHost` to be used when `too many open files error` are encountered.
As explained here https://github.com/golang/go/issues/6785, during high loads, it seems that:
> when the number of requests/s to the proxy goes up, the small amount of bookkeeping that is required to recycle a connection (putIdleConn etc) starts taking just long enough that the next request in the pipeline gets in before a connection is idle. The Transport starts Dial:ing, adding more connections to take care of, and it explodes chaotically. I would prefer if it blocked and awaited an idle connection instead of Dial:ing at some point
Fixes #157 #127
=> Add MaxIdleConnsPerHost. Fixes too many open files error.

README.md, build.Dockerfile
This PR bump to go v1.6 and adds native HTTP2 support :)
Fixes #139
=> Bump go 1.6

.github/CONTRIBUTING.md, LICENSE.md, Makefile, README.md, build.Dockerfile, cmd.go, configuration.go, docs/index.md, integration/integration_test.go, provider/boltdb.go, provider/consul.go, provider/consul_catalog.go, provider/consul_catalog_test.go, provider/docker.go, provider/docker_test.go, provider/etcd.go, provider/file.go, provider/kv.go, provider/marathon.go, provider/marathon_test.go, provider/provider.go, provider/zk.go, script/.validate, script/deploy.sh, server.go, web.go, webui/src/index.html
This PR finalizes transfer from repo `emilevauge/traefik` to `containous/traefik`.
As I created a [company](https://containo.us) to continue to develop Traefik, I transferred the project to an organization repo.
=> Transfer emilevauge/traefik to containous/traefik

glide.yaml, provider/docker_test.go, script/deploy.sh, templates/docker.tmpl
This PR fixes docker network management using `NetworkSettings.Networks` instead of `NetworkSettings.IPAddress`.
Fixes #226
=> Fix docker network

cmd.go, docs/index.md, provider/marathon.go, traefik.sample.toml
as mentioned in https://github.com/containous/traefik/issues/210#issuecomment-190917703
From the docs here https://github.com/gambol99/go-marathon#event-stream doesn't look like anything else is needed to change across APIs
=> Use event stream API instead of event subscriptions

.gitignore, README.md, middlewares/handlerSwitcher.go, server.go
This PR refactor the way Traefik manages hot-reloads.
As it appears there are issues sometimes with [manners](https://github.com/braintree/manners/issues/13), we now simply hot-switch the `http.ServeMux` of the server. This is way more simpler and safer.
Manners is still used for graceful shutdown of Traefik.
Fixes #236
//cc @gbjk
=> Refactor hot reload

provider/kv.go, provider/kv_test.go
- libkv.WatchTree returns a channel whose messages represent changes
to the watched tree. In situations where libkv cannot read from the
underlying store, libkv will close the provided channel.
- This PR handles this edge case and fixes #238.
=> Support libkv.WatchTree chan errors:

docs/index.md, script/deploy.sh
This PR maintains the old docker repo `emilevauge/traefik` up to date.
=> Fix push to old docker repo emilevauge/traefik

server.go
This PR fixes the regex used to redirect entrypoints.
The old regex was not working when there was no port in the URL (ie http://test.com/test).
Fixes #249
=> fixes redirect bug en port 80

.travis.yml
This PR bump to beta version, and now uses [semver](semver.org) : `v1.0.0-beta.$TRAVIS_BUILD_NUMBER`
=> Bump to beta, using semver

Makefile, script/binary, script/test-integration, script/test-unit
Using the VERBOSE environment variable, tests and binary compilation are ran in verbose mode (using -v), but by default there are more quiet :angel: 🐶.
🐸
=> Add a verbose mode to builds

glide.lock, glide.yaml, integration/consul_catalog_test.go, integration/consul_test.go, integration/docker_test.go, integration/etcd_test.go, integration/file_test.go, integration/integration_test.go, integration/marathon_test.go
This changes the integration tests to use [libkermit](https://github.com/vdemeester/libkermit). This is a start, `libkermit` will get more feature in over time and `traefik` will benefit from it first 😇.
- It simplifies writing integration tests.
- It uses `docker/engine` API, and this is the first step to migrate traefik to use `engine-api` as well — will come soon.
An open question (completely related to `libkermit`) is : should `compose.Project` embedded `docker.Project` and thus let it have all the `docker.Project` methods ? (this would mean, no need for the `project` attribute on `DockerSuite` and `ConsulCatalogSuite` for example).
🐸
=> Libkermit integration 😇

README.md, configuration.go, docs/index.md, glide.lock, glide.yaml, server.go, traefik.sample.toml
This PR adds retry request in case of network error.
You can enable retry in your global config file adding `[retry]`.
The default config set a maximum storage in memory by request of 2 Mo and a maximum attempts of `(number servers in backend) -1`.
Your can override this:
```
#
#
[retry]
#
#
attempts = 3
#
#
maxMem = 3
```
Fixes #210 
=> add retries request

docs/index.md, glide.lock, glide.yaml, integration/docker_test.go, integration/fixtures/file/simple.toml, integration/fixtures/https/https_sni.toml, middlewares/stripPrefix.go, provider/consul_catalog.go, provider/consul_catalog_test.go, provider/docker.go, provider/docker_test.go, provider/marathon.go, provider/marathon_test.go, provider/provider.go, rules.go, script/deploy.sh, server.go, templates/consul_catalog.tmpl, templates/docker.tmpl, templates/kv.tmpl, templates/marathon.tmpl, tests/whoami.json, traefik.sample.toml, types/types.go, webui/src/app/sections/providers/frontend-monitor/frontend-monitor.html, webui/src/index.html
⚠ **This PR contains breaking changes** ⚠
This PR refactors frontends rules.
In order to simplify configuration, and also to fix headers issue #257, frontends rules are now configured:
Before:
```
[frontends]
[frontends.frontend1]
backend = "backend1"
[frontends.frontend1.routes.test_1]
rule = "Host"
value = "test.localhost"
```
Now:
```
[frontends]
[frontends.frontend1]
backend = "backend1"
[frontends.frontend1.routes.test_1]
rule = "Host:test.localhost"
```
You can define different types of rule:
- `rule = "Host:test.localhost"`
- `rule = "Path:/test"`
- `rule = "PathStrip:/test"`
- `rule = "PathStrip:/test"`
- `rule = "PathPrefix:/test"`
- `rule = "PathPrefixStrip:/test"`
- `rule = "Methods: GET, PUT"`
- `rule = "Headers: User-Agent, bat/0.1.0, Accept, application/json"`
- `rule = …
=> Refactor frontends rules

acme/acme.go, provider/consul_catalog.go, provider/docker.go, provider/file.go, provider/kv.go, provider/kv_test.go, provider/marathon.go, safe/safe.go, script/deploy.sh, server.go
This PR fixes an issue with Let's Encrypt certificate renew process.
It also adds a recovering mechanism for some goroutines:
```
func GoSafe(goroutine func()) {
go func() {
defer recoverGoroutine()
goroutine()
}()
}
func recoverGoroutine() {
if err := recover(); err != nil {
log.Println(err)
debug.PrintStack()
}
}
```
```
safe.GoSafe(func() {
// my safe go routine
})
```
Fixes #269 
=> Fix acme renew panic

glide.lock, glide.yaml, integration/consul_catalog_test.go
Using `.Container(…)`, it's way easier to get the container from a project's service 🐙.
🐸
=> Update libkermit again for compose enhancements

.travis.yml, README.md, script/deploy.sh
This PR fixes the bug in CI: https://travis-ci.org/containous/traefik/builds/120948445
```
openssl aes-256-cbc -K $encrypted_27087ae1f4db_key -iv $encrypted_27087ae1f4db_iv -in .travis/traefik.id_rsa.enc -out ~/.ssh/traefik.id_rsa -d
iv undefined
```
=> Fix openssl travis

.dockerignore
`*.test` files are generated by `go test`, do not include them into the build context. It will lighter a bit the build context. 🐭.
🐸
=> Add **/*.test to .dockerignore

glide.lock, glide.yaml, provider/docker.go, provider/docker_test.go
The docker provider now uses `docker/engine-api` and `vdemeester/docker-events` instead of fsouza-dockerclient 🐳. 
Compared to *before*, this filters the events by container (the daemon will only send `container` events), thus should receive a little less events.
Fixes #284
/cc @emilevauge for how to run the benchmarks :angel: 
🐸
=> Migrate docker provider traefik to engine-api

provider/consul_catalog_test.go, templates/consul_catalog.tmpl
see https://github.com/containous/traefik/issues/275
**Caution**: Breaking (see issue)
=> feat(consul-catalog-provider): + setting unique backend name + backendd redirecting to internal container ip

templates/kv.tmpl
This PR fixes KV store template when frontend name contain periods.
Fixes #295
=> Fix period in frontend name in KV store

glide.lock, glide.yaml
Update glide files to use most recent version of containous/oxy
Related to https://github.com/containous/oxy/pull/1
=> Update glide files to use most recent version of containous/oxy

glide.lock, glide.yaml
In order to fix the TLS client authentication I have updated the libkv
dependency. Now the connection to secured etcd and consuld should work
properly.
Signed-off-by: Thomas Boerger <thomas@webhippie.de>
=> Updated libkv dependency

README.md, examples/k8s.ingress.yaml, provider/k8s/client.go, provider/kubernetes.go, provider/kubernetes_test.go
This PR fixes Kubernetes watch SSL, and Kubernetes empty schema.
The new schema rule is:
- if `port.Name` is not empty, use it as protocol
- else if `port` = 443, schema is `https` 
- else schema is `http`
Fixes #332 
Fixes #333 
=> Fix Kubernetes watch SSL & empty schema

provider/consul_catalog.go, provider/consul_catalog_test.go, templates/consul_catalog.tmpl
#294 
Summary: In consul, Service.Address is optional. If equal to nil, then use the Node.Address
=> feat(consul-provider): If service ip is nil then use node ip

acme/acme.go
fixes warnings and gives generated certs an A rating on ssl labs
Fixes #345
=> #345: bundle intermediate certificates

build.Dockerfile, script/crossbinary
=> Go back to standard golang image

cmd.go, docs/toml.md, provider/k8s/client.go, provider/kubernetes.go, provider/kubernetes_test.go, traefik.sample.toml
If the flag kubernetes.namespaces is set...
Then we only select ingresses from that/those namespace(s)
This allows multiple instances of traefik to
independently load balance for each namespace.
This could be for logical or security reasons.
Addresses #336
=> Adds option to namespace k8s ingresses

provider/consul_catalog.go, provider/consul_catalog_test.go
Another fun thing consul lets you do is use spaces in your tags. This
means when including tags in backend name it's possible to generate
invalid names.
=> Replace whitespace in tags in consul_catalog

generate.go
Ensure that static folder exists so `go generate` doesn't fail.
=> Create static folder on first generate

.travis.yml, Makefile, build.Dockerfile, glide.lock, glide.yaml, integration/docker_test.go, integration/integration_test.go, script/deploy.sh, script/test-integration
Update `engine-api`, `libcompose` and related dependencies (including `libkermit`), to fix issues with docker v1.9.1 and lower 🐮.
Should fix #360
/cc @emilevauge @gdippolito 
🐸
=> Update docker dependencies to fix issues

provider/kubernetes.go, provider/kubernetes_test.go
By design k8s ingress is only designed to ballance services from within
the namespace of the ingress.
This is disscuessed a little in
https://github.com/kubernetes/kubernetes/issues/17088.
For now traefik should only reference the services in the current
namespace. For me this was a confusing change of behaviour
from the reference implimentations, as I have services
with the same name in each namespace.
=> The referenced k8s service(s) must be in namespace

glide.lock, glide.yaml
Updating an engine-api that has fixed some versioning issues (filters json marshalling) 🐮.
For reference, the fix is https://github.com/docker/engine-api/pull/227/commits/38b38ec9db02d5f4916fa232da6b9dd840c9718c, depending on the client version, we marshall the `filters` different way. I though it was on all filters (that existed in 1.9.1) but turns out it was only on `ContainerList` (So I think, swarm would have the same problem with some heterogeneous agents version).
Should hopefully fix #360 this time. Still thinking of a way to test this without having a *flaky test* (with events it's hard :sweat:).
🐸
=> Update engine-api to fix versions issues

docs/toml.md
Carry PR #312, closes #312.
---
This works out of the box with zero changes.
As per: http://www.gorillatoolkit.org/pkg/mux
Once can use PathPrefix instead of Path, which provides much more predictable usage.
I.e. when i push /web here and / over there, I expect sub directories to work as well.
Tested with Latest & KV
=> Carry: Updating Toml to sure PathPrefix instead of Path

cmd.go, provider/k8s/client.go
Carry #382, closes #382.
---
I need this in order to run kubectl proxy and then
make traefik use http://localhost to get to my cluster
when developing
=> Carry: http protocol should not use TLS

docs/benchmarks.md, glide.lock, glide.yaml
This PR fixes safari error with http1/http2.
Error was due to an issue in `vulcan/oxy`, fixed in https://github.com/vulcand/oxy/pull/44
Fixes #307 
Fixes #392
=> Fix safari http2

cmd.go, configuration.go, examples/compose-k8s.yaml, provider/k8s/client.go, provider/kubernetes.go, server.go, web.go
This PR fixes memory leaks in Kubernetes backend.
/cc @nlf
Fixes #377
=> Fix k8s memory leak

provider/k8s/client.go, provider/k8s/endpoints.go, provider/kubernetes.go, provider/kubernetes_test.go
* Potentialy saves a network hop
* Ability to configure LB algothim (given some work to expose an
anotation etc...)
* K8s config Watch is triggered far less often
=> Build backend config using the K8S endpoint resource.

README.md, configuration.go, glide.lock, glide.yaml, traefik.go
+glide update flaeg & staert
+fix README.md
+fix configFile flag description
Signed-off-by: Martin <martin.piegay@zenika.com>
=> log info about TOML configuration file using

configuration.go, docs/toml.md, glide.lock, glide.yaml, integration/constraint_test.go, integration/integration_test.go, integration/resources/compose/constraints.yml, provider/boltdb.go, provider/consul.go, provider/consul_catalog.go, provider/docker.go, provider/etcd.go, provider/file.go, provider/kubernetes.go, provider/kv.go, provider/marathon.go, provider/provider.go, provider/provider_test.go, provider/zk.go, server.go, traefik.go, types/types.go, web.go
=> feat(constraints): Implementation of constraint filtering (cmd + toml + matching functions), implementation proposal with consul

docs/toml.md, provider/docker.go, provider/docker_test.go, templates/docker.tmpl
The docker template currently results in the IP address for a container being seen as every IP the container has (on every network it is a part of) being concatenated together.
For example a container that is a part of two networks and has the IPs `172.10.1.1` and `172.10.2.1` on those networks will have it's IP in the template filled in as `172.10.1.1172.10.2.1`.
This patch ensures that the user can select the network whose IP will be used with the `traefik.docket.network` label. If there is no label and more than one network, the first network will be used.
=> Added getIPAddress helper for docker template

docs/toml.md, examples/whoami-group.json, provider/docker.go, provider/marathon.go, provider/provider.go, traefik.sample.toml
Fix marathon [groups](https://mesosphere.github.io/marathon/docs/application-groups.html) subdomain management.
Added new optional `groupsAsSubDomains`:
```
#
#
```
If enabled, instead of:
`/foo/bar/myapp` => `foo-bar-myapp.{defaultDomain}`
we now have:
`/foo/bar/myapp` => `myapp.bar.foo.{defaultDomain}`
Fixes #169
=> Fix marathon groups subdomain

docs/basics.md, rules.go, rules_test.go
This PR allow to set more than one route in labels/tags (#419)
=> Allow multiple rules

docs/basics.md, docs/toml.md, examples/compose-marathon.yml, examples/whoami.json, glide.lock, glide.yaml, integration/consul_test.go, integration/etcd_test.go, integration/marathon_test.go, integration/resources/compose/marathon.yml, middlewares/handlerSwitcher.go, middlewares/routes.go, provider/docker.go, provider/marathon.go, rules.go, rules_test.go, server.go, templates/consul_catalog.tmpl, templates/docker.tmpl, templates/kv.tmpl, templates/marathon.tmpl, traefik.go, types/types.go, web.go, webui/src/app/sections/providers/frontend-monitor/frontend-monitor.html
This PR adds routes priorities to avoid path overlap.
By default, routes will be sorted using rules length:
`PathPrefix:/12345` > `PathPrefix:/1234` > `PathPrefix:/1`
You can customize priority by frontend:
```
[backends]
[backends.backend1]
[backends.backend1.LoadBalancer]
method = "wrr"
[backends.backend1.servers.server1]
url = "http://172.17.0.2"
weight = 1
[backends.backend2]
[backends.backend2.LoadBalancer]
method = "wrr"
[backends.backend2.servers.server1]
url = "http://172.17.0.3"
weight = 1
[frontends]
[frontends.frontend1]
backend = "backend1"
priority = 10
passHostHeader = true
[frontends.frontend1.routes.test_1]
rule = "PathPrefix:/to"
[frontends.frontend2]
priority = 5
backend = "backend2"
passHostHeader = true
[frontends.frontend2.routes.test_1]
rule = "PathPrefix:/toto"
``` …
=> Add routes priorities

configuration.go, provider/kv.go
Fixes #411 
Fixes #407 (pretty sure ^^)
=> Fix default KV configuration

docs/toml.md, provider/docker.go, provider/docker_test.go
Related to #311 #342 
```
[docker]
endpoint = "unix:///var/run/docker.sock"
constraints = ["tag==api", "tag==he*ld"]
```
```
$ docker run -d -P --label traefik.tags=api,helloworld emilevauge/whoami
```
=> feat(constraints): Supports constraints for docker backend

provider/docker.go, server.go
This PR should fix the memory leak due to regression on #305.
Fixes #462 
/cc @tooda02 @stevendborrelli
=> Fix memory leak in listenProviders

provider/docker.go
Simple replacement of `inpsect` with `inspect`
=> Fix typo in error message.

acme/challengeProvider.go, docs/toml.md, glide.lock, glide.yaml, mocks/Marathon.go, provider/marathon.go, provider/marathon_test.go, traefik.sample.toml
This PR fixes Marathon TLS/basic auth.
It also adds DCOS token support.
Fixes #365 
=> Fix marathon TLS/basic auth

glide.lock, glide.yaml
This PR fixes empty responses, Bump oxy to b57d6706e9ff606343c596940b60df7f90012d29.
Fixes #463 
Maybe fixes #421
=> Fix empty responses

docs/toml.md
If you use traefik in Docker and use Let's Encrypt, you have to mount the folder containing the acme.json file instead of the file itself.
=> mount acme folder instead of file

provider/consul_catalog.go, provider/consul_catalog_test.go
I noticed traefik was reload constantly from config changes when nothing had actually changed and while I got to the point where the config produced is the same it is still reloading. Any ideas?
The watch of consul can return for various reasons and not of all of
them require a reload of the config. The order of nodes provided by
consul is not stable so to ensure a identical config is generated for an
identical server set the nodes needs to be sorted before creating the
config.
=> Sort nodes before creating consul catalog config

middlewares/cbreaker.go, provider/kubernetes.go, rules.go, server.go, templates/consul_catalog.tmpl
This PR fixes spamming events from providers (mostly for k8s).
Moves the `deepEquals` check from `listenConfigurations` to `listenProviders`, before the Providers Throttle check.
Fixes #448 
Fixes #449
Also fixes some other issues:
Fixes #453 
Fixes #243
Fixes #475
=> Fix spamming events in listenProviders

configuration.go
=> Fix empty tls flag

docs/toml.md, provider/docker.go, provider/docker_test.go
=> Fix host Docker network

server.go
=> Fix acme checkOnDemandDomain

configuration.go, docs/basics.md, glide.lock, glide.yaml, script/deploy-pr.sh, server.go
This PR adds [SSE](https://en.wikipedia.org/wiki/Server-sent_events) support.
Fixes #503 
Fixes #524
=> Add sse support

README.md, configuration.go, glide.lock, glide.yaml, integration/fixtures/mesos/simple.toml, integration/integration_test.go, integration/mesos_test.go, integration/resources/compose/mesos.yml, provider/mesos.go, provider/mesos_test.go, server.go, templates/mesos.tmpl, traefik.sample.toml
Backend Implementation Proposal
We use Marathon, Chronos and homemade Framework on Mesos, and we want to have a universal backend to manage both. 
The Marathon backend works well, and we, first, want to implement a Chronos Backend. But Chronos don't manage callback as Marathon. And what about our handmade Mesos Framework ?
So we decide to lookup in the Mesos DNS code (https://github.com/mesosphere/mesos-dns) to see how callbacks are managed in Mesos. 
Mesos DNS uses a pull mecanism (https://github.com/mesosphere/mesos-dns/blob/master/records%2Fgenerator.go#L190) to check every changes.
We think that having a unified backend for Mesos is a very good point (because we don't know all Mesos frameworks we'll using in the future) using same behavior as Mesos DNS.
It's our first time we use Go …
=> add mesos provider inspired by mesos-dns & marathon provider

webui/Dockerfile
@ldez should we even use node 6 now ? (6.3 is available on the hub)
=> Bump node to 6 for webui

docs/basics.md, docs/user-guide/kv-config.md, glide.lock, glide.yaml, integration/consul_test.go, integration/etcd_test.go, traefik.go
This PR adds the command `storeconfig` which stores the static traefik configuration into a Key-value stores.
TODO :
=> Add command storeconfig

configuration.go, docs/toml.md, docs/user-guide/examples.md, glide.lock, glide.yaml, middlewares/authenticator.go, middlewares/authenticator_test.go, script/deploy-pr.sh, script/deploy.sh, server.go, traefik.sample.toml, types/types.go
This PR adds basic/digest auth in entrypoints.
WebUI can use this creating an entrypoint and adding a frontend connected to localhost.
Fixes #77 
Fixes #201 
=> Add basic/digest auth

configuration.go, docs/toml.md, traefik.go, traefik.sample.toml
Signed-off-by: Stuart Clark <stuart.clark@Jahingo.com>
=> Add global InsecureSkipVerify option to disable certificate checking

acme/acme.go
This PR fixes a bug with the new Let's Encrypt Terms Of Services.
Fixes #579 
=> Fix ACME TOS

provider/kubernetes.go, provider/kubernetes_test.go, templates/kubernetes.tmpl
The Kubernetes provider wasn't setting priorities which was causing
shorter paths to get chosen before longer ones. This now matches the
[documentation](https://github.com/containous/traefik/blob/master/docs/basics.md#priorities)
=> Prioritize kubernetes routes by path length

script/binary
=> Fixed binary script so traefik version command doesn't just print default values

provider/kubernetes.go
The TargetRef contains information from the object referenced
by the pod, unless the service has been set up with bare
endpoints - i.e. not pointing at pods this information
will be present.
It just makes the information that we show in the web-ui
a little more constent with that shown in kubectl
and the kuberntes dashboard.
=> Name servers after thier pods

glide.lock, glide.yaml
This PR fixes the toml parsing behavior :
- If a key on a pointer field of the configuration structure is called in the toml, the default pointer value will be set in the struct.
- If a under field of this pointer is called as well, its value will overwrite the default pointer value.
Running træfik with the following toml :
```toml
[docker]
```
Træfik runs with default pointer value on `docker` field :
```shell
Docker":{"Watch":true,"Filename":"","Constraints":null,"Endpoint":"unix:///var/run/docker.sock","Domain":"","TLS":null,"ExposedByDefault":true}
```
Running træfik with the following toml :
```toml
[docker]
watch=false
```
Træfik runs with default pointer value overwritten by the under field `watch`  :
```shell
Docker":{"Watch":false,"Filename":"","Constraints":null,"Endpoint":"unix: …
```
=> update staert and flaeg

integration/access_log_test.go, middlewares/logger.go
GH #559 points out that the logging of the elapsed time is inconsistent
depending on the scale of the measured time; this is due to Duration’s
String handling.
With this PR, I propose that traefik logs millis, and not fractions of
millis.
=> Make duration logging consistent

.gitignore, provider/k8s/client.go
It was mentioned in the support slack that if the pods and services are not labeled with the same label then changes are not picked up by the watch.
This reverts the change to the watch for endpoints and services so should fix the issue.
I do feel that at some point we should refactor the k8s client a bit so we can do many highly scoped watches rather than one per resource type... but this works for now.
=> Fix k8s watch

contrib/systemd/traefik.service
Having a install section makes it possible to enable/disable traefik
using the standard systemd commands
`systemctl enable traefik`
`systemctl disable traefk`
=> Make systemd unit installable

provider/provider.go, provider/provider_test.go
In testing locally, I found that I was receiving a NPE due to this being nil. I was using the marathon provider at the time, and I believe it happened as a result of that provider asking for client TLS handling even though it hadn't been configured.
=> fix for nil clientTLS causing issue

acme/acme.go
Right now, traefik stores the cert data, including the private key, in a world readable file. This is a big security concern.
Closes #638
=> Use secure mode 600 instead of 644 for acme.json

provider/kubernetes.go
Don't log a warning if traefik.frontend.rule.type is empty, log namespace and ingress if invalide.
Removes the spamming of ```time="2016-08-18T18:37:14+02:00" level=warning msg="Unknown RuleType ``, falling back to \`PathPrefix"``` for every rule.
Example: <https://gist.githubusercontent.com/yvespp/3e7aac2990d1124a0bd631326eaa2ff7/raw/a10c28cd0639434ab9b30dec84a7583525d6dc64/traefik.log4>
=> Kubernetes provider: traefik.frontend.rule.type logging

traefik.sample.toml
Just a small fix for a broken link in the sample config to Let's Encrypt's rate limits. This link was missed in commit 7d936ec which fixed the broken link in the docs.
Also added a few comments to clarify how rate limiting impacts the acme.domains settings.
Thanks for your consideration, Emile! I'm really enjoying working with Traefik and looking forward to putting it into production soon.
=> Update broken link and add a comment to sample config file 

acme/acme.go
Like the official certbot client does.
There are at least a few renewal reminder emails that will be sent by Let's Encrypt if we only renew 7 days before expiry. We can avoid that by renewing sooner.
Using 30 days as the default is a good start, I think, but I'm not sure if/where this should be documented or if it should actually be configurable.
=> ACME: renew certificates 30 days before expiry

provider/marathon.go, provider/marathon_test.go
Healthcheck are not mandatory, so if a result is not present, assume it
is ok to continue. Fixes the case when a new leader is elected and
don't have any healthcheck result's, returning 404 to all requests.
https://github.com/containous/traefik/issues/653
=> If Marathon doesn't have healthcheck, assume it's ok

docs/toml.md, provider/marathon.go, provider/marathon_test.go, provider/provider.go, templates/marathon.tmpl
Initial implementation: Force both maxconn labels to be present to trigger behavior.
=> Add ability for marathon provider to set maxconn values, loadbalancer algorithm, and circuit breaker expression

docs/toml.md, traefik.sample.toml, web.go
Hey there,
this PR enables traefik to protect the web backend per basic auth. All you need to do, is at these lines to your traefik.toml
`[web.auth.basic]
users = ["traefik:$apr1$8EvWcwpO$RaRFXvDJk6LGQ5tM04RRd0"]`
so it looks like:
> [web]
address = ":8000"
[web.auth.basic]
users = ["traefik:$apr1$8EvWcwpO$RaRFXvDJk6LGQ5tM04RRd0"]
Feedback welcome! :)
=> Add basic auth support for web backend

docs/toml.md, glide.lock, provider/docker.go, provider/docker_test.go
Add a flag to get the ipaddress from the binded information (ip/port).
=> Add possibility to use BindPort IPAddress 👼

server.go
This fixes #167 and #651. By default, gorilla/mux cleans URL paths
such that adjacent slashes are collapsed into one single slash. This
behavior is pretty common in application stacks and it is fine, but
for Traefik, this can lead to incorrect URL paths forwarded to backend
servers.
See https://github.com/gorilla/mux/issues/94 for background.
Credits goes to @sybrandy as the author of the original fix in #521
=> Disable gorilla/mux URL cleaning to prevent sending redirect

glide.lock
Updates https://github.com/thoas/stats that [fixes](https://github.com/thoas/stats/pull/19) a race condition.
Fixes #662 
Fixes #458
=> Fix health race

README.md
This PR replace the badge of imagelayers.io with a badge microbadger.com because imagelayers.io doesn't work anymore through the registry v2 specification and docker hub supports only the v2 spec.
=> Replace imagelayers.io with microbadger

provider/marathon.go
When using constraint all unlabeled application (label: traefik.tags) will be display as a separate and common backend.
This PR remove that behavior to make sure just to manage the labeled Application
=> Remove unused endpoint when using constraints with Marathon provider

configuration.go, docs/toml.md, provider/docker.go, provider/docker_test.go, server.go, traefik.sample.toml
This new provide just work with one network and `traefik.port` label.
I include a provide swarm it`s quite similar with docker provider but this swarm provide watch for services data.
=> #504 Initial support for Docker 1.12 Swarm Mode

README.md, docs/index.md, docs/toml.md, glide.lock, glide.yaml, integration/utils/try.go, job/job.go, job/job_test.go, provider/consul_catalog.go, provider/docker.go, provider/kubernetes.go, provider/kv.go, provider/marathon.go, provider/mesos.go, traefik.sample.toml, types/types.go, web.go
=> Some fixes

configuration.go, docs/toml.md, server.go, traefik.sample.toml
This PR resolves issue #535 by allowing a minimum TLS version to be specified for an entrypoint.
Fixes #535
=> Selectable TLS Versions

configuration.go, docs/toml.md, glide.lock, glide.yaml, middlewares/compress.go, server.go, traefik.sample.toml
Create a new middlewares to add HTTP compression
Add an option for it "Compress" in entrypoint configuration.
This add a dependency to "github.com/NYTimes/gziphandler".
=> Add HTTP compression

web.go, webui/src/app/core/version.resource.js, webui/src/app/version/version.controller.js, webui/src/app/version/version.module.js, webui/src/index.html, webui/src/index.js
Show traefik version and codename in the web ui, as a link to the tag or commit for this version.
I know next to nothing about Angular or Go, please review carefully.
=> Show current version in web UI

provider/docker.go, provider/docker_test.go
This add the simplest support for `HEALTHCHECK` for the docker provider.
Fixes #666.
- React to health_status events
- Filter container that have a health status *and* that are not healthy
It works like the other provider that support healthchecks (marathon for example) — if healthcheck are not supported, then it work as usual and if a container supports it, it filters the container if it's not healthy.
🐸
=> Add support for docker healthcheck 👼

docs/user-guide/swarm-mode.md, docs/user-guide/swarm.md, mkdocs.yml
Still a little bit work in progress, I need to add output of commands 👼.
Also small update on the swarm one.
🐸
=> Add documentation for Træfik on docker swarm mode

README.md
Just removed a duplicated link into README. Nothing really important :-)
=> Remove duplicated link to Kubernetes.io in README.md

provider/docker.go
This PR fixes #719 
The problem is due to a moving pointer reference. The networkMap lists network IDs all with the same network information.
=> Fix networkMap construction in ListServices

docs/toml.md, provider/marathon.go, provider/marathon_test.go
Add compatibility with labels: `HAPROXY_GROUP` and `HAPROXY_0_VHOST`.
* `HAPROXY_GROUP` become a new tag
* `HAPROXY_0_VHOST` become a rule `Host:`
https://github.com/mesosphere/marathon-lb
=> Add basic compatibility with marathon-lb

acme/acme.go, rules.go, rules_test.go, types/types.go
=> Fix case sensitive host

contrib/systemd/traefik.service, glide.lock, glide.yaml, server.go, traefik.go
This is useful if a configuration is long to load.
Systemd will continue dependency chain only when server have finish to start.
https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=
=> Use sdnotify for systemd

provider/docker.go, provider/docker_test.go, provider/marathon.go, provider/marathon_test.go, provider/mesos.go, provider/mesos_test.go
This feature use first port (PORT0) by default when there is multiple of ports
=> Use first port by default

README.md, acme/acme.go, configuration.go, docs/toml.md, glide.lock, glide.yaml, traefik.go, traefik.sample.toml, version/version.go
This PR fixes ACME renew job and adds periodical version check.
=> Fix ACME renew & add version check

CHANGELOG.md, README.md
=> Prepare release v1.1.0 rc4

docs/toml.md, traefik.sample.toml
Actually the current Marathon default for exposedByDefault is true, as we can see in
https://github.com/containous/traefik/blob/master/configuration.go
“defaultMarathon.ExposedByDefault = true”
=> Marathon ExposedByDefault is true by default

.github/CONTRIBUTING.md
Initially I got all these wired error messages telling me that various libraries was missing when I tried to run the test suite for Traefik (using the suggested command `go test ./...`). Finally, I realized that I actually was trying to run the tests for all dependency libraries.
I have added a note about how to only run the tests associated with Traefik to the contribution guide. That might keep others from doing the same mistake.
=> Added note for how to avoid running vendor tests

Makefile
git rev-parse --abbrev-ref HEAD can return results in a couple different ways:
1) tag v1.1.0-rc3 exists and branch==v1.1.0-rc3
result: heads/v1.1.0-rc3
2) tag v1.1.0-rc3 doesn't exist and branch==v1.1.0-rc3
result: v1.1.0-rc3
Strip it off GIT_BRANCH regardless as it will break the build.  e.g.
$ make binary
docker build  -t "traefik-dev:heads/v1.1.0-rc3" -f build.Dockerfile .
invalid value "traefik-dev:heads/v1.1.0-rc3" for flag -t: Error parsing reference: "traefik-dev:heads/v1.1.0-rc3" is not a valid repository/tag
See 'docker build --help'.
Makefile:51: recipe for target 'build' failed
make: *** [build] Error 125
=> Makefile: Strip 'heads/' from git rev-parse --abbrev-ref HEAD

webui/package.json
This PR fixes #796 :)
/cc: @containous/traefik
=> Add Nvd3 Dependency to fix UI / Dashboard

integration/https_test.go
To be sure that bug #790 fixed in #814 does not come back
=> Check that we serve HTTP/2

script/crossbinary
Copy variables from ./script/binary
```
Version:      dev
Codename:     cheddar
Go version:   go1.7.3
Built:        I don't remember exactly
OS/Arch:      linux/amd64
```
to
```
Version:      v1.1.0-rc4
Codename:     camembert
Go version:   go1.7.3
Built:        2016-11-10_11:29:24AM
OS/Arch:      linux/amd64
```
=> Pass Version, Codename and Date to crosscompiled

configuration.go, docs/toml.md, provider/marathon.go, traefik.sample.toml
The default value for a connection timeout for the http.Transport is zero; in cases where marathon is behind a proxy or similar device that does not explicitly refuse TCP connections, this means that the current Traefik behavior will be to wait for a connection indefinitely. It would be preferable to set some default that is not indefinite, and allow configuration of same if a different timeout is desired.
=> Allow specification of dialertimeout

acme/acme.go, acme/localStore.go, cluster/datastore.go, cluster/leadership.go, configuration.go, integration/consul_test.go
recent additions to golint mean that a number of files cause the
build to start failing if they are edited (we only run against changed
files)
This fixes all the errors in the repo so things don't unexpectedly start
failing for people making PRs
=> Fix golint

acme/acme.go, acme/localStore.go, cluster/datastore.go, cluster/leadership.go, configuration.go, integration/consul_test.go
Cherry pick b0efd685a959265fa3fb7c9a2032bc01e2a494fb from #848 into branch v1.1.
=> Fix golint in v1.1

provider/docker.go
Signed-off-by: WTFKr0 <thomas.kovatchitch@gmail.com>
=> Normalize backend even if is user-defined

docs/toml.md, provider/k8s/client.go, traefik.sample.toml
Fixes #877 
Fixes #869 
**DO NOT merge before validation made in https://github.com/containous/traefik/issues/877**
=> Fix k8s panic

provider/marathon.go, provider/marathon_test.go, provider/mesos.go, provider/mesos_test.go, provider/provider.go
Bugfix and new tests for the GroupsAsSubDomains bug for Mesos and Marathon providers. Closes #867.
=> Fix GroupsAsSubDomains option for Mesos and Marathon

acme/acme.go, acme/acme_test.go, docs/toml.md, glide.lock, glide.yaml, traefik.sample.toml
This PR enables various DNS Challenges for Let's Encrypt using existing functionality in the lego library.  I've also added an override for the default functionality of DNS validation, and rough logging.
Admittedly I haven't tested it much yet, but started the PR to see if there was any interest.  Hoping to use this myself on internal fire-walled servers.
=> Support Lets Encrypt DNS Challenges

provider/k8s/client.go, provider/kubernetes.go, provider/kubernetes_test.go
This pull includes #929 and cleans up the channel handling of the Kubernetes Provider:
- Only use one channel for all Kubernetes watches
- Re-use stop channel from the provider
- Skip all events that have already been handled by the provider
=> Kubernetes: cleanup channel handling

server.go
This PR fixes redirect regex with domains containing `_`.
Fixes #952
=> Fix redirect regex

provider/docker.go, provider/eureka.go, provider/marathon.go, provider/mesos.go, provider/provider.go, provider/provider_test.go
Add some defaults functions in the configuration template rendering.
- normalize (replace every non letter/number char with "-")
- tolower
- replace
- split
- contains
=> feat: Add defaultFuncMap to template

script/deploy.sh
Having a release tarball including all vendor source makes life of maintainers a lot easier to create downstream packages.
It also ensures that as long as the go release is available the software can be build reproducible.
=> deploy.sh: upload release source tarball

.github/ISSUE_TEMPLATE, cmd/bug.go, cmd/version.go, glide.lock, glide.yaml, middlewares/stats.go, server.go, traefik.go, web.go
This PR adds a bug command to pre-fill an issue on GitHub with Traefik version & config.
URLs & emails are anonymized.
```
Version:      dev
Codename:     cheddar
Go version:   go1.7
Built:        I don't remember exactly
OS/Arch:      linux/amd64
```
```
{
"GraceTimeOut": 10,
"Debug": false,
"CheckNewVersion": true,
"AccessLogsFile": "",
"TraefikLogsFile": "",
"LogLevel": "INFO",
"EntryPoints": {
"http": {
"Network": "",
"Address": ":8888",
"TLS": null,
"Redirect": null,
"Auth": null,
"Compress": false
},
"https": {
"Network": "",
"Address": ":5001",
"TLS": null,
"Redirect": null,
"Auth": null,
"Compress": false
}
},
"Cluster": null,
"Constraints": [],
"ACME": {
"Email": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx,
"Domains": null,
"Storage": "acme.json",
"StorageFile": "acme.json",
"OnDemand": true, …
```
=> Add bug command

docs/toml.md
Having that slash there causes traefik to be able to get keys from ZK
=> toml zookeeper doc fix

docs/basics.md, middlewares/addPrefix.go, rules.go, server.go
Add the ability to add a prefix in the url when the backend is called.
example : 
```
[backends]
[backends.backend-test.servers.server-1]
url = "http:/backend-server"
weight = 1
[frontends]
[frontends.frontend-test]
backend = "backend-test"
entryPoints = ["http"]
[frontends.frontend-test.routes.route-host-test]
rule = "PathPrefix:/test;PathPrefixStrip:/test;AddPrefix:/prefix"
```
when call http://traefik/test/url => forward http://backend-server/prefix/url
=> Add Rule AddPrefix

integration/acme_test.go, integration/fixtures/acme/acme.toml, integration/integration_test.go, integration/resources/compose/boulder.yml
Tests are based on a boulder image I pushed on my personal docker hub account.
Thx @gwallet for the help.
=> Add ACME/Let’s Encrypt integration tests

.github/CONTRIBUTING.md
With the current instructions I was getting the following failure :
```
➜  traefik git:(master) ✗ ./traefik
./traefik flag redefined: log_dir
panic: ./traefik flag redefined: log_dir
goroutine 1 [running]:
panic(0x14ca9e0, 0xc420153230)
/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:500 +0x1a1
flag.(*FlagSet).Var(0xc420016660, 0x239de60, 0xc4201531e0, 0x17cde52, 0x7, 0x1806cac, 0x2f)
/usr/local/Cellar/go/1.7.4_1/libexec/src/flag/flag.go:791 +0x43e
flag.(*FlagSet).StringVar(0xc420016660, 0xc4201531e0, 0x17cde52, 0x7, 0x0, 0x0, 0x1806cac, 0x2f)
/usr/local/Cellar/go/1.7.4_1/libexec/src/flag/flag.go:694 +0x8b
flag.(*FlagSet).String(0xc420016660, 0x17cde52, 0x7, 0x0, 0x0, 0x1806cac, 0x2f, 0xc4201531d0)
/usr/local/Cellar/go/1.7.4_1/libexec/src/flag/flag.go:707 +0x90 …
```
=> instruct to flatten dependencies with glide

glide.lock, glide.yaml, mocks/Marathon.go, provider/marathon.go, provider/marathon_test.go, templates/marathon.tmpl
Support IP per task with marathon/mesos.
Adding tests
Update marathon client version
=> IP-per-task:

acme/localStore.go, server.go
Follow-up from #639. At the moment people that were affected by this security issue would still be vulnerable even after upgrading. This patch makes sure permissions are also checked for already existing files.
This might also happen with docker-compose, where it isn't uncommon to just touch a file so that it bind-mounts as a file instead of a directory, and some users might forget to put the permissions afterwards.
In case of perm issue it'd fail on startup like this :
```
ERRO[2017-01-01T14:45:55+01:00] Error creating TLS config: permissions 644 for acme.json are too open, please use 600
FATA[2017-01-01T14:45:55+01:00] Error preparing server: permissions 644 for acme.json are too open, please use 600
```
=> check permissions on acme.json during startup

configuration.go, docs/toml.md, glide.lock, glide.yaml, middlewares/metrics.go, middlewares/prometheus.go, middlewares/prometheus_test.go, server.go, traefik.go, types/types.go, web.go
I started to look at this so I wanted to get familiar with the source code.
This is a trivial prometheus middleware based on https://github.com/zbindenren/negroni-prometheus
It could be an starting point for https://github.com/containous/traefik/issues/839
I'm happy to continue working on this if there's interest on this feature.
As we've agreed on some points and this is taking shape I'll add a progress tracker here:
```--web.metrics.prometheus```
```--web.metrics.prometheus.Buckets="100,200"```
=> First commit prometheus middleware.

configuration.go, docs/toml.md, middlewares/metrics.go, middlewares/prometheus.go, traefik.sample.toml
Some changes for sticking to best practices on instrumentation according to comments here https://github.com/containous/traefik/pull/1022 ping @brian-brazil @SantoDE
=> Improving instrumentation.

provider/kubernetes.go
Example ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
namespace: deis
name: deis
spec:
rules:
- host: "*.example.com"
http:
paths:
- path: /
backend:
serviceName: deis-router
servicePort: 80
```
=> Allow for wildcards in k8s ingress host, fixes #792

script/test-unit
=> Don't run go test on .glide cache folder

docs/user-guide/swarm-mode.md
I was following https://docs.traefik.io/user-guide/swarm-mode/ and ran across the problem described in #994. This adds a small note to the user guide for future travelers.
=> Update user guide for upcoming `docker stack deploy` 

.github/rpr.sh
First `git config --global alias.rpr '!sh .github/rpr.sh'`.
Then you can rebase a Pull Request from a contributor against current branch using `git rpr pr_number`.
Every maintainer can now easily rebase a pull request if the contributor as ticked [Allow edits from maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/).
=> Add git rpr command

.travis.yml, README.md, build.Dockerfile, webui/Dockerfile
This PR fixes Travis script issues from #843:
- add `skip_cleanup` in pages & releases
- deploy `traefik*` in releases (in order to deploy `traefik` default linux binary)
- fix provider `script` instead of `scripts`
- fix how yarn is installed
- remove docker 1.13 from tests (really, really, really unstable)
- how do i pronounce this damn project ? 
There are still some strange issue on this new script. For example, this job is green but there is one integration test failing https://travis-ci.org/containous/traefik/jobs/194860155#L2078.
/cc @guilhem @vdemeester 
=> Fix travis script

server.go
If you have more than one entry point the server would fail to start with error `panic: duplicate metrics collector registration attempted`.
So I replaced `"Global"` with entry point name.
=> Fix metrics for multiple entry points

.travis.yml
CI is failing (like in https://travis-ci.org/containous/traefik/jobs/197589236) due to clean up made by Travis.
This PR adds `skip_cleanup` in deploy.
=> add skip_cleanup in deploy

docs/toml.md, provider/kubernetes.go, provider/kubernetes_test.go, templates/kubernetes.tmpl
My take on #940 - slightly modified.
As we are setting backend behavior, I think the annotations should be on the backend - the Kubernetes service.
Includes unit tests for sticky and drr. having issues getting integration tests running locally, but I'll figure that out and patch as needed.
=> Allow setting load balancer method and sticky using service annotations

middlewares/retry.go
=> Set a NopCloser request body with retry middleware

build.Dockerfile
[This commit](https://github.com/containous/traefik/commit/c1182377dbc4ec8175dd94e416fb28c118a792e2#diff-4ed9134755756c63936ea8cedb5c3b8f) from PR #1067 introduced a wrong Docker version specifier: The major version is 1 and does not come with a leading `v` character. The PR corrects both.
~~To my surprise, the Docker build on Travis CI did not invalidate the cache when the [originating PR ran](https://travis-ci.org/containous/traefik/jobs/197589236). As far as I understand [the documentation](https://docs.docker.com/engine/reference/builder/#/impact-on-build-caching), this should have been the case.~~ The problem wasn't caught during the Travis CI run since we [set the `DOCKER_VERSION` environment variable in the Travis configuration …
=> Fix docker version specifier

script/crossbinary
Closes #923 
Binaries are successfully built via the `script/crossbinary`.
While I've not got an OpenBSD server or VM to hand, I've tested the `go` + `glide` method on a FreeBSD server, a `go build` completes successfully however a `go test $(glide novendor)` has a build failure in `github.com/containous/traefik/integration` as follows
```
cc: warning: argument unused during compilation: '-gno-record-gcc-switches'
cc: warning: argument unused during compilation: '-pthread'
cc: warning: argument unused during compilation: '-gno-record-gcc-switches'
vendor/github.com/docker/docker/runconfig/opts/parse.go:530: flags.Changed undefined (type *pflag.FlagSet has no field or method Changed)
FAIL	github.com/containous/traefik/integration [build failed]
```
but I'm not really familiar enough with …
=> Add FreeBSD & OpenBSD to crossbinary

provider/marathon.go, provider/marathon_test.go
Have been running into Traefik balancing against marathon balancees on container startup where the container is not yet ready to serve traffic. 
As of the current behavior, the marathon provider will allow balancing to: 
- Items which do not have health checks
- Items which have health checks where all results are passing
- Items which have health checks which have not been run yet 
This PR aims to ensure that items which have health checks have at least one passing health check result prior to allowing them to be balanced against, removing the last category.
=> Ensure that we don't add balancees with no health check runs if there is a health check defined on it

docs/toml.md, docs/user-guide/kubernetes.md, provider/kubernetes.go, provider/kubernetes_test.go, templates/kubernetes.tmpl
Annotation on a service - `traefik.backend.circuitbreaker` - allows one to set a circuit breaker expression.
=> Allow setting circuitbreaker expression via Kubernetes annotation

glide.lock
Updating gziphandler to use commit 6710af535839f57c687b62c4c23d649f9545d885 fixes issue #1059.
=> update NYTimes/gziphandler fixes #1059

provider/marathon.go, provider/marathon_test.go
The IP-Per-Task PR introduced a bug using the marathon application
port mapping. This port should be used only in the proxy server, the
downstream connection should always be made with the task port.
This commit fix the regression and adds an unit test to prevent new
problems in this setup.
Fixes #1072
=> Fix marathon provider

provider/docker.go, provider/docker_unix.go, provider/docker_windows.go
This fixes #1094 and increases the DockerAPIVersion from 1.21 to the minimal supported version 1.24 for Windows containers. Increase the API version only for the Windows binary, so all other platforms aren't affected by this change.
=> Fix Docker API version for Windows

contrib/systemd/traefik.service, glide.lock, glide.yaml, traefik.go
Carrying #818 — not sure `glide.lock` is up-to-date but I can't make this tool to work so… 
---
:warning: May be not ready to be merged
This PR add systemd behavior for watchdog
This is a proof of concept:
=> Carry #818 —  Add systemd watchdog feature

acme/localStore.go, acme/localStore_unix.go, acme/localStore_windows.go
As commented in https://github.com/containous/traefik/issues/1094#issuecomment-276795730 Traefik won't start in a Windows container as the file permission check introduced with #1009 does only work on Linux checking for 0x600.
I don't want to dig too deep into File ACL checks, so I skipped the check for Windows, open for other PR's to improve that.
=> Skip file permission check on Windows

Makefile, build.Dockerfile, glide.lock, glide.yaml, script/validate-glide
This PR fixes a regression introduced here https://github.com/containous/traefik/pull/1116/commits/99f251451e072b39cd8c7ca58c4d75051ecf24a5#diff-395f41b2a27b70ce44399c91c82158c2R36 (name instead of package).
This commit was merged because `glide.lock` has been manually changed, which is never a good idea. This PR also adds a check to avoid manual changes in `glide.lock`.
=> Fix glide go units

configuration.go, docs/index.md, docs/toml.md, glide.lock, glide.yaml, provider/ecs.go, provider/ecs_test.go, server.go, templates/ecs.tmpl, traefik.sample.toml
I need to do a couple things, but I wanted to open this PR for discussion.
TODO:
=> Add an ECS provider

examples/k8s/ui.yaml
Port was out of sync from 495cba591f6f558d5e43804a82b3ba5778913eb3.
=> Fix k8s example UI port.

.github/cpr.sh, .github/rmpr.sh, .github/rpr.sh
This PR adds an argument to manage upstream correctly: `git rpr pr remote/branch`
It also adds `git rmpr` & `git cpr` commands.
/cc @vdemeester 
=> Fix git rpr

docs/toml.md, docs/user-guide/swarm-mode.md, provider/docker.go
SWARM Mode has it's own built in Load balancer, so if we want to leverage sticky sessions, or if we would just prefer to bypass it and go directly to the containers (aka tasks), via
--label traefik.backend.bypass.swarm.loadbalancer=true
then we need to let Traefik know about the underlying tasks and register them as services within it's backend.
See #1024 for more details
=> Support sticky sessions under SWARM Mode. #1024

integration/docker_test.go, provider/docker.go
=> Replace underscores to dash in autogenerated urls (docker provider)

configuration.go, glide.lock, glide.yaml, provider/rancher.go, provider/rancher_test.go, server.go, templates/rancher.tmpl
New Provider - Rancher. I still need to do some stuff, but it's a base for discussions :)
TODO:
=> Feature rancher integration

.github/rpr.sh
=> Fix checkout initial before calling rmpr

Makefile
Running `make test-integration` requires building the binary first. Missing to do so, the integration tests keep failing.
This PR passes the `binary` argument to `make.sh` when invoking the `test-integration` target.
=> Build binary for test-integration Makefile target.

docs/toml.md
Added information about how AWS credentials are resolved and which
access rights is needed the Traefik ECS provider.
=> ECS: Docs - info about cred. resolution and required access policies

.gitattributes
Makes git diff Glide lock files as text, which is helpful to see changes introduced by a `glide update` run.
@emilevauge as discussed on Slack. Please review. :-)
=> Remove .gitattributes file.

traefik.sample.toml
Traefik won’t start correctly if heterogeneous numbers in a toml array.  This commit makes all numbers homogene.
**Error Message Output:**
```bash
traefik_1   | 2017/02/13 10:39:19 Error reading TOML config file /var/traefik/traefik.toml : Near line 96 (last key parsed 'web.metrics.prometheus.Buckets'): Array contains values of type 'Float' and 'Integer', but arrays must be homogeneous.
```
Signed-off-by: solidnerd <niclas@mietz.io>
=> Fix prometheus metrics example

glide.lock
Brings github.com/gambol99/go-marathon version ~0.7.0~ 0.7.1 (updated, see [my comment below](https://github.com/containous/traefik/pull/1170#issuecomment-281103253)).
I previously [merged a PR on go-marathon](https://github.com/gambol99/go-marathon/pull/256) which exposes the task state, which can now be used in Marathon templates. See the upstream PR description for my motivation why I'd like to have the state in Traefik.
Other (auto-)changes to the glide.lock file include upgrading to a later 1.5 client-go commit and removal of an apparently unused dependency (go-metrics).
=> Upgrade dependencies.

docs/user-guide/kubernetes.md, provider/kubernetes.go, provider/kubernetes_test.go
Fixes #1142
Docs will need to be updated but before doing that I wanted to make sure I was at least going about this the right way.
Along with actually supporting the ExternalName service type I added support for the passHostHeader annotation. This is a requirement for actually using ExternalName.
This is basically the first Go code I have written, so very much open to any and all feedback.
=> Kubernetes support externalname service

provider/ecs.go, provider/ecs_test.go
Try harder to query all the possible ec2 instances, and filter on instance state / lack of IP address.
Attempting to fix #1140
=> Better ECS error checking

provider/docker.go, provider/docker_test.go
A couple small issues with Docker fixed in this PR:
* Global tasks (`docker service create --mode global`) do not have a `Slot` ID in the task list, so each entry will end up having the same name in the backend configuration making the docker provider crash. This fallbacks to using the `TaskID` instead if the service is global.
* Dead tasks would be also listed in traefik, added the `desired-state: running` filter to the task list query so that we only use alive tasks as backends.
Fixes #1138
=> Fix docker issues with global and dead tasks

traefik.sample.toml
Refs #1193.
@kleinsasserm do you think this is good enough?
@emile @santode @errm @russ @dtomcej @vdemeester PTAL.
=> Add Traefik TOML sample section on how to bind to specific IP addr.

CHANGELOG.md
=> Prepare release v1.2.0 rc2

glide.lock, glide.yaml
Bump go-rancher version to be compatible with rancher 1.4 and above. 
Fixes #1218
=> Bump go-rancher version

script/validate-glide
`validate-glide` is called with `errexit` enabled (in `script/make.sh` that sources `validate-glide`), which means that grep returning a non-zero exit code will cause the script to terminate prematurely. Thus, we will never get to the point where we see the error message.
The fix is to embed the grep check directly inside the if statement.
=> Evaluate glide-hash result without reading $?.

docs/basics.md
@nikore what do you think, is this good enough?
=> Motivate and explain regular expression rules.

provider/kubernetes.go, provider/kubernetes_test.go
Carved out of #1129.
- Move annotation logic into function.
- Constantify strings.
- Refactor TestRuleType.
- Add test for GetRuleTypeFromAnnotations.
=> Refactor k8s rule type annotation parsing/retrieval.

docs/user-guide/kubernetes.md, provider/kubernetes.go, provider/kubernetes_test.go
This is a first pass of making Traefik understand and respect the kubernetes.io/ingress.class annotation in Kubernetes.
There is a discussion in #1163 about how this should be handled. The objective of this PR is to have Traefik respond to the annotation in the same way other ingress controllers such as NGINX handle it. That being:
* Use ingress that have an annotation matching "traefik"
* Use ingress that have an annotation matching "" (a blank string)
* Use ingress that do not have the annotation at all
* Ignore all ingress that have an annotation of anything else
There is also discussion in the above mentioned issue about support for configuring what the annotation matches, for example being able to say "accept annotations that match traefik-internal" instead of matching on traefik. …
=> Adding support for Traefik to respect the K8s ingress class annotation

docs/toml.md, provider/k8s/client.go, provider/kubernetes.go, server.go, traefik.sample.toml
Detect whether in-cluster or cluster-external Kubernetes client should be used based on the `KUBERNETES_SERVICE_{HOST,PORT}` environment variables.
My main motivation for this PR was to enable connecting to a Kubernetes cluster via `kubectl proxy`, which technically is not an in-cluster usage.
Given a bearer token and CA cert files, it's also possible to connect without a proxy while running outside of a cluster.
I will add some more tests once we agree on the general direction of this PR.
/cc @emilevauge @errm @dtomcej
=> Support cluster-external Kubernetes client.

docs/toml.md, traefik.sample.toml
This complements a change to the default value made in #224.
The PR targets the v1.2 branch.
@emilevauge: As discussed on Slack.
=> Update DefaultMaxIdleConnsPerHost default in docs.

acme/acme.go
Wildcard certs are getting matched too far down:
bacon.text.example.com was matching *.example.com, when it shouldn't.
This regex update removes that match.
=> Tighten regex match for wildcard certs [Addendum to #1018]

provider/ecs.go, provider/ecs_test.go
If the ECS cluster has > 100 tasks, passing them to
ecs.DescribeTasksRequest() will result in the AWS API returning
errors.
This patch breaks them into chunks of at most 100, and calls
DescribeTasks for each chunk.
=> Chunk taskArns into groups of 100

docs/toml.md, middlewares/authenticator.go, middlewares/authenticator_test.go, traefik.sample.toml, types/types.go
=> Allow usersFile to be specified for basic or digest auth

middlewares/prometheus.go, middlewares/prometheus_test.go
Functions `prometheus.NewCounterFrom` and `prometheus.NewHistogramFrom` are using `stdprometheus.MustRegister` which will panic if you try to register the same metric multiple times.
Because of this you would get `Error in Go routine: duplicate metrics collector registration attempted` when traefik tries to update configuration and new services will not get added.
With this fix traefik will use already registered metrics if that happens.
=> Fix metrics registering

.github/rpr.sh
This prevents accidentally overriding a branch that has been changed remotely by another party.
=> .github/rpr.sh: Use --force-with-lease instead of --force.

docs/toml.md, provider/docker.go, provider/docker_test.go, templates/docker.tmpl
It matches expectation of #444 
If labels contain for example:
- `traefik.mycustomservice.port=443`
-  `traefik.mycustomservice.frontend.rule=Path:/mycustomservice`
- `traefik.anothercustomservice.port=8080`
-  `traefik.anothercustomservice.frontend.rule=Path:/anotherservice`
all traffic to frontend on path `/mycustomservice` is redirected to the port `443` of the container defining the label while using path `/anotherservice` will redirect to the port `8080` of the docker container defining the label
Available properties are 
`traefik.<service-name>.port`
`traefik.<service-name>.weight`
`traefik.<service-name>.protocol`
`traefik.<service-name>.frontend.backend`
`traefik.<service-name>.frontend.entryPoints`
`traefik.<service-name>.frontend.rule` …
=> Allow multiple rules from docker labels containers with traefik.<servicename>.* properties

docs/basics.md, healthcheck/healthcheck.go, server.go, types/types.go
Also improve documentation.
@emilevauge @dtomcej as discussed on Slack.
=> Rename health check URL parameter to path.

configuration.go, docs/toml.md, provider/k8s/client.go, provider/kubernetes.go, traefik.go, traefik.sample.toml
Fixes #1248
Small refactor of k8s client config which now support external cluster client.
=> Small fixes

docs/toml.md, provider/docker.go
Closes #1308 - avoids rebase entanglements and general time-travel-related corruption :)
=> Docker: Added warning if network could not be found

provider/docker.go, provider/docker_test.go
This PR solves the issue of passing traffic to a container before it's ready when using docker provider with swarm-mode and Traefik load-balancer (traefik.backend.loadbalancer.swarm=false), which is currently (V1.2-rc2) the default. (See issue #1238)
Current Tasks filter is based only on checking desired state, this PR adds an additional check on the current task state. 
For reference, check lifecycle model in swarmkit: https://github.com/docker/swarmkit/blob/master/design/task_model.md#task-lifecycle
Fixes #1238
=> Add filter on task status in addition to desired status (Docker Provider - swarm)

Makefile
build only builds the build container without the binary.
@emilevauge PTAL.
=> Make image Makefile target depend on binary instead of build.

provider/kubernetes.go, provider/kubernetes_test.go
Update tests too.
Fixes #1330.
@Regner @containous/traefik please take a look.
=> k8s: Do not log service fields when GetService is failing.

docs/toml.md, web.go
Adding 'path' parameter for web provider.
Adding redirect from '/' to '/path'
Path can be :
- ''
- '/'
- '/path'
- '/path/'
=> Feature web root path

glide.lock, glide.yaml
Bump to latest [lego](https://github.com/xenolf/lego), fixes nonce error https://github.com/xenolf/lego/pull/354
=> bump lego 0e2937900

docs/toml.md
This solves the following error:
```
Error reading TOML config file /etc/traefik/traefik.toml : Near line 24 (last key parsed 'web.metrics.prometheus.Buckets'): Array contains values of type 'Float' and 'Integer', but arrays must be homogeneous.
```
=> Make toml Bucket array homogeneous

docs/toml.md, provider/docker.go, provider/docker_test.go
Actually with a project "foo" and service "bar", traefik add a frontend and a backend for each container (foo-bar-1, foo-bar-2...)
Now, frontend and backend are named foo-bar and all the instances of a service are grouped in a single backend.
=> Use docker-compose labels for frontend and backend names

configuration.go, docs/toml.md, glide.lock, glide.yaml, provider/marathon.go, server.go, traefik.sample.toml, vendor/github.com/containous/flaeg/flaeg.go, vendor/github.com/containous/flaeg/parsers.go, vendor/github.com/gorilla/websocket/client.go, vendor/github.com/gorilla/websocket/client_clone.go, vendor/github.com/gorilla/websocket/client_clone_legacy.go, vendor/github.com/gorilla/websocket/conn.go, vendor/github.com/gorilla/websocket/prepared.go, vendor/github.com/gorilla/websocket/server.go
This PR introduces a new `time.Duration`-based type capable of deserializing durations in TOML specs. Without providing a unit specifier, it defaults to seconds for backwards compatibility reasons and the fact that most of our duration specifiers are at the order of seconds.
~~TODO:  Switch `glide.yaml` back to github.com/containous/flaeg once containous/flaeg#34 merges.~~ Done.
Fixes #1342.
=> Use TOML-compatible duration type.

configuration.go, docs/toml.md, docs/user-guide/examples.md, server.go
Without enforcing a timeout Traefik is susceptible to resource leakage, particularly when deployed as a public facing proxy exposed to the Internet.
Make sure IdleTimeout is configurable via the traefik.toml file
Set the default to be 180 seconds
=> Add IdleConnTimeout to Traefik's http.server settings

server.go
Fix "loadd-balancer" typo in log debug message in server.go
=> Fix typo in server.go

provider/kv.go, provider/kv_test.go
Currently with a kv tree like:
/traefik/backends/b1/servers/ẁeb1
/traefik/backends/b1/servers/web2
/traefik/backends/b1/servers/web2/url
Traefik would try to forward traffic to web1, which is impossible as
traefik doesn't know the url of web1.
This commit solve that, by ignoring backend server with no url "key"
when generating the config.
This is very useful, for people who use etcd TTL feature. They can then
just "renew" the url key every X second, and if the server goes down, it
is automatic removed from traefik after the TTL.
=> kv: Ignore backend servers with no url

provider/marathon.go, provider/marathon_test.go
This PR supersedes https://github.com/containous/traefik/pull/1309.
Fixes #261 
Original author: @nicgrayson
=> Allow traefik.port to not be in the list of marathon ports

docs/user-guide/kubernetes.md
This PR adds information about the existence of a Helm Chart for traefik on the Kubernetes documentation.
=> Add documentation about k8s Helm Chart

healthcheck/healthcheck.go, healthcheck/healthcheck_test.go
Do not wait a full tick cycle to execute the first health check.
Additional changes:
- Make request timeout configurable (for testing purposes).
- Support synchronizing on health check goroutine termination through an internal wait group (for testing purposes).
- Stop leaking by closing the HTTP response body.
- Extend health check logging and use WARNING level for (continuously) failing health checks.
=> Start health checks early.

script/glide.sh
The array is empty in the beginning, so referencing`${GLIDE_ARGS[@]` produces an error due to `nounset`.
/cc @vdemeester
=> glide.sh: Push argument to GLIDE_ARGS array.

.travis.yml
Currently `make crossbinary` takes ~ 20 min on Travis, I propose to move `make crossbinary` & `make image` from `after_success` to `before_deploy`
=> Move make cross binary to Travis deploy step

docs/user-guide/kubernetes.md, examples/k8s/traefik-with-rbac.yaml
This PR add documentation and manifest example to use Traefik with k8s 1.6+ and RBAC enabled
=> Add documentation for k8s RBAC configuration

middlewares/stripPrefix.go
This PR resolves #985, making Traefik more accessible to those of us making use of the HATEOAS constraint when building out REST APIs.
=> Pass stripped prefix downstream as header (#985)

.travis.yml
`test-integration` already run `binary` so let's not compile twice for nothing 👼 
=> [ci] Don't run binary twice

traefik.sample.toml
Re-commenting the Rancher backend in the sample config
Resolves #1454
=> Fix Rancher backend left in uncommented state

docs/toml.md, provider/docker/docker.go, provider/docker/docker_test.go, provider/docker/service_test.go, provider/docker/swarm_test.go, provider/rancher/rancher.go, provider/rancher/rancher_test.go, server.go, templates/docker.tmpl, templates/rancher.tmpl, types/types.go
Fixes #751
Currently, only Basic Auth and the docker & rancher provider are supported.
=> Add Basic Auth per Frontend

configuration.go
The timeouts were given without a unit, which caused nanoseconds scale to be applied when we switched the type from `int` to `flaeg.Duration`.
Fixes a regression introduced by #1350.
Discovered along #1390.
=> Fix default timeouts for Marathon provider.

.github/CONTRIBUTING.md, cmd/traefik/bug.go, cmd/traefik/traefik.go, cmd/traefik/version.go, script/binary, script/crossbinary, server/adapters.go, server/configuration.go, server/rules.go, server/rules_test.go, server/server.go, server/web.go
Reviving #1006 👼
- This will help split stuff in smaller, better tested packages
- This moves some stuff like the traefik command to package `cmd`
It's build on top of #1444, so only the 2nd commit should be reviewed 👼 
🦁
=> Extract some code in packages

docs/basics.md
Includes guidelines on proper usage of the more complex path matchers.
Fixes #1411.
/cc @chmod666org @bfqrst
=> Improve documentation for frontend rules.

docs/toml.md
Hello,
Here is a fix in the documentation for an error I had spotted when working on a Docker Swarm project lastly.
Cheers
=> Fix error in documentation for Docker labels

.github/CONTRIBUTING.md, LICENSE.md, README.md, docs/basics.md, docs/index.md, docs/toml.md, docs/user-guide/cluster.md, docs/user-guide/examples.md, docs/user-guide/kubernetes.md, docs/user-guide/kv-config.md, docs/user-guide/swarm-mode.md, docs/user-guide/swarm.md, mkdocs.yml, webui/package.json, webui/readme.md, webui/src/index.html
This PR updates license year to 2017 and replaces  `Træfɪk` by `Træfik` in documentation.
=> License 2017, Træfɪk => Træfik

.dockerignore
As of now, it does nothing (`/dist/` doesn't filter the dist folder) and sending anything from `dist` doesn't make sense as it's mounted anyway (that's why removing `!/dist/traefik`).
To see why it's important : `make cross-binary && make validate`… look at the size of the build context sent on the 2nd command (without this PR >600M, with this PR ~60M).
> Removing the traefik binary from whitelist as the integration script
compiles the binary before running, so we don't need to send it via
the build context.
=> Update dockerignore to ignore dist and sites

.travis.yml, Makefile, provider/docker/docker_test.go, provider/docker/swarm_test.go
Piggyback change to pass `TESTDIRS` env var through to the Docker build container to run the `test-unit` Makefile target on limited packages/files.
Fixes #1443.
=> Move Docker test provider instantiation into t.Run body.

provider/marathon/marathon.go, provider/marathon/marathon_test.go, testhelpers/helpers.go
Check for explicitly defined Marathon port first.
Previously, we did the check too late resulting in the `traefik.port` label not being effective.
The change comes with additional refactorings in production and tests.
Original issue at #261.
Complements PR at #1394.
Discovered along #1390.
=> Check for explicitly defined Marathon port first.

.dockerignore
The master build is [currently broken](https://travis-ci.org/containous/traefik/jobs/225606534). Turns out we can't remove the .dockerfile exclusion for `/dist/traefik` since it's needed to build the Docker image.
This PR reverts that decision taken in #1470.
=> Re-exclude /dist/traefik from .dockerignore.

docs/toml.md, provider/marathon/marathon.go, provider/marathon/marathon_test.go, traefik.sample.toml
The IP-Per-Task feature changed the behavior for
clients without this configuration (using the task IP instead
of task hostname). This patch make the new behavior available
just for Mesos installation with IP-Per-Task enabled. It also
make it possible to force the use of task's hostname.
=> [Marathon] Detect proper hostname automatically.

docs/basics.md, middlewares/replace_path.go, middlewares/replace_path_test.go, server/rules.go, server/server.go
Replaces the old path with the new one and adds the old path to the `X-Replaced-Path` header.
My use case is to map to a FAAS web triggers (i.e. google cloud functions, aws lambda).
=> Add Path Replacement Rule

docs/toml.md, examples/compose-rancher.yml, traefik.sample.toml
=> make docs more clear about how to work with the current api

provider/kubernetes/kubernetes_test.go
=> Updating Kubernetes tests to properly test missing endpoints code path

docs/basics.md, middlewares/stripPrefixRegex.go, middlewares/stripPrefixRegex_test.go, server/rules.go, server/server.go
=> Fix regex with PathStrip

docs/toml.md, healthcheck/healthcheck.go, healthcheck/healthcheck_test.go, integration/fixtures/healthcheck/simple.toml, integration/healthcheck_test.go, integration/integration_test.go, provider/marathon/marathon.go, provider/marathon/marathon_test.go, server/server.go, server/server_test.go, templates/marathon.tmpl
For the two existing health check parameters (path [formerly known as URL] and interval), we add support for Marathon labels.
Changes in detail:
- Extend the Marathon provider and template.
- Refactor Server.loadConfig to reduce duplication.
- Refactor the healthcheck package slightly to accommodate the changes and allow extending by future parameters.
- Update documentation.
Fixes #1232.
=> Make Traefik health checks label-configurable with Marathon.

docs/toml.md, healthcheck/healthcheck.go, server/configuration.go, server/server.go, server/server_test.go, traefik.sample.toml
The new parameter allows to set a health check interval valid for all backends. Custom values set per provider may override the global one.
@containous/traefik Please review.
=> Add global health check interval parameter.

docs/toml.md, provider/rancher/rancher.go, provider/rancher/rancher_test.go, server/configuration.go, traefik.sample.toml
This pull request aims to fix some basic issues which impact the usability of the rancher provider. During my testing with the rancher provider I found that services which did not have a healthy state were removed from the traefik config. In practice we should not care about the health of a service, but only about the health of that services individual containers. As a result I've made the following changes:
1. By default, we no longer filter services by their `HealthState`. A modified version of this functionality may be enabled using the 'EnableServiceHealthFilter' configuration toggle. This is particularly useful for 'advanced' configurations such as doing blue/green deployments.
2. A `RefreshSeconds` configuration parameter has been added (much like in the ECS provider) for …
=> Improve rancher provider handling of service and container health states

safe/routine.go, safe/routine_test.go, safe/safe_test.go
This PR adds tests to package safe.
In some cases the package is a bit awkward to test.
I also noticed something strange in the code here: https://github.com/containous/traefik/blob/e2fdc27d642c9436c9b925e956290e7df95c43bf/safe/routine.go#L110-L117
`Pool.Start()` starts the `Pool.routines`, but the only way to add a routine (not `routineCtx`) from outside of the package is by calling `Pool.Go(goroutine)`, which already starts the goroutine.
The code was added with this commit when routineCtx got introduced: https://github.com/containous/traefik/commit/bea5ad3f132bae27b6c1a83adf00154058b484b5#diff-f7272237e30bd2c1dc9ccb7f7b2ce583R89
Maybe an issue should be opened to find out if `Pool.routines` started by `Pool.Start()` are used at all.
Due to the tests I also found a bug in the …
=> Add unit tests for package safe

docs/basics.md, docs/benchmarks.md, docs/index.md, docs/toml.md, docs/user-guide/examples.md, docs/user-guide/kubernetes.md, docs/user-guide/kv-config.md, docs/user-guide/swarm-mode.md, docs/user-guide/swarm.md
- fix syntax coloration.
- same language, same code fence.
- fix typo.
- add some magic.
=> doc: small documentation review

docs/toml.md, docs/user-guide/kubernetes.md, provider/kubernetes/client.go, provider/kubernetes/kubernetes.go, provider/kubernetes/kubernetes_test.go, templates/kubernetes.tmpl
This will add the kubernetes provider for basic authentication. Thanks to @SantoDE for #1147.
* Basic authentication only
* Realm not configurable; only `traefik`default
* Secret is in same namespace as ingress rule
* Secret must contain only single file (*)
(*) otherwise we can have some conventions here like key name (pattern)
Based on https://docs.traefik.io/user-guide/kubernetes/
* Encode credentials
`htpasswd -c ./auth jane`
* Deploy a secret to k8s
`kubectl --namespace=kube-system create secret generic mysecret --from-file auth`
* Deploy ingress
```yaml
apiVersion: v1
kind: Service
metadata:
name: traefik-web-ui
namespace: kube-system
spec:
selector:
k8s-app: traefik-ingress-lb
ports:
- port: 80
targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: …
```
=> Add basic auth to kubernetes provider

docs/toml.md, provider/rancher/rancher.go, provider/rancher/rancher_test.go, traefik.sample.toml
Added constraint management for the Rancher provider. This enables filtering capabilities like described in the documentation https://docs.traefik.io/toml/#constraints
=> feat(rancher): added constraint management for rancher provider

cmd/traefik/traefik.go
Commit coreos/go-systemd@0c088e introduce cleaning environment.
First usage of sdnotify (for type=notify) was clearing NOTIFY_SOCKET environment variable.
sdnotify in watchdog was unable to ping back.
Fix #1353
=> Fix systemd watchdog feature

provider/marathon/marathon_test.go
The tests part of this change were originally in #1320 but got lost during one of the rebases. Let's bring them back in.
=> Add tests lost during PR 1320.

CHANGELOG.md, provider/docker/docker.go, provider/docker/docker_test.go, provider/docker/service_test.go, provider/docker/swarm_test.go, server/server.go
This PR reports tag `v1.2.3` into master.
Cherry picked:
https://github.com/containous/traefik/commit/40afd641a9488db6b02a09d8eaf18eaa1e935d5b
https://github.com/containous/traefik/commit/b3e6c7f598be510befab97b3b9fdc707604d89aa
https://github.com/containous/traefik/commit/fa4d2d325dbd56d68183ebe69b944f6cd529fe04
https://github.com/containous/traefik/commit/0ecfbb8279d5d3c1e3c5c1c83834f73ad8cb5698
https://github.com/containous/traefik/commit/e21feae56163217674c3406bcf7f724f48521d0f
https://github.com/containous/traefik/commit/37b44cc706ebf28e9f255fc6220418c49ec7d84e
=> Merge v1.2.3 master

Makefile, script/crossbinary-default, script/crossbinary-others
With this PR i have divided the original ./script/crossbinary file in 2 files.
- crossbinary-default
It contains windows and linux
- crossbinary-others
it contains darwin, freebsd and openbsd
Makefile has been modified using the same schema adding new targets to enable parallelism at make level.
The main goal was to reduce the make crossbinary exec time and to separate win/linux platforms  with minimum impact on actual test suite.
see https://github.com/containous/traefik/issues/1266
with parallel execution (make -j2 crossbinary-parallel) we reduce the exec time of ~10%
tested with 
make crossbinary
semaphoreci : <https://semaphoreci.com/atbore/traefik/branches/crossbinary-parallel/builds/4>
=> Makefile target to enable parallel jobs

provider/consul/consul_catalog.go
Possible fix for #1107 
Using health.State only as a trigger for further actions.
=> using more sensible consul blocking query to detect health check changes

.travis.yml, Makefile, script/crossbinary, script/crossbinary-default, script/crossbinary-others
With this PR the make target cross binary is executed before the travis deploy step, so for each PR.
I have also added the parallelization of the same target and a new variable "GO_BUILD_CMD" for the scripts.
=> [CI] Enhance cross-binary builds and parallelism

.travis.yml
the goals of this PR is to run once before_deploy tasks, As reported on https://github.com/travis-ci/travis-ci/issues/2570.
=> [CI ] to run once travis before_deploy

.semaphoreci/setup.sh, .semaphoreci/vars
This PR adds DOCKER_VERSION to install docker during the setup Job phase.
The main goal: to be independent from the default docker installed in the CI's VM.
=> [CI] set Docker version

webui/readme.md
to avoid conflict with Hadoop Yarn cli.
I don’t know the best practice, but i do
have Apache Yarn installed on my machine, so
I get this conflict. Of course this conflict does
not arised when building within the docker.
see https://github.com/yarnpkg/yarn/issues/2337
Signed-off-by: Gaetan Semet <gaetan@xeberon.net>
=> prefere yarnpkg over yarn

provider/kubernetes/kubernetes.go
We are starting to see reports of people using 1.3-rc1 and complaining/wondering about the problem reported in #1548. Hence, I think we should include the fix in the 1.3 branch as well.
=> [Kubernetes] Ignore missing pass host header annotation. [v1.3 - CHERRY-PICK]

provider/boltdb/boltdb.go, provider/consul/consul.go, provider/etcd/etcd.go, provider/eureka/eureka.go, provider/kv/kv.go, provider/kv/kv_test.go, provider/marathon/marathon.go, provider/zk/zk.go
This PR fixes exported fields in Providers done in #1444.
It also adds missing `description` tag.
Fixes #1583
=> Fix exported fields providers

provider/kubernetes/kubernetes.go
=> Merge v1.3 branch into master [2017-05-11]

.travis.yml
This PR removes the unit and integration tests from travis.
Those tests are executed on SemaphoreCI only.
=> [CI] removed unit and integration tests from travis

middlewares/recover.go, middlewares/recover_test.go, middlewares/retry.go, middlewares/stateful.go, middlewares/stats.go, server/server.go
This PR fixes #1315 and adds a generic http recover.
Fixes #1315, #1591
=> Fix stats hijack

server/server.go, server/server_test.go
This PR fixes traefik crash when basic auth user is empty.
Fixes #1592
=> Fix empty basic auth

docs/basics.md, server/server.go, server/server_test.go, testhelpers/helpers.go
Addresses issue raised in  #1569
=> Fixed ReplacePath rule executing out of order, when combined with PathPrefixStrip

server/server.go, server/server_test.go, types/types.go
We previously did not copy the sticky flag if the load-balancer method validation failed, causing enabled stickiness to be dropped in case of a validation error (which, technically, for us is the same as a load-balancer configuration without an explicitly set method). This change fixes that.
A few refactorings and improvements along the way:
- Move the frontend and backend configuration steps into separate   methods/functions for better testability.
- Include the invalid method name in the error value and avoid log   duplication.
- Add tests for the backend configuration part.
Fixes #1568.
=> Maintain sticky flag on LB method validation failure.

.github/MAINTAINER.md
Add an explanation for each label we use.
https://mensuel.framapad.org/p/EYZcWzVbgO
=> doc: add labels documentation.

CHANGELOG.md, docs/basics.md, docs/user-guide/cluster.md, middlewares/recover.go, middlewares/recover_test.go, middlewares/retry.go, middlewares/stateful.go, middlewares/stats.go, provider/boltdb/boltdb.go, provider/consul/consul.go, provider/etcd/etcd.go, provider/eureka/eureka.go, provider/kv/kv.go, provider/kv/kv_test.go, provider/marathon/marathon.go, provider/zk/zk.go, script/deploy.sh, server/server.go, server/server_test.go, testhelpers/helpers.go, types/types.go
This PR merges `v1.3.0-rc2` to master.
=> Merge v1.3.0-rc2 master

docs/user-guide/marathon.md, mkdocs.yml
Copy/pasted from very comprehensive slack response from ~@ttr~ @timoreimann
https://traefik.slack.com/archives/C0CDT22PJ/p1494347929571784?thread_ts=1494339388.375916&cid=C0CDT22PJ
Signed-off-by: Gaetan Semet <gaetan@xeberon.net>
=> Add Marathon guide.

.github/ISSUE_TEMPLATE.md
- Be more explicit in the purpose of the issue tracker.
- Move SO before Slack since it seems preferable.
- Refer to SO and Slack on first question again.
I also lean towards removing the big block of "how to write a good issue?". While I wholeheartedly agree with the content, I think it's just too much information overall and distracts from the other (IMHO more important) other information. But maybe that's to decide in another PR.
=> Issue template: Emphasize SO and Slack for support questions.

docs/toml.md, glide.lock, glide.yaml, middlewares/ip_whitelister_test.go, middlewares/ip_witelister.go, provider/docker/docker.go, provider/docker/docker_test.go, provider/kubernetes/kubernetes.go, provider/kubernetes/kubernetes_test.go, provider/string_util.go, provider/string_util_test.go, server/server.go, server/server_test.go, templates/docker.tmpl, templates/kubernetes.tmpl, types/types.go, vendor/github.com/stretchr/testify/require/doc.go, vendor/github.com/stretchr/testify/require/forward_requirements.go, vendor/github.com/stretchr/testify/require/require.go, vendor/github.com/stretchr/testify/require/require_forward.go, vendor/github.com/stretchr/testify/require/requirements.go, webui/src/app/sections/providers/frontend-monitor/frontend-monitor.html
This PR fixes #816. It adds the ability to specify a List of CIDR Whitelists per Frontend. If Whitelists are configured and the Request-IP does not match one of them, it is aborted with a 403 Forbidden.
This obviously requires traefik to be directly mapped on public ips, if the incoming requests are nat'ed, ie through dockers publish-functionality or docker-compose ports, traefik will only see an ip of the internal network and won't be able to filter according to the source-ip.
This PR adds support for the Docker-Provider and the Kubernetes-Provider, but it should be trivial to extend the support to other Providers, I just have no test-setup for those. For both it parses the Annoatation/Label "traefik.frontend.whitelistSourceRange", for Kubernetes it also accepts the quasi-standard …
=> IP Whitelists for Frontend (with Docker- & Kubernetes-Provider Support)

cmd/traefik/traefik.go, middlewares/logger.go, middlewares/logger_test.go
=> Create log folder if not present

docs/basics.md, healthcheck/healthcheck.go, healthcheck/healthcheck_test.go
Some services use a different port for auxiliary functions such as healthchecks and metrics.  Traefik itself does this.  This PR allows overriding the port used per backend.
=> Allow overriding the port used for healthchecks

provider/kubernetes/kubernetes.go, provider/kubernetes/kubernetes_test.go
Instead of doing sanity checks in the Kubernetes provider, we just accept any non-empty value from the annotation and rely on the server part to filter out unknown rules.
This allows us to automatically stay in sync with the currently supported Path matchers/modifiers.
Fixes #1627.
=> [k8s] Remove rule type path list.

provider/kubernetes/kubernetes.go, provider/kubernetes/kubernetes_test.go, templates/kubernetes.tmpl
We previously fell back to using ClusterIPs. However, the approach can lead to all kinds of problems since Ingresses rely on being able to talk to Endpoints directly. For instance, it can break stickiness and retries.
I believe the issue should still go into 1.3 since the implications can be quite severe and users won't have much of a chance to spot the misconfigurations easily.
Fixes #1462.
=> [k8s] Ignore Ingresses with empty Endpoint subsets.

middlewares/stripPrefix.go, middlewares/stripPrefix_test.go
When pushing data to downstream proxies; malformed requests were being
sent.
The corrected behavior is as follows:
| Route Stripped    |     URL                |  Passed to Backend |
| ----------------- | ---------------------- | ------------------ |
| /                 |     /                  |  /                 |
| Route Stripped    |     URL                |  Passed to Backend |
| ----------------- | ---------------------- | ------------------ |
| /stat             |     /stat              |  /                 |
| /stat             |     /stat/             |  /                 |
| /stat             |     /status            |  /status           |
| /stat             |     /stat/us           |  /us               |
| Route Stripped    |     URL                |  Passed to Backend |
| …
=> Fix behavior for PathPrefixStrip

provider/rancher/rancher.go
=> fix: Empty Rancher Service Labels.

acme/account.go, acme/acme.go, acme/acme_test.go, cluster/datastore.go, cmd/traefik/bug.go, cmd/traefik/version.go, healthcheck/healthcheck.go, middlewares/accesslog/logger_formatters.go, middlewares/accesslog/logger_test.go, middlewares/authenticator.go, middlewares/ip_witelister.go, provider/consul/consul_catalog.go, provider/docker/docker.go, provider/docker/docker_test.go, provider/docker/swarm_test.go, provider/dynamodb/dynamodb.go, provider/kubernetes/kubernetes.go, provider/marathon/marathon.go, provider/mesos/mesos.go, provider/provider_test.go, server/adapters.go, server/configuration.go, server/rules.go, server/rules_test.go, server/server.go, server/web.go
- log & error: remove format if not necessary, add if necessary.
- add constants for k8s annotations.
- fix typos
=> Logs & errors review

Makefile, middlewares/replace_path.go, middlewares/replace_path_test.go, middlewares/stripPrefix.go, middlewares/stripPrefixRegex.go, middlewares/stripPrefixRegex_test.go, middlewares/stripPrefix_test.go, server/rules_test.go
Homogenization of the tests.
The naming of cases is not perfect for `stripPrefixRegex_test` but it is more maintainable.
Use `r.Header.Add("MY-HEADER", value)` instead of  `r.Header["MY-HEADER"] = []string{value}`.
Bonus:
- we can use Git branch name with `/` like `foo/bar`.
=> Enhance rules tests.

docs/user-guide/kubernetes.md, examples/k8s/cheeses-ingress.yaml
This changes the doc and example from pathprefixstrip to PathPrefixStrip.
With v1.3 pathprefixstrip does not work, with the following error:
```
time="2017-06-01T11:46:32Z" level=error msg="Error creating route for frontend cheeses.minikube/wensleydale: Error parsing rule: Error parsing rule: 'pathprefixstrip:/wensleydale'. Unknown function: 'pathprefixstrip'" 
time="2017-06-01T11:46:32Z" level=error msg="Skipping frontend cheeses.minikube/wensleydale..." 
```
=> Fix capitalization of PathPrefixStrip in kubernetes doc

provider/kubernetes/client.go
This was likely just a copy-paste issue, the bug should be benign because the secret is cast to the correct type later, but the additional logging is a major annoyance, and is happening even if basic auth is not in use with Kubernetes.
=> Use correct type when watching for k8s secrets

provider/marathon/marathon.go
When creating custom template for Marathon provider, it really helps to have a `getSubDomain` function be available to use in custom templates.  Otherwise the logic to compute the sub-domain directly inside the template gets very messy, and reusing the same logic as the provider would help with consistency.
=> Exported getSubDomain function from Marathon provider

docs/toml.md, middlewares/accesslog/logger.go, middlewares/accesslog/logger_test.go, server/configuration.go, server/server.go, traefik.sample.toml, types/types.go
Now that access logging uses logrus, [(#1647)](https://github.com/containous/traefik/pull/1647), add JSON as a supported format.
The existing `accessLogFile` config entry is deprecated in favour of a `accessLog` section, allowing both the filePath and format to be specified.  The common log format is retained as default.
To format JSON the standard logrus JSON formatter is used.
=> Add JSON as access logging format

webui/src/app/sections/health/health.controller.js
- format the Oy axis ticks as integers on the Total Status Code Count chart
- prevent the Average Response Time chart from showing negative values on the Oy axis
- remove the deprecated `transitionDuration` field
- set the transition duration to 0 on the Average Response Time chart to avoid triggering an NVD3 marker placement bug
Here is some background on `transitionDuration`: https://stackoverflow.com/questions/30455485/transitionduration-function-does-not-exist-in-nvd3-js
These are some issues that I noticed while developing #1650 and I thought you guys might want to have them fixed. Please note that I'm not much of a web developer, so I hope I got them right :)
=> Minor Health UI fixes

middlewares/metrics.go, middlewares/metrics_test.go, middlewares/prometheus.go, middlewares/prometheus_test.go, middlewares/retry.go, middlewares/retry_test.go, server/server.go, server/server_test.go
This PR adds metrics for the backend_retries_total. On the way to implement this, I did a couple of clean up tasks and improved the testing coverage of the existing implementation.
Cleanup tasks:
- I renamed variables/methods for the request duration metrics, from latency to requestDuration. The concept was confused before in the code and in fact the request duration is tracked and the exported prometheus name was `traefik_request_duration_seconds` all the time. Therefore this is no breaking change, just clarification inside the code base.
- I remove the Handler() method from the Metrics interface as this is a concern not relevant for consumers of the interface, which are concerned about the collection of metrics. Also the method was not even used.
- I made the `ResponseRecorder` in the …
=> add metrics for backend_retries_total

server/server.go
Set cookie name so that it is unique to the backend.
Addresses issue #1574.
See PR #1712 for additional discussion.
=> make the cookie name unique to the backend being served

docs/basics.md, docs/user-guide/examples.md, server/server.go, types/types.go
Copys the incoming TLS client certificate to the outgoing
request. The backend can then use this certificate for
client authentication ie. k8s client cert authentication
fixes #1392
=> enable TLS client forwarding

cluster/leadership.go, docs/user-guide/cluster.md
Traefik should follow modern IT trends, and use manager/leader/worker/agent, etc. instead of "master/slave".
e.g jenkinsci/jenkins#2007 (https://issues.jenkins-ci.org/browse/JENKINS-27268) 
NB: of course, it can only apply where possible, since backends like Mesos should retain their own concepts, and not add more confusion.
=> drop "slave" wording for "worker"

docs/toml.md, integration/fixtures/consul_catalog/simple.toml, provider/consul/consul_catalog.go, provider/consul/consul_catalog_test.go, server/configuration.go, traefik.sample.toml
Enhanced Consul Catalog configuration by adding the following:
- Ability to configure default FrontEndRule using Go Template
- Ability to use all tags for constraint filtering
- Ability to have empty/no prefix
- Added `getTag` and `hasTag` functions to be used in advanced custom configuration template
=> Enhanced flexibility in Consul Catalog configuration

templates/kv.tmpl
This PR adds definitions to the KV template to load backend health check information (path and interval).
I've only tested this change with the etcd backend.
=> Adds definitions to backend kv template for health checking

docs/basics.md, glide.lock, glide.yaml, middlewares/headers.go, middlewares/headers_test.go, middlewares/secure.go, server/server.go, types/types.go, types/types_test.go, vendor/github.com/unrolled/secure/LICENSE, vendor/github.com/unrolled/secure/doc.go, vendor/github.com/unrolled/secure/secure.go
This is a middleware based on github.com/unrolled/secure that allows us to control, and inject request and response headers.
=> Create Header Middleware

docs/toml.md, middlewares/accesslog/logger.go, middlewares/accesslog/logger_test.go, server/configuration.go, traefik.sample.toml, types/types.go
This PR enables sending the access logs to the stdout. It should therefore solve #1306. Consistently to `TraefikLogsFile`, it uses stdout now when the config for `AccessLogsFile` is omitted or empty.
=> enable logging to stdout for access logs

glide.lock, glide.yaml, vendor/github.com/donovanhide/eventsource/server.go, vendor/github.com/donovanhide/eventsource/stream.go, vendor/github.com/gambol99/go-marathon/client.go, vendor/github.com/gambol99/go-marathon/group.go, vendor/github.com/gambol99/go-marathon/subscription.go
This PR should fix the issue #659. The fix is actually in `github.com/gambol99/go-marathon` and this PR updates it and its sub-dependency `github.com/donovanhide/eventsource`.
I updated the dependency according to the approach @timoreimann suggested [here](https://github.com/containous/traefik/pull/1278#issuecomment-286696714). I tested the failover with Traefik against a real running Marathon cluster and took nodes down one after another. Also I tried to take all nodes down at once and see if it recovers and the failover/recovery works consistently.
Fixes #659
=> Fix fallback to other nodes for Marathon

middlewares/compress.go, middlewares/compress_test.go
Don't compress when `Content-Encoding` header is already present.
Fixes #1060
=> fix: Double compression.

docs/user-guide/kv-config.md
Documentation update on how to specify a consul acl token: https://github.com/containous/traefik/issues/1717
=> added consul acl token note

middlewares/prometheus_test.go, middlewares/retry.go, middlewares/retry_test.go, server/errorhandler.go, server/errorhandler_test.go, server/server.go
Now retries only happen when actual network errors occur and not only
anymore based on the HTTP status code. This is because the backend could
also send this status codes as their normal interface and in that case
we don't want to retry.
This PR should solve the issue [1104](https://github.com/containous/traefik/issues/1104)
=> retry only on real network errors

docs/toml.md, server/web.go
=> Add HTTP HEAD handling to /ping endpoint

provider/docker/docker.go
=> Fix error handling for docker swarm mode

cmd/traefik/traefik.go, glide.lock, glide.yaml, provider/rancher/api.go, provider/rancher/metadata.go, provider/rancher/rancher.go, provider/rancher/rancher_test.go, server/configuration.go, traefik.sample.toml, vendor/github.com/rancher/go-rancher-metadata/main.go, vendor/github.com/rancher/go-rancher-metadata/metadata/change.go, vendor/github.com/rancher/go-rancher-metadata/metadata/metadata.go, vendor/github.com/rancher/go-rancher-metadata/metadata/types.go, vendor/github.com/rancher/go-rancher-metadata/metadata/utils.go
Using the API as the only source of Rancher Traefik configuration alienates some Rancher deployments, particularly in secure environments. This PR looks to resolve #1402 by allowing the user to choose between API and internal metadata service for sourcing Traefik configuration. 
Some benefits of the metadata service:
- Payloads are smaller in size as constrained to a single Rancher environment
- User does not have to concern themselves with the secure bootstrap of powerful Rancher API access/secret keys into Traefik
- Accurate almost instantaneous Traefik configuration updates if using long polling config option (rather than the usual wait of up to `RefreshSeconds`)
- Traefik configuration only updated when there's been an actual change in Rancher (thanks to the metadata service's …
=> Refactor into dual Rancher API/Metadata providers

provider/consul/consul_catalog.go, provider/consul/consul_catalog_test.go
Implemented long polling for services and for the health in the separate co-routines and react on either trigger independently by using same channel for both.
Basically two things improved:
1. Decreased Health change detection time.
2. Reduced amount of false triggering for traefik configuration rebuild by doing extra checking for actually changed services.
Detailed description: https://github.com/containous/traefik/issues/1107#issuecomment-300492280
Improvement for #1107  
Relates to #1514
=> Speeding up consul catalog health change detection

contrib/scripts/dumpcerts.sh
In the event that a user needs to explode their acme.json file into
a set of directories and relevant files for troubleshooting or use
with other programs this script will parse them into the components
in the following path structure:
```
certdir
├── certs
│   ├── domain-1.example.com
│   ├── domain-2.example.com
│   └── domain-n.example.com
└── private
└── letsencrypt.key
```
=> contrib: Dump keys/certs from acme.json to files

glide.lock, glide.yaml, vendor/github.com/vulcand/oxy/forward/fwd.go
=> Problem with keepalive when switching protocol failed

middlewares/metrics.go, middlewares/prometheus.go, middlewares/prometheus_test.go
Its best practice to monitor request durations partitioned by the status code of the response.  4xx/5xx usually have a different response time then succeeding requests. In case of 4xx they are most of the time very fast and depending on the type of server error, 5xx are also either very fast or very slow. Having no differentiation of those would distort calculations on the request durations, e.g. when you want to calculate an average.
Adding the label to the metric is not breaking existing Prometheus queries and is therefore backwards compatible.
=> add status code to request duration metric

docs/toml.md, integration/file_test.go, integration/fixtures/file/dir/simple1.toml, integration/fixtures/file/dir/simple2.toml, integration/fixtures/file/directory.toml, provider/file/file.go, provider/file/file_test.go, traefik.sample.toml
Currently the file provider reads service config either from the global config, or from a single file specified in global config.
In some deployments it would be nice to load from multiple files - perhaps because each service is defined in a single file and is maintained separately from the others.  This PR extends the file provider to allow this.
Also added a unit test for the file provider and fixed bug in integration test which didn't check err response of GetRequest.
=> Allow file provider to load service config from files in a directory.

glide.lock, glide.yaml, vendor/github.com/donovanhide/eventsource/server.go, vendor/github.com/donovanhide/eventsource/stream.go, vendor/github.com/gambol99/go-marathon/client.go, vendor/github.com/gambol99/go-marathon/group.go, vendor/github.com/gambol99/go-marathon/health.go, vendor/github.com/gambol99/go-marathon/subscription.go, vendor/github.com/gambol99/go-marathon/unreachable_strategy.go
Fixes a problem with `UnreachableStrategy` being available now in two type-incompatible formats (object and string).
Fixes #1743.
=> Upgrade go-marathon to dd6cbd4.

provider/kubernetes/client.go, provider/kubernetes/kubernetes.go
- Wait for secret controller to finish synchronizing.
- Improve basic auth handling.
- Continue Ingress processing on auth retrieval failure.
The last point is noteworthy: We previously returned an error when we couldn't retrieve basic auth credentials, blocking following Ingresses from being processed. Since retrieving the auth credentials is highly dependent on an external component (the Kubernetes Secret object), we should opt for dropping such failing Ingresses but move forward with the remaining ones.
Fixes #1794.
@dtomcej @errm @emilevauge @ldez and others: PTAL.
=> Fix race on closing event channel.

CHANGELOG.md, glide.lock, glide.yaml, provider/kubernetes/client.go, provider/kubernetes/kubernetes.go, vendor/github.com/gambol99/go-marathon/client.go, vendor/github.com/gambol99/go-marathon/health.go, vendor/github.com/gambol99/go-marathon/unreachable_strategy.go, vendor/github.com/vulcand/oxy/forward/fwd.go
=> Merge v1.3.2 to master 

glide.lock, vendor/github.com/donovanhide/eventsource/decoder.go
Log message produced by go-marathon was:
`time="2017-06-28T09:08:19Z" level=debug msg="listenToSSE(): failed to
handle event: failed to decode the event type, content: , error: EOF"`
The fix for this was done in the upstream project of go-marathon donovanhide/eventsource.
Background is that Marathon periodically sends a `\n` over the SSE subscription, in order to keep the connection alive. This was parsed as empty event by the eventsource and published. go-marathon in turn was not able to do something with this empty event was producing the log message above. By getting rid of publishing empty events in the downstream library, we also get rid of this log message.
=> remove confusing go-marathon log message

provider/kubernetes/kubernetes.go
Logging errors into a file inside a minimalistic container might not be possible, and glog bails out with an exit code > 0 if it fails.
Fixes #1785
=> Tell glog to log everything into STDERR.

docs/basics.md, server/configuration.go
Motivated by [this Stackoverflow answer](https://stackoverflow.com/a/44932934).
Emile and @containous/traefik: PTAL.
=> Clarify that provider-enabling argument parameters set all defaults.

provider/kubernetes/client.go
When Secrets permissions have not been granted (which is likely to be the case for users not needing the basic auth feature), the watch on the Secrets API will never yield a response, thereby causing the controller to never sync successfully, and in turn causing the check for all controller synchronizations to fail consistently. Thus, no event will ever be handled.
Fixes #1826 
Reverts a part of #1798
Verified that #1794 continues to be fixed
Reviewers and @containous/traefik: PTAL.
=> Undo the Secrets controller sync wait.

.travis.yml, Makefile
I think its a good idea to always rebuild the web-ui when building a docker image via `make image`. Otherwise there is the risk that an image is built and used which has not the latest ui version. WDYT?
Side note: I recognised that the `make run-dev` command does not work as expected. The `main` package is now in the `server` directory. Do you think its still in use and should be cleaned up or is it obsolete?
=> rebuild webui when building docker image

examples/k8s/traefik-rbac.yaml
The traefik controller shall have access to secrets for the k8s basic authentication (#1488) to work
=> traefik controller access to secrets

.github/CONTRIBUTING.md
Update to the docs to clarify the build steps.  It took longer than I would like to admit to get build working because I missed a step and also setup glide when it wasn't needed (i wasn't changing dependencies).
I updated the docs to help clarify the steps.  I hope you find this helpful and open to suggestions if I missed something.
=> Update build steps

docs/toml.md, provider/marathon/marathon.go, provider/marathon/marathon_test.go, templates/marathon.tmpl
Adding in support for configuring basic auth via a marathon label; there are similar functions in docker and the rancher providers.  
This addresses the marathon part of #1465
=> Add marathon label to configure basic auth

log/logger.go, provider/dynamodb/dynamodb.go, provider/ecs/ecs.go, provider/marathon/marathon.go, provider/provider.go
Display logs from provider clients.
Link client debug log to Traefik debug log:
- DynamoDB
- ECS
- Marathon
=> Link some providers logs to Traefik

docs/toml.md, server/configuration.go, server/server.go, server/server_test.go, traefik.sample.toml
This re-uses work done on #1332 and allows users to define IP whitelisting at the entrypoint level.
```toml
[entryPoints]
[entryPoints.http]
address = ":1080"
whiteListSourceRange = ["192.168.0.0/16"]
```
=> Add whitelist configuration option for entrypoints

docs/toml.md, docs/user-guide/kubernetes.md
- Add details to the labelselector parameter.
- Add section on ExternalNames in the guide.
=> Improve documentation.

server/server.go
This is a small PR that does a little code cleanup in regards to the load balancer configuration. It extracts the initial configuration into a method and therefore removes code duplication.
One thing to note is that before the healthcheck configuration was setup multiple times for the Drr LB. This was not a problem as the result was always written into the same map key, though unnecessary.
@timoreimann PTAL.
=> extract lb configuration steps into method

provider/marathon/marathon.go, provider/marathon/marathon_test.go, templates/marathon.tmpl
Change Marathon provider to make just one API call instead of two per configuration update by means of specifying embedded resources, which enable retrieving multiple response types from the API at once. Apart from the obvious savings in API calls, we primarily gain a consistent view on both applications and tasks that allows us to drop a lot of correlation logic.  Additionally, it will serve as the basis for the introduction of [readiness checks](https://github.com/containous/traefik/issues/1559) which require application/task consistency for correct leverage on the proxy end.
Additional changes:
marathon.go:
- Filter on tasks now embedded inside the applications.
- Reduce/simplify signature on multiple template functions as we do not need to check for proper application/task correlation …
=> Use single API call to fetch Marathon resources.

glide.lock, glide.yaml, middlewares/compress.go, middlewares/compress_test.go, vendor/github.com/NYTimes/gziphandler/gzip.go, vendor/github.com/NYTimes/gziphandler/wrapper.go
Fix double compression.
Fixes #1851
=> Double compression.

docs/user-guide/kv-config.md
document change to clarify consul ssl, vs consul ssl client certificate security
https://github.com/containous/traefik/issues/1718
=> doc change regarding consul SSL

middlewares/replace_path.go, middlewares/replace_path_test.go
Fixes #1775. 
The path replace middleware wasn't setting the `http.Request.RequestURI` which is used by `oxy.forward` to compose the outgoing URL and from the point of view of the backend the path was never replaced.
Other middlewares, like `addPrefix` and `stripPrefix`, do the same thing.
=> Fix replace path rule

docs/toml.md, traefik.sample.toml
Yesterday I followed the docs (https://docs.traefik.io/toml/#acme-lets-encrypt-configuration) to set traefik with dnsimple as dns provider in order to get Let's Encrypt certs with txt dns challenge.
Thing is traefik says I need to set some env vars for the container to use and setup dnsimple (`DNSIMPLE_EMAIL` and `DNSIMPLE_API_KEY`  in this case), I set them but wasn't able to use dnsimple (the container exited), found out in the logs it exited because of something related to an OAuth key that wasn't found ('cause it was not set), after searching for the library traefik use for this (https://github.com/xenolf/lego/blob/master/providers/dns/dnsimple/dnsimple.go#L25) I figured out I needed to set a different env var instead of `DNSIMPLE_API_KEY` (`DNSIMPLE_OAUTH_TOKEN`) so i did, now it's …
=> Update docs for dnsimple env vars.

integration/healthcheck_test.go, middlewares/empty_backend_handler.go, middlewares/empty_backend_handler_test.go, server/server.go, server/server_test.go
This PR changes the response code Traefik sends to 503, given it has an empty backend. 
This should resolve the issue #1688. In the issue it is furthermore mentioned that a 503 should also be sent when a backend is completely missing. At the moment though, a frontend is not loaded in the `loadConfig` method, given there is no dedicated backend for it. See [here](https://github.com/containous/traefik/blob/2ddae2e856379f7ce2fb9b6509712e1ad523deeb/server/server.go#L689). This looks to me that this case is actually not intentioned to happen. @dtomcej and @timoreimann you had quite some discussions about this topic, WDYT about that case?
Fixes #1688
=> return 503 on empty backend

provider/marathon/marathon.go, provider/marathon/marathon_test.go
We previously assigned them to a copy of each application, which effectively disabled all filtering.
Fixes a bug introduced along commit 779eeba.
Ignore the nasty test struct please; in #1871, the fix will look much nicer. :-)
=> Assign filtered tasks to apps contained in slice.

docs/toml.md, server/configuration.go, traefik.sample.toml
Documentation stated that GraceTimeOut describes the timeout between
hot-reloads, which is not the case. GraceTimeOut describes the timeout
Traefik uses to finish serving active requests before stopping only.
=> fix GraceTimeOut documentation

provider/marathon/builder_test.go, provider/marathon/marathon.go, provider/marathon/marathon_test.go, testhelpers/helpers.go
This change introduces the builder pattern to the Marathon unit tests in order to simplify and reduce the amount of testing boilerplate.
Additional changes:
- Add missing unit tests.
- Make all tests look consistent.
- Use dedicated type for task states for increased type safety.
- Remove obsoleted `getApplication` function.
Note: I pushed the branch to the containous repo because I intend to submit another PR based onto this one.
@containous/marathon @containous/traefik PTAL.
=> Use test builder.

docs/user-guide/kubernetes.md
Previously only existed in the Github-hosted example file.
Fixes an oversight from #1707.
=> Add secrets resource to in-line RBAC spec.

glide.lock, glide.yaml, integration/fixtures/websocket/config.toml, integration/integration_test.go, integration/websocket_test.go, vendor/github.com/vulcand/oxy/forward/fwd.go, vendor/github.com/vulcand/oxy/forward/headers.go
- Use the new websocket implementation in oxy, based on gorilla/websocket
- Add integration tests for verify websocket
fixes #1858 
In order to reproduce the issue:
```bash
docker run -d --name="home-assistant" \
--restart=always \
-v $PWD/config:/config \
-v /etc/localtime:/etc/localtime:ro \
-p 8123:8123 \
--label traefik.port=8123 \
--label traefik.frontend.rule="Host:127.0.0.1" \
homeassistant/home-assistant
```
```
./traefik --docker=true
```
Then just try to view the homepage (http://127.0.0.1)
=> New oxy with gorilla for websocket with integration tests

docs/toml.md, docs/user-guide/kubernetes.md, provider/kubernetes/kubernetes.go, provider/kubernetes/kubernetes_test.go
Added ability to specify ```traefik.frontend.priority``` priority from kubernetes ingress annotation.
This is useful when you have following case:
Ingress A:
Host: *.mydomain
Ingress B:
Host: specific.mydomain
=> Added ability to override frontend priority for k8s ingress router

examples/k8s/traefik-deployment.yaml, examples/k8s/traefik-ds.yaml
Moves the `namespace` key to the correct location in the k8s examples. Currently, these fail with a `found invalid field namespace for v1.ServiceSpec` validation error.
=> Moved namespace to correct place

Makefile, glide.lock, glide.yaml, integration/fixtures/marathon/simple.toml, integration/marathon_test.go, integration/resources/compose/marathon.yml, vendor/github.com/docker/libcompose/docker/service/service_create.go
This is a continuation of #1398.
The tests do not succeed yet, apparently because the external network isn't applied.
=> Improve Marathon integration tests.

cmd/traefik/traefik.go, docs/basics.md, integration/access_log_test.go, integration/fixtures/log_rotation_config.toml, integration/fixtures/traefik_log_config.toml, integration/integration_test.go, integration/log_rotation_test.go, log/logger.go, middlewares/accesslog/logger.go, server/server.go, server/server_signals.go, server/server_signals_windows.go
See Issue [#1696](https://github.com/containous/traefik/issues/1696)
Traefik can currently write to two log files, the traefik log and an access log. These log files grow 
continuously and there is no mechanism for rotating, compressing, or archiving them.
This PR lets Traefik to respond to a USR1 signal by closing and reopening its log files, allowing external software, such as log rotate to be used for the above purposes.
=> Add log file close and reopen on receipt of SIGUSR1

README.md, docs/index.md
This PR changes the video in the readme to the new video made at GopherCon 2017. As it is less than 10m long, it makes a good quick introduction.
=> Change Traefik intro video

examples/k8s/ui.yaml
When deploying traefik on my local kubernetes cluster, I saw that the UI didn't display correctly. I narrowed it down to the ingress port mismatch with the traefik deployment.
=> examples/k8s: fix ui ingress port out of sync with deployment

docs/toml.md
=> Mark Marathon and Kubernetes as constraint-supporting.

docs/toml.md, docs/user-guide/marathon.md, provider/marathon/builder_test.go, provider/marathon/marathon.go, provider/marathon/marathon_test.go, provider/marathon/readiness.go, provider/marathon/readiness_test.go, traefik.sample.toml
This change adds support for Marathon readiness checks: If the option is set on Traefik and applications are found to come with configured readiness checks, the check results (as conducted by Marathon and exposed through its API) will be taken into account at deployment times
in order to decide if a task should be taken into load-balancing rotation or not.
Note that I had to extend the event filter that controls how often the Marathon provider polls the API so that the readiness checker is able to pick up all necessary readiness state transitions.
Fixes #1185, #1559
Based on #1871 for now; will be rebased onto master once the dependent branch gets merged.
=> Add support for readiness checks.

cmd/traefik/traefik.go, docs/toml.md, integration/fixtures/timeout/forwarding_timeouts.toml, integration/integration_test.go, integration/resources/compose/timeout.yml, integration/timeout_test.go, server/configuration.go, server/server.go, server/server_test.go, traefik.sample.toml
This PR adds some configurable timeouts to Traefik. Namely it introduces:
- ForwardingTimeouts -> Timeouts for forwarding requests to the Backend Server's. In specific
- DialTimeout
- ResponseHeaderTimeout
- RespondingTimeouts -> Timeouts for the `http.Server` instances that Traefik opens. 
- ReadTimeout
- WriteTimeout
- Move of IdleTimeout into this configuration section with proper deprecation for uniformity.
The motivation for this PR are the suboptimal default settings of go itself and it is important to make the load balancer robust against bad behaving clients / backends in a microservice environment.
In order to introduce this configuration options I had to first clean up the global modification of the `http.DefaultTransport`. I think a global modification of it is in general …
=> Add configurable timeouts and curate default timeout settings

provider/kubernetes/kubernetes.go, provider/kubernetes/kubernetes_test.go
Conventionally all providers should return a priority of zero if no override is given. The server package will then compute the priority based on the specified rules (i.e., path and host components). See also [here](https://github.com/containous/traefik/blob/94f922cd288ae5110d76be190e26d49d194fa6f9/server/server.go#L868-L870) and [here](https://github.com/containous/traefik/blob/94f922cd288ae5110d76be190e26d49d194fa6f9/server/server.go#L1021) in the server package.
The Kubernetes provider diverges and returns the path length as default value explicitly. This change removes the custom behavior.
As a side refactoring, we change the tests to stop comparing JSON values which are prone to subtle but non-visible differences (namely, nil and empty properties are not reflected). Instead, we use …
=> Use default frontend priority of zero.

docs/toml.md, traefik.sample.toml
It's not the `default` namespace that's watched if nothing is specified, but _all namespaces_.
Proof: Our [Namespaces type](https://github.com/containous/traefik/blob/60a35c8abae23ffbd58810d2ec2790d49e98bd72/provider/kubernetes/namespace.go#L9) is a string slice which we use in the [Kubernetes provider](https://github.com/containous/traefik/blob/60a35c8abae23ffbd58810d2ec2790d49e98bd72/provider/kubernetes/kubernetes.go#L50), and we [accept all Ingresses if the slice is empty](https://github.com/containous/traefik/blob/60a35c8abae23ffbd58810d2ec2790d49e98bd72/provider/kubernetes/client.go#L283-L285).
An alternative approach to fixing this would be to really make the `default` namespace the default. I don't think that's a good solution though because we probably want users to be able to …
=> Fix docs about default namespaces.

docs/toml.md, integration/marathon_test.go, provider/docker/docker.go, provider/marathon/builder_test.go, provider/marathon/marathon.go, provider/marathon/marathon_test.go, provider/provider.go, templates/marathon.tmpl, types/common_label.go
=> Support multi-port service routing for containers running on Marathon

glide.lock, glide.yaml, middlewares/compress.go, middlewares/compress_test.go, vendor/github.com/NYTimes/gziphandler/gzip.go, vendor/github.com/NYTimes/gziphandler/wrapper.go
before the fixes: when compress is enable and the content is already compress, the status code is not preserved.
Fixes #1937
=> compress: preserve status code

cmd/traefik/traefik.go, docs/basics.md, server/web.go
This PR adds a `traefik healthcheck` command that can be used by Docker with the new [`HEALTHCHECK`](https://docs.docker.com/engine/reference/builder/#healthcheck) instruction (see https://github.com/containous/traefik-library-image/pull/12).
The `web` provider needs to be enabled.
/cc @EtienneDufresne @vdemeester 
Fixes #1560
=> Add healthcheck command

docs/toml.md, traefik.sample.toml
Parameters were using colons where they should be equal signs.
=> Fix documentation glitches.

docs/basics.md, server/rules.go
As title says
Usage:
```
Query: foo=bar, bar=baz
```
=> Add support for Query String filtering

provider/provider.go, provider/provider_test.go
Added a check to ensure `clientTLS` configuration contains either a cert or a key
If any of the `ClientTLS` only sets `InsecureSkipVerify` property to `true`, the `CreateTLSConfig()` method fails, because it expects a `Cert` or a `Key` property to always be present.
=> Added a check to ensure clientTLS configuration contains either a cert or a key

docs/toml.md, provider/ecs/ecs.go, templates/ecs.tmpl
The goal of this PR is to add support of sticky session for ECS.
Low balancer configuration will be always present with default values:
`traefik.backend.loadbalancer.method=wrr`
`traefik.backend.loadbalancer.sticky=false`
To override these values you just to add labels 
Fixes #1522
=> Enable loadbalancer.sticky for ECS

cmd/traefik/configuration.go, cmd/traefik/traefik.go, configuration/configuration.go, integration/log_rotation_test.go, provider/web/web.go, server/server.go, server/server_test.go, types/types.go
- split the globalconfiguration to a new package (not in package server)
- split traefik configuration and global configuration
- webprovider is now in package provider
- the run func need a global configuration and not a traefik configuration
=> Refactor globalConfiguration / WebProvider

cmd/traefik/configuration.go, docs/toml.md, integration/consul_catalog_test.go, integration/resources/compose/consul_catalog.yml, provider/consul/consul_catalog.go, provider/consul/consul_catalog_test.go, templates/consul_catalog.tmpl, traefik.sample.toml
Add feature to control in consul service catalog if services are exposed by default or not.
`exposedByDefault = true|false`
Fixes #854
=> Exposed by default feature in Consul Catalog

auth/forward.go, integration/consul_test.go, middlewares/authenticator.go, middlewares/authenticator_test.go, provider/docker/docker.go, provider/kv/kv.go, provider/marathon/marathon.go, provider/provider.go, provider/provider_test.go, traefik.sample.toml, types/types.go
This implements forward authentication, much like in `ngx_http_auth_request_module`.
Based on the discussion in #1030 and [Proposal Doc](https://docs.google.com/document/d/1-DUcCt1k_sgyRurOxcSd4T0bgQvFRvIm4rBdDf1b5bc/edit), it's clear we needed to start with something simple and then build on it later. This implementation is a simplified version of @vladshub's implementation in #1030, removing the request and response body header/query parameter manipulation.
When forward auth is enabled, the request is first forwarded to the specified auth server. If the auth server responds with a 2XX status, the original request is performed. Otherwise, the response from the auth server is returned.
If everyone agrees this is a good starting point, I think the next step would be either copying or …
=> Add forward authentication option

README.md, docs/index.md
This PR update the documentation for the next 1.4 release.
=> Update documentation for 1.4 release

README.md, build.Dockerfile, configuration/configuration.go, docs/toml.md, glide.lock, glide.yaml, server/server.go, server/server_test.go, traefik.sample.toml, vendor/github.com/armon/go-proxyproto/LICENSE, vendor/github.com/armon/go-proxyproto/protocol.go
This PR supersedes #1145 to add [Proxy Protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) support. It is based on the initial work made by [jrb](https://github.com/jrb).
it also bumps Golang to 1.9 (needed to add Proxy Protocol).
Fixes #384
=> Add proxy protocol

CONTRIBUTING.md, cmd/traefik/traefik.go
Signed-off-by: Arika Chen <eaglesora@gmail.com>
Update golang version to 1.9 while using `Server.ServeTLS`
---
Edit by @emilevauge: The initial PR that moves to Go 1.9 is https://github.com/containous/traefik/pull/2004.
The current PR updates the contributing documentation.
=> Update golang version in contributing guide

docs/basics.md, docs/configuration/commons.md, docs/user-guide/marathon.md
Fix error pages configuration.
Related to https://github.com/containous/traefik/pull/1675#discussion_r136500552
=> Fix error pages configuration.

provider/rancher/api.go
This one fixes #1999 and makes it possible that traefik can get the current configuration out of rancher again :)
Test Image (Based on 1.4-rc1) : https://hub.docker.com/r/santode/traefik:experimental
=> fix rancher api environment get

log/logger.go
The default setting in `logrus` is to send the logs to stderr. The documentation states already that the output should be sent to stdout.
=> Send traefik logs to stdout

provider/ecs/cluster_test.go, provider/ecs/ecs.go, provider/ecs/ecs_test.go, templates/ecs.tmpl
Small refactoring of ECS provider and improve tests
=> ECS provider refactoring

docs/configuration/backends/ecs.md
The required IAM policy uses spaces in the `Sid` field, but this is not allowed by IAM. As a result, attempting to create this policy results in a validation error. The fix is simply to remove the spaces from the `Sid`.
=> Fix IAM policy sid.

middlewares/accesslog/logger_formatters.go, middlewares/accesslog/logger_formatters_test.go
=> Access log default values

docs/basics.md
Currently paths in server `url` is silently ignored, and it makes confusion (see #561 for example). Update the doc to address the limitation.
=> doc: add notes on server urls with path

docs/configuration/backends/ecs.md, provider/ecs/ecs.go, provider/ecs/ecs_test.go, templates/ecs.tmpl
Implements frontend basic auth for ecs provider.
This addresses the ecs part of #1465
=> Add basic auth for ecs

glide.lock, glide.yaml, middlewares/compress.go, middlewares/compress_test.go, vendor/github.com/NYTimes/gziphandler/gzip.go, vendor/github.com/NYTimes/gziphandler/wrapper.go, vendor/github.com/vulcand/oxy/forward/fwd.go
- https://github.com/containous/traefik/pull/1948
- https://github.com/containous/traefik/pull/2077
=> Fix: compress and oxy

server/server.go, server/server_test.go
This PR fixes a bug in `Server.prepareServer`.
=> Fix error in prepareServer

middlewares/metrics.go
=> prometheus, HTTP method and utf8

docs/basics.md, glide.lock, glide.yaml, integration/fixtures/ratelimit/simple.toml, integration/integration_test.go, integration/ratelimit_test.go, integration/resources/compose/ratelimit.yml, server/server.go, types/types.go, vendor/github.com/mailgun/minheap/LICENSE, vendor/github.com/mailgun/minheap/minheap.go, vendor/github.com/mailgun/ttlmap/LICENSE, vendor/github.com/mailgun/ttlmap/ttlmap.go, vendor/github.com/vulcand/oxy/ratelimit/bucket.go, vendor/github.com/vulcand/oxy/ratelimit/bucketset.go, vendor/github.com/vulcand/oxy/ratelimit/tokenlimiter.go
This is to add a rate limiting capability in Traefik, as in #643 
- Integrate the oxy ratelimit package
- Add Rate and RateLimit types for frontend configuration 
- Add rate limiting integration test
- Update glide/vendor with new package dependencies
- Add configuration example to basics doc
=> Rate limiting for frontends

docs/user-guide/kubernetes.md
I also removed all existing resource specifications just to make sure people aren't taken them at face value.
/cc @kachkaev
Fixes #1908.
=> Add guide section on production advice, esp. CPU.

docs/user-guide/examples.md
via regular entrypoint and dedicated entrypoint.
Add examples of how to expose `/ping` on one of:
* a regular entrypoint
* a dedicated port entrypoint
This is distinct from running it on the normal admin port (default to `:8080`) and allows you to expose `/ping` to other networks without exposing the admin port.
As requested by @ldez .
Closes #2094
=> Add examples of proxying ping

docs/configuration/commons.md
In particular, someone with sufficient expertise please acknowledge that custom error pages can really be used with the key/value stores we support.
Refs #2035.
=> Document custom error page restrictions.

provider/rancher/api.go
Until now traefik was setting up `PrimaryIpAddress` which is only set for managed network. When host network is chosen, traefik has to setup the IP address of the host machine where the container is running. As shown on the picture below `ghot-1` is on **host** network and `ghot` is on **managed** network.
Fixes  #1498
=> Fix rancher host IP address

log/logger.go, log/logger_test.go, middlewares/accesslog/logger.go, middlewares/accesslog/logger_test.go, server/server_signals.go
There is the chance that Traefik looses log lines for requests during rotation of the log file. This is at the moment true for the traefik log file as well as the access log files. I added two unit tests to prove this. This was also responsible for one flaky behaviour in the integration test [here](https://semaphoreci.com/containous/traefik/branches/pull-request-2054/builds/2).
For the traefik logs this is accomplished by opening the new log file before closing the previous one. The traefik logs use the global `logrus` instance and it is already protected by a mutex on rotation. For the access logs such a mutex also had to be introduced.
I think there is some potential in refactoring and aligning the two logging implementations in order to avoid duplicate code when it comes to the file …
=> Enable loss less rotation of log files

configuration/configuration.go, configuration/configuration_test.go
- `Redirect.Regex`: fix invalid value regex
- `Redirect.Regex`: `RedirectPRegex` is now invalid
- `Redirect.EntryPoint`: `RedirectXEntryPoint`  is now invalid
- `Redirect.Replacement`: `RedirectYReplacement`  is now invalid
- Create a standard string to bool converter
- refactor `EntryPoints.Set()` (split in several functions)
- add a lot of tests
=> Fixes entry points configuration.

glide.lock, glide.yaml, integration/access_log_test.go, vendor/github.com/go-check/check/check.go, vendor/github.com/go-check/check/checkers.go, vendor/github.com/go-check/check/helpers.go, vendor/github.com/go-check/check/reporter.go, vendor/github.com/go-check/check/run.go
Now if one test fail all other tests are skipped.
=> Fail fast in IT and fix some flaky tests

healthcheck/healthcheck.go, integration/fixtures/healthcheck/port_overload.toml, integration/healthcheck_test.go, server/server.go, types/types.go
according to this bug report : #2099
this fix add some missing code to overriding the healthcheck port.
Fixes #2099
=> fix healthcheck port

auth/forward.go, docs/configuration/entrypoints.md, middlewares/auth/authenticator.go, middlewares/auth/authenticator_test.go, middlewares/auth/forward.go, middlewares/auth/forward_test.go, middlewares/auth/parser.go, provider/web/web.go, server/server.go, types/types.go
- copy request headers
- add `X-Forwarded-*` headers
=> Manage Headers for the Authentication forwarding.

cmd/traefik/configuration.go, server/server.go, server/server_test.go
This PR fixes loading of the deprecated top-level option `IdleTimeout`. Also, it changes the semantics so that the deprecated option is now preferred and a warning is logged when it is used.
_All the different configuration constellations I also verified via the matching CLI parameters as well._
I tried the following configs and they deliver now the expected results:
```toml
```
-> default timeout of 30 seconds is used
```toml
idleTimeout="42s"
```
-> deprecated option of 42 seconds is used
```toml
idleTimeout="42s"
[respondingTimeouts]
```
-> deprecated option of 42 seconds is used
```toml
idleTimeout="42s"
[respondingTimeouts]
idleTimeout="23s"
```
-> deprecated option of 42 seconds is used
```toml
idleTimeout="42s"
[respondingTimeouts]
readTimeout="23s"
```
-> deprecated option of 42 …
=> Fix deprecated IdleTimeout config

middlewares/retry.go
This PR fixes #1862. I created a new PR as there was no feedback on https://github.com/containous/traefik/pull/1870 and some implementation details are different, yet the fix is more or less the same.
This fix is already running in our infra for about 2 weeks. I was trying to set up an unit-test, which proved difficult. I am currently thinking about setting up an integration test for this, but that might also prove difficult. Let me know whether you think it is an absolute necessity to have an integration test for that or not.l
=> fix SSE subscriptions when retries are enabled

cmd/traefik/configuration.go, cmd/traefik/traefik.go, configuration/configuration.go, docs/configuration/commons.md, traefik.sample.toml, types/types.go
This PR adds the possibility to use JSON format for the traefik logs. 
Also it aligns the configuration to the accessLogs and deprecates the `traefikLogsFile` option.
Sample log line:
```json
{"level":"info","msg":"Traefik version dev built on I don't remember exactly","time":"2017-09-05T02:34:52+02:00"}
```
This fixes https://github.com/containous/traefik/issues/780.
=> add json format support for traefik logs

contrib/scripts/dumpcerts.sh
I beefed up the script to extract certs and private keys from acme.json, thought I'd share. The sed script needed a bit of tweaking (`-E` switch, `>>` instead of `>`), and I added an openssl check after the sed script to double-check the generated script is correct.
Also, the certificate files were being saved as `*.pem` instead of `*.crt`, and the domain private keys weren't being extracted. I corrected that.
Finally, I cannot for the life of me get the `openssl` script to work (`openssl rsa -inform` etc.). If someone can confirm it works for them, I'll just write it off to me being dumb.
=> Dumpcerts.sh: fixed sed, extracted domain keys

cluster/datastore.go
Clear Object first, as mapstructure's decoder doesn't have ZeroFields set to true for merging purposes
Fixes #2153
=> Be certain to clear our marshalled representation before reloading it

docs/user-guide/swarm-mode.md
This PR is updating the Docker Swarm Mode documentation with examples created with latest version of Docker. It also updates the section describing the access via sticky session by using `curl` command only instead of requiring to amend the `/etc/hosts` file and perform the test via web browser.
=> Updating Docker output and curl for sticky sessions

cmd/traefik/configuration.go, cmd/traefik/traefik.go, configuration/configuration.go, configuration/configuration_test.go, docs/configuration/commons.md, integration/basic_test.go, integration/fixtures/reqacceptgrace.toml, integration/resources/compose/reqacceptgrace.yml, server/server.go, server/server_signals.go
The new grace period defines how long Traefik should continue accepting requests prior to shutting down all connection listeners. It preceeds the existing (HTTP shutdown) grace period and allows for a full-circle graceful termination by expecting downstream load-balancers to take Traefik out of rotation in time, without the need for rather complex and external request draining procedures.
Immediate beneficiaries are providers such as Kubernetes and Marathon which expect in-cluster applications to exhibit the described termination behavior.
This PR addresses one of the two necessary TODOs for #1942. However, it also stands useful on its own.
=> Add request accepting grace period delaying graceful shutdown.

Makefile
The previous implementation of the `pull-images` is susceptible to a hideous formatting bug: If one of the docker-compose files is missing its newline, the cat-grep pipe would merge the grepped image name with the first line of the subsequent YAML file.
For instance, we had the following file with a single whoami image missing a newline:
```yaml
whoami:
image: emilevauge/whoami
```
The next compose file in order would be `timeout.yml` and start like this:
```yaml
timeoutEndpoint:
image: yaman/timeout
```
As a result, `make pull-images` would try to pull the image
```
emilevauge/whoamitimeoutEndpoint
```
and fail silently (which is another problem by the way).
Adding the missing newline fixes the problem but doesn't offer protection against this general problem in the future. Luckily, …
=> grep to-be-pulled-images directly to avoid newline issue.

docs/configuration/entrypoints.md
Fixes #2183 where a bug report was filed because it seemed like the compression middleware was not working because it intentionally does not compress small responses.
=> Improve compression documentation

integration/consul_catalog_test.go, provider/consul/consul_catalog.go
We need to reset the `current` state between two call to `GetServices`
Fixes #2155
=> Consul catalog remove service failed

provider/ecs/ecs.go
This PR fixes a bug in the ECS provider.
When the ECS Provider is configured to poll multiple clusters, it'll show unexpected behavior when one of the clusters has 'zero' tasks running.
1. If the first cluster Traefik encounters has no running tasks the listInstances function is ended immediately by returning an empty slice of ecsInstances. Successive clusters are simply ignored. 
2. If the 2nd or up cluster has no tasks running the listInstances function will continue trying to fetch data for these non-existing-tasks. The 'early return' condition will not detect this due to counting the length of taskArns slice. This slice var is used by each cluster discovery without being emptied, so it'll be filled with taskArns from the previous cluster. This eventually results in incomplete API …
=> Handle empty ECS Clusters properly

docs/user-guide/grpc.md
=> Update gRPC example

server/server.go, server/server_test.go
According to [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt) section 2.2 and [this StackOverflow response](https://stackoverflow.com/a/1969339), only a certain subset of characters is permitted in cookie names. Specifically, slashes contained may cause the cookie to not get set by certain browsers.
This change makes sure that the backend name embedded in the cookie name is sanitized accordingly.
=> Sanitize cookie names.

integration/log_rotation_test.go
This PR fixes https://github.com/containous/traefik/issues/2203 by waiting up to 3 seconds until the new log file is created after the signal was sent to Traefik to rotate the log files. Also, it improves logging of the log file output in case something is not correct to ease the detection of potential other problems that were hidden before.
=> fix flakiness in log rotation test

Makefile
This updates the build instructions in the Makefile to match what is in the documentation.  https://github.com/containous/traefik/blob/master/CONTRIBUTING.md#build-træfik 
In the current state when running `make run-dev` you get back a cryptic error 
```
runtime.main_main·f: relocation target main.main not defined
runtime.main_main·f: undefined: "main.main"
make: *** [run-dev] Error 2 
``` 
and this fixes that error.
=> Updating make run-dev

middlewares/stripPrefix.go, middlewares/stripPrefix_test.go
This PR enables stripping prefixes not only on slash boundaries but also inside of them. The actual mux routing was always capable of routing within the slash boundaries, only the prefix wasn't stripped properly.
Consider we have a fronted rule like `PathPrefixStrip:/stat` and we are calling Traefik with a Path like `/status`. This would route the request to the frontend/it's connected backends but the path wouldn't be stripped. With the fix provided in this PR it will properly strip and forward a path like `/us`.
While fixing this problem I realized that the `stripPrefix` middleware could actually be simplified while keeping all tests working properly.
As there was no bug-report by any other Traefik users I am unsure whether we still want to bring this into the 1.4 release. Let me know …
=> enable prefix matching within slash boundaries

docs/user-guide/kubernetes.md, examples/k8s/traefik-rbac.yaml
The client implementation does not require access to Pods.
=> Remove pod from RBAC rules.

docs/user-guide/kubernetes.md
Judging from support questions, many users seem to be unclear about the options they have to restrict Traefik to certain types of Ingresses. This Kubernetes guide extension is meant to shine some light on the matter.
=> Document ways to partition Ingresses in the k8s guide.

docs/configuration/backends/kubernetes.md, docs/user-guide/kubernetes.md
Otherwise, they'd be interpreted as numbers and rejected/dropped by the API server since annotations must always be strings.
Refs #2225.
=> Quote priority values in annotation examples.

provider/consul/consul_catalog.go, provider/docker/docker.go, provider/dynamodb/dynamodb.go, provider/ecs/ecs.go, provider/kubernetes/kubernetes.go, provider/kubernetes/kubernetes_test.go, provider/kv/kv.go, provider/marathon/marathon.go, provider/marathon/marathon_test.go, provider/provider.go, provider/rancher/rancher.go, server/cookie/cookie.go, server/cookie/cookie_test.go, server/server.go, server/server_test.go, templates/consul_catalog.tmpl, templates/docker.tmpl, templates/ecs.tmpl, templates/kubernetes.tmpl, templates/kv.tmpl, templates/marathon.tmpl, templates/rancher.tmpl, types/common_label.go, types/types.go
- add an option to configure manually cookie name (ensures compatibility).
- use a hash as cookie name by default.
Fixes #2175
=> Stickiness cookie name

docs/user-guide/grpc.md, integration/fixtures/grpc/config_insecure.toml, integration/grpc_test.go, server/server.go
`http2.configureTransport` was called only when RootCAs are configured, certainly a problem during a resolve conflict
=> Move http2 configure transport 

cmd/traefik/anonymize/anonymize_config_test.go, configuration/configuration.go, configuration/configuration_test.go, docs/configuration/entrypoints.md, middlewares/ip_whitelister.go, server/server.go, server/server_test.go, whitelist/ip.go, whitelist/ip_test.go
This PR adds mandatory trusted IP ranges declaration while enabling proxy protocol.
:warning:  **This change will break any `1.4.0-rcx` config with proxy protocol enabled.**
You need to update your config from:
```toml
[entryPoints]
[entryPoints.http]
address = ":80"
proxyprotocol = true
```
to 
```toml
[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.proxyProtocol]
trustedIPs = ["10.5.0.2", "127.0.0.1/8"]
```
with `10.5.0.2` being the IP address of your front load balancer.
I'm working on adding an integration test.
=> Add trusted whitelist proxy protocol

generate.go
Required to guarantee that `go test ./...` does not fail with
```
runtime.main_main·f: relocation target main.main not defined
runtime.main_main·f: undefined: "main.main"
```
=> Create dummy main() function in generate.go.

cmd/traefik/traefik.go, configuration/configuration.go, configuration/configuration_test.go, provider/web/web.go, server/server.go
This PR accomplishes two things: 
1. it makes sure that all traefik logs are written in the specified format. Before the first log messages were written in text, even when you specified JSON as the format. This is because some log output was produced before configuring the logs.
2. it makes sure that all traefik logs are written to the traefik logs file. This is implemented by using `logrus.Exit()` and by closing the file in a `logrus.RegisterExitHandler`.
I also changed that errors from `http.Serve` and `http.ServeTLS` are not logged anymore, in the case they are regular `http.ErrServerClosed` errors, which is expected and the normal case. Those methods will never return a non-nil error.
This fixes https://github.com/containous/traefik/issues/2156.
=> Fix traefik logs to behave like configured

CONTRIBUTING.md, Makefile, docs.Dockerfile, mkdocs.yml
Add `docs` target to makefile to test documentation with docker.
=> Add docker things for documentation

provider/kubernetes/kubernetes.go, provider/kubernetes/kubernetes_test.go
We previously returned an error, thereby prematurely terminating any further Ingress processing.
Fixes #2239.
=> Continue processing on invalid auth-realm annotation.

provider/rancher/metadata.go
This one fixes #2255. The Metadata Provider assumed for the Intervall Poll, that the given value is in seconds but instead it was in ms. So a multiplication with seconds was needed. 
You can test it upfront with my experimental image:
santode/traefik:heavy_load
=> fix seconds to really be seconds

provider/consul/consul_catalog.go, provider/consul/consul_catalog_test.go, provider/docker/docker.go, provider/docker/docker_test.go, provider/ecs/ecs.go, provider/kubernetes/kubernetes.go, provider/kubernetes/kubernetes_test.go, provider/kv/kv.go, provider/kv/kv_mock_test.go, provider/kv/kv_test.go, provider/marathon/marathon.go, provider/marathon/marathon_test.go, provider/rancher/rancher.go, provider/rancher/rancher_test.go, server/server.go, templates/consul_catalog.tmpl, templates/docker.tmpl, templates/ecs.tmpl, templates/kubernetes.tmpl, templates/marathon.tmpl, templates/rancher.tmpl
- Add missing quotes. 😞 
- Add retro compatibility with 1.3
Related to #2232
Fixes #2249
=> Stickiness cookie name.

provider/docker/docker.go
Changed network filtering parameters in docker provider to allow any swarm scoped network, not only overlay network.
This fixes #2019
=> Changed Docker network filter to allow any swarm network

configuration/configuration.go, configuration/configuration_test.go
Fix a problem when you write `--entryPoints='Name:http Address::8080'` (you must add a space at the end : `--entryPoints='Name:http Address::8080 '`)
Side effect:
- entrypoint configuration is now case insensitive 🎉
=> New entry point parser.

docs/basics.md, provider/consul/consul_catalog.go, provider/consul/consul_catalog_test.go, provider/docker/docker.go, provider/docker/docker_test.go, provider/ecs/ecs.go, provider/kubernetes/kubernetes.go, provider/kubernetes/kubernetes_test.go, provider/kv/kv.go, provider/kv/kv_test.go, provider/marathon/marathon.go, provider/marathon/marathon_test.go, provider/rancher/rancher.go, provider/rancher/rancher_test.go, server/server.go, templates/consul_catalog.tmpl, templates/docker.tmpl, templates/ecs.tmpl, templates/kubernetes.tmpl, templates/kv.tmpl, templates/marathon.tmpl, templates/rancher.tmpl
if `sticky=true` -> `cookieName="_TRAEFIK_BACKEND"`
for new custom `cookieName` feature:
- must add `stickiness=true`
- add `cookieName="MyCookie"`
----
summary:
| Options                                   | Result                                                                              |
|-------------------------------------------|-------------------------------------------------------------------------------------|
| only`stickiness=true`                     | activate sticky session and use a 6 chars cookie name (abbrev sha1)                 |
| only`sticky=true`                         | (deprecated) activate sticky session and use the old cookie name `_TRAEFIK_BACKEND` |
| `stickiness=true` and `sticky=true`       | same as `stickiness=true` …
=> Backward compatibility for sticky

glide.lock, glide.yaml, integration/fixtures/websocket/config_https.toml, integration/websocket_test.go, vendor/github.com/vulcand/oxy/forward/fwd.go
fixes #2280
related to https://github.com/containous/oxy/pull/31
=> Force http/1.1 for websocket

docs/configuration/entrypoints.md, docs/user-guide/examples.md
The mechanism used to redirect URLs between entrypoints does not use the fields `regex` and `replacement`, which are overriden if defined.
The PR adds precision about this point in documentation.
=> Add a note about redirection rule to precise how regex/replacement work.

provider/docker/docker.go
Regression from #2244
Fixes #2297
=> Network filter

cmd/traefik/traefik.go, configuration/configuration.go, provider/web/web.go, server/server.go
This PR fixes healthcheck path.
Fixes #2273
=> fix healthcheck path

requirements.txt
The build failed because of mkdocs version.
```console
Traceback (most recent call last):
File "/home/travis/.local/bin/mkdocs", line 11, in <module>
sys.exit(cli())
File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
return callback(*args, …
```
=> Fix mkdocs version

docs/user-guide/kubernetes.md
This fixes the namespace in the docs to also be kube-system, just like
the yaml in the examples says.
=> Fix the k8s docs example deployment yaml

provider/ecs/ecs.go, provider/ecs/ecs_test.go
- Some functions were missing, this adds them to the function
map passed into the template loader
- Adds testing around generating ECS configuration
- This regression was added in #2050
When using ECS, on Traefik start these messages appear in the logs:
```
time="2017-10-24T14:16:51Z" level=error msg="Provider connection error template: :12: function "getProtocol" not defined, retrying in 8.97478573s"
```
=> Add missing functions for ECS template

provider/docker/builder_test.go, provider/docker/docker.go, provider/docker/docker_test.go
This adds support for using the Swarm Node IP when running Swarm Standalone mode (https://github.com/docker/swarm) with a container configured with host networking.
The Node IP that is provided through the Swarm API is one that is reachable by the manager, and is generally reachable by each of the Swarm workers: https://github.com/docker/swarm/blob/master/cli/flags.go#L30-L33
=> Use Node IP in Swarm Standalone with "host" NetworkMode

cluster/datastore.go
This commit fixes a corruption in the datastore that leads to workers becoming
unresponsive due to an invalid configuration.
The bug occurs when the cluster config serialization output length shrinks
below the current config's output length. This typically only happens on
workers since leaders modify their own config directly instead of importing the
serialized version from the kv backend.
This commit truncates the object field before reloading the new config from the
kv, as is done during initial config load.
fixes #2328
=> Fix datastore corruption on reload due to shrinking config size

integration/docker_test.go, provider/docker/docker.go, provider/docker/docker_test.go, provider/docker/swarm_test.go
Because the frontend names are based on the `route` names, it's not possible to set frontends with similar routes (as described in #1070).
This PR adds an index to all frontends names to avoid the problem.
Fixes #1070
=> Make frontend names differents for similar routes

docs/configuration/entrypoints.md
Typo in docs. May save more than one headache for users who copy and paste from the docs.
=> entrypoints -> entryPoints

provider/docker/docker.go
This PR allows returning an IP address for a Docker container which is in `container` network mode.
Fixes #756
=> Fix IP address when Docker container network mode is container

docs/configuration/backends/docker.md, docs/user-guide/docker-and-lets-encrypt.md, integration/docker_test.go, provider/docker/docker.go, provider/docker/docker_test.go
All Docker containers which use `service labels` with no value for the `container label` named `traefik port` are filtered.
This PR fixes this problem.
Fixes : #1321 #1840
=> Make the traefik.port label optional when using service labels in Docker containers.

provider/marathon/marathon_test.go, templates/marathon.tmpl
Fixed an issue of missing Backend key in configuration when no tasks are available for an application
If Marathon application has no valid tasks in existence (either because the tasks are in bad state or they are in the process of being started or shut down), the generated configuration is completely missing the Backend key entry for the bound Frontend, resulting in a 404 response from Traefik instead of the expected 503.
=> Missing Backend key in configuration when application has no tasks

contrib/scripts/dumpcerts.sh
Alpine Linux' "base64" does not support the `--decode` option. Only `-d`. 
In order to run `dumpcerts.sh` inside the office "traefik:1.4-alpine" docker-image,
`base64` must be called with `-d`
=> dumpcerts.sh: Fix call to "base64" for Alpine

types/common_label.go
When looking for the supported labels I noticed a typo in the "...frontend.headers.customresponseheaders" label. This PR fixes this typo.
=> Fix typo in frontend.headers.customresponseheaders label

script/crossbinary-default, script/crossbinary-others
Build binaries for windows does not have the ".exe" postfix so it's always a hassle to rename the files. In addition to that, some people (mostly beginners) do have problems start using traefik the first time.
This PR is adding the ".exe" postfix to the filename on build.
=>  Postfix windows binaries with .exe

cmd/traefik/anonymize/anonymize_doOnJSON_test.go, glide.lock, middlewares/compress_test.go, middlewares/headers.go, middlewares/headers_test.go, vendor/github.com/NYTimes/gziphandler/gzip.go
Fixes #2351 
related to https://github.com/NYTimes/gziphandler/pull/58
=> Keep status when stream mode and compress

docs/configuration/backends/kubernetes.md, docs/user-guide/kubernetes.md
Adds additional documentation to help people setup basic auth with kubernetes ingress.
I was unable to easily find the information I needed to create the secret. I had to resort to tracking down the original PR for that feature.
I think the instructions to create the dashboard auth user and password (types of encryption) is the same for adding auth to an ingress but I could not confirm so I let it as is.
Note: Sublime must have removed some invisible trailing spaces, I see a bunch of lines that are modified but not changed.
=> Add secret creation to docs for kubernetes backend

provider/marathon/marathon.go
This became obsolete at a point when we refactored/simplified the Marathon tests.
=> Remove unused lightMarathonClient.

cmd/traefik/anonymize/anonymize_config_test.go, configuration/configuration.go, configuration/configuration_test.go, docs/basics.md, docs/configuration/entrypoints.md, integration/fixtures/https/clientca/https_1ca1config.toml, integration/fixtures/https/clientca/https_2ca1config.toml, integration/fixtures/https/clientca/https_2ca2config.toml, integration/https_test.go, server/server.go, tls/tls.go, types/types.go
Allow adding optional client CA files.
More details in proposal #2288.
Fixes #2286 #2288
=> Allow adding optional Client CA files

middlewares/compress.go, middlewares/compress_test.go
Exclude GRPC from compress
GRPC provide an internal compression [system](https://github.com/grpc/grpc/blob/master/doc/compression.md).
=> Exclude GRPC from compress

integration/consul_catalog_test.go, integration/resources/compose/consul_catalog.yml, provider/consul/consul_catalog.go, provider/consul/consul_catalog_test.go
This PR fix Træfik's reload if Consul Catalog tags change
Fixes #2370
@trondhindenes Could you please try with my experimental image `mmatur/traefik:fix-consul-tag-change`
=> Fix Traefik reload if Consul Catalog tags change

glide.lock, glide.yaml, vendor/github.com/NYTimes/gziphandler/gzip.go
Only flush once startGzip has been called
This prevents the underlying Flusher
from writing the wrong status code or writing
headers before Content-Encoding has been set.
=> Flush and errorcode

docs/user-guide/kv-config.md, provider/kv/kv.go
Add the prefix `Treafik` to the key used to check the connection to the KV stores.
Fixes #2394
=> Add Traefik prefix to the KV key

CHANGELOG.md, docs/configuration/backends/kubernetes.md, docs/user-guide/docker-and-lets-encrypt.md, docs/user-guide/examples.md, docs/user-guide/kubernetes.md, docs/user-guide/kv-config.md, glide.lock, glide.yaml, integration/consul_catalog_test.go, integration/resources/compose/consul_catalog.yml, middlewares/compress.go, middlewares/compress_test.go, provider/consul/consul_catalog.go, provider/consul/consul_catalog_test.go, provider/kv/kv.go, script/crossbinary-default, script/crossbinary-others, vendor/github.com/NYTimes/gziphandler/gzip.go
Merge v1.4.2 into master
Be sync.
=>  Merge v1.4.2 into master

server/server.go
http.Server log goes to Debug level.
Fixes #1827
=> http.Server log goes to Debug level.

docs/configuration/backends/kubernetes.md, provider/kubernetes/kubernetes.go, provider/kubernetes/kubernetes_test.go, types/common_label.go
Add labels:
- `traefik.frontend.entryPoints`
- `traefik.frontend.passTLSCert`
=> Add labels for `traefik.frontend.entryPoints` & `PassTLSCert` to Kubernetes

api/dashboard.go, api/debug.go, api/handler.go, healthcheck/healthcheck.go, integration/consul_test.go, integration/docker_test.go, integration/https_test.go, integration/websocket_test.go, metrics/prometheus.go, middlewares/accesslog/logger_test.go, middlewares/error_pages_test.go, middlewares/retry.go, middlewares/retry_test.go, ping/ping.go, provider/rest/rest.go, version/version.go
use `http.Status*` and `http.Method*`
to be homogeneous
=> Use contants from http package.

api/debug.go, docs/configuration/api.md, docs/configuration/commons.md
The handlers will be hooked up under the `/debug/pprof` endpoint (enabled via the `--debug` flag).
This is to assist debugging performance problems.
Closes #1648
=> Register pprof handlers.

provider/mesos/mesos_test.go, provider/rancher/rancher.go, provider/rancher/rancher_test.go
Run Rancher tests cases in parallel.
Speed up tests.
=> Run Rancher tests cases in parallel.

provider/rancher/rancher.go
Fix issue using label `traefik.backend.loadbalancer.stickiness.cookieName` at rancher provider.
When label `traefik.backend.loadbalancer.stickiness.cookieName` is used with rancher provider, 
get errors message 
`18/11/2017 13:28:59time="2017-11-18T12:28:59Z" level=error msg="template: :14:24: executing "" at <getStickinessCookieN...>: wrong number of args for getStickinessCookieName: want 2 got 1"` 
https://github.com/rawmind0/rancher-traefik/issues/57
=> Fix issue with label traefik.backend.loadbalancer.stickiness.cookieName

glide.lock, glide.yaml
Remove GzipHandler Fork
Remove a fork.
Related to #2380 and https://github.com/NYTimes/gziphandler/pull/60
=> Remove GzipHandler Fork

cmd/traefik/configuration.go, cmd/traefik/storeconfig.go, docs/user-guide/kv-config.md, integration/consul_test.go, provider/file/file.go
This PR carries #2106 made by @aantono.
#2106 was closed by mistake :angel: 
Fixes #2036, #1682
=> Add file to storeconfig

docs/configuration/backends/marathon.md, provider/marathon/builder_test.go, provider/marathon/marathon.go, provider/marathon/marathon_test.go
Add support for filtering based on Marathon-defined constraints, as described in https://mesosphere.github.io/marathon/docs/constraints.html
Many Marathon clusters have applications deployed with various "constraints", configuring things like application service affinity, cluster binding, etc.  It would be very helpful to not have to add additional/duplicate `traefik.tags` labels to the applications and to be able to filter using already defined Marathon constraints instead.
=> Marathon constraints filtering

middlewares/stripPrefix.go, middlewares/stripPrefixRegex.go, middlewares/stripPrefixRegex_test.go, middlewares/stripPrefix_test.go
This PR fixes forwarding of URL encoded characters to the backend servers. 
Given that Traefik receives a request path in the form: `/some/a%2Fb` it should forward the same path to the backend. This is the case when using e.g. the rule type `PathPrefix`, but as soon as the rule type is either `PathPrefixStrip` or `PathPrefixStripRegex` the path was forwarded in the decoded form like: `/some/a/b`.
The reason why this solution fixes our problem is that go uses the `String()` method of the `URL` object when it constructs the request. The docs state for this:
> // String reassembles the URL into a valid URL string.
// The general form of the result is one of:
//
//	scheme:opaque?query#fragment
//	scheme://userinfo@host/path?query#fragment
//
// If u.Opaque is non-empty, String uses the first …
=> Fix raw path handling in strip prefix

examples/etcd-config.sh
Just fix typo issue,try to avoid mislead others.
=> Fix typo in examples

autogen/gentemplates/gen.go, docs/basics.md, docs/user-guide/kv-config.md, examples/consul-config.sh, examples/etcd-config.sh, integration/consul_test.go, integration/etcd3_test.go, integration/etcd_test.go, integration/fixtures/consul/simple_https.toml, integration/fixtures/etcd/simple_https.toml, templates/kv.tmpl
manage tls cert file and key file in the kv store dynamically,so we can add https service without restart traefik 
almost do the same thing with  PR #2401, but this will looks consistent with the other code, and support multi kv store.
=> Manage certificates dynamically in kv store

cmd/traefik/healthcheck.go, cmd/traefik/traefik.go
Mutualise code for `traefik healthcheck` command and watchdog.
Link to first version of watchdog implementation #818
=> Use healthcheck for systemd watchdog

docs/basics.md, middlewares/headers.go, middlewares/headers_test.go, server/server.go
This PR fix issue with custom headers. Before headers were not overridden but added.
Now if the custom header name is the same as one header name of the request or response, it will be replaced. 
Add feature to delete header
`X-Custom-Request-Header = ""` header `X-Custom-Request-Header` will be deleted
Related to #1155
=> Fix custom headers replacement

cmd/traefik/traefik.go, collector/collector.go, configuration/configuration.go, docs/basics.md, glide.lock, glide.yaml, vendor/github.com/mitchellh/hashstructure/LICENSE, vendor/github.com/mitchellh/hashstructure/hashstructure.go, vendor/github.com/mitchellh/hashstructure/include.go
https://github.com/containous/traefik/issues/2369
**This feature is disabled by default.**
In the future, as discussed in the [proposal](https://github.com/containous/traefik/issues/2369), this may be enabled by default.
https://github.com/containous/traefik/issues/2369
=> Stats collection.

docs/configuration/backends/kubernetes.md
Document the `filename` option for Kubernetes.
The option exists but is not documented.
=> Document filename parameter for Kubernetes.

docs/configuration/backends/kubernetes.md
**Update**: as suggested by @timoreimann I removed the links completely.
=> remove obsolete links in k8s docs

provider/kubernetes/kubernetes.go, provider/kubernetes/kubernetes_test.go
When rewrite-target is specified, any existing PathPrefix rule is
removed. Hence an ingress with rewrite-target is always matched
for the same host regardless of path prefix.
=> Fix kubernetes path prefix rule with rewrite-target

glide.lock, glide.yaml
'expose' as boolean. 
Fix a bug.
Related https://github.com/containous/traefik-extra-service-fabric/pull/5
=> fix: Service Fabric 'expose' as boolean.

autogen/gentemplates/gen.go, generate.go
To be homogeneous with `make fmt` command this PR add option `-s` to gofmt for autogen
=> Add option -s to gofmt for autogen

docs/configuration/backends/consul.md
This PR improve Consul documentation to give some examples of how to set Consul service tags to allow Træfik to use them
=> Improve consul documentation

glide.lock, glide.yaml, vendor/github.com/xenolf/lego/acme/dns_challenge.go, vendor/github.com/xenolf/lego/cli_handlers.go, vendor/github.com/xenolf/lego/providers/dns/azure/azure.go, vendor/github.com/xenolf/lego/providers/dns/dns_providers.go, vendor/github.com/xenolf/lego/providers/dns/godaddy/godaddy.go
The _intention_ is just to bump the version of lego up to aa94fb46, to add support for the GoDaddy DNS provider. But glide and I don't seem to get along very well. It seems to just want to update ALL THE THINGS. I tried just running
```
./script/glide.sh get github.com/xenolf/lego#aa94fb4696349fd6f35168dabe3ab030ddf3e484
```
but I'm told "lego is already in glide.yaml, dummy!"
I've seen that some of you have made very small changes to glide.yaml successfully, and I'd love to know how I can do it too!
Now that that https://github.com/xenolf/lego/pull/416 has been merged, it would be great it the version of lego could be bumped here in traefik so I don't have to keep making custom builds :)
=> Bump Lego Version for GoDaddy DNS Provider

glide.lock, vendor/github.com/containous/flaeg/flaeg.go
Update flaeg with containous/flaeg#39
Fix bug when you set `--web.metrics.prometheus`
When you set `--web.metrics.prometheus`, a flaeg bug set `--metrics` default value too.
When `--web` is set with `--metrics`, we ignore web options so `--web.metrics.prometheus` break the web option !
=> Doesn't ignore web params when web.metrics.prometheus is set

cmd/traefik/configuration.go, integration/basic_test.go, server/server.go
Fix issue when we set only the http entrypoint, `defaultEntrypoints` was no longer `[ http ]`, but `[]`
Fix issue when a frontend use two entrypoints and if the first entrypoint doesn't exist, the frontend is skipped
fixes #2494 #680
=> Fix wrong defaultentrypoint and unexisting entrypoint issue

provider/kubernetes/annotations_parser.go
Reduce logs with new Kubernetes security annotations.
Limit the number of unneeded logs.
Fixes #2500
=> Reduce logs with new Kubernetes security annotations

provider/docker/docker.go, provider/docker/swarm_test.go
Fixes #1494 
Currently we don't manage `DNSRR` resolution mode in Docker swarm mode. This PR only excludes services with `DNSRR` resolution mode. 
We will try to implement `DNSRR` resolution mode in Docker swarm mode ASAP
=> Fix empty IP for backend when dnsrr in Docker swarm mode

docs/configuration/backends/file.md
Clarifies the necessity of enabling a backend.
It's not obvious that the presence of empty [file] table means something; I spent quite some time trying to make the simplest file backend configuration work and only slack suggestions helped.
=> Emphasize the necessity of enabling file backend

api/debug.go
Index must go last, otherwise more specific endpoints are ignored.
=> Fix pprof route order.

acme/acme.go
This PR transforms the `DEBUG` logs generated during the ACME certificates renewing into `INFO` logs in the way to get more information about the process without getting all the others `DEBUG` logs.
Related #2158 and slack support about this subject.
This PR does not solve the problem but allows getting more information about it.
It seems to be a concurrent access problem.
A test is currently running in the way to repoduce the problem on a long period.
=> Modify the ACME renewing logs level

provider/kubernetes/builder_configuration_test.go, provider/kubernetes/builder_endpoint_test.go, provider/kubernetes/builder_ingress_test.go, provider/kubernetes/builder_service_test.go, provider/kubernetes/kubernetes_test.go
Use builders in k8s tests.
Simplify the maintenance.
=> Builders in k8s tests

provider/docker/docker.go, provider/dynamodb/dynamodb.go, provider/ecs/ecs.go
Does some simplification.
Makes code easier to understand since uses less tokens.
- drop `select` with only one `case`
=> Simplification

cmd/traefik/healthcheck.go, docs/basics.md
We tried to add the `web.path`, even if `web` is not defined. Moreover `web` is deprecated, we may use `ping` instead.
fixes #2524
=> fix healthcheck when web is not specified

server/server.go
Close the ring buffer used in the throttling function.
Not closing means leaking a buffer-internal goroutine.
=> Close ring buffer used in throttling function.

docs/configuration/backends/file.md, docs/user-guide/kv-config.md, integration/https_test.go, server/server.go, server/server_test.go, tls/certificate.go, tls/tls.go
The PR allows introducing a mechanism _by default_ for all the providers which add  TLScertificates dynamically.
If no entryPoints are given, the certificates are added to all of the `defaultEntryPoints` (from Træfik global configuration) wich have a TLS configuration.
This PR helps to create the certificates management from K8s secret (#2439)
=> Use default entryPoints when certificates are added with no entryPoints.

docs/basics.md
Please check if I understood `ResponseCodeRatio()` range logic right.
=> Fix broken links and improve ResponseCodeRatio() description

middlewares/auth/forward.go, middlewares/auth/forward_test.go
Added requested URI to auth server for Forward Authentication.
Missing feature for authentication decision based on the URI (frontend).
Added implementation, docs and test.
Could be good enough for #2162 as well.
=> Forward Authentication: add X-Forwarded-Uri

docs/configuration/acme.md, docs/configuration/backends/consul.md
This PR improve documentation for DNS provider
The Cloudflare `Global API Key` needs to be used and not the `Origin CA Key`
Fixes: #2219
=> Improve documentation for Cloudflare API key

server/server.go, server/server_test.go
Fixes frontend redirect when entry point doesn't contain redirect definition.
Fixes #2540
Related to #2133
=> Fix: frontend redirect

middlewares/addPrefix.go, middlewares/addPrefix_test.go
This is an extension of PR #2382 for addPrefix.
This PR fixes forwarding of URL encoded characters to the backend servers.
Below is a copy straight from PR #2382 :
Given that Traefik receives a request path in the form: `/some/a%2Fb` it should forward the same path to the backend. This is the case when using e.g. the rule type `PathPrefix`, but as soon as the rule type is either `AddPrefix` the path was forwarded in the decoded form like: `/some/a/b`.
The reason why this solution fixes our problem is that go uses the `String()` method of the URL object when it constructs the request. The docs state for this:
```go
// String reassembles the URL into a valid URL string.
// The general form of the result is one of:
//
//	scheme:opaque?query#fragment
// …
```
=> Fix RawPath handling in addPrefix

integration/consul_catalog_test.go, provider/consul/consul_catalog.go, provider/consul/consul_catalog_test.go
When a consul service port change, Træfik configuration was not reloading
Fixes #2572
=> Reload configuration when port change for one service

acme/account.go, acme/challengeProvider.go, configuration/configuration.go, provider/ecs/cluster.go, provider/kubernetes/namespace.go, server/server.go, tls/tls.go, types/types.go
Drops unnecessary type conversions
Simpler code. 
However, it was repeated many times so I suspect it was done for documentation. If so, let me know and I revert partially or close it.
Found by [unconvert](https://github.com/mdempsky/unconvert) linter.
=> Drop unnecessary type conversions

cmd/traefik/configuration.go, docs/configuration/backends/zookeeper.md
Change Zookeeper default prefix from `/traefik` to `traefik`. 
Fixes #2550
Related to #948.
=> Change Zookeeper default prefix.

docs/basics.md, docs/configuration/commons.md
Move rate limit documentation.
Keep basic small.
=> Move rate limit documentation.

autogen/gentemplates/gen.go, templates/kv.tmpl
fix bug.the type of "stickiness" show be string,if not,code will panic when decode  the toml file.
My traefik read configuration from etcd,when i try to test the stickiness func of the loadbalancer,i found it doesn't work after i write my conf to etcd server,and after switch  the loglevel to debug,i found some panic logs.
=> Fix stickiness bug due to template syntax error

server/rules.go, server/rules_test.go
This PR adds non regex `PathPrefix` & `PathPrefixStrip` support.
When no `{` character is found in the given path, we now bypass the `gorilla/mux` regex implementation to use our lightweight implementation instead.
Fixes #2376
The leading & trailing slash behavior has been tested to be the same as before.
=> Add non regex pathPrefix

provider/mesos/mesos.go, provider/mesos/mesos_test.go
This is the proper way to set the SlaveIP as done by the underlying `mesos-dns` helper library
Fixes #2545
=> Mesos: Use slave.PID.Host as task SlaveIP.

cmd/traefik/storeconfig.go, docs/configuration/acme.md, examples/cluster/docker-compose.yml, examples/cluster/manage_cluster_docker_environment.sh, examples/cluster/traefik.toml.tmpl
During Træfik configuration migration (from file to KV store (thanks to the `storeconfig` subcommand)), ACME configuration is not correctly initialized if `storageFile` is not provided.
Træfik can not start in this case!
The PR allows initializing correctly all the KV store keys needed by ACME during `storeconfig` process, even if `storageFile` is not provided.
The PR allows deleting automatically the key`/traefik/acme/storagefile` from KV stores when ACME configuration is migrated. This key has to be deleted because : 
- It is deprecated and has no interest if KV store is used.
- It prevents the ACME challenge mechanism to work correctly.
Fixes #927, #2547, #1283
=> Modify ACME configuration migration into KV store

integration/fixtures/https/dynamic_https_sni.toml, integration/https_test.go, server/server.go
The PR fixes TLS dynamic management by allowing deleting all of certificates from an entryPoint.
The entryPoints kept at least one certificate even if user delete all of them from the configuration, the PR fixes this behavior.
=> Allow deleting dynamically all TLS certificates from an entryPoint
