Godeps/Godeps.json
adapters.go
consul.go
docker.go
docs/index.md
file.go
marathon.go
middlewares/cbreaker.go
traefik.go
traefik.sample.toml
web.go

Use logrus instead of go-logging

Logrus logging backend

---

adapters.go
configuration.go
consul.go
docker.go
file.go
marathon.go
middlewares/cbreaker.go
middlewares/logger.go
middlewares/routes.go
traefik.go
web.go

Fix some typos, fmt and imports :)

---

README.md
docs/index.md

Added benchmarks

---

README.md
docs/index.md

Related to #26.. Trying to get this back in.. Github...

Added benchmarks https://github.com/EmileVauge/traefik/issues/22

---

README.md

Just added a little demo in the README using asciinema.

Asciinema demo

---

configuration.go
consul.go
docs/index.md
middlewares/cbreaker.go
providerTemplates/consul.tmpl
templates/configuration.tmpl
tests/consul-config.sh
traefik.go
traefik.sample.toml

This PR provides configuration enhancements towards circuit breakers and load balancers

Configuration on cicuitbreakers and load balancers

---

README.md

Fix README :3

---

integration/file_test.go
static/index.html
static/style.css

refactor(dashboard): font definition correction

---

docs/index.md

This PR is an update of the doc about kv structure #40

Update of the doc about kv

---

configuration.go
docs/index.md
static/app/sections/health/health.controller.js
static/app/sections/providers/backend-monitor/backend-monitor.html
static/app/sections/providers/frontend-monitor/frontend-monitor.html
static/app/sections/providers/providers.html

- update Web UI
- update documentation

refactor(rest) : add json annotation on configuration

---

Godeps/Godeps.json
integration/fixtures/file/simple.toml
integration/integration_test.go

Now that docker/libcompose#55 is merged, use it 🐒.
- No more sleeps !
- Update the `integration/fixture/file/simple.toml` to make sure it's gonna work (see #56)
🐸

Update integration setups to use libcompose events

---

README.md
glide.yaml
middlewares/websocket.go
middlewares/websocketproxy.go
traefik.go

This PR adds web socket support, only for `wrr` load-balancer for now.
Fixes #8 
Fixes #56.

Websockets support

---

circle.yml
script/binary
script/crossbinary
traefik.go

This PR adds a version number created during build time and injected into binary.
```sh
$ traefik --version
37438a6395324e9452f8f6f173f60ba33ce4bafe built on the 2015-10-14_08:02:45PM
```

Adds version in binary

---

integration/file_test.go
integration/fixtures/file/56-simple-panic.toml

Just to make sure #56 won't happen again, add a regression test.
🐸

Add a regression test for #56 :)

---

circle.yml

Fixing circleci builds

---

middlewares/websocketproxy.go

From @jpillora (#78)
> Changes:
> 
> * Include `Authorization` in websocket proxy headers
> * Delete `Origin` as the frontend will differ to the backend (I guess we could set it backend origin instead?)
> * Pass the request headers to the backend (Was there a reason it was previously `nil`?)
> 
> I needed this change for two reasons:
> * https://github.com/jpillora/cloud-torrent uses basic auth ontop of websockets
> * https://github.com/yudai/gotty uses a custom protocol which responds correctly only when this custom protocol (`Sec-WebSocket-Protocol`) is in the backend request
@emilevauge is LGTM
Closes #78

Carry #78 Pass websocket headers to backend

---

Makefile
script/make.sh

Add a all target than runs default tasks

---

marathon.go

Add healthcheck filter in marathon tasks

---

templates/kv.tmpl

Add passHostHeader to kv frontend definition.

---

docs/index.md
provider/docker.go
traefik.sample.toml

Docker TLS support

---

provider/kv.go
provider/kv_test.go
templates/kv.tmpl

Add GetBool function in KV provider, used by passHostHeader

---

traefik.go

Add check in invoked method

---

traefik.go

This PR fixes #125 adding a mutex around `prepareserver` calls.
cc @janeczku in #121.

Add mutex around prepareserver

---

Dockerfile

Adding default port exposed in Docker image.

Adding expose for default port

---

provider/kv.go
provider/kv_test.go
templates/kv.tmpl

Removes getBool from kv provider

---

docs/index.md
web.go

Simple fix to add read-only mode to Traefik ;)

Fix Issue #150: Add possibility to have REST API in read-only mode

---

build.Dockerfile

Bump to Go-1.5.3
Security update: https://groups.google.com/forum/#!topic/golang-announce/MEATuOi_ei4
Just to be sure :wink:.

Bump Go 1.5.3

---

provider/marathon.go
tests/compose-marathon.yml
tests/whoami.json
traefik.sample.toml

This PR adds basic authentication support in Marathon.
See #110

Add basic authentication support in Marathon

---

provider/marathon.go
provider/marathon_test.go
templates/marathon.tmpl

PR for this enclosed. 
No golang expert - I wasn't able to test this properly since I had some issues with my local env and following the instructions to run the test harness.

Fix #170 - getBackend for marathon plugin 

---

Makefile

Add build-ui as dependent target for all. Otherwise it does not build >_<. 🙊
🐸

Fix make all

---

provider/marathon.go
provider/marathon_test.go
templates/marathon.tmpl
tests/compose-marathon.yml

This PR fixes regression on marathon backend.
Fixes #194
cc @dontrebootme @vdemeester

Fix regression on marathon backend

---

Makefile
integration/integration_test.go
webui/Dockerfile

:sweat_smile: 
- target generate-webui depends on build-webui
- generate-webui will run only if the folder static does not exists
- create compose project before starting it >_<'', otherwise it does nothing :'D
- Run npm quietly :smile_cat: 
/cc @emilevauge 
🐸

Do some build / test-integration fixes

---

docs/index.md
provider/kv.go

Implement `/traefik/alias` for KV stores.

---

README.md

fix mantl url typo

---

docs/index.md
glide.yaml
mocks/Marathon.go
provider/marathon.go
provider/marathon_test.go
traefik.sample.toml

This PR adds Marathon TLS client configuration.
Fixes #110

Add Marathon TLS client config

---

.travis.yml
Makefile
README.md
build.Dockerfile
script/.validate
script/deploy.sh
script/test-integration

This PR migrate continuous integration on Travis CI  (instead of CircleCI).

Migrate on travisci

---

server.go

Reading keys from backends such as etcd returns in non-deterministic order, however gorilla/mux routes are order-dependent. This change sorts frontend keys in alphabetical order.

Deterministic frontend registration

---

cmd.go
configuration.go
docs/index.md
glide.yaml
integration/consul_catalog_test.go
integration/fixtures/consul_catalog/simple.toml
integration/integration_test.go
integration/resources/compose/consul_catalog.yml
integration/resources/compose/marathon.yml
provider/consul_catalog.go
provider/consul_catalog_test.go
server.go
templates/consul_catalog.tmpl
traefik.go

Hacked until I got something kinda working, Let me know what you think
Ref #176

WIP consul catalog provider

---

script/deploy.sh

This PR allows publishing traefik binary into https://github.com/containous/traefik-library-image. This allows Docker Hub to build Traefik image automatically on this repo: https://hub.docker.com/r/containous/traefik.

Add publish to traefik-library-image

---

README.md

My $0.02 - Center gopher

---

README.md
docs/index.md

This PR updates benchmarks with haproxy and latest results

update benchmarks with haproxy and latest results

---

contrib/systemd/traefik.service

Oops. was sitting on this change for a bit

Update systemd service file with new cli flags

---

.travis.yml

due to https://github.com/travis-ci/travis-ci/issues/1532

Avoid travis building on tags

---

cmd.go
provider/marathon.go
provider/marathon_test.go

defaultExpose for marathon tasks, idea from https://github.com/containous/traefik/issues/233

Add defaultExpose option to marathon section

---

docs/index.md
traefik.sample.toml

This PR adds documentation for #251 

Add exposedByDefault doc

---

glide.lock
glide.yaml
integration/basic_test.go
integration/consul_catalog_test.go
integration/consul_test.go
integration/docker_test.go
integration/etcd_test.go
integration/file_test.go
integration/https_test.go
integration/integration_test.go
integration/marathon_test.go

Using compose/check package (and less code) 🐍.
Let see how it goes.
🐸

A small update of libkermit

---

README.md
docs/benchmarks.md
docs/index.md
examples/compose-traefik.yml
rules.go
script/deploy.sh
webui/src/app/traefik.scss

fixes #289
fixes #288
Migrate to official Docker image
Fix mkdoc deploy

Fix issues

---

Makefile

Add a make help target

---

docs/benchmarks.md

This PR adds better benchmarks between traefik and nginx.
WDYT?
/cc @vincentbernat
Fixes #271 

add better benchmarks

---

cmd.go
docs/toml.md
integration/consul_catalog_test.go
provider/consul_catalog.go
provider/consul_catalog_test.go
templates/consul_catalog.tmpl
templates/kv.tmpl

feat(traefik,consul-catalog): Set attributes from consul catalog tags (loadbalancer,circuitbreaker,weight)

---

docs/basics.md
docs/toml.md
provider/provider_test.go
server.go
templates/kv.tmpl
types/types.go

Add support for maximum connections for backends.

---

build.Dockerfile

Bump to go v1.6.1

---

provider/docker.go

Support stop chan on docker provider

---

examples/compose-marathon.yml
examples/compose-traefik.yml
examples/whoami.json
provider/marathon.go

This PR adds exponential backoff to the Marathon provider.

Add backoff to marathon provider

---

examples/compose-marathon.yml
provider/marathon.go

This PR fixes marathon backend broken since #315 
Fixes #319 

Fix Marathon backend

---

examples/consul-config.sh
provider/kv.go

This PR fixes KV backend watch.

Fix KV backend

---

provider/consul_catalog.go

If every backends of a service are disabled, then don't create frontend

feat(consul-catalog): Remove frontend when backends disabled

---

README.md
examples/compose-etcd.yml
examples/etcd-config.sh
integration/consul_test.go
integration/etcd_test.go
integration/fixtures/consul/simple.toml
integration/fixtures/docker/simple.toml
integration/fixtures/etcd/simple.toml
integration/integration_test.go
integration/resources/compose/consul.yml
integration/resources/compose/etcd.yml
integration/utils/try.go
provider/kv.go

This PR fixes etcd backend.
It also adds integration tests for etcd & Consul ( ͡° ͜ʖ ͡°)
/cc @tboerger 

Fix etcd backend with prefix /

---

provider/consul_catalog_test.go
provider/docker.go
provider/docker_test.go
provider/kubernetes.go
provider/kubernetes_test.go
provider/kv_test.go
provider/marathon.go
provider/marathon_test.go
templates/consul_catalog.tmpl
templates/kubernetes.tmpl
templates/kv.tmpl

This PR sets passHostHeader to true by default.
Fixes #216

#216: sets passHostHeader to true by default

---

provider/kubernetes.go
provider/kubernetes_test.go

Replace PathPrefixStrip by PathPrefix in k8s

---

middlewares/logger.go

fix hijack logger middleware

---

README.md
docs/index.md

Added Devoxx Video & support

---

docs/toml.md
examples/k8s.ingress.yaml
provider/kubernetes.go
provider/kubernetes_test.go

solves https://github.com/containous/traefik/issues/372

K8s: add an option to configure "PathPrefixStrip" for the ingress-resource using annotation

---

Makefile

<del>Realized this morning that `docker-event` did not pass the context to engine-api… that could lead to potiental goroutin leaks and pancis… 🐰</del>
<del>Related commit : https://github.com/vdemeester/docker-events/commit/b308d2e8d639d928c882913bcb4f85b3a84c7a07</del>
Closes #396 
🐸

Fix Makefile for local builds

---

provider/kubernetes.go
provider/kubernetes_test.go

Support k8s ingresses without a host

---

.travis.yml
script/deploy.sh
traefik.go

Prepare release candidate

---

.travis.yml
script/deploy.sh

Fix travis tag check

---

.travis.yml
Makefile
configuration.go
examples/k8s.rc.yaml
glide.lock
glide.yaml
integration/basic_test.go
provider/provider.go
script/deploy-pr.sh
traefik.go
types/types.go
version.go

Fix default configuration

---

README.md

Welcome to @samber in the maintainers team :)

Add @samber to maintainers

---

acme/acme.go
acme/acme_test.go

This PR fixes ACME certificates renewing (in case of rate limiting) and add some tests.

Fix acme renew

---

rules.go
server.go

This PR:
- trim spaces in rules: ` Host:test.fr, test.com ; Path:/test` => `Host:test.fr,test.com;Path:/test`
- don't break the whole config while only one part is wrong => skip frontend instead of return
Fixes  #459

Fix errors load config

---

docs/toml.md

Disable constraints in doc until 1.1

---

middlewares/retry.go

This PR fixes headers in retry middleware, and simplifies ResponseRecorder.
Fixes #485 (Maybe)

Fix retry headers, simplify ResponseRecorder

---

webui/src/app/core/health.resource.js
webui/src/app/core/providers.resource.js

Fix webui proxying

---

glide.lock
glide.yaml
server.go

Fix default weight in server.LoadConfig

---

glide.lock
glide.yaml
script/crossbinary

Fix windows builds

---

configuration.go
docs/toml.md
examples/compose-etcd.yml
examples/etcd-config.sh
integration/etcd_test.go
integration/fixtures/etcd/simple.toml
traefik.sample.toml

Fix default etcd port

---

configuration.go
docs/toml.md
integration/fixtures/docker/simple.toml
provider/docker.go
provider/docker_test.go
traefik.sample.toml

Carrying #358 🐸
---
In case someone wants to register containers manually.

Carry #358 : Option to disable expose of all docker containers

---

docs/user-guide/kubernetes.md
examples/k8s/cheese-deployments.yaml
examples/k8s/cheese-ingress.yaml
examples/k8s/cheese-services.yaml
examples/k8s/cheeses-ingress.yaml
examples/k8s/traefik.yaml
examples/k8s/ui.yaml
mkdocs.yml

Adds a user-guide for kubernetes

Kubernetes user-guide

---

CHANGELOG.md

Prepare release v1.0.1

---

build.Dockerfile

Bump golang to 1.6.3

---

glide.lock
glide.yaml
integration/integration_test.go
provider/docker.go

And use ContainerAPIClient where needed 👼
🐸

Upgrade libkermit and dependencies

---

CHANGELOG.md
configuration.go
docs/basics.md
docs/toml.md
examples/compose-etcd.yml
examples/etcd-config.sh
glide.lock
glide.yaml
integration/etcd_test.go
integration/fixtures/etcd/simple.toml
script/deploy-pr.sh
server.go
traefik.sample.toml

This PR merges v1.0.1 into master.

Merge v1.0.1 master

---

glide.lock
glide.yaml

This PR bump oxy version with the fix https://github.com/containous/oxy/pull/9

Bump oxy version, fix streaming

---

CHANGELOG.md

Prepare release v1.0.2

---

docs/basics.md

Removed a forgotten `Host` key in the docs.

Fix basic docs for configuration of multiple rules

---

webui/src/app/sections/providers/providers.html

Fixes https://github.com/containous/traefik/issues/577

Upgrade directives name since we use angular-ui-bootstrap

---

glide.lock
glide.yaml
traefik.go

This PR updates staert and flaeg to use a beautiful help
and fixes some issues when help is requested for a sub-command

beautify help

---

build.Dockerfile

Bump go v1.7

---

acme/acme.go
docs/toml.md
rules.go
rules_test.go
server.go
traefik.sample.toml

This PR adds dynamic ACME certificates generation at frontends configuration change.
Fixes #483 

Add Host cert ACME generation

---

middlewares/logger.go
provider/consul_catalog.go
provider/docker.go
provider/kubernetes.go
provider/kv.go
provider/marathon.go
provider/mesos.go
server.go
traefik.go
utils/retry.go

This PR adds a generic way to define an exponential backoff in long term jobs. It comes in replacement of #354.
It also removes misused `Fatal*`.
Fixes #626

Add long job exponential backoff

---

docs/toml.md
web.go

Discussion in the slack room indicated that this might be worthwhile.

add PING handler to dashboard API

---

CODE_OF_CONDUCT.md
README.md

This project is big enough that we should have this...
I was not sure about the email address we should use so used contact@containo.us

Adopt the Code Of Coduct from http://contributor-covenant.org

---

docs/toml.md

I wanted to know what the acceptable log levels are for Traefik. I had to read the source code and then go look at the docs for logrus to get the answer to question. Let's not make the next person do all that! :}

Document accepted values for logLevel.

---

docs/toml.md
docs/user-guide/kv-config.md
provider/kv.go
templates/kv.tmpl

Carry pr 439

---

CHANGELOG.md

Prepare release v1.0.3

---

README.md
examples/k8s.namespace.yaml
glide.lock

Add Ed's video at ContainerCamp

---

provider/marathon_test.go
templates/marathon.tmpl

fIx marathon template with dots in ID

---

docs/toml.md
server.go
traefik.sample.toml

Fix providers throttle duration doc

---

glide.lock
glide.yaml
types/types.go

Update to latest mapstructure that fixes https://github.com/mitchellh/mapstructure/issues/56
Fixes #743

Fix mapstructure issue with anonymous slice

---

configuration.go

Fixes #757 
Fixes #747
/cc @wicaeed

Fix multiple certificates using flag

---

middlewares/retry.go

This PR adds Flush implementation to ResponseRecorder middleware.
Fixes #560

Fix ResponseRecorder Flush

---

CHANGELOG.md

Prepare release v1.1.0-rc3

---

acme/acme.go
configuration.go
glide.lock
glide.yaml
provider/boltdb.go
provider/consul.go
provider/consul_catalog.go
provider/docker.go
provider/etcd.go
provider/file.go
provider/kubernetes.go
provider/kv.go
provider/marathon.go
provider/marathon_test.go
provider/mesos.go
provider/provider.go
provider/provider_test.go
provider/zk.go
server.go
types/types.go
web.go

Fixes ACME renew
Fixes oxy version
Fixes HTTP/2
Fixes constraint store / read from KV
Fixes #807 
Fixes #790
Fixes #794

Fix multiple issues

---

.travis.yml
CHANGELOG.md

Fix mkdoc theme

---

docs/user-guide/kubernetes.md
examples/k8s/traefik.yaml

Remove version numbers from examples

---

Makefile
build.Dockerfile
cluster/datastore.go
docs/basics.md
script/validate-misspell

And adds some validation for this sort of thing, because speelign is harad

Fixes a spelling error

---

README.md
configuration.go
docs/toml.md
glide.lock
glide.yaml
integration/eureka_test.go
integration/fixtures/eureka/simple.toml
integration/integration_test.go
integration/resources/compose/eureka.yml
provider/eureka.go
provider/eureka_test.go
server.go
templates/eureka.tmpl

Add Eureka provider

---

rules.go
rules_test.go

Fix issue with casing in path based rules

---

rules.go
rules_test.go

Fix path case sensitive v1.1

---

docs/index.md
provider/k8s/client.go
provider/kubernetes.go

Fix Kubernetes watch leak

---

provider/k8s/client.go

Fix missing value for k8s watch request parameter

---

provider/docker.go

Fixes #902
**Needs some more test before merging**

Fix Swarm panic

---

CHANGELOG.md

Prepare release v1.1.1

---

integration/eureka_test.go
integration/fixtures/eureka/simple.toml
integration/resources/compose/eureka.yml
templates/eureka.tmpl

- Add integration tests with a test on whoami
- Fix error in template eureka (wrong host)

test-integration(eureka): Add some integration tests

---

docs/index.md

adapted to current schema for compose files
uses networks as necessary in a real world usage
follow-up of #749 with a clean git history.

Updates index.md 'Test it!' section

---

acme/acme.go
cluster/datastore.go
cluster/leadership.go
glide.lock
glide.yaml

Add infinit channels to manage certs in ACME.
Fixes #903

Fix leadership panic

---

acme/acme.go
acme/challengeProvider.go
cluster/datastore.go
cluster/leadership.go
provider/consul_catalog.go
provider/docker.go
provider/kubernetes.go
provider/kv.go
provider/marathon.go
provider/mesos.go
safe/routine.go
safe/routine_test.go

This PR adds recover in case of panic in backoff operations.
Fixes #934

Add operation recover

---

acme/account.go
acme/acme_test.go
acme/crypto.go

This PR removes duplicate ACME cert found in the store at startup.
Fixes #905

Fix duplicate acme certificates

---

README.md

See the right go report badge

---

docs/basics.md

A few typos I could find while browsing that page. Feel free to correct further as my english is far from perfect :)

[doc] few tweaks on the basics page

---

docs/basics.md

Document multiple values for one rule. 
I missed that this was possible, I only found out by searching on github and finding https://github.com/containous/traefik/pull/285.

Add multiple values for one rule to docs

---

server.go

Don't fetch ACME certificates for frontends using non-TLS entrypoints (#989)

---

.travis.yml
mkdocs.yml
requirements.txt

Fix docs build and add missing benchmarks page

---

examples/compose-k8s.yaml
examples/k8s/traefik.yaml

Fix k8s example

---

CHANGELOG.md
acme/account.go
acme/acme.go
acme/acme_test.go
acme/challengeProvider.go
acme/crypto.go
cluster/datastore.go
cluster/leadership.go
glide.lock
glide.yaml
provider/consul_catalog.go
provider/docker.go
provider/kubernetes.go
provider/kv.go
provider/marathon.go
provider/mesos.go
safe/routine.go
safe/routine_test.go
server.go

This PR merges v1.1.2 into master.

Merge v1.1.2 master

---

script/deploy.sh

Fix travis deploy

---

glide.lock
glide.yaml

Fix stats race condition

---

docs/toml.md
examples/compose-rancher.yml
provider/rancher.go
provider/rancher_test.go
traefik.sample.toml

This one is a fix for #1127. I just re-done as the other one was screwed 🗡

Small fixes and improvments

---

README.md

@containous/traefik I need 2 LGTMs here. :-)

Add @timoreimann to list of maintainers.

---

README.md

This PR adds @trecloux to maintainers :)

Add @trecloux to Maintainers

---

docs/user-guide/kv-config.md

I think this is a literal translation from French that doesn't really makes sense here :)

Change a word in the documentation

---

CHANGELOG.md

Prepare release v1.2.1

---

traefik.sample.toml

It took few minutes to understand what is wrong, when I just uncommented sample config :)

fix consul sample endpoints

---

.github/ISSUE_TEMPLATE
cmd/bug.go

We keep asking users to provide logging output, so I extended the issue template accordingly.

Append template section asking for debug log output.

---

provider/docker.go
provider/docker_test.go
server.go

This PR fixes 2 issues:
Fixes #1399
Fixes #1317

Fix postloadconfig acme & Docker filter empty rule

---

server.go

This PR carries #1271
Original work by @argeiger
Fixes #679

Carry PR 1271

---

CHANGELOG.md

Prepare release v1.2.2

---

server.go

Fix too many redirect

---

CHANGELOG.md

Prepare release v1.2.3

---

README.md
docs/index.md

Also replace Træfɪk with Træfik.
Completes #795.

Mention Traefik pronunciation in docs too.

---

provider/consul/consul_catalog.go
provider/consul/consul_catalog_test.go
server/configuration.go

Fix Consul catalog prefix flags

---

provider/docker/docker.go
provider/docker/docker_test.go

Make port deterministic

---

.github/cpr.sh
.github/rmpr.sh
.github/rpr.sh

When contributors use their fork `master` branch to make PR, `cpr` fail to create the branch.

refactor: fix for PR with master branch.

---

.semaphoreci/setup.sh
.semaphoreci/tests.sh
.semaphoreci/vars

This PR adds SemaphoreCI as new CI platform.

 [CI] Add SemaphoreCI 

---

.github/cpr.sh
.github/pfpr.sh
.github/rpr.sh

Like cpr, rmpr but for push force the branch.

feat(github): push force PR branch.

---

integration/resources/compose/boulder.yml
integration/resources/compose/constraints.yml
integration/resources/compose/consul_catalog.yml
integration/resources/compose/file.yml
webui/Dockerfile

With this PR i have started to reduce the size of the docker images:
- replaced with alpine if available (nginx, rabbitmq)
- added clean up apt-cache for webui container

[CI] Reduce size of Docker Images

---

webui/conf/browsersync.conf.js
webui/package.json
webui/yarn.lock

As mentioned in #1542, this PR adds a proxy to localhost:8080/{health,api} in dev mode for the web UI.

Proxy in dev mode

---

.semaphoreci/setup.sh
.semaphoreci/tests.sh
.semaphoreci/vars

This PR adds a retry function (~travis_retry) on semaphore.

[CI] retry function

---

README.md
docs/index.md

The most important thing: the SemaphoreCI badge.

doc(CI): Add SemaphoreCI badge.

---

README.md

This PR adds @ldez to the maintainers team :hugs:

Add @ldez to maintainers

---

.semaphoreci/setup.sh
.semaphoreci/tests.sh
.semaphoreci/vars
.travis.yml
integration/resources/compose/boulder.yml
integration/resources/compose/constraints.yml
integration/resources/compose/consul_catalog.yml
integration/resources/compose/file.yml
webui/Dockerfile

Port changes from master to v1.3 branch.

SemaphoreCI on 1.3 branch

---

docs/user-guide/cluster.md

doc: Traefik cluster in beta.

---

CHANGELOG.md
docs/user-guide/cluster.md

This PR prepares release `v1.3.0 rc2`.

Prepare release v1.3.0-rc2

---

script/deploy.sh

This PR fixes the deploy script.
As we don't use a Docker version matrix anymore, we don't need this check anymore.

Fix deploy script, removes Docker version check

---

README.md

[@Russell-IO](https://github.com/Russell-IO), thanks for your great work on Traefik.
It has been a real pleasure to have you in the team!
:heart:

Remove Russel from maintainers

---

README.md

[@trecloux](https://github.com/trecloux), thanks for your awesome work on Traefik.
Especially on your super useful ACME integrations tests :heart_eyes: 
See you soon in Lille ;)

Remove Thomas Recloux from maintainers

---

docs/toml.md

Fix some "errors" in toml documentation

Small toml documentation update

---

README.md

Fix SemaphoreCI badge.

---

docs/user-guide/kubernetes.md
examples/k8s/cheese-ingress.yaml
examples/k8s/cheeses-ingress.yaml
examples/k8s/ui.yaml

Update usage of `.local` with `.minikube` in k8s docs

---

.github/MAINTAINER.md

Replace `contributor/needs-rebase` by `contributor/needs-resolve-conflicts`.

doc(maintainer): add `contributor/needs-resolve-conflicts`

---

README.md

While usage of the word "guys" can be considered gender neutral depending on location and context, it is widely considered to be gendered -- and more inclusive options are readily available. 💜
References:
* [When is "guys" gender neutral? I did a survey! -- Julia Evans](https://jvns.ca/blog/2013/12/27/guys-guys-guys/)

Use more inclusive language in README.md {guys => folks}

---

glide.lock
glide.yaml
vendor/github.com/stretchr/testify/require/doc.go
vendor/github.com/stretchr/testify/require/forward_requirements.go
vendor/github.com/stretchr/testify/require/require.go
vendor/github.com/stretchr/testify/require/require_forward.go
vendor/github.com/stretchr/testify/require/requirements.go

This is required in order for #1638 to be mergeable.

Get testify/require dependency.

---

CHANGELOG.md

Prepare release v1.3.0 rc3

---

script/validate-misspell

Misspelling in misspelling.

---

docs/user-guide/kubernetes.md
examples/k8s/cheeses-ingress.yaml

Merge current v1.3 to master

---

.github/ISSUE_TEMPLATE.md
cmd/traefik/bug.go

Enhance GitHub issue template.

doc: Enhance GitHub issue template.

---

provider/kubernetes/client.go

Merge current v1.3

---

glide.lock
glide.yaml

`glide.lock` and `glide.yml` are out of sync. 
Related to #1635

fix: glide go-marathon

---

.github/ISSUE_TEMPLATE.md

Enhance GitHub issue template.

Enhance GitHub issue template.

---

provider/eureka/eureka.go
provider/marathon/marathon.go

- Eureka: use Traefik logger instead of directly Logrus
- Marathon: add explicit message

Minor logs changes

---

webui/src/app/core/providers.resource.js

Don't fail when backend or fronted are empty.

Don't fail when backend or frontend are empty.

---

CHANGELOG.md

Prepare release v1.3.1

---

.github/MAINTAINER.md

fix typo in maintainer.md

---

CHANGELOG.md
webui/src/app/core/providers.resource.js

Merge v1.3.1 to master

---

docs/toml.md
provider/rancher/rancher.go
traefik.sample.toml

Update Rancher documentation.
- add metadata service to `toml.md`
- fix config name

Update Rancher documentation.

---

.github/MAINTAINER.md

This PR changes the PR review process to a more flexible one.

Change to a more flexible PR review process

---

.semaphoreci/setup.sh
.semaphoreci/vars
build.Dockerfile

SemaphoreCI: Docker version

---

README.md

This PR adds @juliens to the maintainer team.

Add Julien Salleyron to maintainers

---

README.md

This PR adds @nmengin to the maintainer team.

Add Nicolas Mengin to maintainers

---

.semaphoreci/vars
.travis.yml
build.Dockerfile
script/deploy-docker.sh
script/deploy.sh

- remove `-e` https://github.com/moby/moby/pull/20565
- export docker version to Travis GUI

Bump Docker version to 17.03

---

glide.lock
glide.yaml
vendor/github.com/vulcand/oxy/forward/fwd.go

Fix proxying of unannounced trailers.

Fix proxying of unannounced trailers

---

CHANGELOG.md

Prepare release v1.3.2

---

docs/basics.md

Add a quick documentation for `traefik bug` command.

Traefik "bug" command documentation

---

README.md

A quick documentation for release cycle.

Release cycle.

---

CHANGELOG.md

Prepare release v1.3.3

---

CHANGELOG.md
provider/kubernetes/client.go
provider/kubernetes/kubernetes.go

Merge 1.3.3

---

.github/CONTRIBUTING.md

Remove glide integration documentation.

Remove glide integration documentation.

---

.github/CODEOWNERS

Try new GitHub feature: [code owners](https://help.github.com/articles/about-codeowners/)
Related to [traefik/teams](https://github.com/orgs/containous/teams/traefik/teams)

GitHub Code Owners.

---

glide.lock
glide.yaml

Due to Negroni migration:
- https://github.com/codegangsta/negroni --> https://github.com/urfave/negroni

Change nergoni git url.

---

cluster/datastore.go
provider/dynamodb/dynamodb.go
provider/ecs/ecs.go
provider/eureka/eureka.go
provider/file/file_test.go
provider/kubernetes/client.go
provider/rancher/metadata.go
server/web.go

Add `Safe.Go(...)` everywhere is needing.

replace go routine by Safe.Go

---

.github/CODEOWNERS

Change CODEOWERS file to really match folder content.

Fix CODEOWERS file.

---

CHANGELOG.md

Prepare Release v1.3.4

---

glide.lock
glide.yaml
integration/glide.lock
integration/glide.yaml
integration/vendor/golang.org/x/net/websocket/client.go
integration/vendor/golang.org/x/net/websocket/hybi.go
integration/vendor/golang.org/x/net/websocket/server.go
integration/vendor/golang.org/x/net/websocket/websocket.go
integration/websocket_test.go
vendor/github.com/gorilla/websocket/doc.go
vendor/github.com/gorilla/websocket/json.go
vendor/github.com/gorilla/websocket/server.go
vendor/github.com/gorilla/websocket/util.go
vendor/github.com/vulcand/oxy/forward/fwd.go

Upgrade oxy version with the oxy version with fix for origin problem
(403 on multiple websocket server)
Add integration tests
fixes #1900

Oxy with fixes on websocket + integration tests

---

CHANGELOG.md

Prepare release v1.3.5

---

CHANGELOG.md
glide.lock
glide.yaml
integration/fixtures/websocket/config.toml
integration/integration_test.go
integration/websocket_test.go
middlewares/compress.go
middlewares/compress_test.go
middlewares/replace_path.go
middlewares/replace_path_test.go
vendor/github.com/NYTimes/gziphandler/gzip.go
vendor/github.com/NYTimes/gziphandler/wrapper.go
vendor/github.com/gorilla/websocket/doc.go
vendor/github.com/gorilla/websocket/json.go
vendor/github.com/gorilla/websocket/server.go
vendor/github.com/gorilla/websocket/util.go
vendor/github.com/vulcand/oxy/forward/fwd.go
vendor/github.com/vulcand/oxy/forward/headers.go
vendor/golang.org/x/net/websocket/client.go
vendor/golang.org/x/net/websocket/dial.go
vendor/golang.org/x/net/websocket/hybi.go
vendor/golang.org/x/net/websocket/server.go
vendor/golang.org/x/net/websocket/websocket.go

Merge 1.3.5

---

middlewares/datadog.go
middlewares/datadog_test.go
middlewares/metrics.go
middlewares/statsd.go
middlewares/statsd_test.go

Added RetryMetrics to DataDog and StatsD providers

---

.github/CODEOWNERS

Add more files to CODEOWNERS.

---

acme/acme.go
acme/crypto.go
integration/dynamodb_test.go
integration/etcd_test.go
integration/https_test.go
integration/websocket_test.go
middlewares/accesslog/logger_test.go
middlewares/authenticator_test.go
middlewares/error_pages_test.go
middlewares/ip_whitelister.go
middlewares/retry_test.go
provider/docker/docker.go
provider/file/file_test.go
provider/kubernetes/kubernetes.go
provider/kv/kv.go
provider/kv/kv_test.go
server/configuration.go
server/server.go
types/types.go

Clean some code smells.
Analyze made with:
```shell
go get -u honnef.co/go/tools/cmd/{gosimple,staticcheck}
staticcheck $(go list ./... | grep -v '/vendor/')
gosimple $(go list ./... | grep -v '/vendor/')
```
I have not fixed some smells with chan, need more thinking 😉 
I think we must add those tools to our build chain.

Code cleaning.

---

glide.lock
glide.yaml
vendor/github.com/vulcand/oxy/forward/fwd.go
vendor/github.com/vulcand/oxy/forward/headers.go
vendor/github.com/vulcand/oxy/forward/rewrite.go
vendor/github.com/vulcand/oxy/roundrobin/stickysessions.go

Websocket parameters and protocol.

---

glide.lock
glide.yaml
vendor/github.com/vulcand/oxy/forward/headers.go
vendor/github.com/vulcand/oxy/forward/rewrite.go

Support X-Forwarded-Port.

---

glide.lock
vendor/github.com/containous/mux/context_gorilla.go
vendor/github.com/containous/mux/context_native.go
vendor/github.com/containous/mux/doc.go
vendor/github.com/containous/mux/mux.go
vendor/github.com/containous/mux/regexp.go
vendor/github.com/containous/mux/route.go

Resync our [mux fork](https://github.com/containous/mux) with  [gorilla/mux](https://github.com/gorilla/mux).

Bump gorilla/mux version.

---

MAINTAINER.md

Welcome to the maintainers team @marco-jantke !

Add Marco Jantke to maintainers

---

CHANGELOG.md

Prepare release v1.3.6

---

docs/user-guide/swarm-mode.md

Add more visibility to docker stack deploy label issue

---

cmd/traefik/bug.go
cmd/traefik/bug_test.go
middlewares/stats.go
middlewares/stripPrefix_test.go

- Replace `toml` by `json`
- fix anonymize.

Fix command bug content.

---

glide.lock
glide.yaml
vendor/github.com/vulcand/oxy/forward/rewrite.go

Only forward X-Fowarded-Port.

---

CHANGELOG.md
glide.lock
glide.yaml
vendor/github.com/vulcand/oxy/forward/rewrite.go

Merge v1.3.7

---

mkdocs.yml

fix: documentation Mesos.

---

docs/basics.md

Enhance security headers doc.

---

docs/user-guide/kubernetes.md

[Docs] Fix invalid service yaml example

---

glide.lock
glide.yaml
vendor/github.com/libkermit/compose/compose.go

Upgrade `libkermit/compose` version in the way to allow utilization of new features in tests.

Upgrade libkermit/compose version

---

glide.lock
glide.yaml
vendor/github.com/vulcand/oxy/forward/fwd.go

Update oxy for websocket bug

---

CHANGELOG.md

Prepare release v1.3.8

---

Makefile
script/test-unit
script/validate-gofmt
script/validate-golint
script/validate-govet
script/validate-misspell

Remove old glide elements for integration tests.

Remove old glide elements for integration tests.

---

CONTRIBUTING.md
generate.go

- clean doc
- fix mkdocs installation

Anonymize contributing doc

---

script/crossbinary-default
script/crossbinary-others

Force GOARM to v6.

---

integration/consul_catalog_test.go
integration/fixtures/consul_catalog/simple.toml
integration/resources/compose/consul_catalog.yml
provider/consul/consul_catalog.go
provider/consul/consul_catalog_test.go

fix consul catalog refresh problem when you have multi-nodes services
Thx @mmatur 
fixes #1514

Fix consul catalog refresh problems

---

CHANGELOG.md

Prepare release v1.4.0-rc2

---

provider/rancher/metadata.go

This one fixes #1852 and add's the stack name to the backend name generation to follow the same behavior as in api mode.
You can do a pre test with this docker image:
santode/traefik:issue_1852
Or a dashboard from my dev cluster with 2 services called "whoami" in 2 different stacks:
http://139.59.158.53:8080/dashboard/#/

Add stack name to backend name generation to fix rancher metadata backend

---

MAINTAINER.md

- myrmica lobicornis (merge) learned two new labels: `bot/no-merge`, `bot/light-review`
- myrmica aloba (labels) learned to add milestone to a PR based on a branch version (1.4, 1.3)

Explains new bot features.

---

docs/configuration/entrypoints.md
types/types.go

Add forward auth documentation.

---

docs/configuration/backends/web.md

- add default values for metrics
- add heading for some sections (better permalinks)

Enhance web backend documentation

---

CHANGELOG.md

Description
Prepare release v1.4.0 rc3

Prepare release v1.4.0-rc3

---

integration/consul_catalog_test.go
provider/consul/consul_catalog.go

- Fix flaky tests in consul_catalog integration tests. Fixes #1514, #2072
- Fix refresh problem that appear when flaky tests are fixed

Flaky tests and refresh problem in consul catalog

---

Makefile

Change pull image command in Makefile

---

Makefile
cmd/traefik/configuration.go
integration/consul_catalog_test.go
middlewares/retry.go
provider/consul/consul_catalog.go
server/server.go
server/server_test.go

Merge current v1.4

---

Makefile

Before new sytem 05:30
04:31 : new sytem without parallelism
02:27 : new sytem `-P 2`
01:40 : new sytem `-P 4`
01:17 : new sytem `-P 6`
01:12 : new sytem `-P 10`

CI: speed up pull images.

---

glide.lock
glide.yaml
integration/websocket_test.go
vendor/github.com/vulcand/oxy/forward/fwd.go

Fixes https://github.com/containous/traefik/issues/2182
Related to https://github.com/containous/oxy/pull/28

Forward upgrade error from backend

---

integration/fixtures/websocket/config.toml
integration/websocket_test.go

Add a test to verify urlencoded part in url are not double encoded
fixes #2196

Add tests for urlencoded part in url

---

CHANGELOG.md

Description
Prepare release v1.4.0 rc4

Prepare release v1.4.0-rc4

---

docs/configuration/acme.md
docs/user-guide/docker-and-lets-encrypt.md
docs/user-guide/swarm-mode.md

Fix grammar

---

cmd/traefik/traefik.go

This PR adds a delay to the first version check (only call version check if traefik is stable).

Delay first version check

---

CHANGELOG.md

Prepare release v1.4.0-rc5

---

docs/configuration/entrypoints.md

This PR fixes Proxy Protocol Documentation.

Fix Proxy Protocol documentation

---

glide.lock
glide.yaml
vendor/github.com/vulcand/oxy/forward/fwd.go

Fixes #2246 
Related to https://github.com/containous/oxy/pull/29

Nil body retries

---

cmd/traefik/traefik.go
configuration/configuration.go
configuration/configuration_test.go
docs/configuration/entrypoints.md
middlewares/ip_whitelister.go
server/header_rewriter.go
server/server.go
server/server_test.go
whitelist/ip.go
whitelist/ip_test.go

Add option to trust or not `X-Forwarded-*` header.

Add TrustForwardHeader options.

---

integration/consul_catalog_test.go
provider/consul/consul_catalog.go

Fix retry if consul catalog is not available.
You can test it with my experimental image:
`mmatur/traefik:consul_retry`
Fixes #2147

Fix consul catalog retry

---

cmd/traefik/traefik.go

This PR adds retry backoff to load Staert config.
Partly fixes https://github.com/containous/traefik/issues/2147#issuecomment-336790132

add retry backoff to staert config loading

---

CHANGELOG.md

Fix 1.4.0 release date

---

glide.lock
server/rules_test.go
vendor/github.com/containous/mux/doc.go
vendor/github.com/containous/mux/mux.go
vendor/github.com/containous/mux/regexp.go
vendor/github.com/containous/mux/route.go

Fix the problem is due a breaking change has been added in https://github.com/gorilla/mux/pull/218 and https://github.com/gorilla/mux/pull/185.
Fixes #2272

Regex capturing group.

---

glide.lock
glide.yaml
vendor/github.com/vulcand/oxy/forward/headers.go
vendor/github.com/vulcand/oxy/forward/rewrite.go

- fix trust X headers
- add `X-Forwarded-Port`
- add `X-Real-Ip`
Fixes #1220, #293

Enhance Trust Forwarded Headers

---

MAINTAINER.md

This PR adds Michaël Matur [@mmatur](https://github.com/mmatur) to the maintainers team :tada: 
Welcome into the team :hugs:

Add mmatur to maintainers

---

CHANGELOG.md

Prepare release v1.4.1

---

provider/docker/service_test.go
templates/docker.tmpl

Backends createds as Docker services replicas cause error.
This fix add an unique id to all backends in the way to avoid the problem.
Fixes #1853 #1138 .

Add unique ID to Docker services replicas

---

cmd/traefik/traefik.go

Remove hardcoded runtime.GOMAXPROCS.

---

Makefile
integration/fixtures/proxy-protocol/with.toml
integration/fixtures/proxy-protocol/without.toml
integration/integration_test.go
integration/proxy_protocol_test.go
integration/resources/compose/proxy-protocol.yml
integration/resources/haproxy/haproxy.cfg
script/test-integration

This PR adds Proxy Protocol integration tests.
It also splits integration tests in two suites:
- tests suites that are launched from a container using `go test -container`
- tests suites that are launched from the host using: `go test -host`
We need to run few tests directly from the host because we need to mount files into containers started by https://github.com/docker/libcompose.

Add proxy protocol tests

---

docs/configuration/backends/kubernetes.md

fixed dead link in kubernetes backend config docs

---

.github/PULL_REQUEST_TEMPLATE.md

New PR template

---

docs/configuration/acme.md
provider/ecs/cluster_test.go

Updated documentation after upgrade lego in PR #2304

Update Let's Enrcypt provider list

---

CHANGELOG.md

Prepare release v1.4.2

---

requirements.txt

Freeze version of mkdocs-material.
Ref.  #2315

Freeze version of mkdocs-material.

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
cluster/datastore.go
cmd/traefik/traefik.go
docs/configuration/backends/docker.md
docs/configuration/backends/kubernetes.md
docs/configuration/entrypoints.md
docs/user-guide/docker-and-lets-encrypt.md
docs/user-guide/kubernetes.md
integration/docker_test.go
provider/docker/docker.go
provider/docker/docker_test.go
provider/docker/swarm_test.go
provider/marathon/marathon_test.go
requirements.txt
templates/marathon.tmpl

Merge v1.4.2 into master

---

docs/user-guide/examples.md

Fix typos
Nobody likes typos.
Nope

docs: fix some typos

---

cmd/traefik/anonymize/anonymize_doOnJSON_test.go
middlewares/headers.go
middlewares/headers_test.go

This PR sorts imports
Avoid some conflicts

chore: sort imports

---

docs/user-guide/docker-and-lets-encrypt.md

Fixed documentation by aligning docker-compose volumes vs instructed creation of directory
sharing is caring

Minor fix for docker volume vs created directory

---

integration/websocket_test.go

Add some tests to be sure headers are passed when using websocket
related to #2078

Add tests for websocket headers

---

docs/configuration/backends/kubernetes.md

Now works fine at https://docs.traefik.io/configuration/backends/kubernetes/

Link corrected

---

cmd/traefik/healthcheck.go
cmd/traefik/storeconfig.go
cmd/traefik/traefik.go

Add dedicated files for:
- `storeconfig`
- `healtcheck`

Put subcommand in dedicated files.

---

CHANGELOG.md

Prepare release v1.4.3

---

CHANGELOG.md
docs/configuration/backends/kubernetes.md
docs/user-guide/docker-and-lets-encrypt.md
docs/user-guide/examples.md
docs/user-guide/kubernetes.md
docs/user-guide/kv-config.md
glide.lock
glide.yaml
integration/consul_catalog_test.go
integration/resources/compose/consul_catalog.yml
middlewares/compress.go
middlewares/compress_test.go
provider/consul/consul_catalog.go
provider/consul/consul_catalog_test.go
provider/kv/kv.go
script/crossbinary-default
script/crossbinary-others
vendor/github.com/NYTimes/gziphandler/gzip.go

This reverts commit 6fcab72ec713f9e0ecb0ade12c5ab150a24741f9.

Revert "Merge v1.4.2 into master"

---

CHANGELOG.md
docs/configuration/backends/kubernetes.md
docs/user-guide/docker-and-lets-encrypt.md
docs/user-guide/examples.md
docs/user-guide/kubernetes.md
docs/user-guide/kv-config.md
glide.lock
glide.yaml
integration/consul_catalog_test.go
integration/resources/compose/consul_catalog.yml
middlewares/compress.go
middlewares/compress_test.go
provider/consul/consul_catalog.go
provider/consul/consul_catalog_test.go
provider/kv/kv.go
script/crossbinary-default
script/crossbinary-others
vendor/github.com/NYTimes/gziphandler/gzip.go

Merge v1.4.3 into master
Be sync.

Merge v1.4.3 into master

---

docs/archive.md
mkdocs.yml

Add a page with previous documentation version.
Be able to watch previous documentation version.
Some links must change before merge, it's just a working version.

Documentation archive

---

provider/provider.go
provider/provider_test.go

Allow to use raw string as template.
Facilitate extensibility.

Support template as raw string.

---

.travis.yml

Exclude RC from doc publication.
Publish documentation only on final or bug fix releases.

Exclude RC from doc publication.

---

provider/docker/docker.go
provider/docker/service_test.go

The PR fixes two problems with Docker backends : 
- When swarm services has replicas, Træfik has to create only one frontend by checking if a Swarm service frontend already exists.
- When swarm services are set with the same Træfik configuration, Træfik has to create all the frontends and backends for **all** the services : a new prefix with the container `serviceName` is added to the backend names.
Fixes #2410

Fix problems about duplicated and missing Docker backends/frontends.

---

autogen/gentemplates/gen.go
generate.go

gofmt generated file.
have a repeatable generation.

gofmt generated file.

---

docs/configuration/metrics.md

Fix some mistake in the documentation after #2335 
Good documentation

add entrypoint in prometheus doc and remove web on influxdb doc

---

.travis.yml
CHANGELOG.md
docs/archive.md
glide.lock
glide.yaml
middlewares/stripPrefix.go
middlewares/stripPrefixRegex.go
middlewares/stripPrefixRegex_test.go
middlewares/stripPrefix_test.go
mkdocs.yml
provider/docker/docker.go
provider/docker/service_test.go
provider/rancher/rancher.go
server/server.go

Merge v1.4.4 into master
Be sync.

Merge v1.4.4 into master

---

provider/marathon/marathon.go
server/server.go
server/server_signals.go
server/server_signals_windows.go

Rename `Server` method receiver from `server` to `s`
Respect the convention.
Dedicate to @nmengin 😺

Change server receiver name.

---

provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Merge current v1.4 into master
Be sync.

Merge current v1.4 into master 

---

docs/configuration/entrypoints.md

Add a link to crypto/tls godoc.
Find information more easily

Add link to crypto/tls godoc.

---

docs/configuration/backends/servicefabric.md

describe `refreshSecond` configuration.
Have a complete documentation.

Describe 'refreshSecond' configuration.

---

docs/archive.md

add link to futur 1.5 documentation.
Provide new documentation.

Add link to futur 1.5 documentation.

---

integration/docker_test.go
integration/fixtures/docker/simple.toml
provider/docker/docker.go

Fixes #2459 
Now we register only running container

Fix empty ip when container is stopped

---

glide.lock
glide.yaml
vendor/github.com/containous/traefik-extra-service-fabric/labels.go
vendor/github.com/containous/traefik-extra-service-fabric/servicefabric.go
vendor/github.com/containous/traefik-extra-service-fabric/servicefabric_tmpl.go
vendor/google.golang.org/grpc/call.go
vendor/google.golang.org/grpc/clientconn.go
vendor/google.golang.org/grpc/connectivity/connectivity.go
vendor/google.golang.org/grpc/rpc_util.go
vendor/google.golang.org/grpc/transport/control.go
vendor/google.golang.org/grpc/transport/http2_client.go
vendor/google.golang.org/grpc/transport/http2_server.go

- Update vendor
- sync glide.yml and glide.lock
Have valid vendor files

Sync vendor and glide.

---

glide.lock
glide.yaml
vendor/github.com/containous/traefik-extra-service-fabric/labels.go
vendor/github.com/containous/traefik-extra-service-fabric/servicefabric.go
vendor/github.com/containous/traefik-extra-service-fabric/servicefabric_tmpl.go
vendor/google.golang.org/grpc/call.go
vendor/google.golang.org/grpc/clientconn.go
vendor/google.golang.org/grpc/connectivity/connectivity.go
vendor/google.golang.org/grpc/rpc_util.go
vendor/google.golang.org/grpc/transport/control.go
vendor/google.golang.org/grpc/transport/http2_client.go
vendor/google.golang.org/grpc/transport/http2_server.go

Merge current v1.5 into master
Be sync.

Merge current v1.5 into master 

---

autogen/gentemplates/gen.go
templates/docker.tmpl

This PR is a bugfix to correct unquoted strings on the Docker Template.
Fixes #2493

quote template strings

---

integration/basic_test.go
integration/fixtures/simple_stats.toml
integration/resources/compose/stats.yml
server/server.go

Fix a problem when we have multiple entrypoints
fixes #2489 
When we have multiple entrypoints, the metrics was collected only for the first entrypoint

Fix metrics problem on multiple entrypoints

---

CHANGELOG.md

Prepare release v1.4.5

---

CHANGELOG.md
docs/configuration/backends/file.md

Merge 1.4.5 into v1.5
Be sync.

Merge v1.4.5 into v1.5

---

CHANGELOG.md

Prepare release v1.5.0-rc2 aka Cancoillotte

Prepare release v1.5.0-rc2

---

CHANGELOG.md
acme/acme.go
api/debug.go
cmd/traefik/healthcheck.go
docs/basics.md
docs/configuration/backends/file.md
docs/user-guide/kubernetes.md
server/server.go

Merge 1.5.0-rc2 into master.
Be sync.

Merge 1.5.0-rc2 into master

---

provider/consul/consul_catalog_test.go

Fix Flaky Consul Catalog tests.
Have reproducible tests.

Fix Flaky Consul Catalog tests.

---

glide.lock
glide.yaml
vendor/github.com/containous/traefik-extra-service-fabric/labels.go
vendor/github.com/containous/traefik-extra-service-fabric/servicefabric.go
vendor/github.com/containous/traefik-extra-service-fabric/servicefabric_tmpl.go
vendor/github.com/jjcollinge/servicefabric/servicefabric.go

fix: backend name for Stateful services. (Service Fabric)
Related to https://github.com/containous/traefik-extra-service-fabric/pull/9

fix: backend name for Stateful services. (Service Fabric)

---

glide.lock
glide.yaml
vendor/github.com/containous/traefik-extra-service-fabric/servicefabric.go

fix isHealthy logic for Service Fabric.
https://github.com/containous/traefik-extra-service-fabric/pull/19

fix isHealthy logic.

---

autogen/gentemplates/gen.go
templates/kubernetes.tmpl

Add missing entrypoints template.
Fixes #1898 , #1450
I will add tests in another PR.

Add missing entrypoints template.

---

CHANGELOG.md

Prepare release v1.5.0-rc3 aka Cancoillotte

Prepare release 1.5.0-rc3

---

middlewares/error_pages.go
middlewares/error_pages_test.go
provider/docker/config_container_docker_test.go
types/types.go

Use pointer of error pages
Use pointer of error pages

Use pointer of error pages

---

docs/configuration/commons.md

Remove obsolete paragraph about error pages.
Remove obsolete paragraph about error pages.

Remove obsolete paragraph about error pages.

---

provider/label/label.go
provider/label/label_test.go

No error pages must return nil.
No error pages must return nil.

No error pages must return nil.

---

autogen/gentemplates/gen.go
server/server.go
templates/docker.tmpl
templates/kubernetes.tmpl
templates/marathon.tmpl

- fix headers templates for AllowedHosts and HostsProxyHeaders.
Fix a bug.
Related to #2621
I will rewrite the headers templating system in the part3 of the homogenization of the providers.

Fix custom headers template

---

LICENSE.md
docs/theme/partials/footer.html
mkdocs.yml
requirements.txt

Fixes: #2315 
Have up-to-date dependencies

Upgrade docs dependencies and adapt configuration

---

CHANGELOG.md

Prepare release v1.4.6

---

CHANGELOG.md
cmd/traefik/bug.go
cmd/traefik/bug_test.go
provider/consul/consul_catalog_test.go
provider/docker/docker.go
provider/docker/service_test.go

Merge 1.4.6 into v1.5
Be sync.

Merge v1.4.6 into v1.5 

---

CHANGELOG.md

Prepare release v1.5.0-rc4 aka Cancoillotte

Prepare release 1.5.0-rc4

---

glide.lock
glide.yaml

Put same hash in `glide.yml` as `glide.lock`
to be consistent

fix: glide files.

---

docs/configuration/backends/kubernetes.md

Document the rewrite-target annotation.

Document rewrite-target annotation.

---

autogen/gentemplates/gen.go
provider/kv/kv_config.go
provider/kv/kv_config_test.go
templates/kv.tmpl

homogenization of templates: KV

---

autogen/gentemplates/gen.go
provider/rancher/config.go
provider/rancher/config_test.go
templates/rancher.tmpl

homogenization of templates: Rancher

---

autogen/gentemplates/gen.go
provider/ecs/config.go
provider/ecs/config_test.go
templates/ecs.tmpl

homogenization of templates: ECS

---

autogen/gentemplates/gen.go
templates/docker.tmpl

Typo with load balance in Docker template.
Fixes #2684

fix: typo in Docker template.

---

CHANGELOG.md

Prepare release v1.5.0-rc5 aka Cancoillotte

Prepare release v1.5.0-rc5

---

mkdocs.yml

Add Tracing entry in the documentation.
Show the documentation.
Related to #2587

Add Tracing entry in the documentation.

---

docs/configuration/backends/file.md
docs/configuration/entrypoints.md

This PR fixes documentation on dynamic TLS certificates.
The documentation needed to be fixed of course!

Fix doc dynamic certificates

---

.travis.yml

Use https://github.com/containous/structor
Have a documentation already up-to-date.
Have cool URL.

New multi version documentation mechanism

---

.travis.yml

Deploy pages on all branches.
Have a always green documentation.
Related to #2741

Deploy pages on all branches.

---

autogen/gentemplates/gen.go
templates/kubernetes.tmpl

Fix the k8s redirection template.
Fix a bug

Fix the k8s redirection template.

---

script/test-integration

Increase integration tests timeout.
To build on the CI.

Increase integration tests timeout.

---

.travis.yml

This PR fix an issue introduced by #2745
FIxes #2749

Fix add src.tar.gz in Træfik release

---

.travis.yml

Fix tar gz source only on tags on travis

Fix tar gz source only on tags on travis

---

docs/configuration/acme.md

Explain that you can use redirect with http-challenge in ACME
To answer common question on http-challenge

Add note on redirect for ACME http challenge

---

docs/basics.md
docs/configuration/acme.md
docs/configuration/backends/file.md
docs/configuration/commons.md
docs/configuration/entrypoints.md

Add some file config references.
A better doc for a better life 😃

Enhance file provider documentation.

---

cmd/traefik/traefik.go
configuration/provider_aggregator.go
provider/rest/rest.go
server/server.go
server/server_test.go

This PR extract the configureProvider out of server.
I want to clean server.go with only what is really necessary in the "server".
This is first step, more coming ;)

Extract providers configuration from server.go

---

CHANGELOG.md

Prepare release v1.5.1

---

.travis.yml
script/deploy.sh

- build image.
- remove old `emilevauge/traefik` image.
Rebuild experimental image.

Rebuild experimental image

---

docs/configuration/entrypoints.md
docs/user-guide/cluster-docker-consul.md

Add documentation about entry points definition with CLI.
Easy CLI configuration.
Closes #2797

Add documentation about entry points definition with CLI.

---

examples/compose-rancher.yml
examples/compose-traefik.yml
examples/k8s/traefik-deployment.yaml

Remove web provider in example

---

CONTRIBUTING.md
build.Dockerfile

Due to the disappearance of https://github.com/jteeuwen on GitHub.
Replace https://github.com/jteeuwen/go-bindata by https://github.com/containous/go-bindata
Build !!

Change go-bindata

---

CONTRIBUTING.md
Gopkg.lock
acme/acme.go
build.Dockerfile
cmd/traefik/traefik.go
docs/basics.md
docs/configuration/acme.md
docs/configuration/entrypoints.md
docs/user-guide/cluster-docker-consul.md
docs/user-guide/docker-and-lets-encrypt.md
docs/user-guide/kv-config.md
integration/acme_test.go
integration/fixtures/acme/wrong_acme.toml
provider/docker/docker.go
provider/docker/swarm_test.go

Merge current v1.5 into master
Be sync.

Merge current v1.5 into master

---

CHANGELOG.md

Prepare release v1.5.2

---

autogen/gentemplates/gen.go
cmd/traefik/anonymize/anonymize_config_test.go
cmd/traefik/configuration.go
provider/eureka/config.go
provider/eureka/config_test.go
provider/eureka/eureka.go
templates/eureka.tmpl

- Remove `client` creation from `buildConfiguration`
-  Clean template
Homogenization of the providers [part1]

Homogenization of templates: Eureka 

---

cmd/traefik/healthcheck.go

Check if Ping pointer is not nil.
Fixes  #2851

Check ping configuration.

---

webui/package.json
webui/src/app/sections/providers/providers.controller.js
webui/yarn.lock

Refresh UI only if providers data change.
Facilitate copy-paste.

Smooth dashboard refresh.

---

docs/configuration/backends/consulcatalog.md
docs/configuration/backends/docker.md
docs/configuration/backends/ecs.md
docs/configuration/backends/kubernetes.md
docs/configuration/backends/marathon.md
docs/configuration/backends/mesos.md
docs/configuration/backends/rancher.md

Split security labels and custom labels documentation.
Have a clear documentation

Split security labels and custom labels documentation.

---

middlewares/tracing/tracing.go

Removes unnecessary returns.
Simpler code.
None.

Remove unnecessary returns in tracing setup

---

.gometalinter.json
cmd/traefik/storeconfig.go
cmd/traefik/traefik.go
integration/consul_test.go
log/logger.go
middlewares/metrics_test.go
middlewares/redirect/redirect_test.go
middlewares/retry.go
provider/marathon/builder_test.go
provider/marathon/config_test.go

Fixes some problems:
- remove dead code
- use valid pattern with `print-format`
- missing errors return
- positive error codes
Add a "raw" gometalinter configuration, for now it's not use anywhere.
Enhance code.

Linting some code

---

CONTRIBUTING.md
build.Dockerfile

Updates to golang 1.10.
Being up-to-date on golang ^_^

Update to golang 1.10

---

provider/docker/builder_test.go
provider/docker/docker.go
provider/docker/swarm_test.go

Fixes #2869 
This issue has already been fixed in 1.6  (#2827) with detailed logs and tests
Due to a huge refactor of docker provider in 1.6, I will not add tests and logs in this PR to simplify the merge back. 
Please referrer to #2827

Empty ip address when endpoint mode dnsrr

---

.github/ISSUE_TEMPLATE/bugs.md
.github/ISSUE_TEMPLATE/features.md
.github/PULL_REQUEST_TEMPLATE/mergeback.md
.github/PULL_REQUEST_TEMPLATE/release.md

Add some new issue and PR templates.
It's a first try.
Have better issue and PR templates
https://github.com/blog/2495-multiple-issue-and-pull-request-templates

Multiple issue and pull request templates.

---

docs/configuration/entrypoints.md

This PR fixes cipher suites documentation reported in https://github.com/containous/traefik/issues/1371.
The documentation should give examples that work out of the box.

Fix doc cipher suites

---

.github/ISSUE_TEMPLATE/bugs.md
.github/ISSUE_TEMPLATE/features.md
.github/PULL_REQUEST_TEMPLATE/mergeback.md
.github/PULL_REQUEST_TEMPLATE/release.md
README.md
cmd/traefik/healthcheck.go
docs/configuration/acme.md
docs/configuration/api.md
docs/configuration/backends/web.md
docs/configuration/entrypoints.md
docs/configuration/ping.md
docs/index.md
docs/user-guide/examples.md
integration/basic_test.go
integration/constraint_test.go
integration/consul_catalog_test.go
integration/docker_test.go
integration/fixtures/multiple_provider.toml
integration/ratelimit_test.go
integration/resources/compose/base.yml
integration/resources/compose/constraints.yml
integration/resources/compose/consul_catalog.yml
integration/resources/compose/error_pages.yml
integration/resources/compose/file.yml
integration/resources/compose/ratelimit.yml
server/server.go
webui/package.json
webui/src/app/sections/providers/providers.controller.js
webui/yarn.lock

Merge current v1.5 into master
Be sync.

 Merge current v1.5 into master

---

docs/user-guide/docker-and-lets-encrypt.md

it's -> its

---

middlewares/tracing/tracing.go

This PR fix `<nil>` tracing/tracer value in KV
Fixes #2910

Fix <nil> tracer value in KV

---

server/server.go

This PR adds a `DEBUG` log if no certificate provided dynamically can be served for a domain.
This log will help to analyze the issues when the default certificate is served instead of a provided one.

 Add DEBUG log when no provided certificate can check a domain

---

CHANGELOG.md

Prepare release v1.5.3

---

.travis.yml

Disable edge option.
Publish documentation
Related to https://github.com/travis-ci/dpl/issues/762

fix: gh-pages drop edge.

---

docs/configuration/acme.md

Clarify the link between `dnsProvider` and `dnsChallenge`
Can be confusing for some people.

Clarify some deprecations.

---

autogen/gentemplates/gen.go
templates/consul_catalog.tmpl
templates/docker.tmpl
templates/ecs.tmpl
templates/eureka.tmpl
templates/kubernetes.tmpl
templates/kv.tmpl
templates/marathon.tmpl
templates/mesos.tmpl
templates/rancher.tmpl

Add some missing quotes in templates
Be safe with Unicode characters.

Add some missing quotes in templates

---

provider/ecs/ecs.go

Use `aws` converter for pointer value.
Be safe when use value from a pointer.
Related to #2978

Safe access to ECS API pointer values.

---

whitelist/ip.go
whitelist/ip_test.go

Propagate insecure in white list.
Fix a bug

Propagate insecure in white list.

---

metrics/influxdb.go
metrics/influxdb_test.go

Added entrypoint metrics to influxdb
Added this with reference to #2567

Added entrypoint metrics to influxdb

---

examples/accessLog/traefik.ab.toml
examples/accessLog/traefik.example.toml
examples/acme/acme.toml
examples/compose-rancher.yml
examples/compose-traefik.yml
examples/k8s/traefik-deployment.yaml
examples/k8s/traefik-ds.yaml
integration/fixtures/acme/acme_http01.toml
integration/fixtures/acme/acme_http01_web.toml
integration/fixtures/acme/certificates.toml
traefik.sample.toml

Enhance Traefik TOML sample.
Have a better starting sample.

Enhance Traefik TOML sample.

---

docs/index.md

Changes the `docker-compose.yml` files so they use version 3
Changes the scale command according to the latest docker version

Updated the test-it example according to the latest docker version

---

docs/configuration/backends/file.md

Add [file] in syntax reference.

Add [file] in syntax reference

---

CHANGELOG.md

Prepare release v1.5.4

---

docs/configuration/backends/kubernetes.md

Fix link to `InsecureSkipVerify` option.
No more 404s.
Fixes #3045.

Fix link to InsecureSkipVerify option.

---

CHANGELOG.md
Gopkg.lock
Gopkg.toml
vendor/github.com/containous/traefik-extra-service-fabric/servicefabric_config.go
vendor/github.com/containous/traefik-extra-service-fabric/servicefabric_tmpl.go

Add white list for Service Fabric.
Add white list for Service Fabric

Add white list for Service Fabric

---

configuration/configuration.go

Fix a `panic` when ACME configuration has error in its EntryPoint.
Generate a Fatal message instead of panic.

Fix panic with wrong ACME configuration

---

CHANGELOG.md

Prepare release v1.6.0-rc2

---

autogen/gentemplates/gen.go
provider/docker/config.go
provider/docker/config_container_docker_test.go
provider/docker/config_container_swarm_test.go
provider/label/segment.go
provider/rancher/config.go
provider/rancher/config_test.go
provider/rancher/deprecated_config.go
provider/rancher/deprecated_config_test.go
templates/docker.tmpl
templates/rancher.tmpl

Fixes frontend rule and segment labels.
Fixes #3089, #3094

Frontend rule and segment labels.

---

CHANGELOG.md

Prepare release v1.6.0-rc3.

---

provider/kubernetes/annotations.go
provider/kubernetes/annotations_test.go

Fixes prefixed annotations support for k8s.
Fix a bug

Fixes prefixed annotations support.

---

docs/user-guide/docker-and-lets-encrypt.md

Merge current v1.5 into v1.6
Be sync.

Merge current v1.5 into v1.6

---

CHANGELOG.md

Prepare release v1.6.0-rc4

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bugs.md

Command version explanation for alpine image.
Have a good GitHub template.

Command version explanation for alpine image.

---

README.md
docs/configuration/backends/servicefabric.md
docs/index.md
mkdocs.yml

Fixes Azure brand in the documentation, README.
Service Fabric should be Azure Service Fabric.

Fix Azure brand

---

tls/generate/generate.go

Fixes #3168 
Fix the expirary date for the default cert so its of use again :)

Default certificate expiry

---

provider/ecs/config.go
provider/ecs/config_root.go
provider/ecs/config_test.go
provider/ecs/deprecated_config.go
provider/ecs/deprecated_config_test.go
provider/ecs/ecs.go

Factorize labels managements.
Missing part for ECS
Homogenization of the providers [part5]: have a shared way to manage labels.
Related to #2785

Factorize labels managements.

---

README.md
docs/configuration/backends/servicefabric.md
docs/index.md
mkdocs.yml
tls/generate/generate.go

Merge current v1.5 into v1.6
Be sync.

Merge current v1.5 into v1.6 

---

CHANGELOG.md

Prepare release 1.6.0-rc5

---

Gopkg.lock
Gopkg.toml
vendor/github.com/containous/traefik-extra-service-fabric/servicefabric_tmpl.go

Update extra-service-fabric.
fix: backend name for stateful service.

fix: backend name for stateful service.

---

Gopkg.lock
Gopkg.toml
vendor/github.com/containous/traefik-extra-service-fabric/servicefabric.go
vendor/github.com/containous/traefik-extra-service-fabric/servicefabric_config.go
vendor/github.com/containous/traefik-extra-service-fabric/servicefabric_tmpl.go

Update extra-service-fabric.
- fix: backend name for stateful service.
- fix: weight
- fix: rule for stateful service.
Related https://github.com/containous/traefik-extra-service-fabric/pull/28

fix: backend name for stateful service and more.

---

server/server.go

Add missing argument in log.

---

docs/configuration/backends/consulcatalog.md
docs/configuration/backends/docker.md
docs/configuration/backends/ecs.md
docs/configuration/backends/marathon.md
docs/configuration/backends/mesos.md
docs/configuration/backends/rancher.md

Remove quotes around `templateVersion` in the documentation.
Have a clear documentation.

fix: template version documentation.

---

Gopkg.lock
Gopkg.toml
metrics/influxdb_test.go
metrics/prometheus.go
testhelpers/metrics.go
vendor/github.com/go-kit/kit/log/doc.go
vendor/github.com/go-kit/kit/log/json_logger.go
vendor/github.com/go-kit/kit/log/log.go
vendor/github.com/go-kit/kit/log/stdlib.go
vendor/github.com/go-kit/kit/log/sync.go
vendor/github.com/go-kit/kit/log/value.go
vendor/github.com/go-kit/kit/metrics/doc.go
vendor/github.com/go-kit/kit/metrics/dogstatsd/dogstatsd.go
vendor/github.com/go-kit/kit/metrics/generic/generic.go
vendor/github.com/go-kit/kit/metrics/influx/influx.go
vendor/github.com/go-kit/kit/metrics/internal/lv/space.go
vendor/github.com/go-kit/kit/metrics/metrics.go
vendor/github.com/go-kit/kit/metrics/multi/multi.go
vendor/github.com/go-kit/kit/metrics/statsd/statsd.go
vendor/github.com/go-kit/kit/metrics/timer.go

This PR update `go-kit` to fix an issue on duplicated tags in InfluxDB
Fixes: #3146
It was an [issue of go-kit](https://github.com/go-kit/kit/pull/404)

Fix duplicated tags in InfluxDB

---

integration/docker_compose_test.go
integration/resources/compose/minimal.yml
provider/docker/docker.go
provider/docker/docker_test.go

This PR update the docker provider to fix an issue with the docker compose scale.
Fix #3145

Fix multiple frontends with docker-compose --scale

---

provider/docker/config.go
provider/docker/config_container_docker_test.go
provider/rancher/config.go
provider/rancher/config_test.go

Ignore server for container with empty IP address.
Fix a bug

Ignore server for container with empty IP address.

---

docs/configuration/entrypoints.md

Fix typo in documentation

---

middlewares/errorpages/error_pages.go
middlewares/errorpages/error_pages_test.go

- fix: error pages query redirect.
- fix: error pages headers
Fixes #2939

Fix error pages redirect and headers.

---

docs/basics.md
docs/index.md
examples/quickstart/README.md

Makes minor improvements to the documentation:
- adds a missing space
- fixes a broken link
- fixes some grammar and punctuation
- changes the order/indenting of topics under Basics > Backends to make it a bit easier to get started
Just things I noticed while getting started with Traefik

Minor improvements to documentation

---

webui/src/app/components/providers/providers.component.html
webui/src/styles/app.sass

Add redirect information to web UI.
I forgot to add it in the previous PR #2226 .

Add redirect section.

---

CHANGELOG.md

Add @tcolgate as author of the Open Tracing support.
Sorry for what happened again @tcolgate.
Our change log is generated, we missed to add you manually.

fix: 1.6 change log.

---

acme/acme.go
configuration/configuration.go

Add missing deprecation info in CLI help.
To have a good CLI help.

Add missing deprecation info in CLI help.

---

CHANGELOG.md

Prepare release v1.6.1

---

webui/src/app/components/providers/providers.component.html

- add HealthCheck scheme (related to #3315)
- add Header sslForceHost (related to #3246)
To have a good webui

Add some missing elements in the WebUI

---

.github/PULL_REQUEST_TEMPLATE.md

Fix the contributing guide link in PR template.
It was broken

Fix contributing guide link in PR template

---

middlewares/errorpages/error_pages.go

fix: error pages content. 
Error page returns no content.
Fixes #3338

Fix error pages content. 

---

.semaphoreci/cleanup.sh
.semaphoreci/job1.sh
.semaphoreci/job2.sh
.semaphoreci/setup.sh
.semaphoreci/tests.sh

Modifies tests to only run if code files have been changed. Don't run if documentation or example files have been modified
20 minute CI builds when someone changes a line of documentation
Obviously these aren't the commands that get run during the build, but we should review this for sanity before updating the CI commands

Modify tests to only run if non-static files have been modified

---

server/server.go
types/types.go

Enhance Load-balancing method validation log.
Many people when they saw the previous log thought there was a problem:
```
level=debug msg="Validation of load balancer method for backend backend-foo failed: invalid load-balancing method ''. Using default method wrr."
```

Enhance Load-balancing method validation log.

---

.semaphoreci/setup.sh

Add missing quotes.
Launch tests even if the PR contains one `.md/.yml` file.

Add missing quotes.

---

webui/src/app/components/providers/providers.component.html

Fixes Whitelist overflow.
Fixes #3410

Webui Whitelist overflow.

---

integration/access_log_test.go
middlewares/accesslog/save_backend.go
middlewares/accesslog/save_frontend.go

Add URL and Host for some access logs.
Fix a bug.

Add URL and Host for some access logs.

---

Gopkg.lock
Gopkg.toml
acme/acme.go
provider/acme/provider.go
vendor/github.com/xenolf/lego/acme/client.go
vendor/github.com/xenolf/lego/acme/http.go

Add user agent for ACME.
Allow ACME to see traffic Traefik.

Add user agent for ACME

---

integration/consul_catalog_test.go
provider/consulcatalog/consul_catalog.go

This PR allow Træfik to watch maintenance change
Fixes #3157
Thanks to @trondhindenes for testing

Detect change when service or node are in maintenance mode

---

CHANGELOG.md

Prepare release v1.6.3

---

contrib/grafana/traefik-kubernetes.json
contrib/grafana/traefik.json

Adding grafana dashboards based on promtheus metrics for standard and k8s config

Adding grafana dashboards based on prometheus metrics

---

Gopkg.lock
server/bufferpool.go
server/server.go
vendor/github.com/vulcand/oxy/forward/fwd.go

Merge current v1.6 into master
Be sync.

Merge current v1.6 into master

---

docs/configuration/backends/kubernetes.md

Add missing annotation documentation.
Fixes #3453

Add missing annotation documentation.

---

README.md
docs/index.md
mkdocs.yml

Temporary benchmarks removal during performance optimization process (initiated with https://github.com/vulcand/oxy/pull/138, https://github.com/containous/traefik/pull/3450).
This page will be updated later with latest releases and updated test protocol.
Get updated benchmarks.

Temporary benchmarks removal during performance optimization process

---

docs/user-guide/kv-config.md

Fixes the wrong key in the example for certificate 2, in the key-value store configuration user guide.
Making a better documentation.

Fix typo in kv user guide

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
CONTRIBUTING.md
README.md
cmd/bug/bug.go
docs/index.md
mkdocs.yml

Update Slack URL.
Update Slack URL.

Update Slack URL.

---

provider/docker/config.go
provider/ecs/config.go
provider/marathon/config.go
provider/mesos/config.go
provider/rancher/config.go

Use `net.JoinHostPort` for servers URL.
Support IPv6

Use net.JoinHostPort for servers URL

---

docs/configuration/metrics.md

Clean metrics documentation.

---

acme/acme.go
acme/challenge_http_provider.go
provider/acme/provider.go

Simplify get acme client
Easier to read and change.

Simplify get acme client

---

CHANGELOG.md

Prepare release v1.6.4

---

Gopkg.lock
middlewares/pipelining/pipelining.go
middlewares/pipelining/pipelining_test.go
server/server.go
vendor/github.com/vulcand/oxy/cbreaker/cbreaker.go
vendor/github.com/vulcand/oxy/forward/fwd.go
vendor/github.com/vulcand/oxy/roundrobin/rebalancer.go
vendor/github.com/vulcand/oxy/utils/netutils.go

This PR creates a new middleware to be able to handle correctly HTTP pipelining
Fixes #3443

Create middleware to be able to handle HTTP pipelining correctly

---

provider/docker/config.go
provider/docker/config_container_docker_test.go
provider/docker/config_container_swarm_test.go
provider/docker/config_segment_test.go

segment labels: multiple frontends for one backend.
segment labels: multiple frontends for one backend.

segment labels: multiple frontends for one backend.

---

Gopkg.lock
Gopkg.toml
vendor/github.com/containous/staert/kv.go
vendor/github.com/containous/staert/staert.go
vendor/github.com/containous/staert/toml.go

Update the staert version to have a better support to list element from a kv store
Related to https://github.com/containous/staert/pull/46
Fixes #3249

Better support on same prefix at the same level in the KV

---

docs/user-guide/swarm-mode.md

Minor formatting issue in user-guide

---

docs/user-guide/kv-config.md

Update keyFile first/last line comment in kv-config.md

---

Gopkg.lock
vendor/github.com/vulcand/oxy/forward/rewrite.go
vendor/github.com/vulcand/oxy/utils/handler.go

Update oxy in order to have https://github.com/vulcand/oxy/pull/142
More information when trying to debug some errors (like 502 in #3237 for example)

Add logs when error is generated in error handler

---

provider/acme/challenge_http.go
provider/acme/local_store.go
provider/acme/store.go

Merge current v1.6 into v1.7
Be sync.

Merge current v1.6 into v1.7

---

provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Adds more tests
Tests are good.
Removed unreachable case in rule switch

Add more K8s Unit Tests

---

CHANGELOG.md

Prepare release v1.6.5

---

Gopkg.lock
vendor/github.com/vulcand/oxy/buffer/buffer.go
vendor/github.com/vulcand/oxy/buffer/threshold.go
vendor/github.com/vulcand/oxy/cbreaker/cbreaker.go
vendor/github.com/vulcand/oxy/cbreaker/effect.go
vendor/github.com/vulcand/oxy/cbreaker/fallback.go
vendor/github.com/vulcand/oxy/cbreaker/predicates.go
vendor/github.com/vulcand/oxy/cbreaker/ratio.go
vendor/github.com/vulcand/oxy/connlimit/connlimit.go
vendor/github.com/vulcand/oxy/forward/fwd.go
vendor/github.com/vulcand/oxy/forward/headers.go
vendor/github.com/vulcand/oxy/forward/rewrite.go
vendor/github.com/vulcand/oxy/memmetrics/anomaly.go
vendor/github.com/vulcand/oxy/memmetrics/counter.go
vendor/github.com/vulcand/oxy/memmetrics/histogram.go
vendor/github.com/vulcand/oxy/memmetrics/ratio.go
vendor/github.com/vulcand/oxy/memmetrics/roundtrip.go
vendor/github.com/vulcand/oxy/ratelimit/bucket.go
vendor/github.com/vulcand/oxy/ratelimit/bucketset.go
vendor/github.com/vulcand/oxy/ratelimit/tokenlimiter.go
vendor/github.com/vulcand/oxy/roundrobin/RequestRewriteListener.go
vendor/github.com/vulcand/oxy/roundrobin/rebalancer.go
vendor/github.com/vulcand/oxy/roundrobin/rr.go
vendor/github.com/vulcand/oxy/roundrobin/stickysessions.go
vendor/github.com/vulcand/oxy/utils/auth.go
vendor/github.com/vulcand/oxy/utils/dumpreq.go
vendor/github.com/vulcand/oxy/utils/handler.go
vendor/github.com/vulcand/oxy/utils/netutils.go
vendor/github.com/vulcand/oxy/utils/source.go

Update oxy
Send 'Retry-After' to comply with [RFC6585](https://tools.ietf.org/html/rfc6585#section-4).
Related to https://github.com/vulcand/oxy/pull/141, #3440

Send 'Retry-After' to comply with RFC6585.

---

provider/ecs/deprecated_config.go

This PR fix a bad condition in ECS provider

Fix bad condition in ECS provider

---

configuration/configuration.go

Remove unusable `--cluster` command from flag list
Fixes #3614

Remove unusable `--cluster` flag

---

Gopkg.lock
Gopkg.toml
vendor/github.com/containous/traefik-extra-service-fabric/servicefabric.go

Update service fabric to the new version
we don't to stay on a specific branch anymore

Update service fabric

---

middlewares/retry.go
types/types.go
webui/src/app/components/providers/providers.component.html

- fix: Auth section in web UI. 
- fix JSON api
Fixes  #3612

Auth section in web UI. 

---

Gopkg.lock
provider/docker/config.go
provider/docker/config_container_docker_test.go
provider/docker/config_container_swarm_test.go
provider/docker/deprecated_config.go
provider/docker/deprecated_container_docker_test.go
provider/docker/deprecated_container_swarm_test.go
server/server.go
server/server_configuration.go
vendor/github.com/vulcand/oxy/forward/fwd.go

Merge current v1.7 into master
Be sync.

Merge current v1.7 into master

---

docs/user-guide/kubernetes.md
script/docs-verify-docker-image/validate.sh

This PR allow Docs verify to failed only on 4XX

Docs verify failed only on 4XX

---

integration/consul_test.go
integration/etcd3_test.go
integration/etcd_test.go
integration/https_test.go

This PR improve TLS integration tests
Have more readable tests

Improve TLS integration tests

---

docs/configuration/tracing.md
middlewares/tracing/entrypoint_test.go

This PR fix missing information in tracing documentation
Have a better documentation

Fix missing tracing backend in documentation

---

docs/configuration/tracing.md

Small documentation grammar fix in tracing.md
While reading the documentation I noticed this inconsistency.
I love Træfik! Thanks for all the hard work.

Simple documentation grammar update in tracing

---

docs/index.md

Correction of the syntax of docker-compose command
Allow new users to follow successfully the quick start guide.
Related to #3677

Change syntax in quick start guide

---

docs/configuration/backends/kubernetes.md
docs/configuration/tracing.md
docs/index.md
docs/user-guide/docker-and-lets-encrypt.md
metrics/prometheus.go
metrics/prometheus_test.go
requirements.txt
server/server.go

Merge current v1.7 into master
Be sync.

 Merge current v1.7 into master

---

script/crossbinary-others

This PR is for supporting ppc64le platform support
Recently I attended a talk about traefik in [devconf 2018 event](https://devconfin2018.sched.com/event/FA7c/traefik-the-cloud-native-edge-router) by @dduportal , I liked the project and felt needed for ppc64le platform, hence sending this PR for making it availble on ppc64le platform.
Thanks,
Manjunath.

Add ppc64le platform support

---

docs/configuration/acme.md

Update ACME documentation about TLS-ALPN challenge.

Update ACME documentation about TLS-ALPN challenge

---

acme/acme.go
acme/acme_test.go
examples/acme/manage_acme_docker_environment.sh
provider/acme/provider.go
provider/acme/provider_test.go

This PR adds to the ACME implementations a map which contains all the domains with a resolution in progress.
Thus an ACME certifciate will not be generated twice (or more) for the same domain at the same moment.
Fixes #3414

Avoid duplicated ACME resolution

---

CHANGELOG.md

Prepare Release v1.6.6

---

docs/index.md
mkdocs.yml

This PR adds a link to report vulnerabilities in the documentation.
Implement a responsible disclosure policy.

Add vulnerability form

---

docs/user-guide/docker-and-lets-encrypt.md

This PR mentions that you also need `docker-compose` installed in the server for the steps outlined in the guide to work.
I was following the let's encrypt guide and I found that at a later point, the guide uses the `docker-compose` CLI, so I needed to install it on the server.
_None_.

Mention docker-compose as a requirement in the let's encrypt guide

---

mkdocs.yml

Fix the palette in documentation.
The color palette in documentation is bad.

Fixes bad palette in doc

---

autogen/gentemplates/gen.go
templates/consul_catalog.tmpl
templates/docker.tmpl
templates/ecs.tmpl
templates/kubernetes.tmpl
templates/kv.tmpl
templates/marathon.tmpl
templates/mesos.tmpl
templates/rancher.tmpl

Auth Forward with certificates in templates.
Fixes #3803

Auth Forward with certificates in templates.

---

README.md
docs/index.md

This PR adds security mailing list to doc, and mailing lists to the README.
Get security mailing list to doc, and mailing lists to the README.

Add security mailinglist

---

provider/kubernetes/kubernetes.go

Re-created https://github.com/containous/traefik/pull/3456

Remove unnecessary loop

---

README.md
docs/index.md
mkdocs.yml

Rename traefikproxy twitter account into traefik
Have a correct twitter link

Rename traefikproxy twitter account into traefik

---

README.md
docs/index.md
mkdocs.yml

Merge branch v1.6 into v1.7
Be sync.

Merge v1.6 into v1.7

---

integration/retry_test.go
middlewares/retry.go
middlewares/retry_test.go

Enable retry on websocket
Having retry on websocket

Enable retry on websocket

---

docs/configuration/api.md

Remove a dead link.
Fixes #3849

Remove a dead link.

---

log/logger.go

This PR adds an interface to Trafik logger in the way to make it customizable.
Make the code better.

Add interface to Træfik logger

---

CHANGELOG.md

Prepare release v1.7.0-rc5
Create a new release candidate.

Prepare release 1.7.0-rc5

---

Gopkg.lock
vendor/github.com/xenolf/lego/acme/client.go
vendor/github.com/xenolf/lego/acme/dns_challenge.go
vendor/github.com/xenolf/lego/log/logger.go
vendor/github.com/xenolf/lego/providers/dns/azure/azure.go
vendor/github.com/xenolf/lego/providers/dns/gcloud/googlecloud.go
vendor/github.com/xenolf/lego/providers/dns/iij/iij.go
vendor/github.com/xenolf/lego/providers/dns/ns1/ns1.go

- fix ns1 getHostedZone.
- fix gcloud, azure, iij errors.
-  fix gcloud and wilcard
Fixes #3912, #3871

Fix some DNS providers issues

---

Gopkg.lock
vendor/github.com/vulcand/oxy/buffer/buffer.go
vendor/github.com/vulcand/oxy/cbreaker/fallback.go
vendor/github.com/vulcand/oxy/forward/fwd.go

Update oxy.
Related https://github.com/vulcand/oxy/pull/160
Use the good logger

Fix logger in Oxy

---

acme/acme.go

Set the store after the init.
Fixes #3830

Fix TLS ALPN cluster mode.

---

CHANGELOG.md

Prepare release v1.7.1

---

Gopkg.lock
vendor/github.com/konsorten/go-windows-terminal-sequences/license
vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
vendor/github.com/sirupsen/logrus/entry.go
vendor/github.com/sirupsen/logrus/exported.go
vendor/github.com/sirupsen/logrus/formatter.go
vendor/github.com/sirupsen/logrus/json_formatter.go
vendor/github.com/sirupsen/logrus/logger.go
vendor/github.com/sirupsen/logrus/logrus.go
vendor/github.com/sirupsen/logrus/terminal_appengine.go
vendor/github.com/sirupsen/logrus/terminal_bsd.go
vendor/github.com/sirupsen/logrus/terminal_check_js.go
vendor/github.com/sirupsen/logrus/terminal_check_windows.go
vendor/github.com/sirupsen/logrus/terminal_linux.go
vendor/github.com/sirupsen/logrus/terminal_windows.go
vendor/github.com/sirupsen/logrus/text_formatter.go

Fix colored logs on windows.
Thanks to @AndrewSav

Colored logs on windows.

---

CHANGELOG.md

Prepare release v1.7.2

---

MAINTAINER.md

This PR adds 
* Gérald Croës [@geraldcroes](https://github.com/geraldcroes)
* Jean-Baptiste Doumenjou [@jbdoumenjou](https://github.com/jbdoumenjou)
* Damien Duportal [@dduportal](https://github.com/dduportal)
to the maintainers.
They are now ready to give LGTM ;)

Add Gerald, Jean-Baptiste and Damien to maintainers

---

build.Dockerfile

Change golint path
Seems related to https://github.com/golang/lint/commit/9a272034dedb2a3ed05231d5604ce17fb40f0e58
https://github.com/golang/lint/issues/415

fix: golint.

---

middlewares/recover.go
safe/routine.go
safe/routine_test.go
safe/safe_test.go

Log stack when panic.
To have a better log when a panic occurs.

Log stack when panic

---

CHANGELOG.md

Prepare release v1.7.3

---

MAINTAINER.md

This PR improves maintainers documentation

Improve maintainer documentation

---

webui/src/app/components/providers/providers.component.html

SSL Host -> SSL Force Host
To have a good UI
https://github.com/containous/traefik/issues/4087#issuecomment-432189125

Typo in the UI.

---

provider/consulcatalog/config.go
provider/consulcatalog/config_test.go
provider/docker/config.go
provider/ecs/config.go
provider/ecs/config_test.go
provider/marathon/config.go
provider/mesos/config.go
provider/rancher/config.go

Remove the trailing dot if the domain is not defined.
Fix a bug
Seems related to #4011
Thanks to @hsmade 
Linked to #4086 and #4056

Remove the trailing dot if the domain is not defined.

---

docs/configuration/backends/docker.md

Fixes #4056 
Improve documentation and keep configuration as small and useful as possible without clutter
Couldn't get the last line to not show up in the commit :crying_cat_face:

domain is also optional for "normal" mode

---

webui/src/app/charts/bar-chart/bar-chart.component.ts

Removed unused imports, `easeLinear` and `min` from `bar-chart.component.ts`
Noticed the alerts on [lgtm](https://lgtm.com/projects/g/containous/traefik/alerts/?mode=tree&ruleFocus=1780092).

Removed unused imports

---

provider/docker/docker.go

Use GoCtx in provider docker
Handle provider docker shutdown correctly when traefik is shutting down

Provider docker shutdown problem

---

CHANGELOG.md

Prepare release v1.7.4

---

provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go
provider/kubernetes/weight_allocator.go
provider/kubernetes/weight_allocator_test.go

Support weight-based canary strategy for external-name service
Fixes: #4119

Support canary weight for external name service

---

docs/configuration/api.md
docs/configuration/ping.md

Fixes #4077, #4117 
To improve documentation for newcomers.

Documentation: Rename "admin panel" to "dashboard

---

examples/quickstart/docker-compose.yml

Fixes a minor spelling mistake
Pedants will not be distracted

Fix spelling in comment

---

Gopkg.lock
Gopkg.toml
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/ddtrace.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/ext/app_types.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/ext/db.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/ext/peer.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/ext/tags.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/internal/globaltracer.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/option.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/span.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/span_msgp.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/textmap.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/transport.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/util.go

Upgraded DD APM library to the latest version.

Upgraded DD APM library

---

docs/configuration/backends/docker.md

Cherry pick v1.7 into master:
- Update swarm mode endpoint (https://github.com/containous/traefik/pull/4208)
- Fix partial declaration of authentication. (https://github.com/containous/traefik/pull/4212)
Be sync.

Cherry pick v1.7 into master

---

docs/basics.md

Explains how the associativity works inside and between matchers.

Matcher associativity rule.

---

Gopkg.lock
vendor/github.com/vulcand/oxy/forward/fwd.go

Update vulcand/oxy
Fix a bug with unannonced trailers.
Fixes #4181

Fix unannonced trailers problem when body is empty

---

CHANGELOG.md

Prepare release v1.7.5

---

acme/acme.go
anonymize/anonymize_config_test.go
cmd/storeconfig/storeconfig.go

Remove Deprecated StorageFile.
No more deprecated.

Remove Deprecated StorageFile

---

CHANGELOG.md
build.Dockerfile

Prepare release v1.7.6

---

provider/kubernetes/client.go

Adds a check to ensure that only watched namespaces are requested via the client. Requesting objects outside the watched namespace list results in a panic.
Fixes #4314

Check for watched namespace before getting kubernetes objects

---

CHANGELOG.md

Prepare release v1.7.7

---

mkdocs.yml

Happy 2019

---

Gopkg.lock
Gopkg.toml
acme/acme.go
provider/acme/provider.go
vendor/github.com/xenolf/lego/acme/api/internal/sender/useragent.go
vendor/github.com/xenolf/lego/certificate/certificates.go
vendor/github.com/xenolf/lego/lego/client.go
vendor/github.com/xenolf/lego/lego/client_config.go
vendor/github.com/xenolf/lego/providers/dns/gcloud/googlecloud.go
vendor/github.com/xenolf/lego/providers/dns/rfc2136/rfc2136.go
vendor/github.com/xenolf/lego/providers/dns/transip/transip.go

Update Lego.
Fixes  #4346, #4344, #4141

fix: update lego.

---

docs/configuration/entrypoints.md

Note about quotes for entrypoint definition with docker-compose

---

CHANGELOG.md

Prepare release v1.7.8

---

CHANGELOG.md

Adds missing item in the change log.
To have a good changelog.

doc: update change log.

---

.golangci.toml
cmd/bug/bug.go
cmd/traefik/traefik.go
config/static/entrypoints.go
config/static/static_config.go
healthcheck/healthcheck.go
middlewares/accesslog/logger.go
middlewares/auth/forward.go
middlewares/headers/headers_test.go
middlewares/passtlsclientcert/pass_tls_client_cert.go
middlewares/retry/retry_test.go
provider/acme/local_store.go
provider/acme/provider.go
provider/base_provider.go
provider/docker/config.go
provider/file/file.go
provider/rest/rest.go
server/server_signals.go
server/service/service.go
types/constraints.go

Applies some linting rules.
Enhance code quality.
For now, only some parts of the code are processed, I will do the complete treatment later.

refactor: applies linting.

---

docs/configuration/backends/rest.md

Fixed curl example

---

docs/basics.md

Fixes the display of the associativity rules.
https://docs.traefik.io/v1.7/basics/#matchers

Fixes the display of the associativity rules.

---

CHANGELOG.md

Prepare release v1.7.9

---

anonymize/anonymize_config_test.go
api/dashboard.go
api/handler.go
cluster/datastore.go
cmd/configuration.go
cmd/traefik/traefik.go
configuration/configuration.go
integration/etcd3_test.go
provider/etcd/etcd.go
provider/kubernetes/weight_allocator_test.go

Applies new goimports recommendations.
https://github.com/golang/tools/commit/ee45598d2ff288037f53f9e13ae0b1a6e2165ad5
```
go get -u golang.org/x/tools/cmd/goimports
goimports -w .
```

Applies new goimports recommendations.

---

README.md

fix: image links.
Have a good readme

fix: image links.

---

README.md

Fixed dead link in README.md.
Hi, I fixed dead link in README.md.
Please check this Pull Request.
Thank you.

Fixed dead link in README.md

---

.goreleaser.yml
.travis.yml
Makefile
build.Dockerfile

New packaging system.
Produce archive instead of binary.

New packaging system.

---

docs/content/providers/file.md
docs/content/reference/providers/file.md
docs/mkdocs.yml

Update the file provider documentation with the new configuration.
Have a doc up to date.

Update the file provider documentation

---

pkg/server/server_entrypoint_tcp.go

Fix a lock problem in the server_entrypoint
Fix a bug

Fix lock problem in server

---

docs/configuration/backends/docker.md

Add TraefikEE as a security workaround to the Docker socket exposure issue.
The documentation should be exhaustive.
https://github.com/containous/traefik/issues/4174

Add TraefikEE as security workaround

---

pkg/middlewares/accesslog/logger_test.go
pkg/provider/file/file_test.go

Clean file during tests.
Keep `/tmp` clean.

Clean files during tests.

---

script/deploy.sh

Change deploy script.
Be able to update https://github.com/containous/traefik-library-image during the release.

Change deploy script.

---

exp.Dockerfile

Fix new build system for experimental Docker image. 
Have the WebUI

Fix new build system for experimental Docker image. 

---

docs/content/getting-started/quick-start.md
docs/content/operations/dashboard.md
webui/src/app/app.component.ts

Adds some notice about the WIP Dashboard
Make it a bit more user friendly?
Co-authored-by: Jean-Baptiste Doumenjou <jb.doumenjou@gmail.com>

change docs and adjust dashboard for v2 alpha

---

docs/content/middlewares/forwardauth.md

This PR fixes a small typo in the forwardauth middleware documentation

Fix typo in forwardauth middleware documentation

---

docs/content/getting-started/quick-start.md
docs/content/providers/docker.md
docs/content/providers/file.md

This PR fix the Getting Started. 
Thanks to @skwair for his help ;)

Fix Getting started

---

docs/content/https-tls/overview.md
docs/content/middlewares/digestauth.md
docs/content/middlewares/overview.md
docs/content/operations/dashboard.md
docs/content/operations/ping.md
docs/content/providers/docker.md
docs/content/routing/entrypoints.md
docs/content/routing/routers/index.md
docs/content/routing/services/index.md

Fixes some minor errors on the documentation.
Applies formatting.
Enhance the documentation.

Fix some minors errors on the documentation

---

docs/configuration/acme.md

Closes #3853.
A pointer to the existence of Docker secret support within Traefik's documentation was missing.
None.

Add _FILE Environment Variable Documentation

---

Gopkg.lock
Gopkg.toml
vendor/github.com/thoas/stats/options.go
vendor/github.com/thoas/stats/recorder.go
vendor/github.com/thoas/stats/stats.go

Update dependency to fix #3620
The average response time on my dashboard was really bad because of it counting websocket connect.
not relevant 

Exclude websocket connections from Average Response Time

---

Gopkg.toml

Remove thoas/stats fork since my last PR was merged.
No need to maintain a fork.

Remove thoas/stats fork

---

CHANGELOG.md

Prepare release v1.7.10
