integration/etcd3_test.go
integration/try/condition.go

When I delete all the tls cert/key pairs in my etcd(v3),the debug log and api(/api/providers) show  traefik has read configurations which has an empty tlsconfigure.But Actually it does't work.
After reading the code,I think traefik skip delete when the all the tlsconfigurations in etcd be deleted in a very short time. 
And I wrote some test for this.
when i write test case in my own project,I delete the tls cert/key pairs,expecting recevie the "TRAEFIK DEFAULT CERT" from traefik,but what i receive is still the deleted one after a very long wait.

Add tests for TLS dynamic configuration in ETCD3

---

integration/https_test.go
provider/file/file.go

This PR allows sending empty configuration from `file` provider which is taken in account by Træfik.
Træfik filters dynamic configurations which have backends, frontends and TLS configurations set to nil.
Providers have to send empty configuration to update correctly the information.
The `file` provider sent empty data if it listened to a `directory` but sent nil if it listened to a `fileName` changes.
The PR initializes correctly the dynamic configuration from a `fileName` : if the user delete all his configuration in a file, Træfik will be able to delete the backends, frontends anf TLS configurations.

Send empty configuration from file provider

---

acme/acme.go

Simplification in storing renewed certificate in acme certificate renewal.
Not to mislead readers.
Account argument was passed but it was actually accessed through store and there was no need to pass it so dropped that argument.

Simplify storing renewed acme certificate

---

cmd/traefik/bug.go
cmd/traefik/bug_test.go

Remove the use of `interface{}` in the bug report command.
Fixes #2636

Fix bug report command

---

provider/consul/consul_catalog_test.go
provider/docker/docker.go
provider/docker/service_test.go

This PR fix:
- flaky test in consul
- Normalize serviceName added to the service backends names
Fixes: #2630

Normalize serviceName added to the service backend names

---

docs/configuration/backends/marathon.md
docs/user-guide/marathon.md

Improve documentation on Marathon service labels.
End-user support questions demonstrated that the distinction between application and service labels wasn't clear. Specifically, it wasn't obvious that services can be used to leverage Marathon applications exposing multiple ports.

Improve Marathon service label documentation.

---

glide.lock
vendor/github.com/vulcand/oxy/forward/fwd.go
vendor/github.com/vulcand/oxy/utils/netutils.go

Fix a bug in websocket
related to: https://github.com/containous/oxy/pull/48
Fixes #2629
Fix a bug with packet loss in websocket underlying connection. Instead of use this connection, we read messages with gorilla and write messages with gorilla

Use gorilla readMessage and writeMessage instead of just an io.Copy

---

middlewares/retry.go
middlewares/retry_test.go

Fix an issue in retry middleware
If we flush during the response and not at the end, the last part of the Body could be lost.
Fixes #2637

We need to flush the end of the body when retry is streamed

---

docs/user-guide/kubernetes.md

Leave a note about assumed DaemonSet usage in the Kubernetes guide.
Make sure users are aware of the DaemonSet/Deployment distinction (and the implications as to the reachable port) as they follow the guide.
Fixes #2633.

k8s guide: Leave note about assumed DaemonSet usage.

---

healthcheck/healthcheck.go
healthcheck/healthcheck_test.go
server/server.go

It's useful to understand why health checks failed in the case they do. Therefore I improved the logging output of the health checks, so that you can see whether it was e.g. an http/net issue or a wrong response code.
I also use now the backend name only in the logs. Before, for some logs something like `entryPointName+backendName` was used, but in most places we seem to log the backend name only.

Improve logging output for failing healthchecks

---

docs/configuration/backends/docker.md

Add a note to the docker backend documentation page on how to add a label using a docker-compose file.
I made the mistake too many time and I still forgot about it.
When reading the documentation, I can't find a notice/note about it.

Add a note on how to add label to a docker compose file

---

middlewares/error_pages.go
middlewares/retry.go
middlewares/retry_test.go

Fix a panic in the retry middleware if the responseWriter does not implement CloseNotify. Happen with compress=true (Gzip does not implement CloseNotify yet)
Fixes #2628 
I think this is better that the next handler choose what to do if we don't implement CloseNotify instead of Panic or implement a wrong version of CloseNotify.

Don't panic if ResponseWriter does not implement CloseNotify

---

cmd/traefik/anonymize/anonymize_config_test.go
cmd/traefik/configuration.go
configuration/configuration.go
provider/consulcatalog/consul_catalog.go
provider/consulcatalog/consul_catalog_config.go
provider/consulcatalog/consul_catalog_config_test.go
provider/consulcatalog/consul_catalog_test.go

Split consul and consul catalog.
Split consul and consul catalog.

Split consul and consul catalog.

---

glide.lock
vendor/github.com/NYTimes/gziphandler/gzip.go

GzipResponseWriter doesn't implement CloseNotifier.
We test if the underlying ResponseWriter implement it and if it does, we use it.
If it doesn't, we do not implement it in order to leave the management of the problem to the user.
To keep close notify in the middleware chain. Close notify is used by httputil.ReverseProxy

GzipResponse must implement CloseNotifier if ResponseWriter implement it

---

docs/user-guide/cluster-docker-consul.md
mkdocs.yml

Add a clustering example in the user-guide documentation
The first time I check what the cluster mode do, I can't find the information.
I think it's a really cool feature and adding more information about it, it is important. 
It's base on my blog post: https://jmaitrehenry.ca/2017/12/15/using-traefik-with-docker-swarm-and-consul-as-your-load-balancer/ but I change the format and rewrite a good part of it for the documentation.
In the beginning, I would like to improve the Clustering/HA user-guide, but, as this example use Docker Swarm and Consul with a specific docker-compose file for Docker Swarm, I think it's better to have a page just for it.
Fixes #1200, #736

Add a clustering example with Docker Swarm

---

integration/fixtures/timeout/forwarding_timeouts.toml

Timeout integration test
Make the CI build.

Fix: timeout integration test

---

autogen/gentemplates/gen.go
provider/kv/kv.go
templates/kv.tmpl

Support list entries in KV.
ex:
```
foo/0: bar
foo/1: bir
foo/2: bur
```
Fixes #2667
Fully compatible with the previous behavior.

fix: list entries parsing.

---

autogen/gentemplates/gen.go
provider/label/label.go
provider/marathon/builder_test.go
provider/marathon/config.go
provider/marathon/config_test.go
templates/marathon.tmpl

homogenization of templates: Marathon

---

acme/acme.go
acme/challengeProvider.go

This PR improve the ACME DEBUG messages.
Fix #2664

Modify DEBUG messages to get ACME certificates

---

autogen/gentemplates/gen.go
provider/consulcatalog/consul_catalog_config.go
templates/consul_catalog.tmpl

homogenization of templates: Consul Catalog

---

Gopkg.lock
vendor/github.com/vulcand/oxy/forward/fwd.go
vendor/github.com/vulcand/oxy/forward/headers.go

- add compression if client send the compression header and backend valid compression
- handle close message correctly and log only real error
Related to https://github.com/containous/oxy/pull/50

Add compression and better error handling

---

Gopkg.lock
Gopkg.toml
docs/configuration/backends/web.md
docs/configuration/entrypoints.md
vendor/github.com/abbot/go-http-auth/digest.go

This PR fix concurrent map writes in dependency [go-http-auth](https://github.com/abbot/go-http-auth)
Fixes #2615 
There is already an open issue on [go-http-auth #52](https://github.com/abbot/go-http-auth/issues/52) but for now we use a fork [https://github.com/containous/go-http-auth](https://github.com/containous/go-http-auth).
The concurrent map writes is fixed with this PR https://github.com/containous/go-http-auth/pull/1

Fix concurrent map writes on digest auth

---

api/handler.go
healthcheck/healthcheck.go

This fixes a race between dumping the config and setting up the stats.

Fix data races.

---

provider/docker/docker.go

Logs Errors from the Docker `client.Events` channel and prevents hangs when the event stream will no longer be pushed into.
Backends getting out of sync during intermittent connection issues to the Docker daemon, and not being able to force them to refresh.
All errors in the Docker `client.Events` method cause events to stop being processed, leaving the messages channel open (https://github.com/moby/moby/blob/master/client/events.go#L20-L71). Since events are used as a notification mechanism it's save to reconnect if we lose one or more events.
This area of the codebase is untested. You can test/verify behaviours with a PoC I wrote here: 
``` golang
package main
import (
"context"
"fmt"
"github.com/docker/docker/api/types"
"github.com/docker/docker/api/types/filters" …
```

Return errors from Docker client.Events

---

cmd/traefik/traefik.go

Matches link to docs in log message to actual URL.

Fix typo in anonymous usage log message.

---

integration/acme_test.go
integration/fixtures/acme/acme_http01_web.toml
server/server.go

Ignore web.path when used with ACME HTTP-01 Challenge
Fix a bug in ACME HTTP-01 Challenge

Challenge HTTP must ignore deprecated web.path option

---

cmd/traefik/configuration.go
docs/configuration/tracing.md
middlewares/tracing/jaeger/jaeger.go

This PR fix a missing configuration for Jaeger. 
Add property `LocalAgentHostPort` to allow user to configure host and port where Jaeger reporter will send span
The configuration will be like that now :
```toml
[tracing]
backend = "jaeger"
servicename = "powpow"
[tracing.jaeger]
SamplingType = "const"
LocalAgentHostPort = "jaeger:6832"
SamplingServerURL = "http://jaeger:5778/sampling"
SamplingParam = 1.0
```

Fix missing configuration for jaeger reporter

---

cmd/traefik/configuration.go
integration/basic_test.go

Set a default value for web.metrics.prometheus.entrypoint when it's used in deprecated version
Fix a breaking change

Fix breaking change in web metrics

---

Gopkg.lock
vendor/github.com/vulcand/oxy/forward/fwd.go

Disable websocket compression
WebSocket compression with gorilla failed if server do not manage server_no_context_takeover and client_no_context_takeover.
That's why for now we will disable compression
fixes: #2714
related to: containous/oxy#51

Disable websocket compression

---

docs/user-guide/kv-config.md

The anchor tags seem to have I's in them, this should make them work properly.
Fix links.

Fix some doc links

---

provider/rancher/api.go

Doesn't reload Traefik configuration when Rancher sever is down
We using Traefik in production, it critical for us if Rancher server is down and traefik does not proxying  requests

Don't reload configuration when rancher server is down

---

healthcheck/healthcheck.go

This mutex was introduced in https://github.com/containous/traefik/pull/2287 but it actually has no effect. Executing the health check tests with `go test -race ./...` does not yield any difference. In both cases, it does not report any race.

remove unecessary mutex usage in healthchecks

---

acme/acme.go

It's a temporary fix for ACME with corporate proxies.
Related to #2735, #1110

ACME and corporate proxy.

---

server/server.go

Fix a goroutine leak in the throttling logic.
The variable managing throttling goroutines was only scoped to the local method, effectively disabling goroutine cleanup and producing a leak. We properly hook up the goroutines to live as long as the server does.
This PR partially supersedes #2728.

Fix goroutine leak in throttler logic.

---

autogen/gentemplates/gen.go
docs/configuration/backends/file.md
docs/user-guide/kv-config.md
examples/consul-config.sh
examples/etcd-config.sh
integration/consul_test.go
integration/etcd3_test.go
integration/etcd_test.go
integration/fixtures/acme/certificates.toml
integration/fixtures/https/dynamic_https.toml
integration/https_test.go
provider/file/file.go
provider/file/file_test.go
server/server.go
server/server_test.go
templates/kv.tmpl
tls/tls.go
types/types.go

Rename `TLSConfigurations` to `TLS`.
More readable configuration.

Rename TLSConfigurations to TLS.

---

integration/access_log_test.go
integration/fixtures/access_log_config.toml
integration/resources/compose/access_log.yml
middlewares/accesslog/logger.go
middlewares/accesslog/logger_test.go
middlewares/auth/authenticator.go

This PR fixes issue #2060: logging of authenticated username in accesslog. Works for both Basic and Digest authentication.

Add username in accesslog

---

integration/integration_test.go
integration/resources/compose/tracing.yml
integration/tracing_test.go

This PR fix flaky integration tests in tracing.
Flaky was due to bug in the latest [Zipkin version 2.4.4](https://github.com/openzipkin/zipkin/releases/tag/2.4.4)

Fix integration tests in tracing

---

cmd/traefik/traefik.go
configuration/configuration.go
server/server.go

Delete undefined entrypoints from `frontent.entrypoints`
Move Fatal if `ACME.Entrypoint` does not exists (from `createTLSConfig` to `ValidateConfiguration`)
Handle some weird errors (like panic in `postLoadConfiguration`)

Handle undefined entrypoint on ACME config and frontend config

---

middlewares/tracing/entrypoint.go
middlewares/tracing/forwarder.go
middlewares/tracing/status_code.go
middlewares/tracing/tracing.go

statucCodeTracker does not implement CloseNotify
Avoid noise in logs:
```console
time="2018-01-19T16:11:56Z" level=warning msg="Upstream ResponseWriter of type *tracing.statusCodeTracker does not implement http.CloseNotifier. Returning dummy channel."
```

Tracing statusCodeTracker need to implement CloseNotify

---

webui/package.json
webui/src/app/sections/health/health.controller.js
webui/yarn.lock

So you don't have to lookup status code numbers
I keept googling them
Not sure how to add test for this?

Add status code text to webui bar chart tooltip

---

Gopkg.lock
vendor/github.com/NYTimes/gziphandler/gzip.go

Change receiver for  `GzipResponseWriter` in order to implement `CloseNotifier`
Fixes #2760 
Related to https://github.com/NYTimes/gziphandler/pull/63

Change gzipwriter receiver to implement CloseNotifier

---

healthcheck/healthcheck.go
healthcheck/healthcheck_test.go
metrics/datadog.go
metrics/datadog_test.go
metrics/influxdb.go
metrics/influxdb_test.go
metrics/metrics.go
metrics/metrics_test.go
metrics/prometheus.go
metrics/prometheus_test.go
metrics/statsd.go
metrics/statsd_test.go
middlewares/metrics.go
middlewares/metrics_test.go
server/server.go
server/server_test.go
testhelpers/metrics.go

I know that this PR is large but it grew a long time in our fork now and the changes depend on each other which makes it very hard to split those up into several commits.
I am happy to assist in any way it helps you to make a review, also a e.g. a peer-review via video chat is completely fine for me.
Just let me know how I can help getting this merged.
To make it a bit better I added an extensive commit description that I quoted below to explain the different measures.
To wet the appetite why this is useful here a short list of which metrics Traefik supports now for Prometheus and it is very easy for other providers to move along!
To get the other providers on the same feature level (not required to work right now, see commit description) I shoutout to @aantono and @adityacs who …

extend metrics and rebuild prometheus exporting logic

---

integration/fixtures/retry/simple.toml
integration/integration_test.go
integration/resources/compose/retry.yml
integration/retry_test.go
middlewares/error_pages.go
middlewares/error_pages_test.go
middlewares/retry.go
middlewares/retry_test.go

This PR reduces the amount of RAM Traefik needs to transfer the response body to the client when the retry middleware is enabled. This is accomplished by rebuilding the response recorder for the retry middleware. The principle now is quite simple, the new response recorder does not have a temporary buffer anymore, but directly delegates the calls to the original response writer in case the response should not be retried. This means that the only "overhead" we have left is the 32KB buffer the standard library uses in it's `Write` calls on the http connection.
As the former response recorder was used also at the error handler, I moved it there. I think the error handler is not that critical when it comes to response sizes, e.g. no files will be transferred through it I guess, but there is …

Fix high memory usage in retry middleware

---

tls/certificate.go

This PR fixes a mistake in the dynamic TLS mechanism which introduce duplicated values to check during TLS certificat research and bad domain names.
Improve mechanism by deleting unnecessaries and bad values.

Fix domain names in dynamic TLS configuration

---

docs/configuration/entrypoints.md

Remove an option (`redirect.permanent`) not available in 1.5.
Have a good documentation

doc: option not available in 1.5.

---

autogen/gentemplates/gen.go
docs/configuration/backends/kubernetes.md
provider/kubernetes/annotations.go
provider/kubernetes/builder_configuration_test.go
provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go
templates/kubernetes.tmpl

- add all available annotations
- add passTLSCert annotations.
- add error pages annotations.
- add max conn annotations.
- add rate limit annotations.
- enhance template readability
Homogenization of the providers [part2]: all providers must have the same options available.
Several PRs will come after that for each provider.
Related to #618,  #1465
Closes #2783

 Add all available annotations to k8s Backend

---

cmd/traefik/anonymize/anonymize_config_test.go
cmd/traefik/configuration.go
docs/configuration/backends/kubernetes.md
provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Allow configuring the values of the `kubernetes.io/ingress.class` annotation
on ingress objects that traefik will process. This is useful when you have
multiple traefik servers in one kubernetes cluster, and you want tight control
over which Ingresses are processed by which servers.
Fixes #2221

Allow custom value for kubernetes.io/ingress.class annotation

---

cmd/traefik/traefik.go

Hide the pflag error when displaying help.
Better help display.

Hide the pflag error when displaying help.

---

integration/access_log_test.go
integration/log_rotation_test.go

Display file log when test fails.
Clean some test methods.
Have more information when tests fails.

Display file log when test fails.

---

examples/k8s/traefik-ds.yaml

--web is deprecated, this was updated in the document, but not here.
traffic *--web* command line parameter is deprecated. 
The documentation is fixed with --api but not the example file itself.
Good will ;)
nil

Update traefik-ds.yaml with --api command line parameter

---

provider/docker/docker.go
provider/docker/swarm_test.go

Fix an issue where Træfik stop exposing containers with `endpoint_mode: dnsrr` when label `traefik.backend.loadbalancer.swarm=false`
Fixes #2793

Fix dnsrr endpoint mode excluded when not using swarm LB

---

acme/acme.go
docs/configuration/acme.md
integration/acme_test.go
integration/fixtures/acme/wrong_acme.toml

Fix traefik crash when Let's Encrypt is down
Be able to start traefik even if LE is down.
Fixes #791
The already generated certificates are still used.
If Traefik starts with LE down, you will need to restart Traefik in order to reconnect to LE and onHostRule certificates will generate error logs
In order to have this fix in 1.5.2 we don't change ACME too deeply, more deeply changes may come in 1.6.

Traefik still start when Let's encrypt is down

---

Gopkg.lock
vendor/github.com/vulcand/oxy/forward/fwd.go

Refs containous/oxy#52
I'm not exactly sure why all the reformatting happened in the lock file. Tried with both dep 0.3.2 and the latest 0.4.1, but it didn't seem to have made a difference.

Reduce oxy round trip logs to debug.

---

docs/basics.md

Clarify how setting a frontend priority works.
See #1962 for discussion, and https://github.com/containous/traefik/blob/c0563f1a395d53edbbf1030b2387435077eeb871/server/server.go#L1338-L1347 for the now documented code.
I set the priority on a rule, and it wasn't effective the way I understood it from the documentation. This gave us trouble in routing in our test environment.
Reading #1962, I realized from the code snippet that setting the priority works more like an offset than an absolute ordering of frontends.
Purely a documentation change.
I would be _amazing_ to have a way to get the previously documented behavior, i.e. comparing priorities first, only using rule lengths to break ties.

Clarify how setting a frontend priority works

---

docs/configuration/entrypoints.md

Documentation - hints for regex replacement
Related to #2796
Not sure if you would want the extra link to the Go Playground for testing regex/replacements

Docs: regex+replacement hints for URL rewriting

---

Gopkg.lock
vendor/github.com/vulcand/oxy/forward/fwd.go

This PR fix a goroutine leak in websocket
No leak
Related to: https://github.com/containous/oxy/pull/53

Fix goroutine leaks in websocket

---

docs/configuration/entrypoints.md
docs/user-guide/cluster-docker-consul.md

This PR add an explanation on how to write entrypoint definition with CLI in a compose file.
Træfik CLI binary:
```shell
--entryPoints='Name:http Address::80'
--entryPoints='Name:https Address::443 TLS'
```
Træfik CLI compose file
```yaml
traefik:
image: traefik
command:
- --defaultentrypoints=powpow
- "--entryPoints=Name:powpow Address::42 Compress:true"
```
Better documentation :book:

Explain how to write entrypoints definition in a compose file

---

provider/eureka/eureka.go

Eureka: Continue refresh the configuration after a failure. 
Fixes  #2831

Continue refresh the configuration after a failure.

---

Gopkg.lock
server/server.go
vendor/github.com/vulcand/oxy/buffer/buffer.go
vendor/github.com/vulcand/oxy/cbreaker/cbreaker.go
vendor/github.com/vulcand/oxy/cbreaker/effect.go
vendor/github.com/vulcand/oxy/cbreaker/ratio.go
vendor/github.com/vulcand/oxy/connlimit/connlimit.go
vendor/github.com/vulcand/oxy/forward/fwd.go
vendor/github.com/vulcand/oxy/ratelimit/tokenlimiter.go
vendor/github.com/vulcand/oxy/roundrobin/rebalancer.go
vendor/github.com/vulcand/oxy/roundrobin/rr.go

- Buffer: conditional setter
- Logs level and Forwarder Logger
- Fix goroutine leaks
Related to https://github.com/vulcand/oxy/pull/118, https://github.com/vulcand/oxy/pull/117, https://github.com/vulcand/oxy/pull/116

Logger and Leaks

---

provider/docker/builder_test.go
provider/docker/config_container_swarm_test.go
provider/docker/docker.go
provider/docker/swarm_test.go

This PR fix support of macvlan driver in docker swarm mode.
Today it is impossible to support macvlan driver in swarm mode because we are not able to retrieve IP addresses of containers running on other host in the cluster
Fixes #2412

Fix support for macvlan driver in docker provider

---

docs/user-guide/marathon.md
provider/marathon/config.go
provider/marathon/config_test.go

Remove health check filter from Marathon tasks.
When available, Traefik uses the last Marathon health check result to decide whether a task should be filtered or not. This behavior is incorrect, however, as it ignores the failure threshold denoting the
number of failed health checks it would take for Marathon to actually consider a task as failing and trigger a restart. With Traefik not taking the threshold into account, a task is removed from the
configuration already while Marathon may still deem it healthy. 
Delaying the filtering until the moment when the failure threshold is exceeded would not buy us much: At that point, Marathon will decide to restart the unhealthy task anyway and cause a task state change that will lead to a Traefik configuration update excluding the task in …

Remove health check filter from Marathon tasks.

---

middlewares/metrics.go

Removes unnecessary conversion, since returned value has required type.
Simpler code.

Remove unnecessary conversion

---

Gopkg.lock
vendor/github.com/vulcand/oxy/buffer/buffer.go

Correct conditional setting of buffering retry expression.
Have a non counter intuitive behavior.
Thanks to @harnash (#2859) for the catch 👏 
Related to https://github.com/vulcand/oxy/pull/119

Correct conditional setting of buffering retry expression.

---

docs/configuration/acme.md
docs/configuration/api.md
docs/configuration/backends/web.md
docs/configuration/entrypoints.md
docs/configuration/ping.md
docs/user-guide/examples.md

Update documentation
- on ACME onHostRule option
- on example about ping
- on web deprecated backend (related to: #2837)
Better documentation

Update documentation on onHostRule, ping examples, and web deprecation

---

integration/basic_test.go
integration/fixtures/multiple_provider.toml
integration/resources/compose/base.yml
server/server.go

Isolate each backend on different provider
If you had two backends with same name on different provider, only one backend was used. This PR fix this bug by isolate the backends on each provider.

Isolate backend with same name on different provider

---

docs/configuration/backends/kubernetes.md
provider/kubernetes/annotations.go
provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Rediret only root path elsewhere by ingress annotation. Like Nginx Ingress Controller [documented](https://github.com/kubernetes/ingress-nginx/blob/27c863085e2503e5f3249b596f24529fc2488baa/docs/examples/rewrite/README.md#deployment). Implementing this annotation will only perform `ReplacePath` on `/` path on all hosts present in the annotated ingress.
`ingress.kubernetes.io/app-root` or `traefik.ingress.kubernetes.io/app-root`
We catch this use case in production deployment.
Seems like many new annotation support will be added to Kubernetes provider on 1.5 release, I hope this annotation can also be supported.

Add app-root annotation support for kubernetes ingress

---

metrics/datadog.go
metrics/datadog_test.go
metrics/statsd.go
metrics/statsd_test.go

This is to add the missing metrics to the registry for DataDog and StatsD, following #2567

Added missing metrics to registry for DataDog and StatsD

---

integration/constraint_test.go
integration/consul_catalog_test.go
integration/docker_test.go
integration/ratelimit_test.go
integration/resources/compose/constraints.yml
integration/resources/compose/consul_catalog.yml
integration/resources/compose/error_pages.yml
integration/resources/compose/file.yml
integration/resources/compose/ratelimit.yml

This PR remove all nginx docker images in integration tests.
Avoid manifest issue when we pull images

Replace nginx by whoami in integration tests

---

docs/user-guide/kubernetes.md

Fixes a typo, changed Traefik ->Træfik, and capitalized Kubernetes in the Kubernetes user guide.
Was reading the document and found a few things.
N/A

Docs: Fix typos in k8s user-guide

---

provider/consulcatalog/consul_catalog.go
provider/consulcatalog/consul_catalog_test.go

Check for endpoint ip address while detecting Consul catalog changes
I'm experimenting with Docker Swarm, Registrator and Consul to implement service discovery in my project, and turned out, that scaling or updating an image for  a service does not trigger Traefik to refresh back-ends.  
After some investigation I figured out, that it's looking only on diff of unique node ids (that's why scaling a service on the same node never trigger update) and does not check for endpoint ip changes at all.
Nothing else to mention.

Check for endpoints while detecting Consul service changes

---

tls/certificate.go

This PR allows starting Træfik even if one of the TLS certificate is in error.
A `fatal` message was created when certificates were missing and Træfik was stopped, now it's just an `error` message.
Fixes #2897 
The error messages will be improved in V1.6.

Starting Træfik even if TLS certificates are in error

---

integration/error_pages_test.go
integration/fixtures/error_pages/error.toml
integration/fixtures/error_pages/simple.toml

This PR change Træfik port in error page integration test
Be able to run integration test with Goland without to be sudo

Change port of traefik for error pages integration test

---

autogen/gentemplates/gen.go
templates/kubernetes.tmpl

Fixes a bug related to k8 annotations and template generation.
The hardcoded `frontend` prefix forces the generation of new frontends instead of adding the rate limiting or errors into the existing frontend.
I am trying to run the latest version from master in GKE, and rate limiting was not working.
Was there any specific reason for adding the `frontend` prefix @ldez ?

Remove hardcoded frontend prefix in Kubernetes template

---

Gopkg.lock
Gopkg.toml
docs/configuration/backends/consulcatalog.md
provider/consulcatalog/consul_catalog.go
vendor/github.com/hashicorp/consul/api/acl.go
vendor/github.com/hashicorp/consul/api/agent.go
vendor/github.com/hashicorp/consul/api/api.go
vendor/github.com/hashicorp/consul/api/catalog.go
vendor/github.com/hashicorp/consul/api/coordinate.go
vendor/github.com/hashicorp/consul/api/health.go
vendor/github.com/hashicorp/consul/api/kv.go
vendor/github.com/hashicorp/consul/api/lock.go
vendor/github.com/hashicorp/consul/api/operator_area.go
vendor/github.com/hashicorp/consul/api/operator_autopilot.go
vendor/github.com/hashicorp/consul/api/operator_keyring.go
vendor/github.com/hashicorp/consul/api/operator_raft.go
vendor/github.com/hashicorp/consul/api/operator_segment.go
vendor/github.com/hashicorp/consul/api/semaphore.go
vendor/github.com/hashicorp/consul/api/session.go
vendor/github.com/hashicorp/go-rootcerts/LICENSE
vendor/github.com/hashicorp/go-rootcerts/doc.go
vendor/github.com/hashicorp/go-rootcerts/rootcerts.go
vendor/github.com/hashicorp/go-rootcerts/rootcerts_base.go
vendor/github.com/hashicorp/go-rootcerts/rootcerts_darwin.go
vendor/github.com/mitchellh/go-homedir/LICENSE
vendor/github.com/mitchellh/go-homedir/homedir.go

This PR allow TLS connection to Consul catalog
FIxes #951

TLS Support for ConsulCatalog

---

docs/configuration/backends/kubernetes.md
provider/kubernetes/kubernetes.go

Missing annotation prefix support: `ingress.kubernetes.io/app-root`
Have consistent behavior.
Related to #2522

Missing annotation prefix support.

---

server/server.go
server/server_test.go

Prevent the creation of a redirection on the same entry point.
Fixes #2925
With those labels:
```ini
traefik.frontend.entryPoints=http,https
traefik.frontend.redirect.entryPoint=https
```
The current behavior;
```
http://foo:80 -> https://foo:433 -> https://foo -> https://foo:443 -> https://foo -> ...
```
Due to:
```shell
Creating frontend frontend-PathPrefix-foo-0  
Wiring frontend frontend-PathPrefix-foo-0 to entryPoint http 
Creating route route-frontend-PathPrefix-foo-0 PathPrefix:/foo 
Creating entry point redirect http -> https   # <-----------------------------------
Frontend frontend-PathPrefix-foo-0 redirect created 
Creating backend backend-whoami1             
Creating load-balancer wrr                   
Creating server server-upbeat_goldberg at http://172.17.0.2:80 with …
```

Infinite entry point redirection.

---

docs/basics.md

Add a CLI help command for Docker.
Closes #2918

Add a CLI help command for Docker.

---

rules/rules.go
rules/rules_test.go
server/server.go
server/server_test.go
types/types.go

Træfik rules are managed in the `server` package.
This PR creates a `rules` package.
Low coupling, High cohesion :stuck_out_tongue_winking_eye:

Externalize Træfik rules in a dedicated package

---

cmd/traefik/configuration.go

Fix the life cycle default value
Fix a bug with no default value on `Lifecycle` and his child (`GracefulTimeout`)
`Lifecycle` is a pointer and the default value in the `NewTraefikPointerConfiguration` is not enough.

Default value for lifecycle

---

docs/configuration/acme.md

Fix the documentation for the defaultEntryPoints configuration. It erroneously uses "http" twice where it should use "http" and "https".
Fix a typo in the configuration documentation.
None

Second defaultEntryPoint should be https, not http.

---

Gopkg.lock
Gopkg.toml
server/server.go
server/server_test.go
vendor/github.com/unrolled/secure/csp.go
vendor/github.com/unrolled/secure/secure.go

This PR upgrade `unrolled/secure` dependency to be able to use `ModifyResponse` function to override backend headers
Fixes #2618

Use responseModifier to override secure headers

---

acme/acme.go
anonymize/anonymize_config_test.go
cmd/traefik/traefik.go
integration/https_test.go
provider/acme/provider.go
server/server.go
tls/certificate.go
tls/tls.go
types/types.go

This PR fixes ACME certificates generation in ACME provider.
So far, only C/N of provided certificates was checked before to generate ACME certificate in ACME provider.
This PR adds a check on the SANs and generates ACME certificates only for domains which need it in ACME provider.
Report #2913 modifications in the new ACME provider.
* This PR allows deleting the overkill type `tls.DomainsCertificate` by using directly `maps`.
* This PR allows renaming the `traefik.tls` alias.

Check all the C/N and SANs of provided certificates before generating ACME certificates in ACME provider

---

anonymize/anonymize_config_test.go
cmd/configuration.go
configuration/configuration.go
docs/configuration/backends/eureka.md
provider/eureka/eureka.go

add a new option `RefreshSecond`, it replace `Delay`.
Have the same option's name between provider.

Replace Delay by RefreshSecond in Eureka

---

.travis.yml
requirements.txt

This PR 
- Force mkdocs to use `tornado` version `<5`
- Change [structor](https://github.com/containous/structor) :ant: command to be able to use new parameter that override `requirements.txt`
Fix errors when the documentation is building.
<details>
```console
make docs 
docker build -t traefik-docs -f docs.Dockerfile .
Sending build context to Docker daemon  139.4MB
Step 1/5 : FROM alpine
---> 3fd9065eaf02
Step 2/5 : ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin
---> Using cache
---> a8ec7bbe4f5d
Step 3/5 : COPY requirements.txt /mkdocs/
---> Using cache
---> 7fedefbd2f74
Step 4/5 : WORKDIR /mkdocs
---> Using cache
---> 5b8b5d465777
Step 5/5 : RUN apk --update upgrade && apk --no-cache --no-progress add py-pip && rm -rf /var/cache/apk/* && pip …
```

Unable to generate documentation

---

Gopkg.lock
vendor/github.com/containous/flaeg/parse/parse.go

`MarshalJSON` use `int` value of `time.Duration`
`UnmarshalJSON` handle `int` value and `string` (go duration format)
Fix a bug when Marshalling / Unmarshalling JSON

Handle quoted strings in UnmarshalJSON

---

autogen/gentemplates/gen.go
docs/user-guide/kv-config.md
templates/kv.tmpl

`passHostHeader` is the only key in camel-case.
`storeconfig` command store keys in lower-case.
Add support for `passhostheader`, fallback on `passHostHeader` is needed.
Fixes #2103
Tests will be added on the master branch.

Add lower-case passHostHeader key support.

---

server/server.go
server/server_test.go

The new goroutine in `throttleProviderConfigReload` use the same stop channel as the current goroutine.
(it can be a problem because it doesn't block the goroutine cleanup)
It's better to use a new goroutines in the pool.

Use goroutine pool in throttleProvider

---

provider/rancher/rancher.go

Here is the small change I did to fix the issue. I tested locally and it works.
Fixes #2279
It is my first go changes so I am sure this could be better.

Fix Rancher Healthcheck when upgrading a service

---

docs/configuration/backends/kubernetes.md

Adds a note about how to enable TLS communication in k8s to backend pods.
Resolves #3008

Add TLS Docs

---

docs/user-guide/kubernetes.md
examples/k8s/traefik-deployment.yaml
examples/k8s/traefik-ds.yaml

Lower the log level for the Kubernetes manifests from DEBUG to INFO.
Less logging noise.
We previously enabled DEBUG log level implicitly by means of the `-d` parameter. Apart from being fairly intransparent to the regular user that debug mode hard-wires the DEBUG log level, it also produces an overwhelming amount of logs.
INFO seems much more sensible while still allowing to observe that Traefik has started, even in the absence of warnings and errors.
Finally, we also align the parameter usage across all examples we offer.

Set INFO log level in Kubernetes guide and examples.

---

docs/index.md

Adds Service Fabric to the list of supported backends in docs.
I'm not 100% on which branch this PR should be made against, considered v1.5 as it's relevant for that release but have gone for master to play it safe. Let me know if you want me to update. 
Service Fabric is supported from v1.5 and has docs but isn't liked in the `index.md` of the docs.

Add SF to supported backends in docs

---

provider/consul/consul_catalog.go

Fix goroutine leaks in consulcatalog provider. Use `sync.Once` to avoid blocking when sending errors to the channel which already used and an owner function of it is already exited.
Below is a number of goroutines by metrics data.
```
> date && curl -s http://localhost:10080/metrics | grep go_goroutines             
Fri Mar 16 19:32:28 JST 2018
go_goroutines 28
> sleep 120 && date && curl -s http://localhost:10080/metrics | grep go_goroutines
Fri Mar 16 19:34:29 JST 2018
go_goroutines 54
```
```
> date && curl -s http://localhost:10080/metrics | grep go_goroutines             
Fri Mar 16 18:49:38 JST 2018
go_goroutines 21
> sleep 120 && date && curl -s http://localhost:10080/metrics | grep go_goroutines
Fri Mar 16 18:51:39 JST 2018
go_goroutines 21
```
(traefik command is `./dist/traefik …

Fix goroutine leak in consulcatalog when consul is down

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bugs.md
cmd/bug/bug.go
cmd/configuration.go
cmd/traefik/traefik.go
configuration/configuration.go
docs/configuration/commons.md

Allow overriding the log level in debug mode.
Enabling the debug mode caused the log level to be hard-wired to DEBUG. We change the behavior so that an explicitly defined log level always overrides.
One primary motivation is to allow pprof-based benchmarking without excessive DEBUG logging distorting the results.
We also remove a piece of code from `SetEffectiveConfiguration` which was never effective because the log level would already be set previously.
Fixes #2968.

Allow overriding the log level in debug mode.

---

Gopkg.lock
Gopkg.toml

This PR fix an issue when we do a `make validate`
```console
(129/186) Failed to write github.com/docker/docker@7848b8beb9d38a98a78b75f78e05f8d2255f9dfe
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export gopkg.in/fsnotify.v1: fatal: failed to unpack tree object 629574ca2a5df945712d3079857300b5e4da0236
: exit status 128
make: *** [Makefile:77: validate] Error 1
```
`gopkg.in/fsnotify.v1` is no more available due to a organization renaming. Explanation available [here](https://github.com/go-fsnotify/fsnotify)
The project organization `go-fsnotify` was renamed to `fsnotify`
Building issue

Dependency fsnotify organization has been renamed

---

configuration/configuration.go
configuration/configuration_test.go
provider/file/file.go
provider/file/file_test.go
provider/provider.go

Provides ability to use templates in `file` provider
Be able to templetize static file configs to take advantage of things like `env` variables, loops, maps, etc.
Fixes  #2307

Added support for templates to file provider

---

docs/user-guide/kubernetes.md
examples/k8s/traefik-ds.yaml

Changes example of running DaemonSet on Kubernetes.
Makes Traefik run not in privileged mode but with only capability to bind to ports < 1024.
Reducing attack surface.
The motivation behind `privileged: true` was to have ability for Traefik to bind on privileged ports. Though there is a more fine-grained mechanism to restrict containers capabilities. This is unnecessary for the container to run in privileged mode.
Probably there was another rationale behind running in privileged. If there is it should be added explicitly to the capability list.

Drop capabilities in Kubernetes DaemonSet example

---

cluster/leadership.go
docs/configuration/api.md
server/server.go

This PR introduces a `/cluster/leader` endpoint, which will return `200-OK` or `429-Too-Many-Requests` status, depending on if the particular node is a leader or not.  The corresponding json payload will also be returned with `{"leader":"true"}` in case the node is a leader and `{"leader":"false"}` if it is not.
This will enable creating various Load Balancers on top of a Traefik cluster, which will only route API requests to the current leader, instead of randomly to any instance in the cluster.  The return of `429` status code will make most load balancers (like Netscalar or ELB, etc) to keep the instances in the pool, but "temporarily" not send any requests to them.

Added cluster/leader endpoint

---

docs/configuration/ping.md
integration/basic_test.go
integration/fixtures/reqacceptgrace.toml
ping/ping.go
server/server.go

Enhance /ping handler to return non-200 response upon requestAcceptGraceTimeout initiation, iff it is set.
Fixes #2969
this is same as abandoned https://github.com/containous/traefik/pull/3031, but rebased against master branch.

Toggle /ping to artificially return unhealthy response on SIGTERM during requestAcceptGraceTimeout interval

---

docs/configuration/logs.md
middlewares/accesslog/logger.go
middlewares/accesslog/logger_test.go
types/logs.go
types/types.go
types/types_test.go

This PR implements https://github.com/containous/traefik/issues/3020.

add access log filter for retry attempts

---

docs/basics.md
docs/configuration/entrypoints.md

Fix documentation.
`[entryPoints.https.tls]` appears twice

Fix basic documentation

---

acme/account.go
acme/acme.go
acme/acme_test.go
provider/acme/provider.go
server/server.go
types/domain_test.go
types/domains.go

- Allows matching of hosts like `x.traefik.wtf` to ACME wildcard
certs `*.traefik.wtf`
- Tested wildcard acme v2 and noticed that it was not properly selecting my wildcard domains

Add wildcard match to acme domains

---

README.md

I am not following existing PR template because it's just very little update for fixing broken urls on README.

Fixed documentation urls on README.md

---

server/server.go

As it was brought up in Slack, the `/cluster/leadership` URL is mostly being called from various load balancers and other sources that don't typically do authentication.  Having `/cluster` handler be under API endpoint, which otherwise might need to be guarded with authentication, prevents access to `/cluster/leadership` URL from load balancers.  Moving it under `Ping` endpoint, will solve this problem, and, as it seems from the intent of `/cluster/leadership` URL, it actually belongs under `Ping` to begin with, as it serves similar purpose.

Moved /api/cluster/leadership handler under public routes (requires no authentication)

---

docs/user-guide/docker-and-lets-encrypt.md

Update the docker-compose.yml example in this guide to the latest stable release of Traefik.
I was having issues using with Let's Encrypt due to #1832, 
https://community.letsencrypt.org/t/2018-01-11-update-regarding-acme-tls-sni-and-shared-hosting-infrastructure/50188.
Updating to a newer version of Traefik fixed the issue. This pull request should prevent others from having the same problem.

Update docker-and-lets-encrypt example to show traefik:1.5.4

---

middlewares/ip_whitelister.go
middlewares/ip_whitelister_test.go

Add tests on IPWhiteLister.
Be safe.

Add tests on IPWhiteLister.

---

configuration/entrypoints.go
configuration/entrypoints_test.go
docs/configuration/entrypoints.md

Support TLS MinVersion and CipherSuite as CLI option.
Fixes #3103

Support TLS MinVersion and CipherSuite as CLI option.

---

autogen/gentemplates/gen.go
provider/marathon/builder_test.go
provider/marathon/config.go
provider/marathon/config_test.go
provider/marathon/deprecated_config_test.go
templates/marathon.tmpl

Several apps with same backend name in Marathon.
Fixes #2709

Several apps with same backend name in Marathon.

---

provider/mesos/deprecated_config.go

Use `math.MaxInt32` instead of `math.MaxInt64` for `int` max value.
```
provider/mesos/deprecated_config.go:236:23: constant 9223372036854775807 overflows int
provider/mesos/deprecated_config.go:257:23: constant 9223372036854775807 overflows int
make[1]: *** [crossbinary-others] Error 2
```

fix: overflow on 32 bits arch.

---

provider/acme/provider.go

This PR specifies the TLS EntryPoint which will use the ACME certificates to add these certificates only on the specified `acme.entryPoint`.
Add ACME certificates to the right EntryPoint and only on its.

Add ACME certificates only on ACME EntryPoint

---

webui/src/app/core/providers.resource.js

Remove useless ACME tab from UI.
ACME tab doesn't have meaning.

Remove useless ACME tab from UI.

---

acme/acme.go
acme/localStore.go
integration/acme_test.go
integration/fixtures/acme/acme_http01.toml
integration/fixtures/acme/acme_http01_web.toml
integration/fixtures/acme/acme_provided.toml
integration/fixtures/acme/acme_provided_dynamic.toml
integration/fixtures/acme/no_challenge_acme.toml
integration/fixtures/acme/wrong_acme.toml
integration/fixtures/provideracme/acme.toml
integration/fixtures/provideracme/acme_insan.toml
integration/fixtures/provideracme/acme_onhost.toml
provider/acme/local_store.go
provider/acme/local_store_unix.go
provider/acme/local_store_windows.go
provider/acme/provider.go

This PR allows Træfik to automatically create a acme.json file if necessary.
Fixes #3135

Fix acme.json file automatic creation

---

contrib/scripts/dumpcerts.sh

Closes #3115.
There was an extraneous $1 on line 69 which threw an error.  The locations of keys and certificates in the JSON file have changed.
This pull request modifies `dumpcerts.sh` to run without errors and to access keys and certs in the JSON file correctly.
I now use Traefik to manage my LetsEncrypt certs for my mail server, so I needed to learn how to extract the certs and keys as files.
I'm very new to Traefik.  All I can say about this script is "it works for me".  If it does not work for the general case, I would love to get some feedback to make a proper solution that works for both me and everyone else.  Thank you in advance for your patience!

Minor updates to dumpcerts.sh

---

autogen/gentemplates/gen.go
middlewares/error_pages.go
middlewares/error_pages_test.go
middlewares/errorpages/error_pages.go
middlewares/errorpages/error_pages_test.go
provider/docker/config_container_docker_test.go
provider/docker/config_container_swarm_test.go
provider/docker/config_segment_test.go
provider/ecs/config_test.go
provider/marathon/config_test.go
provider/mesos/config_test.go
provider/provider_test.go
provider/rancher/config_test.go
server/server.go
templates/consul_catalog.tmpl
templates/docker.tmpl
templates/ecs.tmpl
templates/marathon.tmpl
templates/mesos.tmpl
templates/rancher.tmpl

- add prefix for backend name in error pages in to template
- Be able to use error pages with providers without use a custom template
Fix bug.
Fixes #3144

Fix: error pages

---

provider/kubernetes/client.go
provider/kubernetes/client_mock_test.go
provider/kubernetes/kubernetes.go

Limit the Kubernetes label selector to the Ingress factory.
Fix a regression when we switched to the newer shared informer factory.
@yue9944882 could you please take a look and let me know if this seems good to you?
I'm also open to any suggestions how we could possibly implement this more elegantly.
Thanks!
Refs #3128

Limit label selector to Ingress factory.

---

server/server.go

Fixes #3134 by moving the order of middleware invoking
Don't transfer basic auth credentials over an insecure connection if security headers are set.

fix: redirect to HTTPS first before basic auth if header redirect (secure) is set

---

cluster/leadership.go

Added information to display the current cluster leader node to the API

Improved cluster api to include the current leader node

---

provider/kubernetes/builder_endpoint_test.go
provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Support Kubernetes services with multiple defined ports.
- enable more compact port definitions
- be aligned with the existing Service routing behavior
- ~[ ] Added/updated documentation~ (not needed as we simply match what upstream Kubernetes already does on Service objects)
Fixes #3118.

Support multi-port services.

---

configuration/configuration.go
configuration/configuration_test.go
middlewares/tracing/jaeger/jaeger.go
middlewares/tracing/zipkin/zipkin.go

Fix nil value when tracing is enabled
```console
$ docker run traefik:1.6.0-rc5 --tracing --tracing.backend=zipkin --tracing.jaeger=false
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x87f6d7]goroutine 1 [running]:
github.com/containous/traefik/middlewares/tracing/zipkin.(*Config).Setup(0x0, 0x21b1c7b, 0x7, 0xb7413b, 0xc4208d2000, 0xc4208d4000, 0x0, 0x0, 0xc4205ef578)
/go/src/github.com/containous/traefik/middlewares/tracing/zipkin/zipkin.go:23 +0x37
github.com/containous/traefik/middlewares/tracing.(*Tracing).Setup(0xc4203d8910)
/go/src/github.com/containous/traefik/middlewares/tracing/tracing.go:54 +0x111
github.com/containous/traefik/server.NewServer(0xc4201d44f0, 0x0, 0x100, 0x0, 0x0, 0x0, 0x0, …
```

Fix nil value when tracing is enabled

---

integration/docker_compose_test.go
integration/docker_test.go
integration/integration_test.go
integration/resources/compose/minimal.yml
provider/docker/config.go
provider/docker/config_container_docker_test.go
provider/docker/deprecated_config.go

This PR update the docker provider to fix an issue with the docker compose scale.
Fix #3145

Fix multiple frontends with docker-compose --scale

---

acme/localStore.go
cmd/storeconfig/storeconfig.go
docs/configuration/acme.md
provider/acme/local_store.go
provider/acme/provider.go

Creating a backup file which contains the ACME V1 data during migration to ACME V2 file format.
Allow easier rollback to ACME V1.
Fix #3162 by checking ACME certificate content before set and get actions.

Create backup file during migration from ACME V1 to ACME V2

---

middlewares/metrics.go

This PR fix a panic in atomic package when metrics are enabled
Based on https://golang.org/pkg/sync/atomic/#pkg-note-BUG
Fixes #3193

Fix panic in atomic on ARM and x86-32 platforms

---

CHANGELOG.md

Prepare release v1.6.0-rc6

---

Gopkg.lock
Gopkg.toml
provider/label/label.go
vendor/github.com/containous/traefik-extra-service-fabric/servicefabric_tmpl.go

Add HTTP headers to healthcheck.
Homogenization of the providers.
Related to #3047

Add HTTP headers to healthcheck.

---

docs/configuration/backends/servicefabric.md

Fixes docs to use v1.6 labels rather than v1.5.
Reference issue: https://github.com/containous/traefik-extra-service-fabric/issues/31
Inaccurate.

Fix Service Fabric docs to use v1.6 labels

---

middlewares/auth/forward.go
middlewares/auth/forward_test.go

Forward auth: copy response headers when auth failed.
Fix a bug.

Forward auth: copy response headers when auth failed.

---

cmd/traefik/traefik.go
configuration/configuration_test.go
configuration/router/internal_router.go
configuration/router/internal_router_test.go
ping/ping.go
server/server.go
server/server_test.go
types/internal_router.go

Build internal router (api, ping, etc...) out of server.go.
Separation of concern.

Extract internal router creation from server

---

docs/configuration/backends/file.md
docs/configuration/backends/kubernetes.md

Adding documentation about templating in backend `file`.
A section about TLS certificates management into K8s secrets has been added too. :wink:

Add documentation about Templating in backend file

---

cmd/traefik/traefik.go
configuration/configuration.go
configuration/provider_aggregator.go
provider/acme/provider.go
provider/acme/provider_test.go
server/server.go
tls/certificate_store.go
types/certificate_store.go

Remove acme provider dependency in server.
Better separation of concern

Remove acme provider dependency in server

---

cmd/traefik/traefik.go
provider/acme/provider.go
provider/acme/provider_test.go
server/server.go

Change `CertificateStore` to `*CertificateStore` in `server` and `provider.ACME`.
No ACME challenge when a certificate already exists in dynamic certs.

Does not generate ACME certificate if domain is checked by dynamic certificate

---

docs/user-guide/kubernetes.md

Document custom k8s ingress class usage in guide.
Complement #2222.
Kudos to @beyond-code-github for catching. 👏

Document custom k8s ingress class usage in guide.

---

middlewares/tracing/forwarder.go

This PR fix a bad `http.url` tag in `forward` span in tracing middleware
Fixes #3273

Fix wrong tag in forward span in tracing middleware

---

README.md
docs/index.md

Changes `is could` to `should` in the documentation
It bothered me, I had to read the sentence twice because it was phrased weird.

Changed "is could" to should

---

docs/configuration/backends/kubernetes.md

This documentation update adds a link to inform users about the options available in kubernetes to preserve the sourceIP information, when attempting to use whitelisting features.
https://github.com/containous/traefik/issues/2566

Add Documentation update for Kubernetes Ingress

---

configuration/entrypoints_test.go
docs/configuration/entrypoints.md

Enhance entry point TLS CLI reference.
Fixes #3289

Enhance entry point TLS CLI reference.

---

docs/configuration/backends/docker.md
docs/configuration/backends/marathon.md
docs/configuration/backends/rancher.md
provider/docker/config.go
provider/docker/config_segment_test.go
provider/docker/deprecated_service.go
provider/docker/deprecated_service_test.go
provider/label/label.go
provider/label/names.go
provider/rancher/config.go

Fix segment backend name
Fix a bug.

Fix segment backend name

---

middlewares/accesslog/logger.go
middlewares/accesslog/save_backend.go
middlewares/errorpages/error_pages.go

Copy source request context to target request context.
Fix: error when accesslog and error pages.
Fixes #3301

Error when accesslog and error pages

---

Gopkg.lock
acme/acme.go
provider/acme/provider.go
vendor/github.com/xenolf/lego/acmev2/client.go
vendor/github.com/xenolf/lego/acmev2/error.go

Update Lego dependency.
fix: acme errors management.

fix: acme errors management.

---

autogen/gentemplates/gen.go
templates/kubernetes.tmpl

Adds the permanent redirect option to the kubernetes template.
Fixes #3316
Tests and documentation already correct, just missed template entry.

Add redirect-permanent to kubernetes template

---

acme/account.go
acme/acme.go
acme/localStore.go
configuration/configuration.go
docs/configuration/acme.md
examples/acme/manage_acme_docker_environment.sh
integration/acme_test.go
integration/fixtures/provideracme/acme_onhost_ecdsa.toml
integration/fixtures/provideracme/acme_onhost_invalid_algo.toml
provider/acme/account.go
provider/acme/provider.go

This PR allow user to choose which key type to use to generate private key 
Fixes #2940

Add option to select algorithm to generate ACME certificates

---

acme/acme.go
cmd/storeconfig/storeconfig.go
docs/configuration/acme.md

Adds `--acme.keepcerts` option to traefik. When this option is set to true, certificates already in key-value store will not be overwritten when using `storeconfig`.
Closes https://github.com/containous/traefik/issues/3003.

Enable to override certificates in key-value store when using storeconfig

---

provider/kubernetes/builder_service_test.go
provider/kubernetes/kubernetes.go

This fixes issue #1816 
Basically, if the `servicePort.Port` is not 443 or 80, we add it to the url (not the name).
And if the `servicePort.name` is "https" we also use "https" as the protocol. That allows to proxy https traffic to any port.
In my deployment, I need træfik to proxy to external servers on custom ports. I do not control these servers.

 Mapping ExternalNames to custom ports

---

docs/configuration/backends/kubernetes.md
provider/kubernetes/builder_service_test.go
provider/kubernetes/client.go
provider/kubernetes/client_mock_test.go
provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Allows Traefik to update the Status section of Ingress objects either via static IP/Hostname configuration, or via extracting the status section of a fronting service.
Fixes #2173
Users requested that the status field be set so that DNS and other discovery tools would work properly.
This configuration is entirely optional, and will only apply if one of the 3 configuration settings are enabled.

Enable Ingress Status updates

---

docs/user-guide/docker-and-lets-encrypt.md

Rename segment labels.
Removes ambiguity with the word 'default'

Removes ambiguity with the word 'default'

---

docs/configuration/backends/docker.md

Added footnote for parameter `traefik.frontend.auth.basic` which is describe how to use it for example of make secure dashboard of Traefik

Add command for basic auth with Docker Compose

---

docs/user-guide/kv-config.md

added basicAuth to the example

Add basicAuth example for KV

---

docs/user-guide/examples.md

Update caServer field in the examples to put the staging endpoint of letsencrypt instead of private IPs
As we are talking about letsencrypt since the beginning of the doc, I have the feeling that this will help avoid confusion.

Update caServer to letsencrypt one in examples

---

docs/basics.md
healthcheck/healthcheck.go
healthcheck/healthcheck_test.go

Support all 2xx HTTP status code for health check.
Fixes #3081

Support all 2xx HTTP status code for health check.

---

configuration/configuration.go
configuration/configuration_test.go
provider/file/file.go
provider/file/file_test.go
provider/provider.go

We didn't try to do templating when the file (in the file provider) is the Træfik file configuration.
Fixes #3268

No template parsing on traefik configuration file

---

configuration/configuration.go

Force to use ACME v02 endpoint: rewrite API URL if needed.
Have a simple configuration.
Related to #3355

Force to use ACME v02 endpoint.

---

cmd/configuration.go
docs/configuration/backends/marathon.md
provider/marathon/marathon.go

Set sane timeouts for requests to Marathon and make them configurable.
Before the timeouts were either overly excessive or not existent at all. For requests done by go-marathon there was no timeout, which means when there was temporarily a network problem which doesn't immediately show a failure (e.g. when the packets are dropped by a firewall) Traefik will never be able to create a connection to Marathon, as this one request will be running basically forever. I used the same timeouts as go-marathon does by default. We have to do this in Traefik as we pass in our own http.Client.

sane default and configurable Marathon request timeouts

---

docs/configuration/logs.md
middlewares/accesslog/logger.go
middlewares/accesslog/logger_test.go
types/logs.go

Add a async accesslogs.logTheRoundTrip for access logs.
On my current project, we use traefik and recently we activate access logs. When i checked the overhead this functionality, i realize that we lost a lot! So i tried to figure why and i found that we use sync io.Writer. So i did that PR https://github.com/containous/traefik/pull/3059 and after some tests i realized that i can do simpler and more effective with this PR(with or without fileFormat per example).
Small benchs:
Base configuration:
```toml
[entryPoints]
[entryPoints.http]
address = ":8080"
[accessLog]
filePath = 'test'
```
Without accesslogs from hey (without json format):
```console
$ hey -n 200000 http://127.0.0.1:8080/test
Summary:
Total:	6.4238 secs
Slowest:	0.0333 secs
Fastest:	0.0002 secs
Average:	0.0016 secs …
```

Make accesslogs.logTheRoundTrip async to get lost performance

---

api/dashboard.go
api/handler.go
cmd/traefik/traefik.go

This PR changes where we instantiate the assets for dashboard
More flexible code.

Generated assets file are only mandatory in main

---

docs/user-guide/kubernetes.md
examples/k8s/traefik-deployment.yaml
examples/k8s/traefik-ds.yaml

Updates the documentation for kubernetes, in particular the port examples, and adds some notes about best practices
Fixes #3348

Update Kubernetes Port Documentation

---

acme/account.go
acme/acme_test.go

Delete the empty ACME certificates from KV store as we do when certificates are stored in a file.
Allow regenerating in ACME malformed certificates.
Be homogeneouse between KV store and file storages.
Fixes #3372 
Related #3162, #3191

Remove ACME empty certificates from KV store

---

acme/account.go
acme/acme.go
acme/localStore.go
cmd/storeconfig/storeconfig.go
provider/acme/local_store.go
provider/acme/provider.go

This PR allows improving the ACME registration URI management by adding an automatic update when caServer is modified.
- Be homogeneouse between KV store and file : the ACME URI registration is now automatically updated during migration from ACME V1 to ACME V2.
- Update automatically the value if the `acme.caServer` option is updated.
Related to https://github.com/containous/traefik/issues/3372#issuecomment-391641704

Improve ACME account registration URI management

---

middlewares/errorpages/error_pages.go
middlewares/errorpages/error_pages_test.go

Don't copy backend response headers.
The problem occurs if the error page has streamed the content.
Fixes #3338
To reproduce:
- call to backend: return an error and a header `Content-Length`
- call to error page: return the page but without `Content-Length` (stream content)
- write the final response: merge header from backend and error page
- result the `Content-Length` is invalid.

Error pages and header merge

---

docs/user-guide/kubernetes.md

Added some basic information on how a user can extend the helm installation using a values.yaml.
Hope to extend more documentation on how to use helm installation.
I wrote a blog post on how it can be extended to work let's encrypt and DNS-01 challenge. 
[LINK](https://medium.com/@aulin/letsencrypt-tls-certificates-on-aks-azure-kubernetes-service-cluster-using-traefik-with-e9bcc7a9355a)
Would like to extend the official helm documentation at one point.

helm installation using values

---

Gopkg.lock
vendor/github.com/vulcand/oxy/buffer/buffer.go
vendor/github.com/vulcand/oxy/cbreaker/cbreaker.go
vendor/github.com/vulcand/oxy/cbreaker/fallback.go
vendor/github.com/vulcand/oxy/connlimit/connlimit.go
vendor/github.com/vulcand/oxy/forward/fwd.go
vendor/github.com/vulcand/oxy/roundrobin/rebalancer.go
vendor/github.com/vulcand/oxy/roundrobin/rr.go

This PR updates the dependency on vulcand/oxy that includes https://github.com/vulcand/oxy/pull/137
Fixes #3343

Includes the headers in the HTTP response of a websocket request

---

integration/consul_catalog_test.go
provider/consulcatalog/consul_catalog.go

Resolve issue that "Traefik does not refresh backend list on state change of consul catalog health checks" 
The list of backends were not being reflected in Traefik with changes in health checks of nodes.
Fixes #3380
Related to #3157

Reflect changes in catalog healthy nodes in healthCheck watch

---

provider/kubernetes/kubernetes.go

Adds brackets around IPv6 Backend Addresses in the Kubernetes Provider
Fixes #3428 
The brackets are recommended as per https://tools.ietf.org/html/rfc5952 for portability, and required in certain cases.

Update Kubernetes provider to support IPv6 Backends

---

docs/configuration/acme.md

- Corrects several stylistic inadequacies
- Orders topics lexicographically
- Merges the two provider tables into one
- Fixes some links
- Removes duplication in multiple occurrences
- Improves explanation of verification methods and problems
The obvious stylistic inadequacies in the ACME docs article.
Please have a glance over my updated descriptions of methods and problems and check if they are indeed correct.

Docs: ACME Overhaul

---

metrics/prometheus.go
metrics/prometheus_test.go
server/server.go
server/server_test.go
testhelpers/config.go
testhelpers/helpers.go
testhelpers/metrics.go

Improve Prometheus metrics removal.
Formerly metric removal was done by tracking configuration generations. This was an easy first solution but is actually not correct and for setups where Traefik does not receive a lot of configuration updates, old metrics can hang around for quite some time.
The new approach is to keep track of Traefik's current configuration and to remove metrics that "belong" to an outdated configuration, once they were scraped. This way we can be sure that we don't keep old metrics too long and we can ensure that metrics for short-lived configuration still appear when the /metrics is scraped, as we only remove them after the scrape happened.

Improve Prometheus metrics removal

---

provider/kubernetes/builder_configuration_test.go
testhelpers/config.go

Custom frontend name for test helper
Be able to set a custom frontend name.

Custom frontend name for test helper

---

server/server.go
server/server_test.go
testhelpers/config.go
types/types.go

This fixes the way backends are currently cached leading t some frontend configuration being ignored when re-using same backend (reported in #2323).
Not being able to reuse backends in different frontends is unexpected and the workaround results in defining additional, identical backends.
In a current project of mine I could potentially end up with 400 identical backends to work around this.
Fixes  #2323
Currently backends are cached under a key generated by `entryPointName+providerName+frontend.Backend`. The `frontend.Backend` doesn't respect the differences present in frontends.
I add `Hash()` method to the `Frontend` struct and use that instead of just the backend name.
The Hash method uses [github.com/mitchellh/hashstructure](https://github.com/mitchellh/hashstructure) which is also …

Fix backend reuse

---

Gopkg.lock
server/bufferpool.go
server/server.go
vendor/github.com/vulcand/oxy/forward/fwd.go

Add a buffer pool to handle the copy of body in oxy.
https://github.com/vulcand/oxy/pull/138
Better performance
Fixes #3422 
Some benchmark:
I use `emilevauge/whoami` binary, and traefik binary (without docker)
```
$ ./whoamI -port 8090
```
traefik.toml
```toml
maxIdleConnsPerHost = 100000
defaultEntryPoints = ["http"]
loglevel="ERROR"
[entryPoints]
[entryPoints.http]
address = ":8081"
[file]
[frontends.frontend-f]
backend = "b" 
[frontends.frontend-f.routes.test_1]
rule = "Host:localhost"
[backends]
[backends.b]
[backends.b.servers.website]
url = "http://127.0.0.1:8090"
```
```console
$ wrk -t20 -c1000 -d60s -H "Host: localhost" --latency  http://127.0.0.1:8081/bench
Running 1m test @ http://127.0.0.1:8081/bench
20 threads and 1000 connections
Thread Stats   Avg      Stdev     Max   +/- …
```

Handle buffer pool for oxy

---

middlewares/auth/forward.go
middlewares/auth/forward_test.go

Added requested Method to auth server for Forward Authentication.
Missing feature for authentication decision based on the request method. For example CORS responses can not be forwarded to API-endpoints without the ability to white list OPTIONS in the auth server.  This could also be solved by https://github.com/containous/traefik/issues/2162 but this ticket still holds merit.
Added implementation and test.
The PR is very close cousin of https://github.com/containous/traefik/pull/2398/
[There is no standard header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers) for forwarding the HTTP Verb so I went with `X-Forwarded-Method`

Add xforwarded method

---

provider/docker/config.go
provider/docker/config_container_docker_test.go

Fixes backend name with docker-compose and segments.
Fixes #3482

Backend name with docker-compose and segments.

---

provider/kubernetes/client.go

Fixes a panic when trying to compare a non-existent ingress status with the expected status
Fixes #3490

Fix panic setting ingress status

---

acme/acme.go
integration/fixtures/acme/acme_http01.toml
integration/fixtures/acme/acme_http01_web.toml
integration/fixtures/acme/acme_provided.toml
integration/fixtures/acme/acme_provided_dynamic.toml
integration/fixtures/acme/no_challenge_acme.toml
integration/fixtures/acme/wrong_acme.toml
integration/fixtures/provideracme/acme.toml
integration/fixtures/provideracme/acme_insan.toml
integration/fixtures/provideracme/acme_onhost.toml
provider/acme/provider.go

Use logrus writer instead of `os.Stderr`
To have better logs.

Use logrus writer instead of os.Stderr

---

provider/kubernetes/builder_endpoint_test.go
provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Add and fix existing k8s tests
More people using k8s, better tests to assist with refactoring

Add more k8s tests

---

docs/configuration/backends/kubernetes.md
docs/user-guide/kubernetes.md
provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Migrating from one ingress controller to another can require an intentional collision of ingressClass values.
The ingressClass in kubernetes can be used to run multiple ingress controllers or to otherwise split the defined ingresses into multiple sets.
The values that Traefik would allow for an ingress class must start with `traefik`.
This patch removes that limitation as
1. The name is user defined anyway
2. It makes migrations from other ingress controllers harder
I am trying to move a larger cluster over to traefik and our ingress classes were split into internal and external. Traefik can't handle these names which makes a migration harder than necessary.
The key change is the removal of a few lines in `provider/kubernetes/kubernetes.go`

Allow any kubernetes ingressClass value

---

cmd/configuration.go
docs/configuration/backends/consulcatalog.md
provider/consulcatalog/consul_catalog.go

Allow to read stale data from Consul, thus spreading the read load across Consul agents rather than fetching from leader.
https://www.consul.io/api/index.html#consistency-modes
For most of the use-cases, stale read is preferred, when you're willing to take the consistency trade-off and enjoy faster reads and distributed load. 
Fixes #2332 
Started using Traefik, and Consul catalog is the main provider.
As we're having multiple deployments of Traefik, and another systems that are actively fetching catalog
from the leaders, we see slowness of updates after some periods of time, especially when there's noise in Consul. Allowing to read stale data will reduce the load on the leaders, and serve better Traefik users.
Currently, I set the default as false, only for backward compatibility …

Add support for stale reads from Consul catalog

---

middlewares/tracing/jaeger/jaeger.go
middlewares/tracing/jaeger/logger.go

This PR creates a custom logger for jaeger to avoid to use `Printf`
https://github.com/containous/traefik/blob/30ffba78e6f55a00e55e8f90c819469731db9e8b/vendor/github.com/uber/jaeger-client-go/logger.go#L40-L51
Consistent log
Fixes #3539
Jaeger log will be display only when `logLevel=DEBUG`

Create a custom logger for jaeger

---

docs/user-guide/kubernetes.md

@dtomcej Docs still show corrections necessary against Master
https://github.com/containous/traefik/blob/master/examples/k8s/ui.yaml

Change code block of traefik-web-ui to match file

---

configuration/entrypoints.go
configuration/entrypoints_test.go
docs/configuration/entrypoints.md
middlewares/auth/forward.go
middlewares/auth/forward_test.go
types/types.go

Implement functionality for this feature request: https://github.com/containous/traefik/issues/3515
Based on this commit, and updated since the repos have diverged: https://github.com/drampelt/traefik/commit/b10cc88548d699f45460da77677db7a43f0c11e3?diff=unified
Fixes #3515

Forward auth headers

---

docs/configuration/backends/kubernetes.md
docs/user-guide/kubernetes.md

Explain service weights in the Kubernetes guide.
To ease adoption of the feature for users.
Complements #3112.
@dtomcej PTAL
/cc @yue9944882

Add a k8s guide section on traffic splitting via service weights.

---

provider/kubernetes/client.go
provider/kubernetes/client_test.go

Small refactor for kubernetes provider.
Remove those hardcoded `<namespace>/<name>` index and use common functions of `ListerGetter` provided by kubernetes informers.  Or developers might get confused by previous code. 🤔
Note that according to current implementations of kubernetes informers on master branch which haven't been changed for a long time, the error returned by `ListerGetter` can only be "Not Found" error. So, with this PR, the return value by `GetEndpoints`,`GetService`,`GetSecret` will only be:
- Endpoints/Service/Secret, true, nil
- nil, false, "Not Found Error"
For better human readability

Substitude hardcoded "<namespace>/<name>" with k8s ListerGetter

---

provider/consulcatalog/consul_catalog.go

There's a deadlock in Consul Catalog's watch method: the notifyError function writes to the same channel where the select loop is trying to read from.
Separating the watch channel from the stop/kill channels and implement it using a different goroutine 
so that read & write from the error channel won't block each other.
1. Launch traefik using a Consul Catalog against a Consul agent.
2. Restart Consul agent (causes Consul to return an error).
3. Change/deploy a new service to Consul and see that the backends/frontends don't get updated.

Split the error handling from Consul Catalog (deadlock)

---

server/errorhandler.go

Add logs in the error handler when there is an error
More information when trying to debug some errors (like 502 in #3237 for example)

Add logs when error is generated in error handler

---

api/debug.go

Call `runtime.SetBlockProfileRate` and `runtime.SetMutexProfileFraction` when debug mode is enabled.
According to the [documentation](https://golang.org/pkg/net/http/pprof/), these functions must be called for block and mutex pprof profiles to be generated actually.

Call functions to enable block/mutex pprof profiles.

---

CHANGELOG.md

Merge v1.6.5 into v1.7
Be sync.

Merge v1.6.5 into v1.7

---

docs/configuration/metrics.md
metrics/influxdb.go
types/types.go

Add some configuration options and corresponding structures to pass `username` and `password` to the `influxdb` metric backend. These options are **only** usable with HTTP and NOT with the UDP configuration.
Passwords are good for security I guess? Also I needed it for my work and it was easily implemented as the HTTP backend was ready since #3391.
Built and tested, apparently traefik doesn't report metrics when there is no request. Is that by design? Other influxdb colletors (such as `telegraf`) usually report one record per second for each metrics.

Add HTTP authentification to influxdb metric backend

---

docs/configuration/backends/kubernetes.md
provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Corrects App-Root kubernetes Behavior
Fixes #3589 
We will need to update documentation to reflect being unable to mix regex with app-root.
The ingress:
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: whoami
annotations:
traefik.ingress.kubernetes.io/app-root: /app1/index.html
spec:
rules:
- host: localhost
http:
paths:
- path: /
backend:
serviceName: whoami
servicePort: http
```
Now results in:
```console
$ curl -v localhost
* Rebuilt URL to: localhost/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Location: http://localhost/app1/index.html
< Date: Tue, 10 Jul 2018 19:31:55 GMT
< Content-Length: 5
< Content-Type: text/plain; …
```

Correct App-Root kubernetes behavior

---

provider/kv/kv_config.go
provider/kv/kv_config_test.go

change the way to check key path for auth in the KV.
Fixes #3612 
The correction of the web interface will come in another pull request

KV and authentication

---

CHANGELOG.md

Prepare release v1.7.0 rc2
Create a new release candidate.

Prepare release 1.7.0 rc2

---

provider/docker/config.go
provider/docker/config_container_docker_test.go
provider/docker/config_container_swarm_test.go
provider/docker/deprecated_config.go
provider/docker/deprecated_container_docker_test.go
provider/docker/deprecated_container_swarm_test.go

Context: docker provider with usebindportip
Currently:
- Traefik doesn't find the port bindings when the API responds in lowercase.
- When the API responds in uppercase, Traefik uses the external IP only, and not the port
- When no IP is specified, Traefik creates a route using the IP 0.0.0.0
- When the label `traefik.port`is specified, it is used both for selecting the binding _and_ in the route
This PR: 
- ignores the case when looking for port bindings
- takes the external IP _and_ port into account to create the routes
- excludes servers with no binding
- excludes servers with no IP specified in the binding (0.0.0.0)
- the label `traefik.port` is used to select the binding (which enables the use of segments)
To sum it up:
| label                  | Binding      | Routes to | …

Uses both binded HostIP and HostPort when useBindPortIP=true

---

Gopkg.lock
server/server.go
server/server_configuration.go
vendor/github.com/vulcand/oxy/forward/fwd.go

Handle the shutdown of Hijacked connections (like websocket connection for example)
Fixes #3630

Handle shutdown of Hijacked connections

---

integration/consul_test.go
integration/etcd3_test.go
integration/etcd_test.go
integration/fixtures/file/dir/simple2.toml
integration/try/condition.go
integration/try/try.go
types/types.go

This PR removes TLS in the API
Fixes #3651, #3669

Remove TLS in API

---

configuration/configuration.go

Fixed DataDog APM initialization error due to missing default configs.

Added default configuration for DataDog APM Tracer

---

MAINTAINER.md

This PR updates the `Contributions Daily Meeting` section and updates labels list.
Maintainers processes should be more detailed.
WDYT @containous/traefik?
Anything to add/change?

Complete maintainers processes

---

provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Removes an added slash in the Redirect-target annotation regex
Fixes #3698, slash was accidentally added in #3582
The ingress:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: whoami
annotations:
traefik.ingress.kubernetes.io/rewrite-target: /demo
spec:
rules:
- host: localhost
http:
paths:
- path: /testing
backend:
serviceName: whoami
servicePort: http
```
Now properly creates the following path rewrites:
```bash
$ curl -v localhost:31117/testing -silent 2>&1 | grep GET
> GET /testing HTTP/1.1
GET /demo HTTP/1.1
$ curl -v localhost:31117/testing/ -silent 2>&1 | grep GET
> GET /testing/ HTTP/1.1
GET /demo/ HTTP/1.1
$ curl -v localhost:31117/testing/bacon -silent 2>&1 | grep GET
> GET /testing/bacon HTTP/1.1
GET /demo/bacon HTTP/1.1
```

Fix Rewrite-target regex

---

Gopkg.lock
vendor/github.com/vulcand/oxy/forward/fwd.go

…message codes is not forwarding through traefik
Updating oxy dependency to latest version in order to fix issue  #3683 
Issue with websocket not forwarding Ping/Pong messages
The unit tests all pass but i cant make integration tests work since it fails before websocket portion
`FAIL: https_test.go:337: HTTPSSuite.TestWithClientCertificateAuthenticationMultipeCAs`

Updating oxy dependency 

---

integration/fixtures/https/https_redirect.toml
integration/https_test.go
middlewares/addPrefix.go
middlewares/redirect/redirect.go
middlewares/stripPrefix.go
middlewares/stripPrefixRegex.go

Rebuilds entrypoint redirects when used with `PathPrefixStrip` or `AddPrefix`
Fixes #1957
and issues linked to #2024

Correct Entrypoint Redirect with Stripped or Added Path

---

acme/acme.go
provider/acme/provider.go
provider/acme/provider_test.go

prevent traefik from deleting the acme.account without provider change
fixes issue #3650

Fix acme account deletion without provider change

---

provider/acme/provider.go
provider/acme/provider_test.go

This Pull Request introduces a mechanims which allow retrying to generate a ACME certificate when a `DNSChallenge` failed to obtain a certificate for both wildcard and root domain.
Since the feature which allows Træfik users to generate ACME certificates for both wildcard domain (as CN) and root domain (as SAN), a flaky behavior is noted.
Sometimes everything works well, sometines challenges cannot be solved with different errors (TXT record missing or incorrect).
These errors exist for almost all the DNS providers.
Fixes #3468, #3445.
A first analysis showed that **the problem is due to the name of the TXT records** needed by Let's Encrypt: a wildcard domain and its root domain are challenged thanks to a TXT record with the same name. In function of the TTL given to the TXT records, it …

Fix ACME certificate for wildcard and root domains

---

docs/configuration/backends/kubernetes.md
provider/kubernetes/annotations.go
provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Adds posibility to set a custom protocol for an ingress with the K8s provider
Fixes #3641
I'm official dumb and screwed the other pr :)

Add possibility to set a protocol

---

docs/user-guide/kubernetes.md

Documentation: fix missing traefik prefix in k8s authentification annotations.
—
Likely to have other occurences. I can update this PR to change all of them. 
However I need to be clear which annotations requires `traefik` in front of them beforehand.

Add traefik prefix to k8s annotations

---

h2c/h2c.go

The "copy-and-pasted" line had been deleted: this deleted line was overwriting the user-provided verbose mode's switch, forcing the verbose mode to true.
Fixes #3662 
Should be a quick one.

H2C: Remove buggy line in init to make verbose switch working

---

cmd/configuration.go
docs/configuration/tracing.md
middlewares/tracing/entrypoint.go
middlewares/tracing/entrypoint_test.go
middlewares/tracing/forwarder.go
middlewares/tracing/forwarder_test.go
middlewares/tracing/tracing.go
middlewares/tracing/tracing_test.go

In many situations the trace name gets pretty large (over 100 chars, especially when using k8s provider).  This provides an option to truncate the name to a configurable length to avoid dropped traces.

Added support for Trace name truncation for traces

---

webui/Dockerfile

Removes a useless `RUN` in the `webui` `Dockerfile`.
yarn is used instead of npm, this line is outdated :stuck_out_tongue_closed_eyes: 
Clean `Dockerfile`s

No need for npm progress=false

---

metrics/prometheus.go
metrics/prometheus_test.go

Move the `prometheusState.reset()` function to testfile. It's a method just for unit testing, so really, it should be in the test file(s).
Clean code

Move prometheusState.reset() to test file.

---

CHANGELOG.md

Prepare release v1.7.0-rc3
Create a new release candidate.

Prepare release 1.7.0-rc3

---

provider/consulcatalog/config.go
provider/docker/docker.go
provider/dynamodb/dynamodb.go
provider/ecs/ecs.go
provider/kubernetes/client.go
provider/marathon/config.go

- Remove some unused const/var/func/…
- Simplify some code
- Check some errors
- Use named field for struct def.
Clean, readable code.

Small code enhancements on providers

---

anonymize/anonymize_config_test.go
configuration/entrypoints.go
configuration/entrypoints_test.go
docs/configuration/entrypoints.md
middlewares/compress.go
server/server_middlewares.go

Migrate Compress from bool to struct. 
To be able to manage evolutions. For example  #2124

Migrate Compress from bool to struct

---

metrics/prometheus.go
metrics/prometheus_test.go
server/server.go

This PR replaces the function which registers Træfik to Prometheus (which can generate `panic`) by another one which never generates `panic`.
Do not generate `panic` and stop Træfik if it can not be registred to Prometheus (overkill?).

Avoid a panic during Prometheus registering

---

docs/user-guide/docker-and-lets-encrypt.md

Fixes a typo in `docker-and-lets-encrypt.md`

Typo in docker-and-lets-encrypt.md

---

requirements.txt

Fix mkdocs version
Due to the [v1.0 of mkdocs](https://github.com/mkdocs/mkdocs/releases/tag/1.0).
It's a temporary fix.

Freeze mkdocs version.

---

requirements.txt

Fix mkdocs version
Due to the [v1.0 of mkdocs](https://github.com/mkdocs/mkdocs/releases/tag/1.0).
It's a temporary fix.

 Freeze mkdocs version

---

acme/acme.go
provider/acme/provider.go
provider/acme/provider_test.go

This PR set a `KeyType` to an already existent `ACME.account` if necessary.
Relates #3468 ([comment](https://github.com/containous/traefik/issues/3468#issuecomment-410192111)).

Set a keyType to ACME if the account is stored with no KeyType

---

server/server.go

This makes traefik set KeepAlive on TCP connections it accepts, which fixes #3263 and possibly other issues related to socket leak, or file descriptor exhaustion.
Without this change, the configuration option 
```
--respondingtimeouts.idletimeout
```
has no effect, since it only works for keep-alive connections according to this document:
https://golang.org/src/net/http/server.go?s=93090:93158#L2443
This is a relatively trivial change that improves how traefik performs and increases its performance and stability.
I am not actually the author of this code, it is taken from the net.http.Server package, original source here: 
https://golang.org/src/net/http/server.go?s=93090:93158#L3207

Set keepalive on TCP socket so idleTimeout works

---

provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Adds a parsing test to the ingress annotation to prevent unparsable strings being added into the provider template.
Fixes #3731

Prevent unparsable strings from being rendered in the Kubernetes template

---

provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Ensures separate frontends are created when ingress priorities are set
Fixes #3710 
1. The issue reported in the ticket #3710 may not be _solved_ by this ticket, but it does resolve some of the unintended behavior
2. This change still allows duplicate host/paths to be skipped across namespaces.
3. Changing the basename to `{{namespace}}/{{ingress.name}}-{{host}}{{path}}` although unique, would be too breaking for a minor release.

Don't merge kubernetes ingresses when priority is set

---

docs/configuration/api.md
docs/index.md

This Pull Request introduces a few warnings and references in the documentation about the impact of enabling the API/Dashboard.
Related to #3665, #3651, #3669

Docs: Adding warnings and solution about the configuration exposure

---

docs/configuration/api.md

Rewording "secret" to "sensitive data" in the documentation's APi page
for a better semantic and meaning.
The previous word usage was scary and not conveying the right information.

A tiny rewording on the documentation API's page

---

docs/configuration/backends/docker.md
docs/user-guide/docker-and-lets-encrypt.md

This Pull Request introduce 2 changes:
- Improving the wording in the documentation for the Docker configuration page, 
about the `domain` directive
- Fixing the title of the documentation's user guide about Let's Encrypt & Docker
- While trying to reproduce some basic user configuration issue in the Slack support, 
I was stuck on a basic use case: "1 container behind 1 traefik". Being too quick, I directly read the Docker's Configuration page, where it was saying "docker.domain: set the domain to use". This simple rewording put an attention point for the newcomer, so they will search for the rule, and won't be stuck on this. Having checked this with @nmengin confirmed me it could be a good idea to reword (Hence the rewording I propose is not an absolute one :) )
- While proposing ths …

Improve the wording in the documentation for Docker and fix title for Docker User Guide

---

CHANGELOG.md
Gopkg.lock
acme/acme.go
acme/acme_test.go
docs/configuration/api.md
docs/index.md
docs/user-guide/docker-and-lets-encrypt.md
examples/acme/manage_acme_docker_environment.sh
mkdocs.yml
provider/acme/provider.go
provider/acme/provider_test.go
vendor/github.com/vulcand/oxy/forward/fwd.go
vendor/github.com/vulcand/oxy/utils/handler.go

Merge v1.6.6 into v1.7
Be sync.

Merge v1.6.6 into v1.7

---

cluster/datastore.go

The generic missing-key error message that comes from valkeyrie doesn't point the operator at the key that's missing. Several folk, including myself, have spent time figuring out what that missing key is. When setting up TLS there's a further potential confusion between KV store keys and TLS keys!
See https://github.com/containous/traefik/issues/2712 for an example issue that might have gone smoother with this more detailed logging.
I spent several hours debugging this, and that time could've been saved by knowing what the missing key was.
No tests / docs updated. I don't believe this warrants a test.
I began running the tests but had to go do something else before they finished!
Worth checking that the format string is safe with all possible return values.

Include missing key in error message for KV store

---

docs/configuration/backends/kubernetes.md

Updates documentation to reflect https backend configuration
Fixes #3806

Update kubernetes docs to reflect https options

---

cmd/storeconfig/storeconfig.go

The StoreConfig command will now always initialize the account (which key path is defined by acme.storage) if it is not yet initialized.
Related #3787 #3776 
Fixes #3754

 StoreConfig always initializes the account if it is missing

---

provider/acme/provider.go
rules/rules.go
rules/rules_test.go
server/server.go

This PR allows users to know if a `Host` rule is malformed by returning a `bool` to prevent that a `Host` Rule has been detected.
Thus if a `Host` rule is detected and no domain are returned, a specific error message can be created.
User reported that ACME has not created domains with the error message `Error getting valid domain: unable to generate a certificate when no domain is given.`.
The error has came from his `Host` rule but the message has not indicated it.
The PR improves the error management.

Allow Træfik to know if a Host rule is malformed

---

CHANGELOG.md

Prepare release v1.7.0-rc4
Create a new release candidate.

Prepare release v1.7.0-rc4

---

middlewares/tracing/carrier.go
middlewares/tracing/entrypoint.go
middlewares/tracing/tracing.go

This PR fix duplicated header in Tracing.
When an incoming request arrives with a tracing header, Træfik should used this header to create the new tracing headers and keep only the last one.
Closes #3854 
It is an issue in [opentracing/opentracing-go](https://github.com/opentracing/opentracing-go) ant it has been fixed by https://github.com/opentracing/opentracing-go/pull/191 but for now we are not able to upgrade this dependency

Fix tracing duplicated headers

---

autogen/gentemplates/gen.go
templates/kv.tmpl

This PR fixes the KV template with missing quotes around $backendName.
The generated templates are wrong and therefore backends containing dot in the name doesn't work well.
Here is an excerpt of the difference in a generated config (note the quotes for loadbalancer section whereas no quotes for healthCheck) :
```
[backends.\"backend.consul\".loadBalancer]
method = \"drr\"
sticky = false
[backends.backend.consul.healthCheck]
path = \"/\"
port = 0
interval = \"10s\"
```

Add missing quotes around backendName in kv template

---

server/server_configuration.go

Fix a bug on error pages.
Fixes #3643

Fix error pages

---

webui/src/app/app.component.spec.ts
webui/src/app/charts/bar-chart/bar-chart.component.spec.ts

The existing tests in the webui appear to be generated automatically when the project was created, but unfortunately they do not apply on the current project structure anymore, so they break. This PR removes tests which do not make sense anymore and fixes the ones which are still applicable.
Breaking tests can be very disturbing when adding own features and could also affect the impression. Also, they might lead to excluding angular tests from the CI jobs.
n/a

Removed non-applicable default tests and fixed custom tests

---

middlewares/auth/forward.go
middlewares/auth/forward_test.go

Hop-By-Hop headers aren't passed over to the auth backend anymore.
Copying over Hop-By-Hop header might result in a wrong behaviour, e.g. if a websocket is requested, the auth backend request fails and a HTTP 500 error code is returned. Therefore websocket don't work anymore when a forward auth backend is enabled.
Fixes #3039

Do not copy hop-by-hop headers to forward auth request

---

webui/src/app/app.module.ts
webui/src/app/components/providers/providers.component.html
webui/src/app/pipes/humanreadable.filter.pipe.spec.ts
webui/src/app/pipes/humanreadable.filter.pipe.ts
webui/src/app/services/api.service.ts

This PR adds a "Rate limiting" section to the frontend items on the traefik dashboard.
The primary aim is to visualize the presence (and absence) of rate limiting rules in the dashboard in order to provide a quick overview over the rate limit rules traefik gathered from the configuration sources.
I added (Angular) tests for the filter pipe, but the existing appear to need rework. I will issue a separate PR for that.

Added Dashboard table item for Rate Limits

---

provider/acme/provider.go

Verify that the `Host` in `onHostRule` is on the ACME EntryPoint.
Fixes #3918

Don't challenge ACME when host rule on another entry point

---

server/server.go

Remove certs from tls config only if we're not in cluster mode.
Fixes #3939

Don't remove static certs from config when cluster mode

---

configuration/configuration.go
integration/etcd_test.go
server/server_configuration.go

When DefaultCertificate is not defined, we use the first certificate from tls.Certificates.
Fixes #3935

Use the first static certificate as a fallback when no default is given

---

README.md

This PR adds a notice to warn users that a major overhaul is currently occurring on master branch.
Be transparent.

Add master overhaul notice

---

server/server.go

TLS, ACME, cluster and several entrypoints.
Fixes #3949

TLS, ACME, cluster and several entrypoints.

---

cmd/storeconfig/storeconfig.go

It looks like this commit might have introduced a bug
(I'm new to the code, so I might be wrong):
e4bb506#diff-89592b0a96bd24ccd41291548f9a07a3
On line 88, keyExists will return an error ErrKeyNotFound if the key does not exists,
because keyExists seems to not check if a key exists, but if a key is empty.

Correctly initialize kv store if storage key missing

---

docs/configuration/logs.md

Add documentation for the default accessLog format on the logs doc. 
I wanted to know what the access log format was so I could parse and label the fields correctly in my centralized logger. Ex:
```
111.111.133.18 - - [27/Sep/2018:18:25:09 +0000] "GET / HTTP/1.1" 200 1022 "-" "Scalyr-monitor; https://www.scalyr.com/help/monitors" 1234 "frontend" "http://192.168.10.10:8080" 2ms
```
I had to read the code to see what the different values were. https://github.com/containous/traefik/blob/5acd43efaf076ae2204285e750e41976c29069f2/middlewares/accesslog/logger_formatters.go#L34

Document the default accessLog format

---

anonymize/anonymize_config_test.go
api/handler.go
cmd/traefik/traefik.go

Fix a regression on the global configuration log at the start of Traefik
before this PR:
```
time="2018-09-29T10:58:34Z" level=debug msg="Global configuration loaded "
```
after this PR (same behavior as Træfik <v1.7):
```
time="2018-09-29T10:58:34Z" level=debug msg="Global configuration loaded {\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"GraceTimeOut\":0,\"Debug\":false,\"CheckNewVersion\":true,\"SendAnonymousUsage\":false,\"AccessLogsFile\":\"\",\"AccessLog\":null,\"TraefikLogsFile\":\"\",\"TraefikLog\":{\"format\":\"common\"},\"Tracing\":null,\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Address\":\":80\",\"TLS\":null,\"Redirect\":{\"entryPoint\":\"https\"},\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyP …
```

Global configuration log at start

---

server/server_middlewares.go

Whitelist log for deprecated configuration.
```
goroutine 26 [running]:
runtime/debug.Stack(0x772c4e, 0xc0000a8230, 0x2627259)
/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/containous/traefik/safe.defaultRecoverGoroutine(0x21c38e0, 0x449ac60)
/go/src/github.com/containous/traefik/safe/routine.go:148 +0x8c
github.com/containous/traefik/safe.GoWithRecover.func1.1(0x26d4850)
/go/src/github.com/containous/traefik/safe/routine.go:139 +0x5e
panic(0x21c38e0, 0x449ac60)
/usr/local/go/src/runtime/panic.go:513 +0x1c7
github.com/containous/traefik/server.(*Server).buildMiddlewares(0xc0004d0580, 0xc000b52e19, 0x1d, 0xc000483340, 0xc000b46390, 0xc000b34b10, 0x5, 0xc00020e720, 0x26029b0
, 0x4, ...) …
```

Whitelist log for deprecated configuration.

---

README.md

There are a couple if links on the main readme.md that lead to no longer existing sections. These are "Test It" and "Plumbing" links. This PR remove these now defunct links.
Talked this through with Ludovic on slack, and he suggested a PR.

fix broken links in readme.md

---

whitelist/ip.go
whitelist/ip_test.go

Trims whitespace from `X-Forwarded-For` header values.
In case there are multiple comma-separated values for the XFF header, there might be trailing whitespace after the comma e.g.
```
X-Forwarded-For: 1.2.3.4, 1.1.1.1, 8.8.8.8
``` 
If that's the case, then `net.parseIP` will return `nil` and the whitelist check will fail.
This situation was not caught by the test since the fixture:
```
{
desc:                "allow UseXForwardedFor, remoteAddr not in range, UseXForwardedFor in range (compact XFF)",
whiteList:           []string{"1.2.3.4/24"},
allowXForwardedFor:  true,
remoteAddr:          "10.2.3.1:123",
xForwardedForValues: []string{"1.2.3.1, 10.2.3.1"},
authorized:          true,
},
```
listed the matching IP as the first value in the comma separated value, hence not testing the …

Trimming whitespace in XFF for IP whitelisting

---

provider/kubernetes/annotations.go
provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Adds a safety check to avoid template-unsafe values getting applied to the template directly from the k8s API
Fixes issue #3953

Add Template-ability check to Kubernetes API Fields

---

rules/rules.go
rules/rules_test.go

Don't panic when parsing some invalid rules.
```
time="2018-10-03T20:06:12Z" level=error msg="Error in Go routine: runtime error: invalid memory address or nil pointer dereference"
goroutine 77 [running]:
runtime/debug.Stack(0x73e23f, 0xc4200bc2d0, 0x245bb01)
/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/containous/traefik/safe.defaultRecoverGoroutine(0x200c4e0, 0x3a3b0c0)
/go/src/github.com/containous/traefik/safe/routine.go:148 +0x73
github.com/containous/traefik/safe.GoWithRecover.func1.1(0x2501428)
/go/src/github.com/containous/traefik/safe/routine.go:139 +0x57
panic(0x200c4e0, 0x3a3b0c0)
/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/containous/traefik/vendor/github.com/containous/mux …
```

Rule parsing error.

---

docs/user-guide/kubernetes.md
provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

If multiple ingress objects define the same frontend (host + path) and one of the ingresses is broken (e.g. referenced service does not exist) then the frontend will be flapping (appear, disappear, ...).
We found this in production and I've extracted the problem into a testcase...
Given 2 ingresses:
```yml
- apiVersion: extensions/v1beta1
kind: Ingress
metadata:
namespace: testing
name: web-a
spec:
rules:
- host: host-a
http:
paths:
- backend:
serviceName: service1
servicePort: 80
- apiVersion: extensions/v1beta1
kind: Ingress
metadata:
namespace: testing
name: web-b
spec:
rules:
- host: host-a
http:
paths:
- backend:
serviceName: missing
servicePort: 80
```
The `missing` service will cause the whole `host-a` frontend to disappear if the ingress objects are processed in order …

Avoid flapping of multiple Ingress definitions

---

cmd/traefik/traefik.go
configuration/configuration.go
configuration/configuration_test.go
docs/user-guide/kubernetes.md
provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Merge v1.7 into master
Be sync.

Merge current v1.7 into master

---

docs/index.md

Fix a typo.
Making the best of the documentation (which is already excellent)!

Fix a typo

---

docs/user-guide/examples.md

Doc: Added two example / Using labels in docker-compose.yml
https://github.com/containous/traefik/issues/563#issuecomment-421479401
null
https://github.com/containous/traefik/issues/563#issuecomment-421479401

Added two example / Using labels in docker-compose.yml

---

Gopkg.lock
integration/fixtures/websocket/config.toml
integration/fixtures/websocket/config_https.toml
vendor/github.com/vulcand/oxy/buffer/buffer.go
vendor/github.com/vulcand/oxy/forward/fwd.go

Update oxy:
- Body should never be nil in buffer
- Pass host header for Websocket
Fixes #4005 #4006

Fix update oxy

---

Gopkg.lock
Gopkg.toml
script/prune-dep.sh
vendor/github.com/containous/flaeg/flaeg.go

This PR introduces the following changes:
* For end-users: It improves the clarity of the `traefik --help` command line (CLI) output
* For maintainers and contributors: Update of the dependency Flaeg to the version `1.3.0`
* For maintainers and contributors: It allows the commands `make dep-ensure` and `make dep-prune` to be run on macOS and BSD
The current state of the `traefik --help` is very confusing: if you are getting started, you don't know where to put commands: before, after flags?
When updating dependencies on my mac, I also was facing an error message when running `make dep-ensure`. it was a simple fix so it has been smoothly added into the scope of this PR.
Example of the new output:
```
$ ./traefik --help
traefik is …
```

Improve the CLI help (Update of the Flaeg dependency)

---

acme/acme.go
configuration/configuration.go
provider/acme/provider.go

Prevent some malformed errors.
Not being a dominant source of malformed errors in Let's Encrypt logs.
Fixes #4011

acme: prevent some malformed errors.

---

Gopkg.lock
docs/configuration/acme.md
vendor/github.com/xenolf/lego/providers/dns/bluecat/bluecat.go
vendor/github.com/xenolf/lego/providers/dns/cloudxns/cloudxns.go
vendor/github.com/xenolf/lego/providers/dns/dns_providers.go
vendor/github.com/xenolf/lego/providers/dns/dnspod/dnspod.go
vendor/github.com/xenolf/lego/providers/dns/glesys/glesys.go
vendor/github.com/xenolf/lego/providers/dns/sakuracloud/sakuracloud.go
vendor/github.com/xenolf/lego/providers/dns/stackpath/client.go
vendor/github.com/xenolf/lego/providers/dns/stackpath/stackpath.go
vendor/golang.org/x/oauth2/clientcredentials/clientcredentials.go

Fix DNS challenges:
- bluecat
- cloudxns
- dnspod
- glesys
- sakuracloud
Extra:
- Add DNS Provider for Stackpath
Fixes some bugs.

Fix: acme DNS providers

---

middlewares/recover.go

Since go 1.11, http/reverseproxy.go can generate some panic
https://github.com/golang/go/blob/c33153f7b416c03983324b3e8f869ce1116d84bc/src/net/http/httputil/reverseproxy.go#L274-L285
Its can be justify by his piece of code:
https://github.com/golang/go/blob/a0d6420d8be2ae7164797051ec74fa2a2df466a1/src/net/http/server.go#L1761-L1775
Avoid to have this error message
```console
Recovered from panic in http handler: net/http: abort Handler
```

Fix recover from panic handler

---

docs/configuration/backends/docker.md
provider/docker/config.go
provider/docker/config_container_docker_test.go

Changes the behaviour of the usebindportip so it can fallback on the container ip/port when the binding doesn't specify the IP.
**Changes Recap**
| label                  | Binding      | Routed to (before) | Routes to (after) |
|----------------|------------|-----------|-----------|
| `traefik.port` not set | `IP_E1:P_E1:P_I1` | `IP_E1:P_E1` | `IP_E1:P_E1`
| `traefik.port` not set | `P_E1:P_I1` | Warning & Ignored (cannot route to `0.0.0.0`) | ContainerIP:ContainerPort |
| `traefik.port` not set | None | Warning & Ignored (Binding is missing) |  ContainerIP:ContainerPort |
| `traefik.port=P_E1` | `IP_E1:P_E1:P_I1` | `IP_E1:P_E1` | `IP_E1:P_E1` |
| `traefik.port=P_E2` | `IP_E1:P_E1:P_I1` | Warning  & Ignored (cannot find binding for `XX:P_E2:XX`) | ContainerIP:P_E2 |
| `traefik.port=P_E2` …

usebindportip can fall back on the container ip / port

---

integration/fixtures/https/dynamic_https.toml
server/server_configuration.go
tls/certificate.go
tls/tls.go

Don't fail globally but log an error on a bad certificate and append the valid certificates.
Fixes #4010

Fix certificate insertion loop to keep valid certificate and ignore the bad one

---

docs/configuration/acme.md

Adds the note that acme.domains is a startup configuration only.
To make it more obvious for users (cf #4039)

Adds the note: acme.domains is a startup configuration

---

healthcheck/healthcheck.go
middlewares/auth/forward.go
middlewares/errorpages/error_pages.go
middlewares/retry.go

Nil request body with retry.
Fixes #4013
```
github.com/containous/traefik/middlewares.recoverFunc(0x7fc743112078, 0xc000efa090, 0xc00114ea00)
/go/src/github.com/containous/traefik/middlewares/recover.go:40 +0x1b7
panic(0x21d58a0, 0x4530f40)
/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/containous/traefik/middlewares.(*Retry).ServeHTTP(0xc000cbf860, 0x7fc743112168, 0xc000efa0c0, 0xc00114f500)
/go/src/github.com/containous/traefik/middlewares/retry.go:38 +0x5e8
github.com/containous/traefik/middlewares/tracing.(*HTTPHandlerWrapper).ServeHTTP(0xc000cbf890, 0x7fc743112168, 0xc000efa0c0, 0xc00114f500)
/go/src/github.com/containous/traefik/middlewares/tracing/wrapper.go:63 +0xd5
github.com/containous/traefik/middlewares/errorpages.(*Handler).ServeHTTP(0xc0003898f0, 0x7fc743112078, …
```

Nil request body with retry

---

Dockerfile

Fixes buffering by re-adding the missing `/tmp` directory.
Closes #4064

Add missing tmp directory to scratch image

---

provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Adds the option to have an Ingress without Host & Path and have it not broken :)
Fix #4076 

add default path if nothing present

---

Gopkg.lock
rules/rules.go
rules/rules_test.go
vendor/github.com/containous/mux/regexp.go

This PR introduces a failing test for issue #3930.
Here we also rename parameters and variables in the `hostRegexp()` function to better reflect what is actually handled. Indeed, this function is written as if it was manipulating plain hostnames, whereas it actually handles host patterns that might include regular expressions.
I wanted to demonstrate the issue #3930, and also address a misnaming that was pointed out while analyzing that issue.
Relates to #3930.

Case insensitive host rule 

---

docs/configuration/acme.md

Add a note about TLS-ALPN challenge.
To have a good documentation.

Add a note about TLS-ALPN challenge.

---

docs/benchmarks.md
docs/index.md
docs/user-guide/kv-config.md
docs/user-guide/swarm-mode.md
docs/user-guide/swarm.md

Since the project emilevauge/whoami moved to containous/whoami, the PR updates the documentation accordingly.
I haven't updated the integration tests

Replaces emilevauge/whoami by containous/whoami in the documentation

---

acme/acme.go
cmd/traefik/traefik.go
docs/configuration/acme.md
provider/acme/provider.go
types/dns_resolvers.go

- Support custom DNS resolvers for LE.
- allow to remove precheck
Fixes #3585
Related to #4088

Support custom DNS resolvers for Let's Encrypt.

---

integration/access_log_test.go
middlewares/accesslog/logger.go
middlewares/accesslog/logger_test.go
middlewares/accesslog/save_username.go
middlewares/auth/authenticator.go
server/server_loadbalancer.go
server/server_middlewares.go

This PR fixes #4012 by using the context to store the client username in the `http.Request` and by adding a `saveUsername` middleware, like the already existing `saveFrontend` and `saveBackend` implementations.
The feature of displaying the ClientUsername in the access log never actually worked, since the information was discarded when the request was going through the `HandlerSwitcher` middleware.
This PR also adds a unit test (thanks @AndrewSav for the unit test) to ensure that the behavior works as expected.
Fixes #4012
* Run traefik with basic or digest auth enabled, as well as the access log and the following option `--accessLog.fields.names="ClientUsername=keep"`
* Make authenticated requests, and check the access log, the `ClientUsername` variable should be set to the username like …

Fix display of client username field

---

autogen/gentemplates/gen.go
docs/configuration/backends/kubernetes.md
provider/kubernetes/annotations.go
provider/kubernetes/builder_configuration_test.go
provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go
templates/kubernetes.tmpl

Add the pass-client-tls-cert annotation to the kubernetes provider.
Fixes #4048 
Related to #3826

Add the missing pass-client-tls annotation to the kubernetes provider

---

types/logs.go
types/logs_test.go

This PR fixes #3841 and adds a unit test to cover the specific case that was causing it.
Basically, when using a YAML file to pass arguments, they are passed with escaped backquotes if  backquotes are present in the input YAML file.
For example:
```
args:
- --accessLog.fields.names="Username=drop Hostname=drop ClientUsername=drop ClientHost=drop"
```
Would be received by the flaeg parser as `"Username=drop Hostname=drop ClientUsername=drop ClientHost=drop"`. The parser then used to break it down into key value pairs and store it in a map. What happened was that for the last key (here `ClientHost` in this example, the value had a backquote at the end of it (`drop"` in this case), which didn't match with either `drop`, `keep` or `redact`. It was then replaced by the default value.
Removing …

Fix access log field parsing

---

server/server_configuration.go
server/server_configuration_test.go
server/server_middlewares.go
server/server_middlewares_test.go
server/server_test.go

This PR adds the option to have static entrypoint redirects without any frontend / backend
To fix #2109 :)
We dont have any tests covering that situation yet, if someone has a hint shoot at me :)

add static redirect

---

middlewares/secure.go
middlewares/secure_test.go

This PR fix an issue with secure middleware. `SSLForceHost` was not used in the secure middleware options. 
Fixes #4087

Fix ssl force host secure middleware

---

provider/docker/docker.go

Add a select when we want to send configuration message to be sure the ctx is not done
Fix a goroutine leak that can stuck the provider shutdown

Verify ctx when we send configuration message in docker provider

---

server/header_rewriter.go
server/header_rewriter_test.go

Remove X-Forwarded-Uri and X-Forwarded-Method headers if a request
comes from an untrusted IP.
Failing to do so would result in an inconsistent and insecure behaviour
for the forward authentication. If TrustForwardHeader is active in the
forward auth, the auth endpoint receives these two headers if they
have been sent from an untrusted IP. Whereas other X-Forward headers
have been removed in the request and are safe to use in the auth
endpoint.

Remove X-Forwarded-Uri and X-Forwarded-Method from untrusted IP

---

healthcheck/healthcheck.go
healthcheck/healthcheck_test.go

This PR allows user to set query param in health check
Fixes #4182

Query params in health check

---

docs/configuration/backends/docker.md

Add a note which clarifies Traefik's behaviour when the `traefik.backend.loadbalancer.swarm=true` label is set on a backend.
Traefik's behaviour in that case caused some misunderstanding (see #4179  and #2138).
Here's a proposal to improve the documentation.
WDYT folks ?

Clarify swarm loadbalancer documentation

---

docs/configuration/backends/docker.md

According to docker's doc, https://docs.docker.com/engine/swarm/swarm-tutorial/#the-ip-address-of-the-manager-machine, port 2375 is replaced by 2377 for cluster management communications
Use port 2375 simply does not work with the new swarm the doc needs an update
`endpoint = "tcp://127.0.0.1:2377"` is only usable when launching traefik directly on the host. In a dockerized environment, `endpoint = "unix:///var/run/docker.sock"` should be used with a mounted volume `/var/run/docker.sock:/var/run/docker.sock`

Update swarm mode endpoint

---

provider/label/partial.go
provider/label/partial_test.go

Now, when the partial/invalid auth label is defined (eg. `traefik.frontend.auth.foobar`) the auth is skipped.
Fixes #4211
```go
Stack: goroutine 36 [running]:
github.com/containous/traefik/middlewares.recoverFunc(0x7f0ebb409540, 0xc00000c978, 0xc000117200)
/go/src/github.com/containous/traefik/middlewares/recover.go:40 +0x1b7
panic(0x21e5ca0, 0x4551d40)
/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/containous/traefik/middlewares/auth.(*Authenticator).ServeHTTP(0xc0003ed820, 0x7f0ebb409540, 0xc00000c980, 0xc000117800, 0xc0003eddc0)
/go/src/github.com/containous/traefik/middlewares/auth/authenticator.go:161 +0x29
github.com/containous/traefik/vendor/github.com/urfave/negroni.middleware.ServeHTTP(0x2949220, 0xc0003ed820, 0xc0003edae0, 0x7f0ebb409540, 0xc00000c980, 0xc000117800) …
```

Fix partial declaration of authentication.

---

server/server.go

Fixes the fact that traefik used to stop listening for configuration from providers after having received a nil Configuration message.
Fixes #3974

Log configuration errors from providers and keeps listening

---

docs/configuration/backends/docker.md

It adds a section "Security Consideration" in the Docker backend's configuration section, in the documentation.
This new documentation section about Security relates to #4174 , to explains the risk and the ways to leverage or compensate.
It also provides a way to achieve Traefik container's scheduling on worker node with Swarm mode.
Nope

Add a "Security Consideration" section in the Docker's backend section of the documentation

---

cmd/configuration.go
docs/configuration/backends/docker.md
provider/docker/docker.go

This PR allow user to set a custom refresh interval for polling swarm mode socket for docker backend
The default value is 15
The new flag to set in config is `--docker.refreshSeconds`

[docker backend] - Add config flag to set refreshSeconds for swarmmode ticker

---

Gopkg.lock
Gopkg.toml
vendor/github.com/containous/flaeg/flaeg.go
vendor/github.com/containous/flaeg/parse/parse.go

This PR upgrades flaeg dependency to avoid error when deserializing durations with values >= to 2^32 on 32 bits architectures.
https://github.com/containous/flaeg/pull/52

Fix upgrade flaeg

---

provider/ecs/ecs.go

Filters ECS tasks by their LastStatus, only adding them to the list of tasks if they are RUNNING
Fixes https://github.com/containous/traefik/issues/4249

Filter ECS tasks by LastStatus before adding to list of service tasks

---

provider/consulcatalog/config_test.go
provider/consulcatalog/consul_catalog.go

This fixes a bug with the consul catalog label segmentation when using a custom prefix (other than `traefik`). I found this on our QA system when implementing a second traefik cluster for internal traffic. 
I never realised that Provider.label is actually being reset to the standard one: https://github.com/containous/traefik/blob/v1.7/provider/consulcatalog/convert_types.go#L22
- Added a test to reflect this use case

Fix label segmentation when using custom prefix

---

CONTRIBUTING.md
Makefile
docs/user-guide/swarm-mode.md
docs/user-guide/swarm.md
script/docs-verify-docker-image/validate.sh

This PR adds a check for hashes (HTML anchor) on the documentation links on external pages.
It also adds a kill switch for documentation to avoid breaking the build (see below).
We want our documentation to have valid link to external resources.
#4289  shows that we had a broken link, without the actual verify system able to detect it.
A few more dead links (because of changed anchors) where detected and fixed in the current PR.
- The option `--only_4xx` had been removed, because it excludes the option `--check_external_hashes` : 
* Please note this `--only_4xx` option was added here: https://github.com/containous/traefik/commit/37aa902cef1c46beb8b3af03dabf36ba8e5eb38c . it was to unblock a 301 redirect breaking the whole build.
=> Since we need a way to disable the verification (reason …

Check for anchors (hashes) for external links on the documentation

---

CONTRIBUTING.md

Update the contributing guidelines to note that the dep version should be < 0.5.0.
Running `dep ensure` with dep version 0.5.0 printed this error:
```
Solving failure: No versions of github.com/smueller18/goinwx met constraints
```

Update contributing docs: use dep version < 0.5.0

---

provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

This PR sorts and de-dups the set of TLS certs that come from Kubernetes Ingress objects. When not sorted consistently, Traefik believes the config has changed and unnecessarily reloads the server configuration.
Fixes #4187. Note that the issue is simply 2+ Ingress-referenced TLS certs which just happens to be common when using wildcards. Wildcards are not the actual issue.
Fixes #4245.
Fixing a bug. 😄 
Background: Kubernetes returns the list of Ingress objects in varied order. Traefik processes the frontends and backends according to named keys (a standard dict/hash), which avoids any ordering issue.
In contrast, Traefik looks up the TLS secrets and simply appends them to an array. Because the Ingresses vary in order, so does the array of TLS secrets. This only applies to TLS certs …

kubernetes: sort and uniq TLS secrets

---

provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Modifies logic to allow empty paths when used with the app-root annotation
Fixes #4322

Allow empty path with App-root annotation

---

docs/configuration/ping.md
middlewares/redirect/redirect.go
middlewares/redirect/redirect_test.go

For HTTP methods different than GET on redirection status codes should be:
* 307 temporary (https://tools.ietf.org/html/rfc7231#section-6.4.7)
* 308 permanent (https://tools.ietf.org/html/rfc7538)
in order to keep requested HTTP method.
#4040 #hacktoberfest #greywizard

Redirection status codes for methods different than GET

---

contrib/scripts/dumpcerts.sh

In `contrib/scripts/dumpcerts.sh`: Test and exit for `jq` error before domain loop
In an automated (inotify) environment, there are cases where this script gets executed before Traefik actually finishes all writes to `acme.json`. This can result in `jq` errors when it's called in the the `domain` loop. The script did not check the `jq` return code and subsequently exited with return code `0`.
Original jq error:
```
jq: error (at /traefik/acme.json:18): Cannot iterate over null (null)
```
Test and docs are not applicable in this case.
Nope

Test and exit for jq error before domain loop

---

contrib/systemd/traefik.service

Since Traefik is running as root on the system, it makes sense to
apply various lock down measures to keep the system as safe as possible.
Includes mounting most of the directories as read-only or even making them
inaccessible, restricting kernel modifications and limiting the number of
processes the unit may spawn.
Also add checks at service startup to ensure all required files are present.

Harden Traefik systemd service

---

middlewares/retry.go
middlewares/retry_test.go

Make the `retryResponseWriter` store headers written during the attempt only write them when the attempt is successful. 
Fixes #3975 
The retry middleware was loosing response headers written before the request was actually sent to the backend.
This behaviour is caused by [this](https://github.com/containous/traefik/blob/v1.7/middlewares/retry.go#L124) line. 
This is what was happening when sticking a request to a backend for instance (see [here](https://github.com/containous/traefik/blob/ae1569514e87c42f7d5652f8bf1b98cf9d67afa2/vendor/github.com/vulcand/oxy/roundrobin/rebalancer.go#L205)).
To fix that, we make the `retryResponseWriter` carry a header map which represent the
headers gathered for the attempt. Then we propagate this header map to the response if only we decide to respond to …

Retry middleware : store headers per attempts and propagate them when responding.

---

provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

Checks to see if a secret is defined in the `TLS` block of an ingress before attempting to load the secret. Logs a debug message if TLS section is skipped.
Fixes #4280.

Skip TLS section with no secret in Kubernetes ingress

---

docs/user-guide/grpc.md

The TOML config was invalid with a second `[entryPoints.http]`. Removed.
GRPC docs for Traefik contain an invalid config, with a repeated `[entryPoints.http]`.
Observed the issue, checked if already existing issue, couldn't find one, so created PR since its an easy fix to docs.
This is only a documentation change, from my limited knowledge of TOML. Feel free to ignore if its already correct.

Removed repeated entryPoints.http from grpc.md

---

cmd/traefik/traefik.go
config/static/entrypoints.go
config/static/entrypoints_test.go
config/static/static_config.go
middlewares/forwardedheaders/forwarded_header.go
middlewares/forwardedheaders/forwarded_header_test.go
server/server.go
server/server_configuration.go
server/server_entrypoint.go

Add the forwarded header configuration and add the forwarded headers middleware.
To reintegrate forwarded headers.

Add forwarded headers on entry point configuration

---

examples/k8s/traefik-rbac.yaml

This PR updates the manifest of the example ClusterRole for Træfik 1.7 and allows updating the status after successfully provisioning the Ingress. Fixes: #3377

Allow Træfik to update Ingress status

---

integration/timeout_test.go

Check that the timeout service used in integration tests is ready prior to usage.
We have observed flakiness in our local CI when the actual integration test executed already when the timeout service was still being bootstrapped. The PR unflaked things for us.

Assert that test timeout service is ready.

---

docs/basics.md

document minimum priority value
I had the case that i needed a rule to be matched after all other rules and it was not until i started reading the source code (https://github.com/containous/traefik/blob/master/server/router/rules.go#L20) that i realized a value of zero will not place the route to the end of the list.
It would have saved me some time, had the documentation already contained this line.

Route priorities: document minimum priority value

---

Gopkg.lock
Gopkg.toml
cmd/configuration.go
configuration/configuration.go
docs/configuration/tracing.md
middlewares/tracing/datadog/datadog.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/option.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/sampler.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/span.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/spancontext.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/textmap.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go
vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/transport.go

This is #4321 rebased to v1.7.
Add an option to enable [priority sampling](https://docs.datadoghq.com/tracing/advanced_usage/?tab=java#priority-sampling) to the Datadog tracer. This prevents trace sampling from removing segments of a distributed trace (i.e. ensures completeness).
The first commit updates the dd-trace-go dependency to version 1.7.0, because that is the version the functionality appeared in. The second commit exposes the functionality in the configuration.
This pull request fixes #4296.
When using Traefik as an ingress router, it is important to include it in distributed Datadog traces of incoming requests.
The Datadog tracer did not include tests. If tests are required for this change, I would appreciate some pointers. (I have been running this code for a week without …

Support Datadog tracer priority sampling

---

docs/user-guide/kubernetes.md

This PR:
- Capitalizes the first word of a sentence.
- Changes the spacing for three lines so the note annotation in mkdocs will format correctly.

Minor formatting fixes

---

provider/ecs/ecs.go

Stores existing task definitions to avoid rate limiting of the AWS describeTask API.  If there is an existing definition, use instead of making another API call.
Deployments taking hours instead of minutes. Due to using multiple instances of Traefik, each making frequent desribeTask API calls, and quickly hitting AWS's rate limit.

Cache exising task definitions to avoid rate limiting

---

cmd/configuration.go
integration/docker_compose_test.go
integration/docker_test.go
integration/error_pages_test.go
integration/fixtures/access_log_config.toml
integration/fixtures/docker/minimal.toml
integration/fixtures/docker/simple.toml
integration/fixtures/error_pages/error.toml
integration/fixtures/error_pages/simple.toml
integration/fixtures/simple_hostresolver.toml
integration/fixtures/traefik_log_config.toml
integration/integration_test.go
provider/base_provider.go
provider/configuration.go
provider/docker/config.go
provider/docker/config_test.go
provider/docker/docker.go
provider/docker/label.go
server/router/rules.go
server/router/rules_test.go

- Adds default rule system on Docker provider
- Removes `domain` from static configuration
- Removes `traefik.domain` from labels
Be simpler to define default rules.
Co-authored-by: Julien Salleyron <julien@containo.us>

Adds default rule system on Docker provider.

---

configuration/configuration.go

fix: docker swarm mode refresh second for KV.
```
time="2019-01-22T20:27:38Z" level=error msg="Error in Go routine: non-positive interval for NewTicker"
time="2019-01-22T20:27:38Z" level=error msg="Stack: goroutine 82 [running]:\nruntime/debug.Stack(0x26a5d88, 0x17, 0xc000c51e90)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/containous/traefik/safe.defaultRecoverGoroutine(0x21b9300, 0xc000c51e80)\n\t/go/src/github.com/containous/traefik/safe/routine.go:148 +0x89\ngithub.com/containous/traefik/safe.OperationWithRecover.func1.1(0xc0036c9e20)\n\t/go/src/github.com/containous/traefik/safe/routine.go:156 +0x56\npanic(0x21b9300, 0xc000c51e80)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ntime.NewTicker(0x0, 0x0)\n\t/usr/local/go/src/time/tick.go:23 …
```

Fixes docker swarm mode refresh second for KV.

---

server/server_loadbalancer.go

Apply the global InsecureSkipVerify Configuration to the passTLSCert transport.
Allow to apply insecure skip verify between Traefik and the backend

insecureSkipVerify for the passTLSCert transport

---

provider/rancher/api.go

This PR adds error handling for requests to rancher api
Before: only first http request was used to check if the server is alive
After: all http requests are checked, if any of them fails, traefik configuration is not updated.
Motivation: sometimes http requests can fail randomly, and this results in inconsistent traefik configuration

handle errors when working with rancher

---

webui/Dockerfile

- Update webui docker image to Node Carbon (a compatible version of Node and with LTS until dec/2019)
- Remove `yarn` JS package manager from image layers because it is now already installed in Node official image 
- Maintain webui up to date :tada: 
- [Release schedule of NodeJS](https://github.com/nodejs/Release)
- [Yarn install in Node official image](https://github.com/nodejs/docker-node/blob/86b9618674b01fc5549f83696a90d5bc21f38af0/8/stretch/Dockerfile#L47)

chore(webui): update docker node version

---

webui/.dockerignore

- add `.dockerignore` file
- ignore target builded files during docker image build
- ignore dependencies during docker image build
It is consider a bad practice to copy dependencies and target in a docker "build pattern" image.
This won't affect current build, but it will protect contributors to locally image building latency.

chore(webui): ignore target/dependencies in docker copy

---

integration/fixtures/grpc/config_retry.toml
integration/grpc_test.go
middlewares/retry.go

When the retry middleware has already sent the headers, use the original headers map to be able to send trailers.
Fix trailers and Grpc issues.
Fixes #4433

fix missing trailers with retry

---

docs/configuration/metrics.md

Updated default value if buckets for Prometheus metrics. It should be homogeneous so the last value had a missing decimal place.
I've got an error: `Array contains values of type 'Float' and 'Integer', but arrays must be homogeneous` after coping default value from the documentation.

Update default value in docs of buckets for Prometheus

---

webui/Dockerfile
webui/src/app/services/api.service.ts

- Fix lint issues with current lint configuration
- include lint in webui docker image
- lint is here to protect contributor to add dead code or to break some code styling rules. (we are not in a really typed world here 🤣 )
- [TSLint](https://palantir.github.io/tslint/)

chore(lint): include lint in build process

---

.travis.yml

This PR changes the behavior for getting [structor](https://github.com/containous/structor) for generating versioned documentation in Travis:
- Using [godownloader script](https://github.com/goreleaser/godownloader), added in latest release of structor
- Fix the structor version, instead of getting "latest" release all the time, to have a constant behavior. 
- Update structor version from `1.3.2` to `1.4.0`
- Better automation and release management
- Constant behavior of builds for future releases
- Get latest structor changes
👋

Update Structor to  v1.4.0

---

.travis.yml

Cherry pick v1.7 into master:
Skip:
Be sync.

Cherry pick v1.7 into master

---

provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

This PR resolves an issue where service ports and endpoint ports mismatch on global backends, despite both being correct, and correctly named. This was due to the matching logic used on multiport services, and services that are named/not named.
This PR also updates the test for named endpoint ports, since the original case in the tests could not have happened (non-named endpoint port with named service port).
Fixes #4465

Loop through service ports for global backend

---

.travis.yml

Fix build for version <=1.4 of the documentation, by switching to a working `docs.Dockerfile` from the branch `v1.7`.
One does not want 404/HTTP when checking old versions pages. 
Quick one.

Travis: switch fallback dockerfile for structor

---

docs/content/routing/routers/index.md

Address documentation fix as proposed in https://github.com/containous/traefik/pull/4587#pullrequestreview-214415594

Use rule HostSNI in documentation

---

pkg/config/static/static_config.go

This PR allow user to configure his traefik log with CLI.
Run command `traefik --log.loglevel=debug`
Actual result:
```console
....
2019/03/15 13:40:49 Error parsing command: unknown flag: --log.loglevel
```
Traefik should start with debug log level.

Allow user to configure traefik log

---

pkg/provider/kubernetes/ingress/kubernetes.go

Re add the update ingress status in the kubernetes provider.
To add the address of the ingress controller when we `kubectl describe` the ingress.

(re)Add update ingress status

---

.travis.yml
docs/content/contributing/maintainers.md
docs/mkdocs.yml

Adds a maintainer's page into the documentation.

Adds a maintainer's page into the documentation.

---

.gitignore
script/deploy.sh

Change deploy script.
Be able to update https://github.com/containous/traefik-library-image during the release.

Change deploy script.

---

pkg/provider/aggregator/aggregator.go

Fix a concurrent bug in provider aggregator
Fix a bug

Fix problem in aggregator provider

---

CHANGELOG.md

Prepare release v2.0.0-alpha2

---

README.md

This CL simply fixes a dead link toward the maintainers pages in the
README.md.
Just found it while reading the documentation :)

Fix dead maintainers link on the README.md

---

docs/content/providers/docker.md
integration/docker_test.go
pkg/config/dyn_config.go
pkg/provider/configuration.go
pkg/provider/docker/config.go
pkg/provider/docker/config_test.go

Handle labels for tcp routing in the docker provider
Be able to do tcp with the docker provider

Add support for tcp labels in docker provider

---

pkg/server/server_entrypoint_tcp.go

Fix a concurrent map write and read.
Fix a panic during Traefik shutdown.
<details><summary>Detail</summary>
<p>
```
fatal error: concurrent map iteration and map write
goroutine 94 [running]:
runtime.throw(0x1fd042e, 0x26)
/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc00017fde0 sp=0xc00017fdb0 pc=0x42dae2
runtime.mapiternext(0xc00017fee8)
/usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc00017fe68 sp=0xc00017fde0 pc=0x40f097
runtime.mapiterinit(0x1c1dfe0, 0xc0005e2c00, 0xc00017fee8)
/usr/local/go/src/runtime/map.go:850 +0x1c9 fp=0xc00017fe88 sp=0xc00017fe68 pc=0x40ea09
github.com/containous/traefik/pkg/server.(*connectionTracker).Close(0xc0005e1700)
/go/src/github.com/containous/traefik/pkg/server/server_entrypoint_tcp.go:315 +0x78 fp=0xc00017ff58 sp=0xc00017fe88 pc=0x19d69e8 …
```

Fix panic while server shutdown

---

README.md
pkg/provider/label/parser_test.go

Remove old links in readme
Fixes #4641

Remove old links in readme

---

pkg/provider/acme/provider.go
pkg/provider/kubernetes/crd/fixtures/with_tls_acme.yml
pkg/provider/kubernetes/crd/kubernetes_test.go
pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroute.go

When we did the kubernetes crd implementation, we forgot to test the
case for when one wants TLS, but handled with Let's Encrypt, i.e.
without having to provide a Kubernetes Secret. We assumed it would be
enough to provide (in YAML) a tls object with no field set, which would
get us a non-nil IngressRouteSpec.TLS, allowing us to use
IngressRouteSpec.TLS as the sentinel for whether TLS should be enabled.
However, as IngressRouteSpec.TLS is a pointer, a tls object with no
fields set will actually result in IngressRouteSpec.TLS being nil. This
means at least one of the fields of the YAML tls object must exist.
Therefore, we now use the secretName field value (for now, as it is
the only field anyway) as the sentinel for whether Let's Encrypt should
be used.
This PR documents the above …

Document the TLS with ACME case

---

docs/content/https-tls/acme.md

Updates documentation as discussed with @dduportal 
Makes it more clear that manual dnsChallenge provider requires image to be run with docker run -it and that it isn't going to work with just docker stack deploy
Save others from stumbling upon this
https://github.com/containous/traefik/issues/4626
- [v] Added/updated documentation

Clarify that manual dnsChallenge provider works only when run as docker run -it

---

middlewares/tracing/datadog/datadog.go

Provide ability to configure Trace Header name overrides to enable integration of DataDog tracer with other OpenTracing compliant systems like Zipkin, Jaeger, Haystack and others.

Added support for configuring trace headers for DataDog tracing

---

provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

This PR adds support for global backends pointing to an ExternalName services. This is accomplished by checking the service type when adding the global default backend. If the service type is an ExternalName service, the backend is mapped to the ExternalName service's url. This is basically a copy paste of what is done with normal backends. 
It would be useful in my environment (and others I'm sure) for the Kubernetes provider to support a global default backend that's points to an ExternalName service. This is already supported for regular backends so I imagine not supporting it here was an oversight.
None

Support external name service on global default backend

---

provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

If the annotation `ingress.kubernetes.io/frontend-entry-points` is specified, we add a prefix with the entrypoints in the frontend/backend id.
Fixes #4445 

Add entrypoints prefix in kubernetes frontend/backend id 

---

docs/content/providers/docker.md
docs/content/reference/providers/docker.md

It fixes two small issues found in the Traefik 2.0 documentation.
I just upgraded to Traefik 2.0 and was confused how to configure routing rules. I think this is because the provided label in the documentation is incorrect in one location.

Fix two minor nits in Traefik 2.0 docs

---

docs/configuration/commons.md

In TOML first is 100 req/10s and second is 5req/3s, so it will be better to keep it this way in the text also

Keep consistent order

---

docs/configuration/acme.md

This updates the documentaiton to remove mention of a non-existent limitation. There
is no longer an ACME limitation on generating wildcard certs with wildcard SANs, per https://community.letsencrypt.org/t/acme-v2-production-environment-wildcards/55578
Correct documentation
Nope.

Update Wildcard Domain documentation

---

docs/content/middlewares/addprefix.md
docs/content/middlewares/basicauth.md
docs/content/middlewares/buffering.md
docs/content/middlewares/chain.md
docs/content/middlewares/circuitbreaker.md
docs/content/middlewares/digestauth.md
docs/content/middlewares/errorpages.md
docs/content/middlewares/forwardauth.md
docs/content/middlewares/headers.md
docs/content/middlewares/ipwhitelist.md
docs/content/middlewares/maxconnection.md
docs/content/middlewares/passtlsclientcert.md
docs/content/middlewares/ratelimit.md
docs/content/middlewares/redirectregex.md
docs/content/middlewares/redirectscheme.md
docs/content/middlewares/replacepath.md

Adds middlewares examples for k8s.

---

pkg/server/router/router.go

This PR fixes the middleware names passed as argument to the response modifier middleware Builder. The Builder Build method is expecting qualified names (prefixed with the provider type), so that it can check their existence in the configs map. Before this change, the Build method was receiving non-prefixed names, so the middleware names were never found in the configs map.
While investigating #4708 we found out that custom response headers supposedly added with the response modifier middleware never seemed to actually show up in the responses.

Fix response modifier initial building

---

.travis.yml

Get Structor version from CI env var.
Be able to update Structor without a commit on Traefik.
Fix #4742

Get Structor version from CI env var.

---

tls/certificate.go
tls/tls.go

It improves a log message about when a TLS certificate already exists for a given entrypoint.
Also fixed a func name which had an incorrect plural while I was at it.
Fixes #4650

Improve log message about redundant TLS certificate

---

docs/content/providers/kubernetes-crd.md
docs/content/user-guides/crd-acme/index.md

k8s static configuration explanation.

k8s static configuration explanation

---

docs/content/middlewares/basicauth.md
docs/content/middlewares/digestauth.md
docs/content/middlewares/headers.md
docs/content/middlewares/ipwhitelist.md
docs/content/middlewares/passtlsclientcert.md
docs/content/providers/file.md
docs/content/reference/static-configuration.toml

- adds missing Marathon examples
- clean File provider section's titles
- fixes tracing and loglevel
- adds Rancher to the static configuration reference

Review documentation

---

provider/kv/kv.go
provider/kv/kv_config.go
provider/kv/kv_config_test.go

Manage errors during the KV configuration generation.
Avoid empty configuration due to network error. 

Enhance  KV client error management

---

docs/content/providers/docker.md
docs/content/providers/rancher.md

- fix reference configuration
- fix defaultRule doc.

fix: Rancher documentation.

---

CONTRIBUTING.md
acme/acme.go
acme/acme_test.go
docs/theme/partials/footer.html
provider/acme/provider.go
provider/acme/provider_test.go

Allow issue certificates with multiple wildcard domains.
* I need certificate that support multiple wildcard domains (e.g. *.domain.tld and *.tunnel.domain.tld)
* This fixes #4585
ACME specification actually allows multiple wildcard domains, it only says one wildcard (the * character) per domain, not one wildcard domain per certificate

Allow SANs for wildcards domain.

---

script/test-integration
script/update-cert.sh
script/update-generated-crd-code.sh
script/validate-vendor

Fix a shell script which fails on macOS and BSD, 
allowing the command `PRE_TARGET= make validate` to work fine on macOS.
Because some of us have damned souls using macOS :trollface: 
This fix is from @mpl :)

Fix `make validate` on MacOS outside container

---

docs/content/contributing/submitting-pull-requests.md
integration/fixtures/file/simple-hosts.toml
integration/simple_test.go
pkg/rules/rules.go
pkg/rules/rules_test.go

Allows host and request matching with FQDNs with trailing periods.
Fixes #4622 
Interestingly enough, trailing periods in request hosts are apparently more common that I thought! Its most common use is to reduce the number of DNS lookups due to relative domain names.

Allow matching with FQDN hosts with trailing periods

---

docs/content/routing/routers/index.md

fix: typo in routing example.

---

docs/content/providers/docker.md

Small documentation clarification regarding labels when running in Swarm Mode.
Many folks here have gotten confused on where labels go when running in Swarm Mode. They don't realize that Traefik isn't watching the individual container, but only the services running in the Swarm. Hopefully, these adjustments help clarify the how and why.
None.

Clarify docs with labels in Swarm Mode

---

pkg/server/router/router.go
pkg/server/router/tcp/router.go
pkg/server/service/tcp/service.go
pkg/server/service/tcp/service_test.go
pkg/tcp/proxy.go
pkg/tcp/rr_load_balancer.go

Don't add TCP proxy when error occurs during creation.
Fixes #4856
```
Stack: goroutine 6489 [running]:
runtime/debug.Stack(0xc0000cc240, 0x1fd8c52, 0x17)
/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/traefik/pkg/safe.defaultRecoverGoroutine(0x1c9ab60, 0x3a09680)
/go/src/github.com/containous/traefik/pkg/safe/routine.go:148 +0x9e
github.com/containous/traefik/pkg/safe.GoWithRecover.func1.1(0x207e5c0)
/go/src/github.com/containous/traefik/pkg/safe/routine.go:139 +0x57
panic(0x1c9ab60, 0x3a09680)
/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/containous/traefik/pkg/tcp.(*Proxy).ServeTCP(0x0, 0x23a9440, 0xc0004d6750)
/go/src/github.com/containous/traefik/pkg/tcp/proxy.go:30 +0x115
github.com/containous/traefik/pkg/tcp.(*RRLoadBalancer).ServeTCP(0xc000089800 …
```

Don't add TCP proxy when error occurs during creation.

---

script/binary
script/test-integration
script/test-unit

This PR fixes a regression introduces by #4859 , where calling some of the plumbing shell with multiple flags has an unwanted behavior: flags are passed to the `go` command a a single string, instead of a collection.
We want developers and maintainers to work locally with multiple flags to have a good experience: CI is not the only use case for such scripts.
- How to test it: run the following use cases on your local machine:
```shell
$ make binary
$ make test
$ PRE_TARGET="" CI=1 TESTFLAGS="-tlog -check.f K8sSuite" make test-integration
```
- More on the "how": https://github.com/koalaman/shellcheck/wiki/SC2086

Fix regression on plumbing scripts for developer usages

---

autogen/gentemplates/gen.go
templates/kubernetes.tmpl

Fix the template error for Kubernetes provider
Setting traefik.ingress.kubernetes.io/responseforwarding-flushinterval annotation on a Kubernetes service resource results in below template error:
"msg":"template: :13:34: executing \"\" at \u003c$backend.responseFor...\u003e: can't evaluate field responseForwarding in type *types.Backend"

fix kubernetes template for backend responseforwarding flushinterval setting

---

docs/content/middlewares/overview.md
docs/content/providers/kubernetes-crd.md
docs/content/reference/dynamic-configuration/kubernetes-crd.yml

I used traefik 2.0, I found When the name contains point，The domain name Can't match. 
After the test，Traefik fails to match when the name contains point.
```console
$ kubectl get ingressroutes.traefik.containo.us whoami.crd -o yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"traefik.containo.us/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"whoami.crd","namespace":"kube-system"},"spec":{"entryPoints":["web"],"routes":[{"kind":"Rule","match":"Host(`www.whoami.com`)","priority":12,"services":[{"name":"whoami","port":80}]}]}}
creationTimestamp: 2019-05-23T05:16:52Z
generation: 1
name: whoami.crd
namespace: kube-system
resourceVersion: "79805677"
selfLink: …
```

Fix typo in the CRD documentation

---

docs/content/reference/static-configuration.txt
pkg/config/static/static_config.go

Fix Entry points CLI description.
Have good documentation.

Entry points CLI description.

---

docs/content/middlewares/overview.md
docs/content/providers/docker.md
docs/content/providers/marathon.md
docs/content/providers/rancher.md

fix the documentation about middleware labels.

---

CONTRIBUTING.md
docs/content/contributing/thank-you.md

- The `./CONTRIBUTING.md` file now points to the "v2.0 -> Contributing -> Thank You!" page
- Improve the "v2.0 -> Contributing -> Thank You!" page by adding an admonition serving as "micro-ToC".
Improved reading path for new (or potential) contributors.
A fun GIF because... why not?

Docs: improve the "reading path" for new contributers

---

provider/docker/docker.go
provider/docker/docker_unix.go
provider/docker/docker_windows.go

Updates the docker API version to 1.24
Fixes #4905 
From https://docs.docker.com/develop/sdk/#api-version-matrix
```
Docker does not recommend running versions prior to 1.12,
which means you are encouraged to use an API version of 1.24 or higher.
```

Update docker api version

---

docs/user-guide/cluster-docker-consul.md
docs/user-guide/docker-and-lets-encrypt.md
docs/user-guide/kv-config.md
docs/user-guide/swarm-mode.md
docs/user-guide/swarm.md

This pr updates version of the traefik docker container in the example docker-compose file in the user guide for using traefik with docker and LE.
I've had some issues caused by me using an outdated version of traefik (see #4926) which was mostly caused by just copying the docker compose file. From [docker hub](https://hub.docker.com/_/traefik) it looks like `latest` ist the latest stable image, so I propose to just use that in the examples.

Use the latest stable version of traefik in the docs

---

docs/content/providers/rancher.md

Updates the Rancher documentation to specify it is specific to Rancher 1.x.
Rancher 2.x is basically a super-duper reverse proxy and control plane for Kubernetes.

Specify that Rancher provider is for 1.x only

---

integration/fixtures/tcp/catch-all-no-tls-with-https.toml
integration/fixtures/tcp/catch-all-no-tls.toml
integration/resources/compose/tcp.yml
integration/tcp_test.go
pkg/tcp/router.go

Forward directly the tcp traffic when only one router without TLS and rule `HostSNI("*")`  is configured on an entrypoint.
To be able to handle when a protocol needs a connection confirmation without sending any bytes.
Fixes #4875 

Remove first byte wait when tcp catches all

---

Gopkg.lock
docs/content/routing/services/index.md
pkg/config/dyn_config.go
pkg/provider/label/parser_test.go
pkg/server/service/service.go
pkg/server/service/service_test.go
vendor/github.com/vulcand/oxy/roundrobin/stickysessions.go

Introduce 2 new boolean entries to the configuration for marking the affinity cookies HttpOnly and Secure. They are "false" by default for backward compatibility. Additionally, it uses the configured values to create the affinity cookie as such.
Security
Fixes #4738 and #2653 
The PR in Oxy (the vendor using which affinity cookie is implemented) has been reviewed and merged.

HttpOnly and Secure flags on the affinity cookie

---

docs/configuration/logs.md
middlewares/accesslog/logger_formatters.go
middlewares/accesslog/logger_formatters_test.go

This PR introduces a fix to allow local timezone for the field `timestamp` on the log.
Kudos to @ldez for providing this code fix without breaking the current behavior!
We want user to be able to print the time in their local,
without requiring switching to JSON,
and without introducing a breaking change.
closes #3870

Allows logs to use local time zone instead of UTC

---

docs/content/middlewares/headers.md

Middleware docs were using wrong casing for kubernetes. See https://github.com/containous/traefik/blob/master/pkg/config/middlewares.go#L125L164 for the specification.

Update headers middleware docs for kubernetes crd

---

.travis.yml
CHANGELOG.md

Prepare release v2.0.0-alpha5.

Prepare release v2.0.0-alpha5

---

pkg/cli/commands.go
pkg/cli/commands_test.go

Don't allow non flag arguments by default.
Be able to pass [`override-cmd` test](https://github.com/docker-library/official-images/tree/3f87965eeb524bd3d47d0b5f37381c71fe20f71f/test/tests/override-cmd)
To validate the test, the following command must return an error:
```
traefik echo 'Hello world-1194-26292'
```
Related to https://github.com/docker-library/official-images/pull/6102#issuecomment-502883063
Related to https://github.com/containous/traefik-library-image/blob/master/alpine/entrypoint.sh

Don't allow non flag arguments by default.

---

CHANGELOG.md

Prepare release v2.0.0-alpha6.

Prepare release v2.0.0-alpha6.

---

pkg/cli/commands.go
pkg/cli/commands_test.go

Display an error when help is called on a non existing command.
Be able to pass [`override-cmd` test](https://github.com/docker-library/official-images/tree/3f87965eeb524bd3d47d0b5f37381c71fe20f71f/test/tests/override-cmd)
To validate the test, the following commands must return an error:
```bash
./traefik echo Hello world-$RANDOM-$RANDOM
./traefik traefik echo Hello world-$RANDOM-$RANDOM
./traefik echo --help
./traefik traefik echo --help
```
Related to #4970
Related to https://github.com/docker-library/official-images/pull/6106#issuecomment-503314187
Related to https://github.com/containous/traefik-library-image/blob/master/alpine/entrypoint.sh

Display an error when help is called on a non existing command.

---

docs/content/getting-started/configuration-overview.md
pkg/cli/loader_env.go
pkg/config/env/env.go
pkg/config/env/env_test.go
pkg/config/env/filter.go
pkg/config/env/filter_test.go
pkg/config/env/fixtures_test.go
pkg/config/file/file_node.go
pkg/config/file/raw_node.go
pkg/config/file/raw_node_test.go
pkg/config/flag/flag.go
pkg/config/flag/flagparser.go
pkg/config/label/label.go
pkg/config/parser/element_nodes.go
pkg/config/parser/element_nodes_test.go
pkg/config/parser/labels_decode.go
pkg/config/parser/labels_decode_test.go
pkg/config/parser/node.go
pkg/config/parser/parser.go

Filter env vars configuration.
Kubernetes automatically creates a bunch of variables prefixed with `TRAEFIK_` (probably based on the image name), and since our config loader was checking for the presence of the above prefix, this situation was obviously creating a conflict.
https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables

Filter env vars configuration

---

pkg/tls/tlsmanager.go
pkg/tls/tlsmanager_test.go

Fix a panic in TLS Manager
Avoid panic
```
reverse-proxy_1  | time="2019-06-21T12:37:25Z" level=error msg="Error while creating certificate store default"
reverse-proxy_1  | time="2019-06-21T12:37:25Z" level=error msg="Error while creating certificate store default"
reverse-proxy_1  | 2019/06/21 12:37:29 server.go:3012: http: panic serving 8.16.32.64:35996: runtime error: invalid memory address or nil pointer dereference
reverse-proxy_1  | goroutine 52 [running]:
reverse-proxy_1  | net/http.(*conn).serve.func1(0xc0003a1d60)
reverse-proxy_1  |      /usr/local/go/src/net/http/server.go:1769 +0x139
reverse-proxy_1  | panic(0x1d57040, 0x3bad010)
reverse-proxy_1  |      /usr/local/go/src/runtime/panic.go:522 +0x1b5
reverse-proxy_1  | github.com/containous/traefik/pkg/tls.(*Manager).Get.func1(0x …
```

Fix panic in tls manager

---

CHANGELOG.md

Prepare release v2.0.0-alpha7.

Prepare release v2.0.0-alpha7

---

types/types.go

Uses `dynamodbav tags` to override json tags.
https://github.com/aws/aws-sdk-go/blob/edc3c2b3cf8402559c7242b17f7793cd799938d7/service/dynamodb/dynamodbattribute/encode.go#L185-L197
```
// A MarshalOptions is a collection of options shared between marshaling
// and unmarshaling
type MarshalOptions struct {
// States that the encoding/json struct tags should be supported.
// if a `dynamodbav` struct tag is also provided the encoding/json
// tag will be ignored.
//
// Enabled by default.
SupportJSONTags bool
}
```
Related to #4918
Fixes #4998

Use dynamodbav tags to override json tags.

---

cmd/traefik/traefik.go
docs/content/getting-started/configuration-overview.md
pkg/cli/loader_env.go
pkg/cli/loader_flag.go

Changes the loading resource order:
- before: file > env > flags
- after: file > flags > env
Related to #4985
Kubernetes automatically creates a bunch of variables prefixed with `TRAEFIK_` (probably based on the image name), and since our config loader was checking for the presence of the above prefix, this situation was obviously creating a conflict.

Change the loading resource order

---

docs/index.md

This PR replaces the Slack badge of the documentation's homepage by the Discourse badge
With the Community Support moving to Discourse, we want our users to use the right website.

Update Slack support channel references to Discourse community forum

---

docs/content/user-guides/crd-acme/index.md

This change specifies the required minimum kubectl version for the Acme with CRD guide.
The guide fails with kubectl version < 0.11
Fixes #4279 (maybe?)

doc/crd-acme: specify required kubectl version

---

pkg/api/handler.go
pkg/api/handler_test.go

This PR (re-?)adds `Content-Type` to the Traefik `/api` endpoints. 
I'm unsure if I'm meeting the testing standards but I modified as little as I thought was necessary. Completely happy to receive feedback as I'm not primarily a Golang developer. 
I noticed in the recent `alpha7` that the raw JSON being returned was not being formatted nicely in Firefox anymore. This was working in the past, but I didn't notice any changes to this file which would've added this in the history. I may be unaware of the appropriate Headers being added in some other http middleware. 
Example response headers from `alpha7` `/api/rawdata`
```
HTTP/1.1 200 OK
X-Next-Page: 1
Date: Tue, 25 Jun 2019 13:30:58 GMT
Content-Length: 1338
Content-Type: text/plain; charset=utf-8
```

Adding content-header to api endpoints

---

middlewares/tlsClientHeaders.go
middlewares/tlsClientHeaders_test.go
server/server_middlewares.go

If no client peer certificates could be found always clear the headers so no request could pass them to backends, e.g. if TLSMutualAuth is optional.
Using an optional TLSMutualAuth we've seen that clients could pass the headers into the request and the final request to the backend may look like it has been TLS mutual authenticated.

Clear TLS client headers if TLSMutualAuth is optional

---

docs/content/middlewares/overview.md
docs/content/providers/kubernetes-crd.md
integration/testdata/rawdata-crd.json
pkg/provider/kubernetes/crd/fixtures/with_middleware_crossprovider.yml
pkg/provider/kubernetes/crd/kubernetes.go
pkg/provider/kubernetes/crd/kubernetes_test.go

This PR handles the case where a middleware is defined in a provider other than the kubernetes CRD one (e.g. file provider), and is used from a Kubernetes CRD.
In this case, the usual cross-provider syntax (middlewarename@provider) should be used, and whatever namespace attribute specified in the middleware reference is ignored.
Some documentation for TLS Option was also added/fixed as it is a similar situation and behaviour.
Having a consistent cross-provider story everywhere.
Fixes #4855

Handle cross-provider middleware in kubernetes CRD

---

docs/configuration/logs.md

This PR clarifies the documentation page about logs:
- Adding comment to explicit that the default value is `common` and refers to the default CLF format
- Clarifies that customizing the fields requires to switch to the JSON format
This PR follows up #3942 and is inspired by #3870 where the user was not aware about the mandatory format switch, which could have avoided wasting time searching for a non existent configuration.
Closes #4869.

Update documentation to clarify the default format for logs

---

provider/kubernetes/fixtures/loadGlobalIngressWithMultiplePortNumbers_endpoints.yml
provider/kubernetes/fixtures/loadGlobalIngressWithMultiplePortNumbers_ingresses.yml
provider/kubernetes/fixtures/loadGlobalIngressWithMultiplePortNumbers_services.yml
provider/kubernetes/kubernetes.go
provider/kubernetes/kubernetes_test.go

This PR checks for port matches on multiport services. This check is present in the main ingress processing, but was absent for the global ingress processing.
Fixes #5000

Check for multiport services on Global Backend Ingress

---

docs/content/observability/access-logs.md
pkg/types/logs.go

Drop headers by default in access logs.
Prevent some miss-configuration of the access logs.

Drop headers by default in access logs.

---

CHANGELOG.md

Prepare release v2.0.0-alpha8.

Prepare release v2.0.0-alpha8

---

docs/content/routing/routers/index.md
docs/content/user-guides/crd-acme/01-crd.yml
integration/fixtures/https/https_tls_options.toml
integration/https_test.go
pkg/server/router/tcp/router.go
pkg/tcp/router.go

This PR handles the conflict that occurs when several routers have the same Host in their rule, but have different TLS options associated to that Host.
To address that problem, this PR:
1) Documents the conflict.
2) Warns the user about the situation with log messages.
3) Fallbacks to the default TLS option when such a conflict is detected.
In addition, we took the opportunity to fix some related documentation (about TLS options) in the acme CRD user-guide.
To fix the conflict, which could potentially even have security implications (e.g. when a router would end up using some less strict TLS options than the ones specified by the user).
Fixes #5046 

TLSOptions: handle conflict: same host name, different TLS options

---

docs/configuration/entrypoints.md

Explains what is the real behavior of the `optional` configuration for a Mutual Authentication. 
Avoids misunderstanding about the configuration of mutual authentication.
-  ~~[ ]   Added/updated tests~~

Fixes the TLS Mutual Authentication documentation

---

docs/content/observability/tracing/jaeger.md
docs/content/reference/static-configuration/cli-ref.md
docs/content/reference/static-configuration/env-ref.md
docs/content/reference/static-configuration/file.toml
docs/content/reference/static-configuration/file.yaml
integration/fixtures/tracing/simple-jaeger-collector.toml
integration/tracing_test.go
pkg/tracing/jaeger/jaeger.go

Adds the Jaeger collector endpoint and basic auth reporter configuration settings.
Allows trace submission to Jaeger collectors via http, removing agent requirement.

Add Jaeger collector endpoint

---

pkg/api/handler_overview.go
pkg/api/handler_overview_test.go
pkg/api/handler_tcp_test.go
pkg/api/testdata/overview-dynamic.json
pkg/api/testdata/tcprouters.json
pkg/api/testdata/tcpservices.json

Manages status for TCP element in the endpoint overview.
Be able to get the status for TCP routers and services in the endpoint overview.

Manage status for TCP element in the endpoint overview.

---

pkg/provider/file/file.go
pkg/provider/file/file_test.go
pkg/provider/file/fixtures/toml/dir01_file03.toml
pkg/provider/file/fixtures/yaml/dir01_file03.yml

fix: TLS configuration from directory.
Related to:
- https://community.containo.us/t/traefik-v2-alpha8-tls-configuration-options-default-cert-not-applied/921
- #5114

fix: TLS configuration from directory.

---

cmd/healthcheck/healthcheck.go
docs/content/observability/metrics/prometheus.md
docs/content/operations/api.md
docs/content/operations/ping.md
docs/content/reference/static-configuration/cli-ref.md
docs/content/reference/static-configuration/env-ref.md
integration/fixtures/marathon/simple.toml
integration/fixtures/ratelimit/simple.toml
integration/simple_test.go
pkg/anonymize/anonymize_config_test.go
pkg/api/handler.go
pkg/config/static/static_config.go
pkg/ping/ping.go
pkg/provider/rest/rest.go
pkg/server/router/route_appender_aggregator.go
pkg/server/router/route_appender_aggregator_test.go
pkg/types/metrics.go

This PR removes the Middlewares and Entrypoint fields of the API handler configuration. As we're probably going to redo the routing and TLS handling (among other things) of other handlers (such as Ping, Rest provider, Prometheus metrics, etc) in the same way we're going to do it for the API handler, this PR also removes similarly extraneous fields for these as well.
This change comes in preparation of a a rework of the API handler configuration, which will define how traffic is routed to it, how we handle TLS with it, etc.
We envision that the Entrypoint and Middlewares are not going to be part of its configuration anymore when we redo it, so remove them as of now, so that we don't have to break the configuration later on.

API: remove configuration of Entrypoint and Middlewares

---

pkg/provider/acme/challenge_http.go
pkg/provider/acme/provider.go

In the logs, the provider name is `<name>.acme` instead of `acme.<name>` to be consistent with the configuration.
Have better logs.

Improve acme logs.

---

webui/package.json
webui/src/components/EntityStateDoughnut.vue
webui/src/components/Tile.vue
webui/src/main.js
webui/src/views/Home.vue
webui/yarn.lock

Now the new `webui` has been bootstrapped, this need some code cleanup

refactor(webui): use components to split Home concerns

---

docs/user-guide/docker-and-lets-encrypt.md

There are few examples for CLI, and I see necessary CLI example to have everything in the docker-compose manifest; 
in a single file instead of in a manifest and in a TOML file

Add example for CLI

---

tls/generate/generate.go

Adds missing KeyUsages for the default generated certificate
Fixes #5006 
Chrome Pre-v75 did not strictly enforce the keyUsage parameter for self-signed certificates, as the user already had to allow them.
I have added in:
- Digital Signature (Required by chrome)
- Key Agreement (can be used with DH ciphers)
- Data Encipherment (for encrypting data)
More information can be found in:
(https://www.ibm.com/support/knowledgecenter/sl/SSKTMJ_9.0.1/admin/conf_keyusageextensionsandextendedkeyusage_r.html)
and (https://www.ietf.org/rfc/rfc3280.txt) section `4.2.1.3  Key Usage`

Add missing KeyUsages for default generated certificate

---

pkg/cli/commands_test.go
pkg/cli/loader_file.go
pkg/config/flag/flag_test.go
pkg/config/flag/flagparser.go
pkg/config/flag/flagparser_test.go

Take the CLI flags case into account to apply the static configuration.
For the static configuration, some elements are case sensitive (like access log fields), so we need to apply the right static configuration from the command line.

Apply the case of the CLI flags for the configuration

---

docs/content/routing/routers/index.md

Fixes the indentation of the YAML snippet to show that the domains section is actually under the TLS section.
When it's not configured under the TLS section, it gets omitted from the config parsing and leads to requesting a cert with the FQDN of the host rule only, leading to plenty of certificate requests to Let's Encrypt.
Following the old documentation:
```
traefik_1  | time="2019-08-03T19:16:18Z" level=debug msg="Configuration received from provider file: {\"http\":{\"routers\":{\"SERVICE\":{\"entryPoints\":[\"https\"],\"service\":\"SERVICE\",\"rule\":\"Host(`subdomain.SOME.DOMAIN.com`)\",\"tls\":{\"certResolver\":\"default\"}}},\"services\":{\"SERVICE\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://X.X.X.X:XX\"}],\"passHostHeader\":false}}}},\"tcp\":{},\"tls\":{}}" …
```

[Docs] YAML indent for domains under TLS section

---

cmd/configuration.go
docs/configuration/backends/consulcatalog.md
provider/consulcatalog/consul_catalog.go

I would like to have a behavior like the DNS provider of consul.
Even if the service is warning, It is considered as UP.
Moreover, another difference is that if any service not served by traefik is in warning state, traefik remove it from consul catalog.
Change failure detection for consul catalog
A warning on a service on a node disable all frontends of this node on consul
- Not Added/updated tests
- Not Added/updated documentation
I have tested it manualy, I don't know what test I could write.
related to #4536

warning should not be a fail status

---

docs/content/user-guides/docker-compose/acme-dns/docker-compose.yml
docs/content/user-guides/docker-compose/acme-dns/docker-compose_secrets.yml
docs/content/user-guides/docker-compose/acme-dns/index.md
docs/content/user-guides/docker-compose/acme-http/docker-compose.yml
docs/content/user-guides/docker-compose/acme-http/index.md
docs/content/user-guides/docker-compose/acme-tls/docker-compose.yml
docs/content/user-guides/docker-compose/acme-tls/index.md
docs/content/user-guides/docker-compose/basic-example/docker-compose.yml
docs/content/user-guides/docker-compose/basic-example/index.md
docs/mkdocs.yml

Addind a User Guide to the existing documentation giving an example with docker-compose and let's encrypt ~~behind a basic auth~~
- I personally would have liked to find something like this in the doc
- it respond to some topics in the forum 
- https://community.containo.us/t/thats-it-time-to-learn-traefik/896
- ~~https://community.containo.us/t/a-global-http-https-redirection/864~~
I wanted to know if you could be interested in this ?
If yes, feel free to give me feedback =) (I did it quite quickly)
Thanks.

Add a docker-compose & let's encrypt user-guide

---

healthcheck/healthcheck.go
healthcheck/healthcheck_test.go

Patches the `checkBackend` method in `healthcheck/healthcheck.go` to preserve the weight of servers that fail a health check, and then restores the weight when a server recovers.
Fixes #2986
I was testing out health checks on my system and discovered that if a server with a very high weight fails and then recovers, it is treated as having a weight of 1 until the server's weight value is modified in any way.
I am not sure if additional tests are required for this change, let me know if they are.
I was unable to get the Web UI to function when building from source, even before I made any modifications to Traefik's code, but everything else was working as intended.
Also, I made this change in the v1.7 branch because my current use case requires Consul KV as a provider which isn't in v2 yet. …

Wrr loadbalancer honors old weight on recovered servers

---

server/server.go

This PR fixes a potential panic on the `hijackConnectionTracker.Close` method.
The access to the `conns` attribute wasn't protected against concurrent calls,
potentially causing a `concurrent map writes` panic.
This is causing a panic on our side.

Make hijackConnectionTracker.Close thread safe

---

webui/src/App.vue

- ✨ Add Version in Navbar
- ✨ Add Documentation (based on version) link in Navbar
**Question** How can I map *version api* to *doc api* ?
- Helping User find Documentation directly in the Navbar is a sweet feature

feat(webui): add doc and version in navbar

---

pkg/middlewares/retry/retry_test.go

Fixes `url.Parse` due to go1.12.8 changes.
See #5201

Fix `url.Parse` due to go1.12.8 changes.

---

pkg/provider/kubernetes/crd/fixtures/services.yml
pkg/provider/kubernetes/crd/kubernetes.go
pkg/provider/kubernetes/crd/kubernetes_test.go
pkg/provider/kubernetes/ingress/fixtures/Ingress-with-a-basic-rule-on-one-path-with-https-(port-==-443)_endpoint.yml
pkg/provider/kubernetes/ingress/fixtures/Ingress-with-a-basic-rule-on-one-path-with-https-(port-==-443)_service.yml
pkg/provider/kubernetes/ingress/kubernetes.go
pkg/provider/kubernetes/ingress/kubernetes_test.go

When applying the port value heuristic to decide whether to contact a Kubernetes _Service_'s _Endpoints_ using HTTP or HTTPS, inspect the _Service_'s front-end port instead of the upstream servers' port values. That is, for example, when Traefik services an _Ingress_ or _IngressRoute_ object pointing at a _Service_ that forwards from port 443 to servers listening on port 8443, it should use HTTPS.
Fixes #5164 (though not yet honoring the "ingress.kubernetes.io/protocol" annotation yet [like in Traefik version 1.7](https://github.com/containous/traefik/blob/v1.7/provider/kubernetes/kubernetes.go#L355-L363))
Should we include the "ingress.kubernetes.io/protocol" annotation here? At present, this patch addresses only the _Service_ port value.

Correct Kubernetes Ingress and IngressRoute port heuristic for choosing HTTPS

---

docs/content/user-guides/docker-compose/acme-http/docker-compose.yml

Removes the extra colon.  Otherwise the docker will not compose.
(First time contibutor, hopefully this is the right process)

Removed extra colon before the 8080 docker port

---

autogen/gentemplates/gen.go
templates/kubernetes.tmpl

Template modified to support ingress.kubernetes.io/auth-header-field
Change to the kubernetes template to take auth-header-field into account.
A kubernetes ingress with authentication always sends a header `X-WebAuth-User` with the username to the backend. The [documentation](https://docs.traefik.io/configuration/backends/kubernetes/#authentication) states, that the header name can be changed through the annoation `ingress.kubernetes.io/auth-header-field`. This annotation is currently read from the kubernetes api but ignored when building the frontend definition.
The default behaviour of the code will change. The documentation does not exactly describe if that header field will be set without an annotation.

Kubernetes support for Auth.HeaderField

---

go.mod
go.sum

Updating projects using libraries that were recently updated to support Risc-V architecture.
Go upstream work is tracked on: golang/go#27532
Risc-V software support tracker on https://github.com/carlosedp/riscv-bringup
Run Traefik on Risc-V architecture.

Bump x/sys to support Risc-V architecture

---

docs/content/routing/entrypoints.md
go.mod
go.sum
integration/proxy_protocol_test.go
integration/resources/haproxy/haproxy.cfg
pkg/server/server_entrypoint_tcp.go

This PR adds support for proxyprotocol v2 headers.
The package provides support for proxy protocol v1 (https://github.com/armon/go-proxyproto) is replaced by the package (https://github.com/c0va23/go-proxyprotocol) supporting the analysis of both proxy protocol versions at the same time.
Support for proxy protocol v2 need that traefik can be run using AWS NLB.
Package github.com/c0va23/go-proxyprotocol tested manually with HA Proxy (v1 and v2) and on production with AWS NLB.
It PR #4561 migrated on branch v2.0

Add support proxyprotocol v2

---

go.mod
go.sum
pkg/version/version.go

This PR fix #5256
Before go module the dependency [github.com/google/go-github](https://github.com/google/go-github) was in version [fe7d11f8add400587b6718d9f39a62e42cb04c28](https://github.com/google/go-github/blob/fe7d11f8add400587b6718d9f39a62e42cb04c28/github/github.go#L241-L271)
https://github.com/containous/traefik/pull/5191/files#diff-bd247e83efc3c45ae9e8c47233249f18L808
Today this dependency is in version [v27.0.4](https://github.com/google/go-github/blob/v27.0.4/github/github.go#L338-L371)
And there is a check for the trailing slash
```go
if !strings.HasSuffix(c.BaseURL.Path, "/") {
return nil, fmt.Errorf("BaseURL must have a trailing slash, but %q does not", c.BaseURL)
}
```
Be able to check new version

Fix trailing slash with check new version

---

pkg/server/service/loadbalancer/mirror/mirror.go
pkg/server/service/loadbalancer/mirror/mirror_test.go

blackholeResponseWriter now implements `http.Hijacker` and `http.Flusher` interface.
Fix a recovered panic when websocket is mirrored.
When websocket is mirrored, we mirror the upgrade request but not the websocket messages after that.

Fix recovered panic when websocket is mirrored

---

docs/configuration/backends/kubernetes.md
provider/kubernetes/kubernetes.go

This is an in-progress change to throttle how frequently we refresh the Kubernetes ingress configuration.
This isn't ready to merge; I wanted to start a discussion about the approach and share my results testing this change in my production environment. 
My team is in the process of moving from the Nginx ingress controller to Traefik. Overall, it's been going well but we saw concerningly high CPU usage from Traefik. We're not handling very much traffic, but each of our 19 Traefik pods was using around 200 millicores, with spikes up to 700-800 millicores. For reference, our nginx pods were using around 40-50 millicores for a heaver traffic load.
Our cluster is roughly 25 nodes, but we're running many more independent services than is typical for a Kubernetes cluster -- we have about 2000 …

Throttle Kubernetes config refresh

---

docs/content/observability/tracing/zipkin.md
docs/content/reference/static-configuration/cli-ref.md
docs/content/reference/static-configuration/env-ref.md
docs/content/reference/static-configuration/file.toml
docs/content/reference/static-configuration/file.yaml
go.mod
go.sum
integration/fixtures/tracing/simple-zipkin.toml
integration/resources/compose/tracing.yml
pkg/anonymize/anonymize_config_test.go
pkg/config/file/file_node_test.go
pkg/config/file/fixtures/sample.toml
pkg/config/file/fixtures/sample.yml
pkg/tracing/zipkin/zipkin.go

This PR changes the Zipkin dependency to use the latest Zipkin Go OpenTracing Bridge which builds on the native Zipkin Go tracer instead of the now deprecated zipkin-go-opentracing implementation. 
Zipkin has moved away from the old V1 data model to the new V2 data model allowing for improved efficiency, faster encoding and smaller transmit payloads. Up to release 0.4.0 the zipkin-go-opentracing package held its own internal implementation which was purely V1 based. The latest release of zipkin-go-opentracing uses the native Zipkin Go tracer which uses the V2 datamodel and provides the bridge to the OpenTracing API. 
The change from v0.3.5 to v0.4.3 holds a breaking change in the bootstrap code of the tracer. This PR fixes that by bootstrapping the native Zipkin Go tracer and wrapping it …

Update Zipkin OpenTracing driver to latest 0.4.3 release

---

.semaphoreci/setup.sh
build.Dockerfile
docs/content/contributing/building-testing.md
exp.Dockerfile

This PR update the go version to `1.13rc2`
Be up-to-date

Update go version to go 1.13rc2

---

cmd/traefik/traefik.go
pkg/server/middleware/middlewares.go
pkg/server/middleware/middlewares_test.go

fix buffering middleware
```
DEBU[2019-09-02T15:52:55+02:00] Configuration received from provider file: {"http":{"routers":{"router0":{"entryPoints":["http"],"middlewares":["test-stripprefix"],"service":"service-foo","rule":"Path(`/bar`)"}},"middlewares":{"test-stripprefix":{"buffering":{"maxRequestBodyBytes":250000}}},"services":{"service-foo":{"loadBalancer":{"servers":[{"url":"http://127.0.0.1:3030"}],"passHostHeader":false}}}},"tcp":{},"tls":{}}  providerName=file
DEBU[2019-09-02T15:52:55+02:00] Creating middleware                           middlewareName=pipelining entryPointName=http routerName=router0@file serviceName=service-foo middlewareType=Pipelining
DEBU[2019-09-02T15:52:55+02:00] Creating load-balancer                        entryPointName=http routerName=router0@file …
```

fix buffering middleware

---

pkg/responsemodifiers/response_modifier.go
pkg/responsemodifiers/response_modifier_test.go
pkg/server/middleware/middlewares.go
pkg/server/middleware/middlewares_test.go

fix: undefined middleware.
```
DEBU[2019-09-03T11:44:52+02:00] Configuration received from provider file: {"http":{"routers":{"router0":{"entryPoints":["http"],"middlewares":["test-middleware"],"service":"service-foo","rule":"Path(`/bar`)"}},"middlewares":{"test-middleware":null},"services":{"service-foo":{"loadBalancer":{"servers":[{"url":"http://127.0.0.1:3030"}],"passHostHeader":false}}}},"tcp":{},"tls":{}}  providerName=file
ERRO[2019-09-03T11:44:52+02:00] Error in Go routine: runtime error: invalid memory address or nil pointer dereference 
ERRO[2019-09-03T11:44:52+02:00] Stack: goroutine 88 [running]:
runtime/debug.Stack(0xc00013a000, 0x24bdd12, 0x17)
/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x208cf40, …
```

Don't panic with undefined middleware

---

docs/content/middlewares/stripprefixregex.md
integration/fixtures/https/https_redirect.toml
pkg/middlewares/stripprefix/strip_prefix.go
pkg/middlewares/stripprefix/strip_prefix_test.go
pkg/middlewares/stripprefixregex/strip_prefix_regex.go
pkg/middlewares/stripprefixregex/strip_prefix_regex_test.go

Don't return a 404 when the path is not stripped.
To be able to use  stripPrefix and stripPrefixRegex.

fix: stripPrefix and stripPrefixRegex.

---

docs/content/middlewares/retry.md

Try to be more explicit on the retry middleware mechanism.

Enhance the Retry Middleware Documentation

---

docs/content/observability/access-logs.md
pkg/middlewares/accesslog/logger.go

This PR makes the accesslog middleware default to Common Log Format when the provided format is unsupported (e.g. user made a config mistake). Previously we used to return an error in that case, now we log instead and provide a working middleware with CLF.
To have a sane fallback in case of PEBKAC.

Default to CLF when accesslog format is unsupported

---

pkg/server/server_entrypoint_tcp.go

Write HTTP server logs into the global logger.
Allow to move all logs in a file.

Write HTTP server logs into the global logger.

---

integration/testdata/rawdata-crd.json
pkg/server/middleware/middlewares.go
pkg/server/router/router.go
pkg/server/router/router_test.go

This PR adds the provider in middleware chain.
We want to have only middleware ref with provider in the API.

Add provider in middleware chain

---

CHANGELOG.md
docs/content/providers/kubernetes-crd.md
docs/content/providers/kubernetes-ingress.md
docs/content/reference/static-configuration/cli-ref.md
docs/content/reference/static-configuration/env-ref.md
docs/content/reference/static-configuration/file.toml
docs/content/reference/static-configuration/file.yaml
pkg/provider/kubernetes/crd/kubernetes.go
pkg/provider/kubernetes/ingress/kubernetes.go

Cherry pick v1.7 into v2.0:
Skip:
Be in sync.

Cherry pick v1.7 into v2.0

---

CHANGELOG.md

Prepare release v2.0.0-rc3
aka `montdor` (Mont d'Or)

Prepare release v2.0.0-rc3

---

tls/certificate_store.go
tls/certificate_store_test.go

This allows for the default certificate to be considered when getting all domains from a TLS certificate store.
When getting all domains for a store, the default cert domain should be included in the domains list. This is applicable when generating ACME domains, it should not generate a certificate for a domain that falls under the default domain.
Co-authored-by: Nicolas Mengin <nmengin.pro@gmail.com>

Consider default cert domain in certificate store

---

docs/configuration/logs.md

This PR improves the documentation page for the configuration of Access Logs.
- Feedback from this user: <https://github.com/containous/traefik/issues/5221#issuecomment-522454024>
- Found that customization of access logs fields, as well as access log headers were complicated to understand for end users.
This content is for `v1.7` branch, but it should be reusable after the next merge back to the `v2.0`.

Improve Access Logs Documentation page

---

docs/content/routing/services/index.md

It fixes "A Service with One Server" .yaml example
Example yaml has wrong format which leads to error:
`level=error msg="Cannot start the provider *file.Provider: yaml: unmarshal errors:\n  line 10: cannot unmarshal !!map into []dynamic.Server"`

fix a service with one server .yaml example

---

middlewares/errorpages/error_pages.go

This PR adds the implementations of Hijacker and Flusher for one of the responseWriter implementations used in the error pages middleware.
These implementations should have been done in #5285 but that omission was overlooked. Without them, the support for websockets (among other things), is broken.
Co-authored-by: Julien Salleyron julien.salleyron@gmail.com

implement Flusher and Hijacker for codeCatcher

---

docs/content/providers/kubernetes-crd.md
pkg/middlewares/ratelimiter/rate_limiter_test.go
pkg/provider/kubernetes/crd/fixtures/with_options.yml
pkg/provider/kubernetes/crd/kubernetes_http.go
pkg/provider/kubernetes/crd/kubernetes_test.go
pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroute.go
pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go

This PR adds `serverOptions`  in `IngressRoute` .
To be able to configure `passHostHeader` and `flushInterval` in an `IngressRoute`.
Unrelatedly; we also disabled a flaky rate limiter test.

Add passHostHeader and responseForwarding in IngressRoute

---

pkg/config/flag/flagparser.go
pkg/config/flag/flagparser_test.go

Fix boolean (or pointer) flag parsing when the flag is related to map.
Example:
With the flag `--certificatesresolvers.default.acme.tlschallenge` the related key for the type is  `--certificatesresolvers.<name>.acme.tlschallenge`, so the name (`default`) must be neutralized to allow matching with the type.
Fixes #5333

fix: boolean flag parsing with map.

---

integration/testdata/rawdata-crd.json
integration/testdata/rawdata-ingress.json
pkg/provider/kubernetes/crd/kubernetes.go
pkg/provider/kubernetes/crd/kubernetes_test.go
pkg/provider/kubernetes/ingress/kubernetes.go
pkg/provider/kubernetes/ingress/kubernetes_test.go

This PR replace `/` by `-` for ID in kubernetes providers to be able to navigate easily in the webui
Be able to navigate in the webui

Fix kubernetes id name

---

cmd/traefik/traefik.go
docs/content/contributing/data-collection.md
pkg/anonymize/anonymize_config_test.go
pkg/config/static/static_config.go

Disable collect data by default.
> Before the GA, leaving this option unset will not prevent Traefik from running but will generate an error log indicating that it enables data collection by default.

Disable collect data by default.

---

pkg/server/service/proxy.go

Force `Sec-WebSocket-Key` header case to fix Handshake problem on websocket. 
It works with more websocket server implementation.
Fixes #5330 

Fix case-sensitive header in websocket

---

pkg/server/service/service.go

The status of the loadbalancer servers were not updated accordingly to the health check.
This PR fixes this issue by applying the loadbalancer status updater wrapper on the original loadbalancer.
Fixes #5231

Return an actual server status updater

---

docs/configuration/backends/kubernetes.md

Adds note clarifying client certificate header is not passed through unless it is from a CA specified on the EntryPoint.
This section suggests the client certificate sent is added to the header if the configuration is set on the Ingress; this alone is not sufficient (it must also pass validation at the EntryPoint, which requires separate config.)

Add note clarifying client certificate header

---

pkg/config/parser/labels_decode.go
pkg/config/parser/labels_decode_test.go

Before this PR, the flags are case sensitive but the flags require a consistent case.
By example:
the following flags doesn't have a consistent case on `certificatesresolvers`:
```
--certificatesresolvers.default.acme.email=my@email.com
--certificatesResolvers.default.acme.storage=/my-acme.json
--certifiCatesresolvers.default.acme.httpchallenge.entrypoint=http
```
=> only one flag is read (not expected) 
With this PR, the flags names don't need to have a consistent case.
Fixes #5360

Flag names don't need a consistent case.

---

docs/content/middlewares/forwardauth.md
docs/content/providers/docker.md
docs/content/providers/marathon.md

Improve documentation for the TLS  section of the provider connection.
Remove TODO

Improve documentation for the TLS  section of the provider connection.

---

docs/content/operations/cli.md
docs/content/providers/docker.md
docs/content/providers/marathon.md
docs/content/providers/rancher.md

Flags and labels are case insensitive.
Fixes #5424

doc: Flags and labels are case insensitive.

---

middlewares/errorpages/error_pages.go
middlewares/errorpages/error_pages_test.go

Before this change, the codeCatcher relied on the fact that Write would
always be called, and hence was in charge of actually sending the headers
that WriteHeader had "cached" when it had been called.
However, in the case of e.g. a 304, since the response should not have
any body, there is no reason for the caller (i.e. another proxy or
middleware in the chain of calls) to call the codeCatcher's Write.
Therefore, neither the headers, and hence nor the the response code,
were actually forwarded to the client.
Consequently, this change moves the responsibility of actually
forwarding the headers and response code to where it belongs, i.e. in
WriteHeader.
In addition, this change adds a wrapper of the codeCatcher, so that we
can satisfy the CloseNotify interface as well.
N.B: in hindsight, I …

Actually send header and code during WriteHeader, if needed

---

docs/content/https/acme.md
docs/content/https/tls.md

Adds examples for TLS options with k8s.
Adds note about router and certificates resolver.
Cipher suites defined for TLS 1.2 and below cannot be used in TLS 1.3, and vice versa.
The new cipher suites are defined differently and do not specify the certificate type (e.g. RSA, DSA, ECDSA) or the key exchange mechanism (e.g. DHE or ECHDE).
>    A TLS-compliant application MUST implement the TLS_AES_128_GCM_SHA256
>    [GCM] cipher suite and SHOULD implement the TLS_AES_256_GCM_SHA384
>    [GCM] and TLS_CHACHA20_POLY1305_SHA256 [RFC8439] cipher suites (see
>    Appendix B.4).
https://tools.ietf.org/html/rfc8446
This is why all cipher suites are considered as safe for TLS1.3

Improve TLS documentation.

---

middlewares/accesslog/logger.go

When StdOut is used as the Access Log handlers file, on close or rotation, StdOut can and does get closed.
Closing StdOut is almost never a good.
Co-authored-by: jlevesy <julien.levesy@containo.us>

Avoid closing stdout when the accesslog handler is closed

---

pkg/server/middleware/middlewares.go
pkg/server/router/router.go

This PR makes sure that when a router does not refer to any middleware, the corresponding list in the config stays a nil slice instead of being initialised to an empty (non-nil) slice.
Otherwise, when a router refers to no middleware, we would still build
an empty (but non nil) slice of middlewares in the config.
Which means, when a (e.g. docker swarm) event sends us a config that is
in theory identical, it would still look different from the current one
because it would have a nil slice, whereas the current one would have an
empty slice. Therefore, all the handlers would be unnecessarily
rebuilt.
This was particularly visible with docker swarm, because, as opposed to
the other providers, it regularly polls to check for a config change,
instead of waiting for an event from the …

Do not initialize list of middlewares if not needed

---

integration/docker_compose_test.go
pkg/provider/docker/config.go
pkg/provider/docker/docker.go

fix: docker service name.
In some case the docker service name can start with `/`.
Fixes #5489

fix: docker service name.

---

docs/content/routing/providers/docker.md
docs/content/routing/providers/marathon.md
docs/content/routing/providers/rancher.md
docs/content/routing/providers/service-by-label.md
docs/content/routing/routers/index.md
pkg/provider/docker/config_test.go

This PR specifies in the doc some particular cases of automatic service creation and/or assignment to a router, with providers making use of labels.
Close #5455

clarify automatic service creation/assignment with labels

---

docs/content/routing/providers/docker.md

Fixed typo in routing/providers/docker documentation

Fixed typo in routing/providers/docker documentation

---

docs/content/middlewares/redirectscheme.md

Update text from RegexRedirect to RedirectScheme. The word used is wrong since the documentation is an example using `redirect scheme`

Fix misleading text

---

docs/content/routing/providers/docker.md
docs/content/routing/providers/marathon.md
docs/content/routing/providers/rancher.md
docs/content/routing/services/index.md

Add the pass host header section to the services documentation with a file provider example.

Add the pass host header section to the services documentation

---

docs/content/observability/metrics/influxdb.md
docs/content/observability/metrics/statsd.md

- doc: fix influxDB case in configuration page.
- doc: fix statsD case in configuration page.
Fixes #5530

doc: fix influxDB and statsD case in configuration page.

---

docs/content/migration/v1-to-v2.md

As with other parts of the documentation, the `$` must be escaped for `docker-compose.yml` integration and these are the ones I just found.
Just found them and wanted to fix.

$ needs escaping in docker-compose.yml

---

docs/content/routing/providers/docker.md
docs/content/routing/providers/marathon.md
docs/content/routing/providers/rancher.md
docs/content/routing/services/index.md

Add a Response Forwarding section to the service documentation with a File Provider example.
To have a better documentation.

Add a response forwarding section to the service documentation 

---

docs/content/operations/api.md

Add the missing `/api/overview` to the list with a description what I think it does.
Ran into a problem where I wanted just the API calls of traefik beeing routed through the `/api` ingress and found out, that the entry was missing from the documentation.

Add overview to API documentation

---

docs/content/routing/routers/index.md

Fix minor typo in documentation

fix: remove extra backtick from routers docs

---

docs/content/routing/services/index.md

Fixes typo in routing/services/#health-check
services is misspelled as servicess

fix: typo in healthCheck examples

---

Gopkg.lock
vendor/github.com/unrolled/secure/secure.go

When SSL is enabled the Location response header is not replaced to HTTPS, causing an unnecessary redirect.

Fix Location response header http to https when SSL

---

integration/https_test.go
integration/integration_test.go

This backports fixes from traefik 2 to 1.7 in order to make it possible
to build traefik 1.7 and run integration tests with a Go 1.13 runtime.
Fix #5140

Backport Go 1.13 integration test fixes

---

README.md

Remove old and deprecated videos from README, replace with the Youtube channel.
All good things must come to an end.

Remove deprecated videos

---

docs/content/migration/v1-to-v2.md
docs/content/operations/dashboard.md

This PR updates the API and Dashboard documentation pages to clarify how 
to set up and access the dashboard.
Closes #5561 .
- Community support led to misunderstandings, and users were facing a `404 Not Found` page instead of the dashboard.
> `/` ! Ah-ah! Savior of the universe

Clarifies how to configure and access the dashboard in the api & dashboard documentations

---

cmd/healthcheck/healthcheck.go
docs/content/operations/cli.md
docs/content/operations/ping.md

The term `API` could be mistaken with the Traefik web interface
exposing the configuration of router, services and middlewares
(As in https://docs.traefik.io/v2.0/operations/api/).
This pr replaces this term with the word `endpoint`, which is also
used in the documentation for this feature
(https://docs.traefik.io/v2.0/operations/ping/).
Fixes: #5226

Replace ambiguous cli help message wording

---

docs/content/migration/v1-to-v2.md
docs/content/routing/routers/index.md

Removed the TLS_RSA_WITH_AES_256_GCM_SHA384 cipher that causes the B rating from https://www.ssllabs.com/ssltest/ 
This cipher is considered weak and including it will result in a B rating by default.
Adding the ciphers that are not considered weak will result in an A rating out of the box.
Removes the TLS_RSA_WITH_AES_256_GCM_SHA384 cipher that is considered weak.
After the removal of this cipher the site security rating raises from a **B** to an **A**. 
It'd be useful, in the future, to provide a configuration that gives an **A+** rating out of the box.

Improve ciphersuite examples

---

docs/content/user-guides/crd-acme/03-deployments.yml

Update apiVersion in documentation descriptor
The old extensions/v1beta1 Deployment API is [deprecated](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/).

Update apiVersion in documentation descriptor

---

docs/content/index.md

Updates a misspelled word on the documentation page. ("businness" misspelled. Should be: "business") 
Saw the misspelled word while browsing the docs and I thought I would just help out by fixing it.

fix misspelling on documentation landing page

---

pkg/provider/kubernetes/ingress/kubernetes.go
pkg/provider/kubernetes/ingress/kubernetes_test.go

fix: default router name for k8s ingress.
be able to use api and dashboard with the default router.
Fixes #5611

fix: default router name for k8s ingress.

---

webui/src/components/_commons/PanelServiceDetails.vue
webui/src/components/_commons/StickyServiceDetails.vue

Add a vue component to display sticky details from both loadBalancer and weighted services.
Display the loadbalancer service sticky configuration.

Add a service sticky details vue component 

---

docs/content/https/acme.md

It is not possible to mount a relative file. A mount path has to be be absolute.
```
docker: Error response from daemon: invalid volume specification: '/my/host/acme.json:acme.json': invalid mount config for type "bind": invalid mount path: 'acme.json' mount path must be absolute.
See 'docker run --help'.
```

Fix acme storage file docker mounting example

---

docs/content/routing/services/index.md
pkg/provider/file/file.go

Add filename in the file provider logs.
Adding the file name makes it easier to understand an error.

fix: add filename in the file provider logs.

---

pkg/provider/kubernetes/ingress/kubernetes.go

Normalize service and router names for ingress.
remove `/` from names
Fixes  #5611

Normalize service and router names for ingress.

---

exp.Dockerfile
webui/Dockerfile
webui/readme.md

- Update Node to a up to date version
- Update readme of the webui
Keep træfik up to date ❤️ 
- The webui is not concerned by the breaking changes of NodeJS between 8 and 12.
- This will normally boost the build time for the webui
- *Node version 8 will be a dead version by the end of the year https://github.com/nodejs/Release*

chore(node/webui): update node to 12.11 version

---

docs/content/migration/v1-to-v2.md

This PR introduces the following changes on the migration guide of documentation:
- [chore] Remove empty whitespaces
- [chore] Fix title casings to fit a "Chicago" US casing (ref. https://capitalizemytitle.com/)
- [enhancement] Add a section about transforming URL path prefix, to educate v1 users to split responsibilities (1 router catch the request with the rule, and then middleware transform request)
#5562 #5408 
We want to improve the user experience of users migrating from v1
Nope

Migration guide: pathprefixstrip migration

---

docs/content/observability/access-logs.md

Clarifies the unit of duration field in access logs.
Fixes #3493.
See https://github.com/containous/traefik/issues/3493#issuecomment-523503228
I too needed clarification and did not find it in the docs.
No.

Clarify unit of duration field in access log

---

docs/content/reference/static-configuration/cli-ref.md
docs/content/reference/static-configuration/env-ref.md
pkg/tracing/instana/instana.go

Passing an empty string as default host allows instana/go-sensor to look up INSTANA_HOST_AGENT env var.
See https://github.com/instana/go-sensor/blob/master/fsm.go#L82-L92
In a kubernetes env it enables the possibility to give to traefik the ip of the host which should have a local instana agent.

Let instana/go-sensor handle default agent host

---

pkg/provider/kubernetes/crd/kubernetes_http.go
pkg/provider/kubernetes/ingress/kubernetes.go

This PR adds support for HTTPS with Kubernetes ExternalName, for both CRD and Ingress Class.
Trying to configure a backend with HTTPS, traefik hardcodded "http://" in front of the URL
I've already tested it with docker image kpeiruza/traefik:2.0 and is working. Dunno why the build has failed with travis-ci, it said something about documentation!!!!

Adding support for HTTPs backends with Kubernetes ExternalName services

---

docs/content/middlewares/forwardauth.md

Fix documentation forForwardAuth middleware tls.skipVerify option (k8s, yaml, toml).
Avoiding people to lose some time with wrong configuration ;)
- [x ] Added/updated documentation
Nope. Thx for your work.

fix ForwardAuth tls.skipverify examples

---

docs/content/middlewares/headers.md

Headers configuration not valid with `SSLRedirect` or `FrameDeny`  should be lowercase.

Fix Security Headers Doc

---

docs/scripts/verify.sh

skip akamai url verify.
On TravisCI the calls to `https://www.akamai.com` produce a 403.

fix: skip akamai url verify.

---

tls/generate/generate.go

This PR adds the extended key usage flag to the default certificate to allow the default certificate to work on macOS 10.15.
Fixes #5609 
Why that OID is required IDK, but Apple thinks it should be.

Allow Default Certificate to work on macOS 10.15

---

docs/content/routing/routers/index.md

Add documentation about backtick for rule definition.
To have a clear documentation.

Add documentation about backtick for rule definition.

---

Makefile

Increase the release timeout from 30m to 60m.
The v2.0.3 release is blocked by:
```
⨯ release failed after 1800.00s error=context deadline exceeded
```

fix: release timeout.

---

docs/content/routing/providers/docker.md
docs/content/routing/providers/marathon.md
docs/content/routing/providers/rancher.md

This renames the description of the Link to ../routers/index.md#priority from options to priority. The old description was probably an copy and paste error.
I read the documentation and noticed this small error.

Fix error in link description for priority

---

go.mod
go.sum

Upgrades zipkin-go-opentracing to v0.4.4 in order to fix #5646
Fixes #5646
Ping @ddtmachado @trajano
https://github.com/openzipkin-contrib/zipkin-go-opentracing/compare/v0.4.3..v0.4.4

Upgrades zipkin library to avoid errors when using textMap.

---

docs/content/providers/consul-catalog.md
docs/content/reference/static-configuration/cli-ref.md
docs/content/reference/static-configuration/env-ref.md
docs/content/reference/static-configuration/file.toml
docs/content/reference/static-configuration/file.yaml
pkg/provider/consulcatalog/consul_catalog.go

Adds consul catalog options:
- requireConsistent
- stale
- cache
Closes  #5581

feat: add consul catalog options

---

docs/content/middlewares/replacepathregex.md

Add a double dollar sign on docker-compose example, because docker-compose would throw an error like this otherwise:
```
ERROR: Invalid interpolation format for "labels" option in service "my-service": "traefik.http.middlewares.test-replacepathregex.replacepathregex.regex=/bar/$1"
```
Avoid confusion when starting with Traefik and Docker

Double dollar on docker-compose config

---

traefik.sample.toml

Remove field api.entryPoint in traefik.sample.toml, though commented out.
ref: #5119

docs: remove field api.entryPoint

---

pkg/middlewares/ratelimiter/rate_limiter.go

While using long lasting SSE connections the mutex is not released
until the connection is closed. This caused rate limiter to throttle
any SSE endpoint to 1 service connection.
Replacing the defer call that releases the mutex by a direct call
at the appropriate location removes the contention.

Fix rate limiting and SSE

---

docs/content/routing/providers/kubernetes-crd.md

This snippet provided in that section uses 'web' as an endpoint instead of 'websecure'.

Wrong endpoint on the TLS secret example

---

docs/content/observability/metrics/statsd.md
docs/content/reference/static-configuration/cli-ref.md
docs/content/reference/static-configuration/env-ref.md
docs/content/reference/static-configuration/file.toml
docs/content/reference/static-configuration/file.yaml
pkg/metrics/statsd.go
pkg/metrics/statsd_test.go
pkg/types/metrics.go

We installed multiple instances of traefik for request seperation. To monitor our setup in a better way, we needed configurable statsd prefixes, so the metrics won't end up in one big bucket :)

Added configurable prefix for statsd metrics collection

---

docs/.markdownlint.json
docs/check.Dockerfile
docs/docs.Dockerfile
docs/requirements.txt

- Update docker base image of documentation tooling to Alpine 3.10 
- Install `html-proofer` using the native nokogiri Ruby gem thanks to Alpine 3.10 and its package `ruby-nokogiri`
- Bump `markdownlint` (and the CLI) versions
- Ignoring markdown rule MD046
- Bump mkdocs's dependencies updates
- Keep tooling clean and up to date
- Improve contributors "first experience", as switching to native nokogiri made the first image documentation build from ~45s to ~10s.

Update tooling used for documentation

---

docs/content/https/acme.md

Remove reference to KV storage for Traefik CE. Per https://github.com/containous/traefik/issues/5426

Update ACME storage docs to remove reference to KV store in CE

---

integration/consul_catalog_test.go
pkg/provider/consulcatalog/config.go
pkg/provider/consulcatalog/consul_catalog.go

This PR fixes an issue when a consul service is registered without an IP
Fixes #5811 

Fix empty address for registering service without IP

---

docs/content/contributing/submitting-security-issues.md
docs/mkdocs.yml

- Docs fixes
Docs: Add back the security section that was on the homepage from v1.7 docs
This docs was delete by accident when we merge from v1.7 to v2.0
That's my first PR over here :)

Add back the security section from v1
