traefik/traefik

- docs/content/middlewares/addprefix.md
- docs/content/middlewares/basicauth.md
- docs/content/middlewares/buffering.md
- docs/content/middlewares/circuitbreaker.md
- docs/content/middlewares/compress.md
- docs/content/middlewares/digestauth.md
- docs/content/middlewares/errorpages.md
- docs/content/middlewares/forwardauth.md
- docs/content/middlewares/headers.md
- docs/content/middlewares/ipwhitelist.md
- docs/content/middlewares/maxconnection.md
- docs/content/middlewares/overview.md
- docs/content/middlewares/passtlsclientcert.md
- docs/content/middlewares/ratelimit.md
- docs/requirements.txt
> Enhance middleware examples.

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/Bug_report.md
- README.md
- docs/content/getting-started/configuration-overview.md
Adds a note to the v2 docs about incompatible behaviour and adds a checkbox to the issue templates about that fact to check.
Make it clear
> Adds notes about incompatibility between 1.X and 2.X configurations.

- CHANGELOG.md
> Prepare release v2.0.0-alpha3.

- docs/content/middlewares/basicauth.md
- docs/content/middlewares/buffering.md
- docs/content/middlewares/compress.md
- docs/content/middlewares/digestauth.md
- docs/content/middlewares/errorpages.md
- docs/content/middlewares/overview.md
> fix: remove invalid commas.

- integration/simple_test.go
- pkg/middlewares/forwardedheaders/forwarded_header.go
- pkg/middlewares/forwardedheaders/forwarded_header_test.go
This PR adds the X-Forwarded headers to the proxied request.
Fixes #4659 
> Set X-Forwarded-* headers

- docs/content/middlewares/headers.md
- pkg/middlewares/headers/headers.go
This PR fixes the part about removing headers, in the website documentation about the Headers middleware.
Fixes #4667 
> Fix doc about removing headers

- pkg/tcp/router.go
Remove a wrong error log.
Fixes #4726
> Fix EOF error

- docs/content/observability/tracing.md
If I count correctly, these are four
Fix a typo in tracing documentation for 2.0.
> Fix typo in tracing docs

- docs/content/contributing/building-testing.md
- docs/content/getting-started/concepts.md
- docs/content/https-tls/acme.md
- docs/content/middlewares/addprefix.md
- docs/content/middlewares/basicauth.md
- docs/content/middlewares/buffering.md
- docs/content/middlewares/chain.md
- docs/content/middlewares/circuitbreaker.md
- docs/content/middlewares/compress.md
- docs/content/middlewares/digestauth.md
- docs/content/middlewares/errorpages.md
- docs/content/middlewares/forwardauth.md
- docs/content/middlewares/headers.md
- docs/content/middlewares/ipwhitelist.md
- docs/content/middlewares/maxconnection.md
- docs/content/middlewares/passtlsclientcert.md
- docs/content/middlewares/ratelimit.md
- docs/content/middlewares/redirectregex.md
- docs/content/middlewares/redirectscheme.md
- docs/content/middlewares/replacepath.md
- docs/content/middlewares/replacepathregex.md
- docs/content/middlewares/retry.md
- docs/content/middlewares/stripprefix.md
- docs/content/middlewares/stripprefixregex.md
Update the middleware documentation.
Have a middleware documentation up to date
> Update the middleware documentation

- .goreleaser.yml
Use the same pattern for checksum file and archives.
Be homogeneous
> Checksum file name.

- docs/content/middlewares/overview.md
- docs/content/reference/dynamic-configuration/kubernetes-crd.yml
Replace `middleware` by `middlewares` in IngressRoute definitions.
Fixes the documentation.
> doc: middleware -> middlewares.

- docs/content/providers/marathon.md
- docs/content/reference/static-configuration.txt
> Enhance Marathon documentation

- CHANGELOG.md
Prepare release v2.0.0-alpha4.
> Prepare release v2.0.0-alpha4.

- old/docs/user-guide/examples.md
It fixes a small typo in the examples documentation.
I saw a small typo in the [examples documentation](https://docs.traefik.io/user-guide/examples/) on your website so I tried to fix it.
Thanks for your review.
> Fix a typo in documentation

- docs/content/middlewares/overview.md
Compress link was pointing to circuit breaker doc
"Don’t Live with Broken Windows" (The Pragmatic Programmer)
> compress link fixed

- CHANGELOG.md
> Prepare release v1.7.11

- docs/content/middlewares/stripprefix.md
This PR fix strip prefix documentation
Correct documentation
> Fix strip prefix documentation

- docs/content/middlewares/overview.md
- docs/content/providers/docker.md
- docs/content/providers/kubernetes-crd.md
- docs/content/providers/marathon.md
- docs/content/providers/rancher.md
Adds a reference to the middleware overview.
> Adds a reference to the middleware overview.

- README.md
- docs/theme/main.html
- old/docs/theme/partials/footer.html
Re-introduces the pronunciation guide removed in https://github.com/containous/traefik/pull/3048 (See 426ce222fef468d02fa28033b46d1b4fa6d4d6cd).
Overhearing people talk about "Traffic" and "Trayfick" assuming they were different things.
I've raised this PR under the assumption that the project is _still_ pronounced "traffic". Feel free to amend if I'm incorrect!
> Clarification of the correct pronunciation of the word "Traefik"

- docs/content/routing/overview.md
Fixes small spelling mistake
Good docs!
> Fixed spelling typo

- docs/content/https-tls/acme.md
Adds a note about ACME renewal
Project Card
> Add note about ACME renewal

- provider/kv/kv_config.go
Give more context when an error occurs.
Enhance KV logs.
> Enhance KV logs.

- Gopkg.lock
- Gopkg.toml
- vendor/google.golang.org/api/dns/v1/dns-gen.go
- vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/ddtrace.go
- vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/ext/tags.go
- vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/opentracer/option.go
- vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/option.go
- vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/sampler.go
- vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/span.go
- vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/spancontext.go
- vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/textmap.go
- vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go
- vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/transport.go
- vendor/gopkg.in/DataDog/dd-trace-go.v1/internal/globalconfig/globalconfig.go
> Upgraded DataDog tracing library to 1.13.0

- cmd/storeconfig/storeconfig.go
- docs/content/getting-started/concepts.md
- docs/content/getting-started/quick-start.md
- docs/content/operations/cli.md
- docs/content/providers/docker.md
- docs/content/providers/overview.md
- docs/content/routing/overview.md
- docs/content/routing/routers/index.md
Fix typos in documentation.
n/a
n/a
> Fix typos in documentation

- webui/readme.md
This pull request is fixing misspelling in the readme of the webui.  
Better language in the documentation will make the project look more professional.
> Fixed readme misspelling

- docs/content/providers/docker.md
documentation remove traefik.port.
> documentation remove traefik.port.

- docs/configuration/logs.md
Adds a log fields documentation.
Extracted from #4162
> Adds a log fields documentation.

- cmd/traefik/traefik.go
This PR fixes a couple of grammar errors in the message about anonymous data collection.
> Fix typos in data collection message

- Gopkg.lock
- vendor/github.com/vulcand/oxy/forward/fwd.go
Updates oxy dependency
Fixes https://github.com/containous/traefik/issues/4864
> Add missing callback on close of hijacked connections

- types/types.go
Remove authentication hashes from API.
Fixes #4917
> Remove authentication hashes from API

- CHANGELOG.md
> Prepare release v1.7.12

- docs/configuration/api.md
Improve wording and description of the documentation page "API/Dashboard".
Because a better documentation is a must-have.
> Improve API / Dashboard wording in documentation

- docs/content/middlewares/ratelimit.md
Fix an error in the file provider example in the documentation on rate-limiting middleware.
Save others some time ;)
> Correct typo in documentation on rate limiting

- docs/content/contributing/maintainers.md
This PR adds [Mathieu Lonjaret](https://github.com/mpl) to the maintainers team.
Welcome @mpl 👏 
@mpl is now ready to serve the values and principles of our reverse-proxy ⚔️ 🛡
> Add Mathieu Lonjaret to maintainers

- docs/content/middlewares/chain.md
- docs/content/providers/docker.md
- docs/content/providers/marathon.md
- docs/content/providers/rancher.md
fix misleading docs
irritation ;)
I'm not tracking the project closely. There may be some unknown intent, here?
> change doc references to scheme[Rr]edirect -> redirect[Ss]cheme

- script/deploy.sh
fix: deploy script.
Fix regression from #4859
> fix: deploy script.

- script/deploy.sh
fix: deploy script.
Fix regression from #4859
> fix: revert deploy script.

- docs/content/middlewares/compress.md
- docs/content/middlewares/stripprefix.md
- docs/content/middlewares/stripprefixregex.md
- pkg/config/middlewares.go
Fixes middleware names for CRD.
> doc: fix middleware names for CRD.

- docs/content/middlewares/maxconnection.md
- docs/content/middlewares/ratelimit.md
- docs/content/middlewares/stripprefixregex.md
Fixes some Kubernetes CRD documentation.
I missed these in the previous PR, sorry.
> Kubernetes CRD documentation fixes

- docs/content/user-guides/crd-acme/k3s.yml
- integration/resources/compose/k8s.yml
This PR upgrades k3s version for k8s integration tests.
Be update to date.
Thanks to @ldez for his help ;)
> Upgrade k3s version

- docs/content/reference/static-configuration/cli.txt
- docs/content/reference/static-configuration/env.md
- pkg/cli/commands.go
- pkg/config/static/static_config.go
- fix: allow --log.
- fix: help flag. 
Fix some bugs
> Fix some CLI bugs

- docs/content/observability/logs.md
- docs/content/routing/entrypoints.md
- docs/content/routing/routers/index.md
Improve some parts of the documentation.
Fixes #4995
> Improve some parts of the documentation.

- docs/configuration/backends/rancher.md
> Add remarks about Rancher 2

- docs/content/middlewares/overview.md
Improves examples to show that a middleware needs to be referenced by a router.
> Improve middleware documentation.

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- README.md
- docs/content/contributing/maintainers.md
- docs/content/contributing/submitting-issues.md
Switch the following elements from Slack to Discourse:
- Badges and links on the documentation's homepage
- Links in Github templates about community
With the Community Support moving to Discourse, we want our users to use the right website.
> Update Slack support channel references to Discourse community forum

- pkg/provider/docker/config.go
- pkg/provider/marathon/config.go
- pkg/provider/rancher/config.go
Fix the error log message for when an error occurs in the constraint parser.
To have a good log message.
> fix: error log message.

- docs/content/https/acme.md
- docs/content/providers/docker.md
- docs/content/providers/kubernetes-crd.md
- docs/content/providers/marathon.md
- docs/content/providers/rancher.md
- docs/content/providers/rancher.txt
- docs/content/providers/rancher.yml
- docs/content/routing/entrypoints.md
- docs/content/routing/overview.md
Improve providers documentation.
> Improve providers documentation.

- docs/user-guide/examples.md
Fixes YAML formatting for Docker Compose examples in order to make it easier to copy-paste in a docker-compose.yml file.
The example YAML files are wrongly formatted that may lead errors for people who copy-paste the example, not familiar with Docker Compose, ...
> Format YAML example on user guide

- integration/fixtures/headers/basic.toml
- integration/fixtures/headers/cors.toml
- integration/headers_test.go
- integration/resources/compose/headers.yml
- integration/try/condition.go
- pkg/middlewares/headers/headers.go
- pkg/middlewares/headers/headers_test.go
- pkg/responsemodifiers/headers.go
Reworks the response header handling for the new v2 middleware chain handling
fixes #4825, #4979
> Properly add response headers for CORS

- build.Dockerfile
- docs/content/contributing/building-testing.md
This PR updates dep version to version 0.5.4
Be up-to-date
> Update dep version

- .semaphoreci/setup.sh
- build.Dockerfile
This PR updates docker version for build system.
Be up-to-date.
> Update docker version for build

- integration/rest_test.go
- integration/simple_test.go
- pkg/config/dynamic/config.go
- pkg/provider/rest/rest.go
- pkg/server/server_configuration.go
Adds TCP/TLS parsing to the rest provider so that TCP/TLS configurations can be posted.
API Control of Traefik v2
> Enhance REST provider

- .semaphoreci/setup.sh
- build.Dockerfile
Update Docker version.
Be homogeneous with v2.0 branch, required by the CI.
> Update Docker version.

- .semaphoreci/setup.sh
- build.Dockerfile
The name of the package has been changed since 18.09.0
https://download.docker.com/linux/static/stable/x86_64/
Be able to build.
> Docker URL

- docs/content/user-guides/crd-acme/03-deployments.yml
Fixes a mistake in the deployment definition.
Fixes #5094
> user guide: fix a mistake in the deployment definition

- docs/content/observability/tracing/datadog.md
- docs/content/observability/tracing/haystack.md
- docs/content/observability/tracing/instana.md
- docs/content/observability/tracing/jaeger.md
- docs/content/observability/tracing/overview.md
- docs/content/observability/tracing/zipkin.md
This PR adds YAML part for tracing documentation
> Improve tracing documentation

- docs/content/getting-started/install-traefik.md
- docs/mkdocs.yml
Enhance the documentation with a basic Traefik install guide.
Have a useful documentation.
> Add a basic Traefik install guide

- docs/content/providers/kubernetes-crd.md
- docs/content/providers/kubernetes-ingress.md
- docs/mkdocs.yml
This PR adds the documentation page about the Kubernetes Ingress provider.
That page was missing.
- ~[] Added/updated tests~
> Add documentation about Kubernetes Ingress provider

- docs/content/https/acme.md
Fix a typo
Better doc, better life!
> Lets encrypt documentation typo

- integration/testdata/rawdata-crd.json
- pkg/api/handler_overview.go
- pkg/api/handler_overview_test.go
- pkg/api/testdata/getrawdata.json
- pkg/api/testdata/middleware-auth.json
- pkg/api/testdata/middlewares-page2.json
- pkg/api/testdata/middlewares.json
- pkg/config/runtime/runtime.go
- pkg/server/middleware/middlewares.go
- pkg/server/router/router.go
- pkg/server/router/tcp/router.go
- pkg/server/router/tcp/router_test.go
- pkg/server/service/tcp/service.go
Improve error on router without service.
Improve error on router without service.
> Improve error on router without service.

- docs/content/middlewares/overview.md
> Fixed a typo in label.

- CHANGELOG.md
> Prepare release v2.0.0-beta1

- docs/content/https/acme.md
Fixes a wrong header in tabbed view. Second Tab is for YAML-file, not TOML
> Fix acme example

- docs/content/routing/routers/index.md
Adds backticks around the content in the method rule documentation
Missing backticks lead to parsing errors in the log.
> Fix malformed rule

- pkg/metrics/prometheus.go
This PR fix an issue where Prometheus metrics where collected multiple times.
Be able to collect Prometheus metrics correctly
> Fix prometheus metrics

- docs/configuration/backends/servicefabric.md
Updates Service Fabric's documentation.
To ensure no one else waste time dealing with an issue like https://github.com/containous/traefik/issues/5145
Fixes #5145
> Updating Service Fabric documentation

- CHANGELOG.md
> Prepare release v1.7.13

- CHANGELOG.md
> Prepare release v1.7.14

- go.mod
- go.sum
Fixes lego version.
Due to an error with the tag v3.0.1, the previous tag is replaced by v3.0.2
> fix: lego version.

- .golangci.toml
- .semaphoreci/golang.sh
- .semaphoreci/setup.sh
- build.Dockerfile
- cmd/traefik/traefik.go
- docs/content/contributing/building-testing.md
- exp.Dockerfile
- go.mod
- integration/fixtures/https/clientca/https_2ca1config.toml
- integration/fixtures/https/clientca/https_2ca2config.toml
- integration/https_test.go
- integration/integration_test.go
Updates to go1.13rc1
Be ready.
> Update to go1.13rc1

- docs/content/migration/v1-to-v2.md
- docs/content/migration/v1.7-to-v2.md
- docs/mkdocs.yml
Start a Migration Guide from Traefik v1 to Traefik v2.
Help users migrate from the previous major version.
> Base of the migration guide

- provider/kubernetes/kubernetes.go
It adds a bit to the kubernetes provider that was forgotten when refactoring for bee370ec6be6bd6192faf1a3a91350d99ba3838a
Without it, I think we can end up trying to use a nil channel, so bad things would probably ensue.
> Finish kubernetes throttling refactoring

- docs/content/contributing/data-collection.md
- docs/content/https/tls.md
- docs/content/operations/api.md
Update restrictions in the documentation.
> Update restrictions in the documentation.

- docs/content/middlewares/basicauth.md
- docs/content/middlewares/circuitbreaker.md
- docs/content/middlewares/compress.md
- docs/content/middlewares/errorpages.md
- docs/content/middlewares/headers.md
- docs/content/middlewares/inflightreq.md
- docs/content/middlewares/ipwhitelist.md
- docs/content/middlewares/passtlsclientcert.md
- docs/content/middlewares/ratelimit.md
- docs/content/providers/docker.md
- docs/content/providers/file.md
- docs/content/routing/routers/index.md
- docs/content/user-guides/marathon.md
Fix some documentation issues like:
* ambiguous elements
* typo
* bad examples
* wrong information
> Fix some documentation issues

- CHANGELOG.md
Prepare release v2.0.0-rc2
aka `montdor` (Mont d'Or)
> Prepare release v2.0.0-rc2

- .semaphoreci/setup.sh
- build.Dockerfile
- docs/content/contributing/building-testing.md
- exp.Dockerfile
This PR updates go to version 1.13
Be up-to-date
> Update to go 1.13

- docs/content/observability/access-logs.md
- docs/content/providers/docker.md
- docs/content/providers/marathon.md
- docs/content/routing/routers/index.md
This PR fixes some documentation mistakes.
Having the best doc in the world.
> misc documentation fixes

- pkg/provider/kubernetes/crd/kubernetes_http.go
- pkg/provider/kubernetes/crd/kubernetes_tcp.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroute.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroutetcp.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
fix: TLS domains with IngressRoute.
Be able to get wildcard certificates with k8s.
> fix: TLS domains with IngressRoute.

- CHANGELOG.md
> Prepare release v1.7.16

- CHANGELOG.md
Prepare release v2.0.0-rc4
aka `montdor` (Mont d'Or)
> Prepare release v2.0.0-rc4

- webui/quasar.conf.js
- webui/src/components/dashboard/PanelEntry.vue
> Web UI graph names.

- docs/content/https/acme.md
Fix an error in the CLI configuration example, in the https/acme section.
Avoid an error while copy/past the configuration example
> Fix error in the documentation for CLI configuration example

- docs/configuration/entrypoints.md
- docs/index.md
- docs/user-guide/cluster-docker-consul.md
- docs/user-guide/docker-and-lets-encrypt.md
- docs/user-guide/kubernetes.md
- docs/user-guide/kv-config.md
- examples/compose-rancher.yml
- examples/compose-traefik.yml
- examples/k8s/traefik-deployment.yaml
- examples/k8s/traefik-ds.yaml
- examples/quickstart/README.md
- examples/quickstart/docker-compose.yml
- webui/.gitignore
Update Traefik image version.
Fixes #5398
> Update Traefik image version.

- docs/content/migration/v1-to-v2.md
Add some content to the migration guide v1 to v2
> Improve the Migration Guide

- docs/content/user-guides/crd-acme/index.md
Fix a typo for the kubectl version in the user guide for IngressRoute with ACME.
https://community.containo.us/t/minimum-required-k8s-version-for-traefik-2-0/1661
> fix typo for kubectl version

- .travis.yml
- CONTRIBUTING.md
- README.md
- cmd/traefik/traefik.go
- contrib/systemd/traefik.service
- examples/quickstart/README.md
- webui/src/app/components/header/header.component.html
Update docs links.
Be able to validate the doc link during the build on the CI.
> Update docs links.

- docs/content/migration/v1-to-v2.md
Fixes a wrong indentation for tab `tracing` -> `info v2` ->  `yaml`.
Migrate to v2. 😉 
nope 😅
> fix indentation for tab on migration guide

- docs/content/operations/api.md
This PR fixes a couple of mistakes in the doc page about the API.
> fixed doc typoes

- docs/content/operations/dashboard.md
This PR clarifies that the dashboard is served at /dashboard and that / is actually a redirect to it.
> document that /dashboard should be preferred over /

- docs/content/https/acme.md
- docs/content/migration/v1-to-v2.md
> Wrong acme example.

- docs/content/migration/v1-to-v2.md
Fix a typo in example TOML file for HTTP to HTTPS redirection
I ran into problem following the example.
> fix: typo in TOML for HTTP to HTTPS redirection

- docs/content/routing/providers/kubernetes-crd.md
This PR adds some indentation, because Markdown.
To keep on having the best and most beautiful doc in the world.
> add indent to fix notes

- CHANGELOG.md
> Prepare release v1.7.17

- docs/content/middlewares/headers.md
- go.mod
- go.sum
Updates the `unrolled/secure` dependency to update casing on the STS Header directives
Fixes #5323
> Update Casing on STS Header Directive

- docs/content/reference/static-configuration/cli-ref.md
- docs/content/reference/static-configuration/env-ref.md
- pkg/provider/file/file.go
Add the right doc about `file.filename`
Have a better documentation
> fix doc about file.filename

- pkg/server/middleware/middlewares.go
Improve log for invalid middleware.
` middleware "xxx" does not exist` is ambiguous in some cases.
> fix: improve log for invalid middleware.

- docs/content/routing/providers/docker.md
- docs/content/routing/providers/marathon.md
- docs/content/routing/providers/rancher.md
- docs/content/routing/routers/index.md
Add the priority attribute documentation with examples to explain the mechanism.
Have a documentation up to date
Close #5301
> Add the router priority documentation

- CHANGELOG.md
> Prepare release v1.7.18

- CHANGELOG.md
This PR prepares the v2.0.1 release.
> Prepare release v2.0.1

- docs/content/migration/v1-to-v2.md
> Change instances of "dymanic" to "dynamic"

- pkg/middlewares/metrics/recorder.go
Check type assertion.
Fixes #5532
> fix: panic with metrics recorder.

- docs/content/routing/overview.md
This PR describes the serversTransport option in the documentation.
> document serversTransport

- pkg/config/file/raw_node.go
- pkg/config/file/raw_node_test.go
fix: return an error instead of panic.
Don't panic.
> fix: return an error instead of panic.

- docs/content/providers/overview.md
This PR describes the providers.providersThrottleDuration option in the documentation.
> document providersThrottleDuration

- docs/content/middlewares/headers.md
Typo in documentation that might cause issues in validating headers.
Just corrected the typo.
I used the yaml example  and got some issues with validating the headers. The dashboard only indicated the failing header and it took me a while to figure out which part of the header was failing.
> Typo in documentation

- docs/content/routing/routers/index.md
Fix the example
I was frustrated why the example did not work.
> Fix yaml domains example

- docs/content/observability/metrics/prometheus.md
> typo in cli command

- docs/content/middlewares/overview.md
In the middleware documentation, the Kubernetes example scope of the services and middlewares is misaligned and thus, ignored by the route match.
The example is wrong and does not work.
Full example with middlewares here https://github.com/Thoorium/kubernetes-local-cluster-flannel-metallb-traefik/blob/master/cheese/cheese-ingress.yaml
> Update scope of services and middlewares

- pkg/provider/kubernetes/crd/client.go
> Fix typo in log

- docs/content/providers/file.md
Enhance the documentation of the file provider and state that the `directory` and `filename` are mutual exclusive.
Ran into a problem, asked in the forum and [was asked to create a PR](https://community.containo.us/t/directory-and-filename-not-working-together/1959/2).
> State clearly, that they are mutual exclusive

- .golangci.toml
- build.Dockerfile
- pkg/job/job_test.go
- pkg/safe/routine_test.go
- pkg/tracing/tracing.go
Update linter
Reduces memory consumption of the linter.
> ci: reduce memory consumption of the linter

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
doc: update issues and PRs templates.
Improve issues quality.
> doc: update issues and PRs templates.

- go.mod
- go.sum
- integration/fixtures/tracing/simple-jaeger.toml
- integration/resources/compose/tracing.yml
- integration/tracing_test.go
This Pr updates jaeger dependency and adds a new integration test for custom header trace
Be update to date
> Update jaeger dependencies

- docs/content/migration/v1-to-v2.md
- docs/content/providers/consul-catalog.yml
- docs/content/providers/overview.md
This PR fix documentation for consul catalog
Have a correct documentation
- ~[] Added/updated tests~
> Fix consul catalog documentation

- pkg/provider/acme/provider.go
Fix spelling mistake in debug messages in ACME system
Hacktoberfest
> Fix spelling mistake: "founded" -> "found"

- docs/content/migration/v1-to-v2.md
This PR is to fix typo in Strip Path Prefix When Forwarding to Backend.
I just want to give little contribution for traefik v2 documentation.
> fix typo for stripPrefix in tab File (YAML)

- examples/k8s/traefik-ds.yaml
Ref https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals
> Update DaemonSet apiVersion

- pkg/server/server_entrypoint_tcp.go
This PR force the debug log to DEBUG for proxyprotocol
Fixes #5697
> Set proxy protocol logger to DEBUG level

- pkg/config/dynamic/zz_generated.deepcopy.go
```
make generate-crd
```
fix: deep copy of passHostHeader on ServersLoadBalancer.
> fix: deep copy of passHostHeader on ServersLoadBalancer.

- pkg/provider/kubernetes/crd/kubernetes.go
- pkg/provider/kubernetes/ingress/kubernetes.go
Remove unnecessary reload of the configuration.
Fixes #5696
> Remove unnecessary reload of the configuration.

- script/binary
Fix Version, Date and Codename not being overwritten during build.
> Fix ldflags using incorrect pkg url

- docs/content/operations/.markdownlint.json
- docs/content/operations/api.md
- docs/content/operations/dashboard.md
Update documentation for API and Dashboard sections in "Operations".
Helping new users to get from zero to a secured dashboard with a better understanding of the  routing configuration in v2.
Nope
> Improve documentation of the router rules for API and dashboard

- docs/content/providers/docker.md
- docs/content/routing/providers/docker.md
- docs/content/routing/providers/marathon.md
- docs/content/routing/providers/rancher.md
- docs/content/routing/providers/service-by-label.md
- docs/content/routing/routers/index.md
- docs/content/routing/services/index.md
`@` is not authorized in names definition.
Closes #5733
> doc: @ is not authorized in names definition.

- pkg/server/server.go
Fix wrong invalid scope for the default tracing backend.
fix default tracing backend.
> fix: default tracing backend.

- CHANGELOG.md
> Prepare release v1.7.19

- docs/content/routing/providers/docker.md
- docs/content/routing/services/.markdownlint.json
- docs/content/routing/services/index.md
Adds an example doc and some clarification around the loadbalancer service.
I read the docs for days trying to figure how to specify the port traefik should use to connect to the container. It wasn't clear how to do `traefik.port=1234` in v2.
> Add example for changing the port used by traefik to connect to a service

- docs/content/routing/providers/docker.md
Fix a typo in routing documentation for Docker after #5224.
User comment: https://github.com/containous/traefik/pull/5224#pullrequestreview-307934426
> Fix a typo in routing documentation for Docker

- CHANGELOG.md
This PR prepares the v2.0.3 release.
> Prepare release v2.0.3

- docs/content/contributing/building-testing.md
Adds `go-bindata` as requirement.
Fixes #5770
> Improve building documentation

- docs/content/operations/api.md
- docs/content/operations/dashboard.md
> Adds missed quotes in api.md

- README.md
Self explanatory 
Going to the wrong page 😢 
> Fix quickstart link in README

- docs/content/routing/services/index.md
> slashes ended up in bad place.

- pkg/metrics/prometheus.go
- pkg/metrics/prometheus_test.go
Excludes non server LB from metrics.
Fixes #5755
> fix: metric with services LB.

- exp.Dockerfile
Use alpine for v2 experimental images.
Be able to run a shell inside the experimental image.
> Use alpine for v2 experimental images.

- docs/content/migration/v1-to-v2.md
Fixes a simple typo in the v1-to-v2 migration guide.
We all love clean documentation, right?! ;)
Thanks for all your effort :) Traefik is awesome :heart:
> fix typo in v1 to v2 migration guide

- CHANGELOG.md
This PR prepares the v2.0.5 release.
> Prepare release v2.0.5

- docs/content/routing/routers/index.md
> Fixed spelling error

- go.mod
- go.sum
Update [unrolled/secure](https://github.com/unrolled/secure)
Fix #5807
Co-authored-by: Daniel Tomcej <daniel.tomcej@gmail.com>
> fix: location header rewrite.

- docs/content/routing/routers/index.md
> doc: fix wrong acme information

- integration/testdata/rawdata-ingress.json
- pkg/provider/traefik/fixtures/api_insecure_with_dashboard.json
- pkg/provider/traefik/fixtures/api_insecure_without_dashboard.json
- pkg/provider/traefik/fixtures/full_configuration.json
- pkg/provider/traefik/fixtures/ping_simple.json
- pkg/provider/traefik/fixtures/prometheus_simple.json
- pkg/provider/traefik/fixtures/rest_insecure.json
- pkg/provider/traefik/internal.go
use MaxInt32.
Temporary fix for 32bits arch.
> fix: use MaxInt32.

- CHANGELOG.md
Prepare release v2.1.0-rc2
aka `cantal`
> Prepare release v2.1.0-rc2

- webui/src/_services/HttpService.js
- webui/src/_services/TcpService.js
Avoid unnecessary duplicated api calls
All paginated api calls where duplicated fetching all resources before fetching the paginated one.
> Web UI: Avoid unnecessary duplicated api calls

- webui/package-lock.json
- webui/package.json
- webui/src/_helpers/Errors.js
- webui/src/components/_commons/MainTable.vue
- webui/src/components/_commons/TLSState.vue
- webui/src/index.template.html
- webui/src/pages/http/Middlewares.vue
- webui/src/pages/http/Routers.vue
- webui/src/pages/http/Services.vue
- webui/src/pages/tcp/Routers.vue
- webui/src/pages/tcp/Services.vue
- webui/src/store/http/actions.js
- webui/src/store/http/mutations.js
- webui/src/store/tcp/actions.js
- webui/src/store/tcp/mutations.js
Handle pagination with infinite scrolling
Give a modernest feeling browsing large lists
> Web UI: Table infinite scroll

- docs/content/getting-started/install-traefik.md
This PR adds a section for Helm installation in the documentation, tagged as "experimental".
We have an experimental helm chart, and we should give awareness during the "testing/building" time of it.
> Mention the experimental Helm Chart in the installation section of documentation

- integration/consul_catalog_test.go
- integration/resources/compose/consul_catalog.yml
- pkg/provider/consulcatalog/config.go
- pkg/provider/consulcatalog/config_test.go
- pkg/provider/consulcatalog/consul_catalog.go
This PR fix an issue when a service is registered with the same name and id on different consul nodes
Fixes #5850 
> Service registered with same id on Consul Catalog

- docs/content/routing/providers/docker.md
- docs/content/routing/providers/marathon.md
- docs/content/routing/providers/rancher.md
Fixes problem described in [comment 545077143](https://github.com/containous/traefik/issues/5506#issuecomment-545077143) and [comment 549100716](https://github.com/containous/traefik/issues/5506#issuecomment-549100716) which can be mislead users.
Updates docker.md
[comment 545077143](https://github.com/containous/traefik/issues/5506#issuecomment-545077143)
[comment 549100716](https://github.com/containous/traefik/issues/5506#issuecomment-549100716)
> Update router entrypoint example

- integration/fixtures/healthcheck/multiple-routers-one-same-service.toml
- integration/healthcheck_test.go
- pkg/healthcheck/healthcheck.go
- pkg/server/service/service.go
Iterates on all health check load balancers to apply the status from servers.
Fixes #5231 
> Healthcheck managed for all related services

- pkg/cli/commands.go
- pkg/cli/commands_test.go
- pkg/cli/loader_file.go
This PR allows specifying a custom help template for commands and subcommands using the `traefik/v2/pkg/cli` package.
> Add custom help function to command

- CHANGELOG.md
This PR prepares the v2.0.6 release.
> Prepare release v2.0.6

- CHANGELOG.md
This PR prepares the v2.1.0-rc3 release.
> Prepare release v2.1.0-rc3

- CHANGELOG.md
This PR prepares the v2.0.7 release.
> Prepare release v2.0.7

- CHANGELOG.md
- README.md
- docs/check.Dockerfile
- docs/content/https/.markdownlint.json
- docs/content/https/acme.md
- docs/content/https/include-acme-multiple-domains-example.md
- docs/content/https/include-acme-multiple-domains-from-rule-example.md
- docs/content/https/include-acme-single-domain-example.md
- docs/content/index.md
- docs/content/middlewares/passtlsclientcert.md
- docs/content/migration/v1-to-v2.md
- docs/content/operations/dashboard.md
- docs/content/providers/file.md
- docs/content/providers/kubernetes-crd.md
- docs/content/providers/kubernetes-ingress.md
- docs/content/routing/overview.md
- docs/content/routing/providers/marathon.md
- docs/content/user-guides/grpc.md
- docs/mkdocs.yml
- pkg/middlewares/passtlsclientcert/pass_tls_client_cert.go
- pkg/middlewares/passtlsclientcert/pass_tls_client_cert_test.go
- pkg/server/server_entrypoint_tcp.go
- pkg/server/service/loadbalancer/mirror/mirror.go
- pkg/tls/certificate.go
Merge current v2.0 branch into v2.1
Be sync.
> Merge current v2.0 branch into v2.1

- docs/content/operations/ping.md
- docs/content/routing/services/index.md
- add k8s for weighted and mirroring.
- fix header level. 
> Several documentation fixes

- webui/src/_services/HttpService.js
- webui/src/_services/TcpService.js
- webui/src/_services/utils.js
- webui/src/index.template.html
Use `X-Next-Page` response header to know if there is a next page or not
Fixes #5959
> Fix http/tcp resources pagination

- CHANGELOG.md
> Prepare release v1.7.20

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
Prepare release v2.1.0
aka `cantal`
> Prepare release v2.1.0

- docs/content/contributing/building-testing.md
Improve documentation about Traefik build.
#6015, #5936, #5934
> Improve documentation about Traefik build.

- CHANGELOG.md
Prepare release v2.1.1
aka `cantal`
> Prepare release v2.1.1

- docs/content/https/acme.md
- docs/content/https/include-acme-multiple-domains-from-rule-example.md
- docs/content/https/include-acme-single-domain-example.md
- docs/content/https/ref-acme.toml
- docs/content/https/ref-acme.txt
- docs/content/https/ref-acme.yaml
Use consistent name in ACME documentation
Fixes #6018
> Use consistent name in ACME documentation

- docs/content/contributing/building-testing.md
Remove section about templates.
Have better documentation
> doc: remove section about templates

- go.mod
- go.sum
jaeger: Malformed x-b3-traceid Header
Fix #5842
> fix: Malformed x-b3-traceid Header

- pkg/config/file/file_node.go
- pkg/config/file/file_node_test.go
- pkg/config/file/fixtures/no_conf.toml
Improves error message when a configuration file is empty.
Related to #6062
> Improves error message when a configuration file is empty.

- CHANGELOG.md
Prepare release v2.1.2
aka `cantal`
> Prepare release v2.1.2

- docs/content/user-guides/docker-compose/basic-example/index.md
Fix small typo in **user-guides** documentation
> Fix small typo in user-guides documentation

- docs/user-guide/kubernetes.md
- examples/k8s/traefik-deployment.yaml
Update the Deployment API version in the documentation.
Fixes #6075
> Update the k8s api version in the documentation

- .golangci.toml
- build.Dockerfile
Update golangci-lint version.
Update golangci-lint version.
> Update golangci-lint version.

- docs/content/getting-started/install-traefik.md
- docs/content/migration/v1-to-v2.md
Adds an explanation of the global redirection pattern.
> doc: adds an explanation of the global redirection pattern.

- CHANGELOG.md
Prepare release v2.1.3
aka `cantal`
> Prepare release v2.1.3

- cmd/traefik/traefik.go
Improvement if the certificates resolvers logs
Have a clear error message.
> Improvement of the certificates resolvers logs

- docs/content/https/include-acme-multiple-domains-example.md
- docs/content/https/include-acme-multiple-domains-from-rule-example.md
- docs/content/https/include-acme-single-domain-example.md
Adds missing certResolver in IngressRoute examples.
Have a better documentation
> Add missing certResolver in IngressRoute examples.

- README.md
> readme: update links to use HTTPS

- docs/content/middlewares/overview.md
> Minor documentation tweaks.

- pkg/server/configurationwatcher.go
Properly purge the certificate contents from providers before logging
Clean logging
> Properly purge default certificate from stores before logging

- CHANGELOG.md
Prepare release v2.1.4
aka `cantal`
> Prepare release v2.1.4

- docs/configuration/commons.md
Expand a bit on the meaning of the configuration parameters for rate-limiting.
Fixes #4549 
> Improve rate-limiting doc

- docs/content/index.md
Added link to community forum.
> Added link to community forum

- webui/quasar.conf.js
Development is easier now since dev can work with native Traefik API from dev mode.
I wanted to do some improvements to web UI and noticed that I've got API call errors.
> Proxy API to Traefik in dev mode

- integration/consul_test.go
- integration/etcd_test.go
- integration/redis_test.go
- integration/zk_test.go
Correction of tests by inserting data into the KV before starting the tests.
Kill flaky tests.
> fix: KV flaky tests.

- docs/content/middlewares/overview.md
> Fix formatting in "Kubernetes Namespace" block

- pkg/provider/kubernetes/crd/kubernetes_http.go
Use the right error in the log.
fixes #6275
> fix: use the right error in the log

- cmd/traefik/traefik.go
- docs/content/getting-started/configuration-overview.md
- docs/content/getting-started/install-traefik.md
- docs/content/getting-started/quick-start.md
- docs/content/https/acme.md
- docs/content/https/include-acme-multiple-domains-example.md
- docs/content/https/include-acme-multiple-domains-from-rule-example.md
- docs/content/https/include-acme-single-domain-example.md
- docs/content/https/ref-acme.toml
- docs/content/https/ref-acme.txt
- docs/content/https/ref-acme.yaml
- docs/content/middlewares/redirectscheme.md
- docs/content/migration/v1-to-v2.md
- docs/content/providers/docker.md
- docs/content/providers/kubernetes-ingress.md
- docs/content/user-guides/crd-acme/03-deployments.yml
- docs/content/user-guides/crd-acme/04-ingressroutes.yml
- docs/content/user-guides/crd-acme/k3s.yml
- docs/content/user-guides/docker-compose/acme-dns/docker-compose.yml
- docs/content/user-guides/docker-compose/acme-dns/docker-compose_secrets.yml
- docs/content/user-guides/docker-compose/acme-dns/index.md
- docs/content/user-guides/docker-compose/acme-http/docker-compose.yml
- docs/content/user-guides/docker-compose/acme-http/index.md
- docs/content/user-guides/docker-compose/acme-tls/docker-compose.yml
- docs/content/user-guides/docker-compose/acme-tls/index.md
- docs/content/user-guides/docker-compose/basic-example/docker-compose.yml
- fix non consistent traefik version.
- improve example of resolver names. 
- fix some hard link to the doc.
- semantic line breaks
- improve redirectScheme doc.
Fixes #6326
Related to #6322
> Improve documentation.

- docs/content/operations/include-api-examples.md
dashboard example with k8s CRD.
> fix: dashboard example with k8s CRD.

- docs/content/providers/file.md
Add information about filename and directory options.
> Add information about filename and directory options.

- CHANGELOG.md
> Prepare release v1.7.21

- h2c/h2c.go
- Fix memory leak caused by addition of hijacked h2c connections to managed list, but never evicting them.
- Fix redundant wait period during shutdown when h2c connections have been established.
- Remove redundant error logs during shutdown when h2c connections have been established.
Memory leak noticed In a scenario where grpc connections are established via Traefik repeatedly.
By using pprof heap analysis, it is evident that `hijackConnectionTracker` memory consumption keeps increasing as long as Traefik stays up.
See image for example:
Also, since h2c hijacked connections are closed properly by Traefik after the connection is served, errors are logged when `hijackConnectionTracker` attempts to close these connections again during shutdown (after waiting for the full grace period):
``` …
```
> Clear closed hijacked h2c connections

- docs/content/providers/file.md
fix: YML example of template for the file provider.
> fix: YML example of template for the file provider.

- CHANGELOG.md
- docs/content/reference/static-configuration/cli-ref.md
- docs/content/reference/static-configuration/env-ref.md
Prepare release v2.1.6
aka `cantal`
> Prepare release v2.1.6

- pkg/middlewares/replacepath/replace_path.go
- pkg/middlewares/replacepath/replace_path_test.go
- pkg/middlewares/replacepathregex/replace_path_regex.go
- pkg/middlewares/replacepathregex/replace_path_regex_test.go
Added support for replacement containing escaped characters
Fixes #6355
> Added support for replacement containing escaped characters

- .dockerignore
- build.Dockerfile
- pkg/tracing/elastic/elastic.go
Disable default APM tracer.
Remove unwanted requests.
> Disable default APM tracer.

- docs/content/https/include-acme-multiple-domains-example.md
Added missing wildcard ACME setting to https acme configuration
examples. Thanks to https://community.containo.us/t/wildcard-cert-from-lets-encrypt/1978/4
I think this belongs in the documentation, not only to the community forums.
> Added wildcard ACME example

- docs/content/https/acme.md
- docs/content/https/include-acme-multiple-domains-example.md
- docs/content/providers/docker.md
- docs/content/reference/static-configuration/cli-ref.md
- docs/content/reference/static-configuration/env-ref.md
- pkg/config/dynamic/zz_generated.deepcopy.go
- pkg/metrics/datadog.go
- pkg/metrics/influxdb.go
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/metrics/prometheus.go
- pkg/metrics/statsd.go
- pkg/middlewares/metrics/metrics.go
- pkg/middlewares/replacepath/replace_path.go
- pkg/middlewares/replacepath/replace_path_test.go
- pkg/middlewares/replacepathregex/replace_path_regex.go
- pkg/middlewares/replacepathregex/replace_path_regex_test.go
- pkg/provider/docker/docker.go
Merge current v2.1 branch into master
Be sync.
> Merge current v2.1 branch into master

- .github/PULL_REQUEST_TEMPLATE.md
- .semaphoreci/vars
- .travis.yml
- docs/content/getting-started/install-traefik.md
- docs/content/getting-started/quick-start.md
- docs/content/migration/v1-to-v2.md
- docs/content/providers/docker.md
- docs/content/providers/kubernetes-ingress.md
- docs/content/routing/providers/kubernetes-crd.md
- docs/content/user-guides/crd-acme/03-deployments.yml
- docs/content/user-guides/crd-acme/k3s.yml
- docs/content/user-guides/docker-compose/acme-dns/docker-compose.yml
- docs/content/user-guides/docker-compose/acme-dns/docker-compose_secrets.yml
- docs/content/user-guides/docker-compose/acme-http/docker-compose.yml
- docs/content/user-guides/docker-compose/acme-tls/docker-compose.yml
- docs/content/user-guides/docker-compose/basic-example/docker-compose.yml
> Update version references.

- docs/readme.md
I'm sorry, if this is the wrong branch. :grimacing:
> Fix broken documentation link

- provider/label/label.go
- provider/label/label_test.go
- provider/label/partial.go
- provider/label/partial_test.go
Skip redirection with invalid regex syntax.
Fixes #6431
> Skip redirection with invalid regex syntax.

- docs/content/routing/providers/kubernetes-ingress.md
Adding a complete configuration example for Kubernetes Ingress.
Have a working example for Kubernetes Ingress
fixes #5855 
> Improve documentation for kubernetes ingress configuration

- docs/user-guide/kubernetes.md
Complete TLS example for Ingress in user guide
fixes #6438
> Complete TLS example for Kubernetes Ingress in user guide

- docs/content/contributing/maintainers.md
This PR removes Damien Duportal (@dduportal) from the maintainers team.
@dduportal asked us on Slack to remove him from the maintainers team.
> dduportal  10:25
Hello y'all. Can you please remove me from the maintainers of the project ? I cannot find the time neither the motivation to help, so better asking to stop :wink: Enjoy the next steps !
Thank you for everything you brought to the project.
We are sad to see you leave.
We wish you the best in your new adventure.
> Remove  @dduportal from the maintainers team

- docs/content/getting-started/install-traefik.md
Since the helm chart is production ready, we need to update the documentation
Be up-to-date
> Update traefik install documentation

- go.mod
- go.sum
https://github.com/rancher/go-rancher-metadata/commits/master
> Stop using fork of go-rancher-metadata

- docs/content/routing/entrypoints.md
> doc: fix typo.

- docs/content/operations/ping.md
Be more explicit about the entry point used by default by the ping.
> Improve ping documentation.

- docs/content/routing/providers/kubernetes-crd.md
- docs/content/routing/services/index.md
- docs/content/user-guides/crd-acme/index.md
- pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroute.go
This PR adds some documentation about how stickiness works, especially when there are multiple levels of load-balancing.
Fixes #6133 
> docs: clarify multi-levels stickiness

- docs/content/observability/access-logs.md
- pkg/middlewares/accesslog/logger_formatters.go
- pkg/middlewares/accesslog/logger_formatters_test.go
- pkg/middlewares/accesslog/logger_test.go
Add missing field quotes.
Fixes #6481
> Access log field quotes.

- docs/content/routing/routers/index.md
Fix a typo.
No contribution is totally useless.
> Fix wrong copy/pasted with service name warning

- CHANGELOG.md
> Prepare release v1.7.22

- CHANGELOG.md
Prepare release v2.1.7
aka `cantal`
> Prepare release v2.1.7

- .goreleaser.yml
- CHANGELOG.md
- docs/content/observability/access-logs.md
- docs/content/reference/static-configuration/cli-ref.md
- docs/content/reference/static-configuration/env-ref.md
- docs/content/reference/static-configuration/file.toml
- docs/content/reference/static-configuration/file.yaml
- pkg/middlewares/accesslog/logger_formatters.go
- pkg/middlewares/accesslog/logger_formatters_test.go
- pkg/middlewares/accesslog/logger_test.go
Merge current v2.1 branch into v2.2
Be sync.
> Merge current v2.1 branch into v2.2

- CHANGELOG.md
Prepare release v2.2.0-rc3
aka `chevrotin`
> Prepare release v2.2.0-rc3

- CHANGELOG.md
Prepare release v2.1.8
aka `cantal`
> Prepare release v2.1.8

- server/server.go
fix max TLS version.
Fixes #6530
> fix: max TLS version.

- docs/content/routing/providers/kubernetes-crd.md
fix terminationDelay word case.
Have a better documentation
> doc: fix terminationDelay word case.

- pkg/config/dynamic/middlewares.go
period field name.
Have a consistent field case.
> fix: period field name.

- CHANGELOG.md
> Prepare release v1.7.23

- CHANGELOG.md
Prepare release v2.1.9
aka `cantal`
> Prepare release v2.1.9

- autogen/gentemplates/gen.go
- templates/kubernetes.tmpl
fix wrong field names.
Fixes #6574
> fix: stickiness annotations support.

- CHANGELOG.md
> Prepare release v1.7.24

- docs/content/middlewares/headers.md
- docs/content/middlewares/ipwhitelist.md
- docs/content/migration/v1-to-v2.md
This PR fix typo in Kubernetes middleware name
> KubernetesCRD Middleware name in lowercase

- pkg/provider/consulcatalog/config.go
- pkg/provider/consulcatalog/config_test.go
Normalize default names for ConsulCatalog.
Have a consistent behavior with the other providers
> Normalize default names for ConsulCatalog.

- docs/content/migration/v1-to-v2.md
Fixes bad address syntax in Global HTTP to HTTPS redirection v2 TOML documentation example
The failure I got when using the code snippet
> Fix bad address syntax in Global HTTP to HTTPS redirection v2 TOML

- traefik.sample.toml
Fix defaults in example config.
Fix #6670
> Fix documentation about api.insecure defaults

- pkg/server/service/proxy.go
This PR fix issue with Websocket header
> FIx wS heAder

- docs/content/routing/entrypoints.md
I've added a missing precision that yaml file is also allowed
When reading the documentation, I've found the missing information.
As by just clicking on the Edit icon I could propose the change, I've allowed myself to do it
Please, fell free to close this PR if it's not relevant
> Added missing text `a yaml file` in Configuration

- docs/content/providers/kubernetes-crd.md
- docs/content/routing/routers/index.md
Replace the word `Ingress` by `resource`.
Closes  #6680
> doc: improve CRD documentation.

- docs/content/providers/file.md
> Edit code indentation for correct alignment

- docs/content/migration/v1-to-v2.md
> doc: add apiVersion for "kind: Middleware"

- pkg/server/service/proxy.go
This PR manages WebSocket case for all headers describe in the RFC
> Manage case for all Websocket headers

- docs/content/middlewares/compress.md
- docs/content/middlewares/contenttype.md
This PR adds more explanations about the behavior of middleware Content-Type and Compress.
This PR aims to clarify the actual behavior of middleware Content-Type and Compress, regarding the header `Content-Type`.
Related to #6636
> Doc middleware compress content type

- docs/content/reference/dynamic-configuration/docker-labels.yml
- docs/content/reference/dynamic-configuration/marathon-labels.json
- docs/content/routing/providers/docker.md
- docs/content/routing/providers/kv.md
- docs/content/routing/providers/marathon.md
- docs/content/routing/providers/rancher.md
- pkg/config/dynamic/http_config.go
- pkg/provider/kubernetes/ingress/fixtures/Ingress-with-annotations_service.yml
fix: cookie documentation.
Have consistent documentation.
> fix: cookie documentation.

- docs/content/middlewares/redirectscheme.md
This PR:
- Updates the quotation on the port section of the redirect scheme documentation
Fixes #6760
> Improve redirectScheme documentation

- docs/user-guide/kubernetes.md
Some of users have problem in setup traefik in kubernetes environment. I hope this will help for them to setup easier.
This just add setup ingress command for minikube. The issue was opened in #4495. To avoid the same situation as an user, I am opening this PR.
This is for v1.7 docs.
> Add ingress setup for minikube in docs

- docs/content/https/acme.md
Fix small typo in ACME integration documentation.
> Fix acme.md typo

- docs/content/getting-started/install-traefik.md
Fixed incorrect parameter for logging in the helm chart documentation.
Improve documentation
> Fixed incorrect logging parameter in documentation

- docs/content/middlewares/headers.md
Fix the documentation of middleware Headers, usage of proper bool.
fixes #6853
> Fix Headers middleware documentation, usage of proper bool

- docs/content/migration/v2.md
- docs/content/providers/file.md
- integration/fixtures/acme/certificates.toml
- integration/fixtures/tcp/mixed.toml
- integration/fixtures/timeout/keepalive.toml
- integration/fixtures/tracing/simple-jaeger-collector.toml
- integration/fixtures/tracing/simple-jaeger.toml
- integration/fixtures/tracing/simple-zipkin.toml
- pkg/cli/fixtures_test.go
- pkg/config/dynamic/http_config.go
- pkg/config/dynamic/middlewares.go
- pkg/config/dynamic/tcp_config.go
- pkg/config/dynamic/udp_config.go
- pkg/config/file/file.go
- pkg/config/file/file_test.go
- pkg/config/file/fixtures_test.go
- pkg/config/parser/tags.go
- pkg/config/static/entrypoints.go
- pkg/config/static/static_config.go
- pkg/provider/acme/provider.go
- pkg/provider/file/file.go
- pkg/provider/file/file_test.go
- pkg/provider/file/fixtures/toml/simple_file_01.toml
- pkg/provider/file/fixtures/toml/simple_file_02.toml
- pkg/provider/file/fixtures/toml/template_in_directory_file02.toml
- pkg/provider/file/fixtures/yaml/template_in_directory_file01.yml
- pkg/types/metrics.go
Uses parser to load dynamic config from file.
Be able to use `SetDefault` method.
> feat: use parser to load dynamic config from file.

- docs/content/contributing/maintainers.md
This PR adds Romain Tribotté [rtribotte](https://github.com/rtribotte) to the maintainers team.
Romain is recognized for outstanding and valiant actions carried out lately.
> Add rtribotte to maintainers

- server/server_configuration.go
- server/server_configuration_test.go
Fixes #6626
Use the same approach for `Same Configuration Check` as in master.
To fix the bug.
> Backport "Same Configuration Check" from master

- docs/content/providers/file.md
This is a minor change to clear up the language about using Go templating in dynamic configuration files.
This is the result of some discussion on the TraefikEE project. Since the TraefikEE documentation links here, it seemed appropriate to make a change or two here, for consistency's sake.
> Minor fix to Go templating documentation

- docs/content/routing/providers/kubernetes-ingress.md
- pkg/provider/kubernetes/ingress/annotations_test.go
Fix the documentation about ingress annotations for sticky cookie.
fixes #6916
> Fix sticky cookie ingress annotation doc

- docs/mkdocs.yml
- docs/theme/main.html
Change doc analytics.
Change doc analytics.
> Change doc analytics.

- docs/content/https/include-acme-multiple-domains-example.md
> added required quotes to domains config

- pkg/provider/acme/provider.go
Fix #6871
During startup it is common for a provider to trigger the validation of domains requiring a certificate multiple times. As there was only a read lock in place when fetching the unchecked domain list, it was possible that two or more routines proceeded to do requests to Acme/LetsEncrypt.
> Fix triggering multiple concurrent requests to ACME

- pkg/responsemodifiers/response_modifier.go
- pkg/responsemodifiers/response_modifier_test.go
> Fix panic when using chain middleware.

- CHANGELOG.md
> Prepare release v2.2.3

- CHANGELOG.md
> Prepare release v2.2.4

- CHANGELOG.md
> Prepare release v2.2.5

- CHANGELOG.md
- cmd/traefik/traefik.go
- docs/content/https/tls.md
- docs/content/migration/v2.md
- docs/content/reference/static-configuration/cli-ref.md
- docs/content/reference/static-configuration/env-ref.md
- docs/content/reference/static-configuration/file.toml
- docs/content/reference/static-configuration/file.yaml
- docs/content/routing/routers/index.md
- integration/fixtures/grpc/config.toml
- integration/fixtures/grpc/config_h2c_termination.toml
- integration/fixtures/grpc/config_insecure.toml
- integration/fixtures/grpc/config_retry.toml
- integration/grpc_test.go
- pkg/config/static/entrypoints.go
- pkg/config/static/static_config.go
- pkg/provider/kubernetes/crd/kubernetes.go
- pkg/rules/rules.go
- pkg/rules/rules_test.go
- pkg/server/router/router_test.go
- pkg/tcp/router.go
- traefik.sample.toml
Merge current v2.2 branch into master
Be sync.
> Merge current v2.2 branch into master

- CHANGELOG.md
> Prepare release v1.7.25

- .semaphoreci/vars
- .travis.yml
- CHANGELOG.md
- docs/content/getting-started/install-traefik.md
- docs/content/getting-started/quick-start.md
- docs/content/migration/v2.md
- docs/content/providers/docker.md
- docs/content/providers/kubernetes-ingress.md
- docs/content/routing/providers/kubernetes-crd.md
- docs/content/routing/providers/kubernetes-ingress.md
- docs/content/user-guides/crd-acme/03-deployments.yml
- docs/content/user-guides/crd-acme/k3s.yml
- docs/content/user-guides/docker-compose/acme-dns/docker-compose.yml
- docs/content/user-guides/docker-compose/acme-dns/docker-compose_secrets.yml
- docs/content/user-guides/docker-compose/acme-http/docker-compose.yml
- docs/content/user-guides/docker-compose/acme-tls/docker-compose.yml
- docs/content/user-guides/docker-compose/basic-example/docker-compose.yml
Prepare release v2.3.0-rc1
aka `picodon`
> Prepare release v2.3.0-rc1

- .goreleaser.yml
- CHANGELOG.md
Prepare release v2.3.0-rc2
aka `picodon`
>  Prepare release v2.3.0-rc2

- pkg/config/file/raw_node.go
- pkg/config/file/raw_node_test.go
file parser: skip nil value.
allow to manage pointer of bool.
> file parser: skip nil value.

- docs/content/routing/routers/index.md
- integration/acme_test.go
- integration/fixtures/https/https_domain_fronting.toml
- integration/headers_test.go
- integration/https_test.go
- pkg/server/router/tcp/router.go
Implement a fix for the domain fronting problem.
Fix a CVE.
Related to #7039
> Fix domain fronting

- CHANGELOG.md
> Prepare release v2.2.6

- integration/https_test.go
- pkg/server/router/tcp/router.go
- pkg/tcp/router.go
drop host port to compare with SNI.
Fixes #7070
> fix: drop host port to compare with SNI.

- CHANGELOG.md
> Prepare release 2.2.7

- CHANGELOG.md
- docs/content/https/acme.md
- docs/content/routing/entrypoints.md
- docs/content/routing/routers/index.md
- integration/acme_test.go
- integration/fixtures/https/https_domain_fronting.toml
- integration/headers_test.go
- integration/https_test.go
- pkg/middlewares/accesslog/logger.go
- pkg/middlewares/accesslog/logger_test.go
- pkg/provider/traefik/fixtures/redirection_with_protocol.json
- pkg/provider/traefik/internal.go
- pkg/provider/traefik/internal_test.go
- pkg/server/router/tcp/router.go
- pkg/tcp/router.go
Merge current v2.2 branch into v2.3
Be sync.
> Merge current v2.2 branch into v2.3

- examples/k8s/cheese-deployments.yaml
Hopefully fixes #7089.
Error when trying to perform tasks in example documentation.
> Change apiVersion to apps/v1 in examples/k8s/cheese-deployments.yaml

- docs/content/providers/ecs.md
- integration/helloworld/helloworld.pb.go
This PR fix documentation for ECS
> Fix documenation for ECS

- CHANGELOG.md
> Prepare release v1.7.26

- CHANGELOG.md
> Prepare release v2.2.8

- CHANGELOG.md
Prepare release v2.3.0-rc3
aka `picodon`
> Prepare release v2.3.0-rc3

- README.md
- SECURITY.md
doc: add security policies.
Follow GitHub recommendations.
> doc: add security policies.

- docs/content/migration/v1-to-v2.md
doc: replace underscore by hyphen.
Fixes #7130
> doc: replace underscore by hyphen for k8s metadata names.

- webui/Dockerfile
- upgrade NodeJS webui build image
- make traefik use a LTS version of NodeJS fo webui
- [NodeJS release milestones](https://nodejs.org/en/about/releases/)
> chore(webui): upgrade nodejs to Node current LTS

- .travis.yml
This PR adds mixtus for documentation.
> Add mixtus for documentation

- docs/content/providers/docker.md
> doc: fix dead link.

- docs/content/migration/v1-to-v2.md
Syntax error in the TOML example text....
> doc: fix typo in migration guide

- CHANGELOG.md
Prepare release v2.3.0-rc4
aka `picodon`
> Prepare release v2.3.0-rc4

- webui/src/components/platform/PlatformNotification.vue
- webui/src/store/platform/index.js
Decrease pilot notification size + add ability to dismiss it saving state in browser's local storage.
Fix #7120
> Add ability to dismiss pilot notification

- CHANGELOG.md
> Prepare release 2.2.9

- CHANGELOG.md
> Prepare release v2.2.10

- pkg/plugins/builder.go
- pkg/server/middleware/middlewares.go
- pkg/server/middleware/plugins.go
- pkg/server/routerfactory.go
Improves plugins builder.
Improve testability
> Improve plugins builder.

- CHANGELOG.md
> Prepare release v2.2.11

- CHANGELOG.md
Prepare release v2.3.0-rc5
aka `picodon`
> Prepare release v2.3.0-rc5

- docs/content/middlewares/buffering.md
fixed typo in buffering.md docs
typo
> fixed typo in buffering.md docs

- docs/content/middlewares/circuitbreaker.md
Changes wording a bit.
Instead of being "close" (representing proximity), contrary to a circuit being open one would say the circuit is "closed".
> Change wording

- cmd/traefik/plugins.go
- cmd/traefik/traefik.go
- pkg/config/static/experimental.go
- pkg/config/static/pilot.go
- pkg/config/static/static_config.go
Moves pilot outside the experimental section.
Be prepare.
> Moves pilot outside the experimental section.

- build.Dockerfile
- integration/docker_test.go
- pkg/middlewares/customerrors/custom_errors.go
- pkg/middlewares/passtlsclientcert/pass_tls_client_cert_test.go
- pkg/provider/marathon/config.go
- pkg/tls/certificate_store_test.go
update golangci-lint to v1.31.0
update golangci-lint to v1.31.0
> chore: update linter.

- CHANGELOG.md
Prepare release v2.3.0-rc6
aka `picodon`
> Prepare release v2.3.0-rc6

- CHANGELOG.md
Prepare release v2.3.0-rc7
aka `picodon`
> Prepare release v2.3.0-rc7

- docs/basics.md
Fix small typo in the `basics.md` file
> Fix typo "CA's" instead of "CA:s"

- docs/content/providers/kubernetes-crd.md
Fixes yaml syntax in example config
Noticed error while reading
> Fix syntax in yaml config examples

- docs/content/providers/docker.md
- docs/content/providers/kubernetes-ingress.md
- docs/content/routing/providers/docker.md
- docs/content/routing/services/index.md
> Fix yaml documentation

- docs/content/providers/consul-catalog.md
Fixes consul catalog router tag example.
Fixes #7330
> Fix consul catalog router tag example

- pkg/provider/acme/provider.go
Changes precheck option's order.
Fixes #7316
> fix: precheck function.

- CHANGELOG.md
Removes invalid items in the changelog.
Fixes  #7338
> Removes invalid items in the changelog.

- script/gcg/readme.md
- script/gcg/traefik-bugfix.toml
- script/gcg/traefik-final-release-part1.toml
- script/gcg/traefik-final-release-part2.toml
- script/gcg/traefik-rc-first.toml
- script/gcg/traefik-rc-new.toml
Added configuration files for generating the changelog of a release.
Simplify the release process.
> chore: Added configuration files for generating the changelog of a release.

- docs/content/getting-started/install-traefik.md
Update of the Helm repo localisation in the doc
The previous url doesn't provide last chart/traefik version
> Update of the helm repo localisation

- webui/package-lock.json
- webui/package.json
- webui/src/components/_commons/NavBar.vue
Avoid to use `semver-regex` which fail on some browsers.
Fix https://github.com/traefik/traefik/issues/7357
> Fix blank webui on some browsers

- CHANGELOG.md
Prepare release v2.3.1
aka `picodon`
> Prepare release v2.3.1

- pkg/provider/acme/local_store.go
- pkg/provider/acme/local_store_test.go
Fixes race condition in the `acme` `LocalStore` during saving.
Fix the bug and make a contribution :)
I'm not sure about tests with real files.
> acme: Fix race condition in LocalStore during saving.

- pkg/config/runtime/runtime.go
fixing a typo in json annotation.
> fix: udp json struct tag

- README.md
Fixes at the bottom of readme "Thanks Peka for the logo" where the logo was named incorrectly
> Fix broken logo

- docs/content/middlewares/forwardauth.md
- docs/content/reference/dynamic-configuration/docker-labels.yml
- docs/content/reference/dynamic-configuration/file.toml
- docs/content/reference/dynamic-configuration/file.yaml
- docs/content/reference/dynamic-configuration/marathon-labels.json
- pkg/config/dynamic/fixtures/sample.toml
- pkg/config/dynamic/middlewares.go
- pkg/config/dynamic/zz_generated.deepcopy.go
- pkg/config/label/label_test.go
- pkg/middlewares/auth/forward.go
- pkg/middlewares/auth/forward_test.go
- pkg/provider/kubernetes/crd/kubernetes.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/middleware.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
- pkg/provider/kv/kv_test.go
- webui/src/components/_commons/PanelMiddlewares.vue
> Filter ForwardAuth request headers

- CODE_OF_CONDUCT.md
- README.md
This PR fixes the remaining containous links in the readme.
> Fix containous links in readme

- .github/PULL_REQUEST_TEMPLATE.md
fix: versions in the PR template.
Inform about the right branch to use.
> fix: versions in the PR template.

- docs/content/getting-started/install-traefik.md
- traefik.sample.yml
> doc: add YAML sample.

- docs/content/reference/static-configuration/file.toml
- docs/content/reference/static-configuration/file.yaml
As Pilot configuration as moved from the experimental stage, the documentation has to be updated accordingly.
Keep the documentation up to date
> fix: pilot static configuration documentation

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- CODE_OF_CONDUCT.md
- README.md
- docs/content/getting-started/install-traefik.md
- docs/content/https/acme.md
- docs/content/reference/static-configuration/file.toml
- docs/content/reference/static-configuration/file.yaml
- pkg/config/runtime/runtime.go
- pkg/provider/acme/local_store.go
- pkg/provider/acme/local_store_test.go
- pkg/provider/acme/provider.go
- pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_serverstransport.go
- pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/serverstransport.go
- pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/serverstransport.go
- pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/serverstransport.go
- pkg/tls/tlsmanager.go
- script/gcg/readme.md
- script/gcg/traefik-bugfix.toml
- script/gcg/traefik-final-release-part1.toml
- script/gcg/traefik-final-release-part2.toml
- script/gcg/traefik-rc-first.toml
- script/gcg/traefik-rc-new.toml
- traefik.sample.yml
- webui/package-lock.json
- webui/package.json
- webui/src/components/_commons/NavBar.vue
Merge current v2.3 branch into master
Be sync.
> Merge current v2.3 branch into master

- docs/content/reference/dynamic-configuration/kv-ref.md
Add missing configuration in generated kv reference in documentation.
Having documentation up to date.
> fix: kv doc reference

- go.mod
- go.sum
> fix: update Yaegi to v0.9.4

- docs/content/providers/consul-catalog.md
- docs/content/reference/static-configuration/cli-ref.md
- docs/content/reference/static-configuration/env-ref.md
- pkg/provider/consulcatalog/consul_catalog.go
Fixes Consul Catalog address documentation.
Fixes  #7428
> fix: Consul Catalog address documentation.

- .gitignore
- CHANGELOG.md
- pkg/middlewares/accesslog/logger_formatters_test.go
- script/gcg/traefik-bugfix.toml
Prepare release v2.3.2
aka `picodon`
> Prepare release v2.3.2

- docs/content/routing/entrypoints.md
- docs/content/routing/providers/kubernetes-ingress.md
This PR adds a TLS example for the Ingress provider, clarifies the usage of the TLS section in the Ingress Spec, cleans unnecessary elements in the first example, and re-orders elements in the TLS documentation section. 
Clarify how to configure an Ingress.
related to #7420
> Fix ingress documentation

- docs/content/providers/overview.md
Fix little typo in documentation, "traedik" instead of "traefik".
To clear confusion for future doc readers.
> fix typo in providers overview documentation

- docs/content/routing/overview.md
Updates yaml example to be in sync with toml example
> Add missed tls config for yaml example

- docs/content/contributing/maintainers.md
Propose @kevinpollet to be promoted to be a maintainer
🎉
> Propose kevinpollet to Maintainers

- docs/content/routing/providers/kubernetes-crd.md
- docs/content/routing/providers/kubernetes-ingress.md
Update documentation link with the right path.
Add a missing line.
Having valid documentation.
> fix documentation

- pkg/server/server_entrypoint_tcp.go
Fix #7409 
2 others ways for the fix: 
- completely ignoring the error, if any
- making the call to the function conditionnal with a runtime.GOOS=="openbsd"
> Ignore errors when setting keepalive period is not supported by the system

- pkg/provider/kubernetes/crd/client.go
- pkg/provider/kubernetes/ingress/client.go
Fix #7391
Better observability of k8s providers clients.
> Set kubernetes client User-Agent to something meaningful

- pkg/provider/consulcatalog/consul_catalog.go
This PR fixes a panic in the consul catalog provider that happens sporadically when registering or deregistering a service in the catalog. The panic is due to the way we get the services from the catalog. We made 2 distinct HTTP calls that can be looking at the state of the catalog at 2 different point in time. In some cases, the number of services and health results are different.
Fixes #7551 
> Fix consul catalog panic when health and services are not in sync

- docs/content/providers/kubernetes-ingress.md
> Fix grammar in kubernetes ingress controller documentation

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.3.3
aka `picodon`
> Prepare release v2.3.3

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.3.4
aka `picodon`
> Prepare release v2.3.4

- docs/content/migration/v1-to-v2.md
This changes adds a couple of missing quotations in the YAML section of the v1-to-v2.md file.
I've lost 10 minutes of my time debugging this. I don't want others to suffer as I did.
> Fix typos in migration guide 

- cmd/traefik/plugins.go
- cmd/traefik/traefik.go
Add comments and create some functions to improve readability and maintainability.
Improves readability and maintainability.
> Improve setup readability.

- docs/content/https/acme.md
- docs/content/reference/static-configuration/cli-ref.md
- docs/content/reference/static-configuration/env-ref.md
- docs/content/reference/static-configuration/file.toml
- docs/content/reference/static-configuration/file.yaml
- pkg/provider/acme/provider.go
Add external account binding (EAB) support.
Fixes #7118
> acme: add external account binding support.

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.3.5
aka `picodon`
> Prepare release v2.3.5

- docs/content/observability/access-logs.md
Add configuration examples for the filePath option of Access Logs
Stumbled across these missing code example while looking for specific configuration in the docs.
> Add configuration example for access log filePath

- docs/content/contributing/maintainers.md
This PR adds Harold Ozouf [jspdown](https://github.com/jspdown) to the maintainers team.
Harold is recognized for outstanding and valiant actions carried out lately.
> Add jspdown to maintainers

- .semaphoreci/vars
- .travis.yml
- CHANGELOG.md
- script/gcg/traefik-rc-first.toml
Prepare release v2.4.0-rc1
aka `livarot`
> Prepare release v2.4.0-rc1

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.3.6
aka `picodon`
> Prepare release v2.3.6

- CHANGELOG.md
- pkg/rules/rules.go
- pkg/rules/rules_test.go
- pkg/server/router/router_test.go
- script/gcg/traefik-bugfix.toml
Merge current v2.3 branch into v2.4
Be sync.
> Merge current v2.3 branch into v2.4

- docs/content/middlewares/forwardauth.md
Suggesting a rewording for the v2.4 RC's new feature description.
The incoming feature looks relevant for https://github.com/oauth2-proxy/oauth2-proxy/pull/957, but this sentence is in need of some love.
> docs: rephrase forwardauth.authRequestHeaders

- webui/src/components/_commons/PanelMiddlewares.vue
This PR prepends the header name to the configured custom request and response header chips in the header middleware description.
Fixes #6733
**Before:**
**After:**
> webui: fix missing custom request and response header names

- docs/user-guide/cluster-docker-consul.md
> docs: fix language "if challenge is not known"

- .travis.yml
This PR does a docker login for travis
Be able to pull images
> Do a Docker login on Travis

- .golangci.toml
- CHANGELOG.md
- build.Dockerfile
- docs/content/middlewares/forwardauth.md
- docs/content/providers/docker.md
- docs/content/providers/overview.md
- pkg/metrics/pilot_test.go
- pkg/metrics/prometheus_test.go
- pkg/middlewares/accesslog/logger_test.go
- pkg/provider/file/file_test.go
- pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-host_endpoint.yml
- pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-host_ingress.yml
- pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-host_service.yml
- pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-path_endpoint.yml
- pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-path_ingress.yml
- pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-path_service.yml
- pkg/provider/kubernetes/ingress/kubernetes.go
- pkg/provider/kubernetes/ingress/kubernetes_test.go
- pkg/rules/rules.go
- pkg/rules/rules_test.go
- pkg/server/router/router_test.go
- pkg/server/server_entrypoint_tcp_test.go
- pkg/server/server_entrypoint_udp_test.go
- pkg/server/service/proxy_websocket_test.go
- pkg/tcp/proxy_test.go
- pkg/udp/conn_test.go
- pkg/udp/proxy_test.go
- script/gcg/traefik-bugfix.toml
- webui/src/components/_commons/PanelMiddlewares.vue
Merge current v2.4 branch into master
Be sync.
> Merge current v2.4 branch into master

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.3.7
aka `picodon`
> Prepare release v2.3.7

- CHANGELOG.md
- script/gcg/traefik-rc-new.toml
Prepare release v2.4.0-rc2
aka `livarot`
> Prepare release v2.4.0-rc2

- LICENSE.md
- mkdocs.yml
This PR updates the copyright year for 2021 🎉 ⭐ 
> Update copyright year for 2021

- CHANGELOG.md
- script/gcg/readme.md
- script/gcg/traefik-bugfix.toml
> Prepare release v1.7.27

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
> Prepare release v1.7.28

- .github/workflows/documentation.yml
- .travis.yml
Merge current v2.4 branch into master
Be sync.
> Merge current v2.4 into master

- pkg/middlewares/accesslog/logger.go
- pkg/middlewares/metrics/metrics.go
- pkg/tls/cipher.go
- pkg/tls/version.go
This PR refactor the TLS version and cipher functions used in logger and metrics middlewares.
Clean the code.
> Mutualize TLS version and cipher code

- go.mod
- go.sum
- pkg/provider/configuration.go
- pkg/provider/file/file.go
Updates the version of the sprig library to v3.2.0 to include, among other things, the `fromJson, mustFromJson` functions.
I saw the `fromJson, mustFromJson` functions in sprig's documentation but could not use them in Traefik's dynamic configuration in the File provider.
http://masterminds.github.io/sprig/defaults.html#fromjson-mustfromjson
> Update sprig to v3.2.0

- pkg/middlewares/forwardedheaders/forwarded_header.go
- pkg/middlewares/recovery/recovery.go
- pkg/middlewares/recovery/recovery_test.go
- pkg/server/router/router.go
Improve forwarded header and recovery middlewares.
Better performance!
> perf: improve forwarded header and recovery middlewares

- docs/content/routing/services/index.md
Corrects a typo in the documentation
3 hours of debugging
> Fix typo in server transports documentation

- pkg/provider/aggregator/aggregator_test.go
This PR fixes a comment in the aggregator test.
Update the comment to reflect the actual test.
> Fix aggregator test comment

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.4.1
aka `livarot`
> Prepare Release v2.4.1

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.4.2
aka `livarot`
> Prepare release v2.4.2

- .github/workflows/documentation.yml
- docs/content/providers/kubernetes-gateway.md
- docs/content/routing/providers/kubernetes-gateway.md
This PR adds seo support for traefik
Manage seo stuff in the documentation
> Add seo support

- docs/content/routing/providers/consul-catalog.md
- docs/content/routing/providers/ecs.md
- docs/content/routing/providers/kv.md
- docs/content/routing/providers/marathon.md
- docs/content/routing/providers/rancher.md
- docs/content/routing/services/index.md
Add missing doc about servers transport.
> Add missing doc about servers transport.

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.4.3
aka `livarot`
> Prepare release v2.4.3

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.4.4
aka `livarot`
> Prepare release v2.4.4

- .goreleaser.yml
- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.4.5
aka `livarot`
> Prepare release v2.4.5

- docs/content/routing/services/index.md
> Fix typo in routing/services/index.md

- cmd/traefik/traefik.go
- pkg/provider/aggregator/aggregator.go
- pkg/provider/aggregator/aggregator_test.go
- pkg/server/configurationwatcher.go
- pkg/server/configurationwatcher_test.go
Wait for file and internal before applying configurations.
Fixes #7902
> fix: wait for file and internal before applying configurations

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.4.6
aka `livarot`
> Prepare release v2.4.6

- docs/content/providers/kubernetes-ingress.md
Explaining the ingressclass name filter.
Update the Doc
> Clarify doc for ingressclass name in k8s 1.18+

- .github/ISSUE_TEMPLATE/config.yml
- .goreleaser.yml
Add new GitHub issue chooser.
Improves community interactions.
https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
> Add new GitHub issue chooser.

- pkg/provider/acme/challenge_tls.go
avoid closing 2 times the same chan.
Fixes #7955
> fix: double close chan on TLS challenge

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.4.7
aka `livarot`
> Prepare release v2.4.7

- docs/content/middlewares/headers.md
This pull request removes a note referenced in issue #7924
I'd like to get involved in an open source project, i use Traefik at work a-lot and thought i'd liek to contribute.  also selfishly - i'd like to draw attention to my comment on issue [6322](https://github.com/traefik/traefik/issues/6322) and show i'd be happy to help document the kubernetes uses of Traefik, with a little support :).
Closes #7924
nice to meet you :)
> updating docs to remove a no longer needed note

- docs/content/middlewares/chain.md
Minor docs fix in line with syntax shown here: https://doc.traefik.io/traefik/routing/providers/docker/
> Add missing `traefik.` prefix across sample config

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.4.8
aka `livarot`
> Prepare release v2.4.8

- docs/content/observability/metrics/overview.md
This PR adds a detailed list of provided metrics in the documentation.
Better documentation :)
> Add metrics documentation

- .golangci.toml
- build.Dockerfile
update golangci-lint to v1.39.0
update golangci-lint to v1.39.0
> chore: update linter

- CHANGELOG.md
- script/crossbinary-others
- script/gcg/traefik-bugfix.toml
> Prepare release v1.7.29

- docs/content/getting-started/configuration-overview.md
Fixes a typo in the doc.
i.e. means "that is to say"
e.g. means "for example"
It was burning my eyes.
> doc: typo fix

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
> Prepare release v1.7.30

- docs/content/middlewares/ratelimit.md
Fix a syntax error in ratelimit TOML configuration sample
Improve doc
> doc: fix a syntax error in ratelimit TOML configuration sample

- docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutes.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutetcps.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_ingressrouteudps.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_middlewares.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_serverstransports.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_tlsoptions.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_tlsstores.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_traefikservices.yaml
- integration/fixtures/k8s/01-traefik-crd.yml
Update CRDs by executing make generate-crd.
Proper CRDs.
> Fix: regenerate crd

- pkg/provider/kubernetes/k8s/event_handler.go
Removes logging of changed object, as it can't be guaranteed that it actually is an endpoint.
Build from master branch panics in k8s cluster.
Related to #7646
> kubernetes: remove logging of changed object with cast

- docs/content/middlewares/headers.md
> docs: add examples for removing headers

- pkg/provider/acme/provider.go
The preferred chain option was missing from the certificate request, then the PR set this option.
Fixes #7936
> fix: ACME preferred chain.

- docs/content/routing/routers/index.md
- pkg/rules/parser.go
- pkg/rules/rules.go
- pkg/rules/rules_test.go
This PR adds a `!` in the rule mechanism to be able to invert a rule.
Fixes #5228
> Support not in rules definition

- docs/content/getting-started/faq.md
- docs/mkdocs.yml
This PR adds a new documentation section FAQ and gives explanations about a first a question: "Why is Traefik Answering XXX HTTP Response Status Code".
Document a frequently asked question.
> Explains Traefik HTTP response status codes

- docs/content/contributing/maintainers-guidelines.md
Adding formatting to the document and fixing the link to the main image. 
The formatting has been updating in order to meet Semantic Break Lines requirements. 
N/A
> Adding formatting to the document.

- docs/content/reference/dynamic-configuration/kv-ref.md
- docs/content/reference/static-configuration/cli-ref.md
- docs/content/reference/static-configuration/env-ref.md
- docs/content/reference/static-configuration/file.toml
- docs/content/reference/static-configuration/file.yaml
- pkg/config/static/static_config.go
This PR updates documentation references.
Be consistent.
> Update documentation references

- .github/workflows/check_doc.yml
- .travis.yml
- docs/check.Dockerfile
This PR moves documentation check from travis to github action
Smoother documentation check
> Use github action to check and verify doc

- .golangci.toml
- build.Dockerfile
- pkg/middlewares/tracing/mock_tracing_test.go
Upgrades `golangci-lint` to 1.41.1
Bugfixes and performance
> chore: upgrade linter

- README.md
Removes the microbader bage as microbadger.com will shutdown on 1st July 2021
https://microbadger.com/shutdown
> Remove microbadger (Shutdown)

- docs/content/contributing/maintainers-guidelines.md
> fix maintainers-guidelines page title

- docs/content/contributing/maintainers-guidelines.md
- docs/content/contributing/maintainers.md
We need "Maintainer's" to be cohesive across the document.
To have better documentation.
> Typos in contributing section

- docs/content/providers/overview.md
Add docs of the list of available provider names
Fixes #8220
> Add the list of available provider names

- docs/content/reference/static-configuration/cli-ref.md
- docs/content/reference/static-configuration/env-ref.md
- docs/content/reference/static-configuration/file.toml
- docs/content/reference/static-configuration/file.yaml
Update generated doc and configuration reference.
Have a doc up to date.
> Update generated and reference doc for plugins

- CHANGELOG.md
- Makefile
- docs/content/reference/static-configuration/cli-ref.md
- docs/content/reference/static-configuration/env-ref.md
- docs/content/reference/static-configuration/file.toml
- docs/content/reference/static-configuration/file.yaml
Merge current v2.5 branch into master
Be sync.
> Merge back v2.5 into master

- pkg/middlewares/headers/responsewriter.go
Implements http.CloseNotifier in the *headers.responseModifier.
Fixes #8222
> Add *headers.responseModifier CloseNotify()

- docs/scripts/verify.sh
Exclude unstable URL from check.
Avoid URL check fails.
> fix doc verify

- Makefile
- docs/content/getting-started/faq.md
- docs/content/migration/v2.md
- docs/content/providers/kubernetes-crd.md
- docs/content/providers/kubernetes-ingress.md
- docs/content/reference/static-configuration/cli-ref.md
- docs/content/reference/static-configuration/env-ref.md
- integration/fixtures/k8s_crd.toml
- pkg/middlewares/accesslog/logger.go
- pkg/middlewares/accesslog/logger_test.go
- pkg/middlewares/headers/responsewriter.go
- pkg/provider/file/file.go
- pkg/provider/file/file_test.go
- pkg/provider/file/fixtures/toml/tls_file_key.cert
- pkg/provider/kubernetes/crd/fixtures/udp/with_externalname_service.yml
- pkg/provider/kubernetes/crd/kubernetes.go
- pkg/provider/kubernetes/crd/kubernetes_http.go
- pkg/provider/kubernetes/crd/kubernetes_tcp.go
- pkg/provider/kubernetes/crd/kubernetes_test.go
- pkg/provider/kubernetes/crd/kubernetes_udp.go
- pkg/provider/kubernetes/ingress/fixtures/Ingress-with-IPv6-endpoints-externalname-enabled_ingress.yml
- pkg/provider/kubernetes/ingress/fixtures/Ingress-with-IPv6-endpoints-externalname-enabled_service.yml
- pkg/provider/kubernetes/ingress/fixtures/Ingress-with-service-with-externalName-enabled_ingress.yml
- pkg/provider/kubernetes/ingress/fixtures/Ingress-with-service-with-externalName-enabled_service.yml
- pkg/provider/kubernetes/ingress/kubernetes.go
- pkg/provider/kubernetes/ingress/kubernetes_test.go
- pkg/rules/rules.go
- pkg/server/configurationwatcher.go
Merge current v2.4 branch into v2.5
Be sync.
> Merge current v2.4 into v2.5

- docs/content/migration/v2.md
Remove bad title.
Having a clean doc.
> Fix migration guide

- cmd/internal/gen/centrifuge.go
- go.mod
- go.sum
Update code generator for plugin's dyn conf.
Generate better code.
> Update code generator for plugin's dyn conf

- docs/content/reference/dynamic-configuration/kv-ref.md
This PR updates KV reference documentation.
Be consistent.
> Fix KV reference documentation

- CHANGELOG.md
- docs/scripts/verify.sh
- pkg/provider/file/file.go
- pkg/provider/file/file_test.go
- pkg/provider/file/fixtures/yaml/simple_empty_store.yml
- script/gcg/traefik-bugfix.toml
Merge current v2.4 branch into v2.5
Be sync.
> Merge back v2.4 into v2.5

- CHANGELOG.md
- script/gcg/traefik-rc-new.toml
Prepare release v2.5.0-rc3
aka `brie`
> Prepare release v2.5.0-rc3

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.4.12
aka `livarot`
> Prepare release v2.4.12

- .semaphore/semaphore.yml
- integration/k8s_test.go
- integration/resources/compose/k8s.yml
This PR restore the cache only one time on SemaphoreCI
Avoid to have failing integration tests
> fix: restore cache only once

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.4.13
aka `livarot`
> Prepare release v2.4.13

- CHANGELOG.md
- script/gcg/traefik-rc-new.toml
Prepare release v2.5.0-rc4
aka `brie`
> Prepare release v2.5.0-rc4

- .semaphore/semaphore.yml
This PR change the machine type for the release of Traefik
Be able to do a release
> fix: change machine type for release

- CHANGELOG.md
- script/gcg/traefik-rc-new.toml
Prepare release v2.5.0-rc6
aka `brie`
> Prepare release v2.5.0-rc6

- docs/content/routing/providers/kv.md
fix a doc error.
i try `traefik.http.routers.myrouter.entrypoints/0` not working, then i try  `traefik/http/routers/myrouter/entrypoints/0`, its work.
thanks reviewing.
> fix: an example code error in doc

- docs/requirements.txt
This PR updates the mkdocs dependency version
Fix documentation builds.
> Update mkdocs dependency version

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.4.14
aka `livarot`
> Prepare release v2.4.14

- .github/workflows/build.yaml
- .github/workflows/test-unit.yaml
- .github/workflows/validate.yaml
- build.Dockerfile
- exp.Dockerfile
- go.mod
- go.sum
Adds support for Go 1.17 GA and bump to Yaegi v0.9.23.
Keep in sync with Go GA release.
- [] ~Added/updated tests~
- [] ~Added/updated documentation~
> Update Go version to v1.17

- docs/content/middlewares/http/overview.md
Adds content type middleware to middleware's overview table.
Omission content type middleware to middleware's overview table.
> Adds ContentType to middleware's overview table

- docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
- docs/content/routing/providers/kubernetes-crd.md
Link in missing CRD in documentation
v1beta APi is removed from k8s 1.22.
~Should fix (at least partly) https://github.com/traefik/traefik/issues/8336~
fixes #8336
> Adds MiddlewareTCP CRD documentation

- docs/content/https/tls.md
- docs/content/reference/dynamic-configuration/file.toml
- docs/content/reference/dynamic-configuration/file.yaml
- docs/content/reference/dynamic-configuration/kubernetes-crd-resource.yml
- docs/content/reference/dynamic-configuration/kv-ref.md
- docs/content/reference/dynamic-configuration/traefik.containo.us_tlsoptions.yaml
- docs/content/routing/providers/kubernetes-crd.md
- integration/fixtures/k8s/01-traefik-crd.yml
- pkg/provider/kubernetes/crd/kubernetes.go
- pkg/provider/kubernetes/crd/kubernetes_test.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/tlsoption.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
- pkg/provider/kv/kv_test.go
- pkg/server/aggregator_test.go
- pkg/server/configurationwatcher_test.go
- pkg/tls/tls.go
- pkg/tls/tlsmanager.go
- pkg/tls/zz_generated.deepcopy.go
This PR adds a new option in the TLSOptions to specify the list of ALPN protocols to negotiate.
fixes #8376 
fixes #7776
> Makes ALPN protocols configurable

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.5.1
aka `brie`
> Prepare release v2.5.1

- .github/workflows/experimental.yaml
This PR adds a Github action to build experimental images on branches.
Build experimental images on branches with Github actions, since we are not able to build experimental images on Docker Hub anymore.
> Build experimental images

- .github/workflows/experimental.yaml
This PR fixes the workflow of the experimental image, by changing conditions to build for branches `v*` and not for tags.
Having a working experimental images build for branches `v*`.
> Fix experimental images workflow

- pkg/server/service/loadbalancer/mirror/mirror.go
- pkg/server/service/loadbalancer/mirror/mirror_test.go
Fix bug https://github.com/traefik/traefik/issues/8045
I need usefull feature
fixes #8045
> Fix empty body error in mirror

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.5.2
aka `brie`
> Prepare release v2.5.2

- docs/content/middlewares/tcp/ipwhitelist.md
- docs/content/providers/consul-catalog.md
- docs/content/providers/docker.md
- docs/content/providers/ecs.md
- docs/content/providers/file.md
- docs/content/providers/marathon.md
- docs/content/providers/rancher.md
- pkg/tls/cipher.go
- pkg/tls/version.go
Merge current v2.5 branch into master.
Be synced.
> Merge current v2.5 into master

- exp.Dockerfile
This PR fixes the experimental build image.
Have a working experimental image build.
> fix: experimental image build

- go.mod
- go.sum
Update yaegi to v0.10.0
https://github.com/traefik/yaegi/compare/v0.9.23...v0.10.0
>  Update yaegi to v0.10.0

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.5.3
aka `brie`
> Prepare release v2.5.3

- docs/content/observability/tracing/datadog.md
- docs/content/observability/tracing/elastic.md
- docs/content/observability/tracing/haystack.md
- docs/content/observability/tracing/instana.md
- docs/content/observability/tracing/jaeger.md
- docs/content/observability/tracing/zipkin.md
- docs/content/reference/static-configuration/cli-ref.md
- docs/content/reference/static-configuration/env-ref.md
- pkg/tracing/datadog/datadog.go
- pkg/tracing/elastic/elastic.go
- pkg/tracing/haystack/haystack.go
- pkg/tracing/instana/instana.go
- pkg/tracing/jaeger/jaeger.go
- pkg/tracing/tracing.go
- pkg/tracing/zipkin/zipkin.go
This PR rewords the tracing config descriptions to be consistent and also fixes some typos.
Have better tracing config descriptions.
> docs: reword tracing config descriptions to be consistent

- docs/content/providers/consul.md
- docs/content/providers/etcd.md
- docs/content/providers/redis.md
- docs/content/providers/zookeeper.md
Fix typo for username in sample
> Fix typo in KV providers documentation

- README.md
This PR removes a link to the now defunct microbadger.com website in the project README.
My deep-seated hate for broken links.
> docs: remove link to microbadger.com

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.5.4
aka `brie`
> Prepare release v2.5.4

- go.mod
- go.sum
- pkg/plugins/builder.go
Update yaegi to v0.11.0
https://github.com/traefik/yaegi/compare/v0.10.0...v0.11.0
> Update yaegi v0.11.0

- docs/content/observability/metrics/overview.md
As discussed in #8430, the documentation had misleading information on how to include metrics in the configuration file. This solves #8430. 
#8430
> docs: remove misleading metrics overview configuration

- .semaphore/semaphore.yml
- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.5.5
aka `brie`
> Prepare release v2.5.5

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
> Prepare release v1.7.34

- docs/content/middlewares/http/passtlsclientcert.md
Fix reused name from another middleware
Fix docs
With this exceptional PR contribution I'll be disappointed if I'm not nominated as a maintainer :trollface:
> Fix passTLSClientCert CRD example name

- .semaphore/semaphore.yml
- CHANGELOG.md
- docs/content/getting-started/configuration-overview.md
- docs/content/getting-started/install-traefik.md
- docs/content/getting-started/quick-start.md
- docs/content/migration/v1-to-v2.md
- docs/content/observability/access-logs.md
- docs/content/providers/docker.md
- docs/content/reference/dynamic-configuration/kubernetes-gateway-traefik-lb-svc.yml
- docs/content/routing/providers/kubernetes-crd.md
- docs/content/routing/providers/kubernetes-ingress.md
- docs/content/user-guides/crd-acme/03-deployments.yml
- docs/content/user-guides/crd-acme/k3s.yml
- docs/content/user-guides/docker-compose/acme-dns/docker-compose.yml
- docs/content/user-guides/docker-compose/acme-dns/docker-compose_secrets.yml
- docs/content/user-guides/docker-compose/acme-http/docker-compose.yml
- docs/content/user-guides/docker-compose/acme-tls/docker-compose.yml
- docs/content/user-guides/docker-compose/basic-example/docker-compose.yml
- script/gcg/traefik-rc-first.toml
> Prepare release v2.6.0-rc1

- docs/content/operations/api.md
Add missing endpoints to api.md
> Add missing API endpoints documentation

- go.mod
- go.sum
Update Yaegi to v0.11.2
Fixes #8450
https://github.com/traefik/yaegi/compare/v0.11.1...v0.11.2
> Update Yaegi to v0.11.2

- .semaphore/semaphore.yml
- build.Dockerfile
- docs/content/operations/api.md
- go.mod
- go.sum
Merge current v2.5 branch into v2.6.
Be synced.
> Merge current v2.5 into v2.6

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.5.6
aka `brie`
> Prepare release v2.5.6

- docs/content/observability/tracing/jaeger.md
Update broken Jaeger documentation link
Have a working documentation.
> Fix broken jaeger documentation link

- .semaphore/semaphore.yml
- CHANGELOG.md
- build.Dockerfile
- docs/content/observability/tracing/jaeger.md
- docs/content/operations/api.md
- go.mod
- go.sum
- script/gcg/traefik-bugfix.toml
Merge current v2.6 branch into master.
Be synced.
> Merge current v2.6 into master

- LICENSE.md
- mkdocs.yml
This PR updates the copyright year for 2022 🎉 ⭐ 
> Update copyright for 2022

- CHANGELOG.md
- script/gcg/traefik-rc-new.toml
> Prepare release v2.6.0-rc2

- docs/scripts/verify.sh
This PR excludes www.cloudxns.net from documentation verification.
Fix the documentation verification.
> Exclude www.cloudxns.net from documentation verification

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.5.7
aka `brie`
> Prepare release v2.5.7

- CHANGELOG.md
- script/gcg/traefik-rc-new.toml
> Prepare release v2.6.0-rc3

- docs/content/https/acme.md
This PR clarifies that an ACME challenge has to be defined for a certificate resolver to be usable.
> Clarify that ACME challenge is mandatory

- pkg/provider/acme/challenge_http.go
Add domain to the errors of the HTTP challenge.
Fixes #8738
> Add domain to HTTP challenge errors

- docs/content/user-guides/marathon.md
> Fix brand typo

- .golangci.toml
- go.mod
- go.sum
- pkg/types/metrics.go
This PR update metrics configuration tags from `omitEmpty` (which is invalid) to `omitempty`.
Have a configuration that is 'marshalable'.
> Fix struct tag typo  

- Makefile
The PR changes the way to generate the WebUI. This change allows using more features of `make` (e.g. `make -B`).
To have a better build system
> Add a target that is a real resource to generate-webui

- docs/content/providers/docker.md
This PR fixes the doc about constraints for the docker provider.
The doc was incorrectly stating that the constraints are using the "Tag" syntax instead of the "Label" syntax.
> doc: fix, docker uses Label(), not Tag()

- webui/src/pages/_commons/RouterDetail.vue
This PR adds the way to go to a service displayed in the router view detail by a click
I used a lot Traefik to have an overview of my router and my service and ensure all is correct when I am doing my configuration. However, I cannot go to the service from the router detail view, I have to click on "services" tab, search my service (among 30, for the moment...) and click again. I add the link and it works perfectly!
I did the feature the more simple way I could find and the most soft. I am opened to every suggestions or changes to respect the code's guidelines of the project :)
Thank for your work! ❤️
> Add a link to service on router detail view

- docs/content/getting-started/concepts.md
Clarified wording: “the opposite is true” is contradictory; “the inverse is also true” is accurate and less confusing.
When I was reading the docs online, this sentence confused me and I had to use context to figure out what it meant to say.
> Clarify concepts documentation page

- docs/content/routing/overview.md
Fixes minor inconsistencies between documentation text and example code. Matched the text copy to the code instead of the other way around.
Attention to detail.
> Fix routing overview examples

- docs/content/middlewares/http/buffering.md
Fixes one typo on buffering page in docs
Saw a typo
> Fix fenced code block typo in Buffering middleware page

- docs/content/routing/entrypoints.md
- Makes sure CLI syntax is consistent. (one per row)
| Before | After 
|--------|--------|
|   ![](https://i.imgur.com/GInM1eg.png) | ![](https://i.imgur.com/UJsg2vd.png)
I was being lazy and could not easily copy-paste for my compose file.
> Update entrypoint.md to add consistent CLI syntax

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
> Prepare release v2.6.2

- .semaphore/semaphore.yml
- CHANGELOG.md
- docs/content/getting-started/configuration-overview.md
- docs/content/getting-started/install-traefik.md
- docs/content/getting-started/quick-start.md
- docs/content/migration/v1-to-v2.md
- docs/content/observability/access-logs.md
- docs/content/providers/docker.md
- docs/content/providers/kubernetes-ingress.md
- docs/content/reference/dynamic-configuration/kubernetes-gateway-traefik-lb-svc.yml
- docs/content/routing/providers/kubernetes-crd.md
- docs/content/routing/providers/kubernetes-ingress.md
- docs/content/user-guides/crd-acme/03-deployments.yml
- docs/content/user-guides/crd-acme/k3s.yml
- docs/content/user-guides/docker-compose/acme-dns/docker-compose.yml
- docs/content/user-guides/docker-compose/acme-dns/docker-compose_secrets.yml
- docs/content/user-guides/docker-compose/acme-http/docker-compose.yml
- docs/content/user-guides/docker-compose/acme-tls/docker-compose.yml
- docs/content/user-guides/docker-compose/basic-example/docker-compose.yml
- script/gcg/traefik-rc-first.toml
Prepare release v2.7.0-rc1
aka `epoisses`
> Prepare release v2.7.0-rc1

- CHANGELOG.md
- script/gcg/traefik-rc-new.toml
Prepare release v2.7.0-rc2
aka `epoisses`
> Prepare release v2.7.0-rc2

- Makefile
This PR lints the Makefile by:
- adding `.PHONY` to targets
- adding more verbose to ifs that do not need to be inlined
- fixing some documentation
- linting targets
Having a better Makefile.
> Add .PHONY to Makefile targets

- docs/content/reference/dynamic-configuration/kubernetes-gateway-resource.yml
I was reading the documentation and found a mistake, which I have corrected.
> docs: fix certificateRefs in dynamic configuration

- pkg/collector/collector.go
- pkg/collector/collector_test.go
- pkg/collector/hydration_test.go
add test on collect
fix: prevent failure of collected data
> fix: prevent failure of collected data

- Makefile
- webui/static/DONT-EDIT-FILES-IN-THIS-DIRECTORY.md
This pull request fixes the `clean-webui` target to make sure that the `webui/static/DONT-EDIT-FILES-IN-THIS-DIRECTORY.md` file is generated consistently on every system. 
To fix the release process.
> Fix clean-webui target

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
> Prepare release v2.6.5

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
> Prepare Release v2.6.6

- CHANGELOG.md
- Makefile
- pkg/collector/collector.go
- pkg/collector/collector_test.go
- pkg/collector/hydration_test.go
- pkg/provider/acme/provider.go
- pkg/provider/acme/provider_test.go
- pkg/provider/ecs/ecs.go
- script/gcg/traefik-bugfix.toml
- webui/dev/scripts/transfer.js
- webui/static/DONT-EDIT-FILES-IN-THIS-DIRECTORY.md
Merge current v2.6 into v2.7.
To be in sync.
> Merge current v2.6 into v2.7

- go.mod
- go.sum
- update oxy
https://github.com/vulcand/oxy/compare/v1.4.0...v1.4.1
> Upgrade to oxy v1.4.1

- docs/content/routing/entrypoints.md
fix default priority of the entrypoint redirection.
Have the right value.
> docs: fix default priority of the entrypoint redirection

- docs/content/middlewares/http/headers.md
Update browserXssFilter to camel case
> Updated browserXssFilter key to camel case

- pkg/tcp/proxy.go
- pkg/udp/proxy.go
Append destination address in debug log.
Debug log shows source address only.
However the destination address is important for debugging as well, like debuging wrr. Can we append it?
> Add destination address to debug log

- docs/content/middlewares/http/stripprefix.md
- docs/content/routing/providers/kubernetes-gateway.md
Merge current v2.7 into master.
To be in sync.
> Merge current v2.7 into master

- docs/content/contributing/advocating.md
S/A
corrects the link for folks to let us know when they create content.  This link was over a year out of date.
I like to be helpful.  It makes me feel warm and fuzzy, but at the same time powerful.  Like a god, but of something very tiny and not very important.  Goddess of the specks of dust that no one sees, but also will never coalesce into something more powerful.  Or maybe, goddess of the trailing space.  
Mostly, though, I was motivated by my job.
> Update the link for contributor swag

- docs/content/contributing/submitting-issues.md
* made "help us help you" a subtitle using hashtags
* something weird is happening with the subtitle tag? I did nothing
* clarified what we consider issues up top
* softened language about saving time to show how it helps the user
* updated the community forum to lower the perceived cost of entry and look smoother.  (left the button to see how it renders)
* Examples of titles that will help with navigation
* changed the spelling of open source to align with our style guide and corrected "you" to "your"
* noted that community support is important to us
* asked folks who want to make a pr to let us know.
> Update the contributing docs for clarity and to encourage community activity

- docs/content/traefik-hub/index.md
- docs/mkdocs.yml
Add Hub documentation.
Add Hub documentation.
related to #8837
Co-authored-by: Baptiste Mayelle <baptiste.mayelle@traefik.io>
> Hub documentation

- .semaphore/semaphore.yml
- CHANGELOG.md
- docs/content/getting-started/configuration-overview.md
- docs/content/getting-started/install-traefik.md
- docs/content/getting-started/quick-start.md
- docs/content/migration/v1-to-v2.md
- docs/content/observability/access-logs.md
- docs/content/providers/docker.md
- docs/content/providers/kubernetes-ingress.md
- docs/content/reference/dynamic-configuration/kubernetes-gateway-traefik-lb-svc.yml
- docs/content/routing/providers/kubernetes-crd.md
- docs/content/routing/providers/kubernetes-ingress.md
- docs/content/user-guides/crd-acme/03-deployments.yml
- docs/content/user-guides/crd-acme/k3s.yml
- docs/content/user-guides/docker-compose/acme-dns/docker-compose.yml
- docs/content/user-guides/docker-compose/acme-dns/docker-compose_secrets.yml
- docs/content/user-guides/docker-compose/acme-http/docker-compose.yml
- docs/content/user-guides/docker-compose/acme-tls/docker-compose.yml
- docs/content/user-guides/docker-compose/basic-example/docker-compose.yml
- script/gcg/traefik-rc-first.toml
Prepare release v2.8.0-rc1
aka `vacherin`
> Prepare release v2.8.0-rc1

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.7.1
aka `epoisses`
> Prepare release v2.7.2

- CHANGELOG.md
- docs/content/middlewares/http/overview.md
- docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
- docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutes.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutetcps.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_middlewares.yaml
- integration/fixtures/k8s/01-traefik-crd.yml
- pkg/metrics/datadog.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/middleware.go
- pkg/types/domains.go
- script/gcg/traefik-bugfix.toml
Merge current v2.7 into v2.8.
To be in sync.
> Merge current v2.7 into v2.8

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- docs/content/providers/kubernetes-crd.md
- docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
- docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutes.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutetcps.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_ingressrouteudps.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_middlewares.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_middlewaretcps.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_serverstransports.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_tlsoptions.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_tlsstores.yaml
- docs/content/reference/dynamic-configuration/traefik.containo.us_traefikservices.yaml
- docs/content/user-guides/crd-acme/index.md
- integration/fixtures/k8s/01-traefik-crd.yml
- pkg/config/dynamic/middlewares.go
- pkg/config/dynamic/tcp_config.go
- pkg/config/dynamic/tcp_middlewares.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroute.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroutetcp.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressrouteudp.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/middleware.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/middlewaretcp.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/serverstransport.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/service.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/tlsoption.go
- pkg/provider/kubernetes/crd/traefik/v1alpha1/tlsstore.go
- script/gcg/traefik-final-release-part1.toml
- script/gcg/traefik-final-release-part2.toml
Prepare release v2.8.0
aka `vacherin`
> Prepare release v2.8.0

- docs/content/deprecation/features.md
- docs/content/deprecation/releases.md
Update the deprecation notices page
Align with current planning
> Update deprecation notices

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.8.1
aka `vacherin`
> Prepare release v2.8.1

- docs/content/contributing/submitting-pull-requests.md
This updates the guidelines for the contributing docs.  They have been approved by the c-suite, proxy team, and community team. 
To make it easier for the community to understand our PR process. 
There seems to be something wrong with the spacing in lines 55-57.  I cannot figure it out.  Is it just me?
> Update the PR guidelines in Contributing docs

- CONTRIBUTING.md
This PR add the items missing in this doc that exist in the other contributing docs. 
maintain the same level of clarity across all docs until we can pick one (or 2 if you insist).
> Update CONTRIBUTING.md to contain all information in one place

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- README.md
- docs/readme.md
- integration/resources/tls/README.md
This PR lints markdown files that are not in the `docs/` directory.
More lint.
> Lint markdown files

- docs/content/contributing/thank-you.md
I updated the page with the proper branding for Traefik Proxy and some small grammar fixes.
Getting the link for a blog post that we hope has excellent reach, I noticed that we conflated traefik and Traefik Proxy.
> Update Thank You page with proper branding and grammar fixes

- docs/content/providers/kubernetes-crd.md
- docs/content/providers/kubernetes-gateway.md
- docs/content/providers/kubernetes-ingress.md
Fix the wording of the default behaviour for the `namespaces` config key for the K8s provider.
> Fix wording of default behavior for namespaces option

- docs/content/getting-started/quick-start-with-kubernetes.md
- docs/mkdocs.yml
This PR adds a new getting started guide for Kubernetes using native ingresses.
The documentation needs more beginner oriented contents.
> Add getting started guide for Kubernetes

- pkg/middlewares/ipwhitelist/ip_whitelist.go
This PR removes the request dump from IPWhitelist debug log and tracing message.
To avoid leaking sensitive headers content in logs.
Fixes #9240.
> Remove request dump from IPWhitelist debug log and tracing message

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.8.2
aka `vacherin`
> Prepare release v2.8.2

- docs/content/migration/v2.md
Add migration guide for v2.8.3
Related to #9249
> Add migration guide for v2.8.3

- docs/content/deprecation/features.md
This PR updates the deprecation documentation about Traefik Pilot.
Provide up-to-date documentation.
Allow reaching the Plugin Catalog from the deprecation page.
> Update deprecation notes about Pilot

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.8.4
aka `vacherin`
> Prepare release v2.8.4

- docs/content/getting-started/concepts.md
- docs/content/getting-started/configuration-overview.md
- docs/content/getting-started/install-traefik.md
- docs/content/getting-started/quick-start.md
- docs/content/https/acme.md
- docs/content/https/overview.md
- docs/content/https/tls.md
- docs/content/includes/.markdownlint.json
- docs/content/includes/traefik-for-business-applications.md
- docs/content/middlewares/http/headers.md
- docs/content/middlewares/http/overview.md
- docs/content/middlewares/overview.md
- docs/content/operations/dashboard.md
- docs/content/providers/docker.md
- docs/content/providers/file.md
- docs/content/providers/kubernetes-crd.md
- docs/content/providers/kubernetes-ingress.md
- docs/content/providers/overview.md
- docs/content/routing/entrypoints.md
- docs/content/routing/overview.md
- docs/content/routing/providers/kubernetes-crd.md
- docs/content/routing/providers/kubernetes-ingress.md
- docs/content/routing/routers/index.md
- docs/content/routing/services/index.md
- docs/content/user-guides/docker-compose/basic-example/index.md
- docs/mkdocs.yml
This PR adds links to resources for users building and managing business applications.
Wanted to provide avenues for anyone who needs more advanced, enterprise-specific capabilities to find more information.
All additions are at the end of each article. Happy to chat about it if need be.
> Added resources for businesses

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.8.5
aka `vacherin`
> Prepare release v2.8.5

- script/binary
- script/code-gen.sh
- script/make.sh
- script/test-integration
- script/test-unit
This PR fixes some errors in shell scripts
> fix: shellcheck

- docs/content/getting-started/faq.md
- docs/content/routing/routers/index.md
- pkg/plugins/middlewares.go
- pkg/server/middleware/plugins.go
Merge current v2.8 into v2.9
To be in sync.
> Merge current v2.8 into v2.9

- .semaphore/semaphore.yml
- CHANGELOG.md
- script/gcg/traefik-rc-new.toml
Prepare release v2.9.0-rc3
aka `banon`
> Prepare release v2.9.0-rc3

- docs/content/migration/v2.md
Merge the current v2.8 branch into v2.9
Be sync.
> Merge current v2.8 branch into v2.9

- docs/content/providers/ecs.md
- docs/content/providers/overview.md
This PR adds documentation for ECS constraints option.
> Add documentation for ECS constraints option

- pkg/provider/docker/config.go
- pkg/provider/ecs/config.go
- pkg/provider/nomad/config.go
- pkg/provider/rancher/config.go
Simplifying AddServer algorithms.
Have readable algorithms.
same approach as #9357
> providers: simplify AddServer algorithms

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.8.6
aka `vacherin`
> Prepare release v2.8.6

- CHANGELOG.md
- script/gcg/traefik-rc-new.toml
Prepare release v2.9.0-rc4
aka `banon`
> Prepare release v2.9.0-rc4

- .goreleaser.yml
- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.8.7
aka `vacherin`
> Prepare release v2.8.7

- CHANGELOG.md
- script/gcg/traefik-rc-new.toml
Prepare release v2.9.0-rc5
aka `banon`
> Prepare release v2.9.0-rc5

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- docs/content/getting-started/install-traefik.md
- docs/content/providers/kubernetes-ingress.md
- script/gcg/traefik-final-release-part1.toml
- script/gcg/traefik-final-release-part2.toml
Prepare release v2.9.0
aka `banon`
> Prepare release v2.9.0

- CHANGELOG.md
- script/gcg/traefik-bugfix.toml
Prepare release v2.9.1
aka `banon`
> prepare-release-v2.9.1
