traefik/traefik

pkg/middlewares/redirect/redirect.go, pkg/middlewares/redirect/redirect_regex_test.go, pkg/middlewares/redirect/redirect_scheme_test.go
Before the PR, if the request contains the header `X-Forwarded-Proto: https` the HTTPS redirect is skipped.
To be able to create a HTTPS redirection even if the header `X-Forwarded-Proto: https` is set.
=> X-Forwarded-Proto must not skip the redirection.

.semaphoreci/vars, .travis.yml, CHANGELOG.md
Prepare release v2.1.0-rc1
aka `cantal`
=> Prepare release v2.1.0-rc1

docs/content/https/acme.md, docs/content/https/ref-acme.txt, docs/content/migration/v1-to-v2.md, docs/content/observability/access-logs.md, docs/content/observability/logs.md, docs/content/observability/metrics/datadog.md, docs/content/observability/metrics/influxdb.md, docs/content/observability/metrics/prometheus.md, docs/content/observability/metrics/statsd.md, docs/content/observability/tracing/datadog.md, docs/content/observability/tracing/haystack.md, docs/content/observability/tracing/instana.md, docs/content/observability/tracing/jaeger.md, docs/content/observability/tracing/overview.md, docs/content/observability/tracing/zipkin.md, docs/content/operations/ping.md, docs/content/providers/docker.md, docs/content/providers/kubernetes-crd.md, docs/content/providers/kubernetes-ingress.md, docs/content/providers/marathon.md, docs/content/providers/rancher.md, docs/content/providers/rancher.txt, docs/content/providers/rancher.yml, docs/content/routing/entrypoints.md, docs/content/routing/overview.md, docs/content/routing/providers/docker.md, docs/content/routing/routers/index.md, docs/content/user-guides/grpc.md
doc: remove double quotes on CLI flags.
Related to #5797, #5822
=> doc: remove double quotes on CLI flags.

webui/src/components/_commons/PanelServiceDetails.vue
Fix the details displayed for tcp services
For tcp services:
- passHostHeader was wrongly displayed
- terminationDelay was missing
https://community.containo.us/t/pass-host-header-for-tcp/3018
=> Web UI: Fix displayed tcp service details

cmd/healthcheck/healthcheck.go
Uses the entry point of ping if it is provided, otherwise uses the `traefik` entrypoint.
Fixes #5856 
=> Uses, if it exists, the ping entry point provided in the static configuration

webui/src/pages/dashboard/Index.vue
Avoid polling `/api/entrypoints` on webui dashboard route.
On webui dashboard route 2 api endpoints were poll every x seconds. Discussing with @ldez the `/api/entrypoints` one doesn't need to refreshed since data is coming from the static configuration.
=> Web UI: Avoid polling on /api/entrypoints

webui/src/components/_commons/ToolBarTable.vue
Sync the web ui ToolbarTable component state with the url query parameters.
Changing status and searching in a table state wasn't saved in the navigation. So state was lost going to an other route then going back to the previous one.
=> Web UI: Sync toolbar table state with url query params

webui/src/components/_commons/PanelRouterDetails.vue
Set some web ui router properties as wrappable.
Avoid some web ui router properties to overflow their container.
=> Web UI: Avoid some router properties to overflow their container

integration/grpc_test.go, integration/simple_test.go, pkg/provider/file/file_test.go, pkg/provider/rancher/rancher.go, pkg/server/service/tcp/service.go, pkg/tcp/proxy_test.go
Fix duration order consistency when multiplying number by time unit
I saw some inconsistency in the code and wanna fix it :)
=> Duration order consistency when multiplying number by time unit

pkg/cli/commands.go, pkg/cli/commands_test.go
sub command help
before:
```console
$ ./cmd test subtest subsubtest --help
command test error: command not found: subtest
```
after:
```console
$ ./cmd test subtest subsubtest --help
subsubtest    
Usage: subsubtest [command] [flags] [arguments]
Use "subsubtest [command] --help" for help on any command.
Commands:
subsubsubtest    
```
=> fix: sub command help

pkg/provider/rancher/rancher.go
Changes the internal Service Name for the services discovered through the rancher provider.
Make the WebUI work with Rancher Services
=> Change service name in rancher provider to make webui service details view work

docs/content/providers/docker.md, docs/content/routing/providers/docker.md
This PR aims at adding a Swarm section in the Docker provider documentation,
introducing the following changes:
- [Docker provider documentation] Elaborate that Swarm Mode is supported + elaborate and moving upfront the "Routing Configuration" for Docker standalone
- [Docker provider documentation] Add a section "Routing Configuration with Labels" for Docker standalone to elaborate the concept (as the quickstart is not really explicit about the "label" magic), and mention other tools that could be used if Docker is used in background
- [Docker provider documentation] Add a section "Port Detection" for Docker standalone to explain the port detection mechanism
- [Docker provider documentation] Add a section "Docker API Access" for Docker standalone with the content around security moved …
=> Add Swarm section to the Docker Provider Documentation

docs/configuration/entrypoints.md
Adds a warning to the TLS mutual authentication section regarding non-universal client support for optional client certificates during handshaking.
We got burned by certain clients which do not treat this option as truly optional; see [this Chromium ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=1002638) for an example of this incompatibility in the wild.
=> Add a warning note regarding optional TLS mutual auth

pkg/provider/kubernetes/crd/client.go, pkg/provider/kubernetes/ingress/client.go
Remove the usage of deprecated SharedInformerFactory in kubernetes providers. 
The kubernetes providers should use NewSharedInformerFactoryWithOptions(), due to the fact that NewFilteredSharedInformerFactory() is deprecated and may get removed in future releases.
=> Update deprecated function call in k8s providers 

pkg/middlewares/headers/headers.go, pkg/middlewares/headers/headers_test.go
This PR Removes the `Access-Control-Request-Headers` requirement for determining if the request is a Preflight or not.
Fixes #5896 
The W3 cors documentation leaves much to be desired:
https://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0
=> Remove Request Headers CORS Preflight Requirement

docs/content/providers/consul-catalog.md, docs/content/routing/providers/consul-catalog.md, pkg/provider/constraints/constraints_labels.go, pkg/provider/constraints/constraints_labels_test.go, pkg/provider/constraints/constraints_tags.go, pkg/provider/constraints/constraints_tags_test.go, pkg/provider/consulcatalog/config.go, pkg/provider/consulcatalog/config_test.go, pkg/provider/consulcatalog/consul_catalog.go, pkg/provider/consulcatalog/convert_types_test.go, pkg/provider/docker/config.go, pkg/provider/marathon/config.go, pkg/provider/rancher/config.go
Consul catalog constraints by using tags instead of labels.
Be able to use all kind of tags as constraints.
Closes #5911
=> fix: consul catalog constraints.

pkg/provider/traefik/fixtures/full_configuration.json, pkg/provider/traefik/internal.go, pkg/provider/traefik/internal_test.go
Add a router for the debug endpoint when the API use the insecure mode.
Be able to use pprof.
-  ~~[ ] Added/updated documentation~~
Related to https://github.com/containous/traefik/issues/5904#issuecomment-561507210
=> fix: debug endpoint when insecure API.

pkg/server/server_entrypoint_tcp.go, pkg/tls/certificate.go
This PR prevents the tcp entrypoints listeners to crash when encountering a temporary error on `Accept` calls.
Under heavy load, Traefik could open too many files, reaching the limit and causing `Accept` to fail with the temporary error `too many open files`. Since we returned in the case, this silently broke the accept loop, crashing the entrypoint and preventing it to server further requests.
Fixes #3933
Took the opportunity of opening this PR to actually make use of the `IsPath` method of `FileOrContent` :slightly_smiling_face:
=> Do not stop to listen on tcp listeners on temporary errors 

README.md
Fix a broken link
A broken link that wastes user Googling time
I ran into this broken link on `master` (and suppose other people will run into it there) and hence I'm targetting `master`. Should it target branch `v2.1` instead?
=> readme: Fix link to file backend/provider documentation

docs/content/migration/v1-to-v2.md
This PR fixes incorrect router name in Docker example from "Strip and Rewrite Path Prefixes" part of migration guide - router created in this example is named "admin", but `stripprefix` middleware is set for router "web"
I've spotted this inconsistency when trying to migrate my docker-compose configuration to traefik 2.06
=> Fix Docker example in "Strip and Rewrite Path Prefixes" in migration guide

docs/content/https/acme.md, docs/content/providers/kubernetes-crd.md, docs/content/providers/kubernetes-ingress.md
This PR improves the documentation for LetsEncrypt use by making note of the HA caveats, and providing workarounds for known design choices.
Documentation was not clear on the removal of distributed LetsEncrypt, and how it would affect kubernetes users.
Fixes #5792
=> Document LE caveats with Kubernetes on v2

docs/content/migration/v1-to-v2.md, docs/content/providers/file.md, docs/content/routing/overview.md, docs/content/user-guides/grpc.md
Exposes the limitations of the file provider with file system notifications and update the documentation examples accordingly.
Sometime, the dynamic configuration is not updated on file changes.
After some [tests](https://github.com/jbdoumenjou/fsnotify-sandbox), we can deduce that according to the configuration, it may be:
* a broken link between two file systems (host <-> container)
* a file system behavior/compatibility issue with [fsnotify](https://github.com/fsnotify/fsnotify).
So, the issue does not come from Traefik, but from the file systems, the orchestrators and the fsnotify library. That's why we improve the Traefik documentation.
Close #5589
=> Improve documentation on file provider limitations with file system notifications

acme/account.go, provider/acme/account.go
This PR truncates the private key to 16 characters for use for identification in the log.
The entire key should not be provided in the log.
Fixes #5284
=> Truncate key for identification in log

docs/content/middlewares/passtlsclientcert.md, pkg/middlewares/passtlsclientcert/pass_tls_client_cert.go, pkg/middlewares/passtlsclientcert/pass_tls_client_cert_test.go
Use `,` as separator for certificates in the header `X-Forwarded-Tls-Client-Cert-Info` as for the header `X-Forwarded-Tls-Client-Cert`
Be homogeneous. 
Closes #5919
=> fix: PassClientTLSCert middleware separators and formatting

docs/content/operations/dashboard.md
Right now it makes it harder for people not using the `insecure` mode to recognize that the dashboard can only be reached using the trailing slash only since it is at the bottom of the page to the "insecure" chapter ( which those people will most probably skip ) -
I assume the trailing slash is somewhat surprising, it might be helpful to make the fact more prominent
-
=> Make trailing slash more prominent for the "secure dashboard setup" too

pkg/server/service/loadbalancer/mirror/mirror.go
This PR removes impact on accesslogs when we use the mirroring.
Fixes #5953 
And fix that sometimes, when using mirroring, in the access log, the `serviceName` field was incorrect because mirroring replaced the main `serviceName`.
=> Remove mirroring impact in accesslog

cmd/traefik/traefik.go, pkg/server/configurationwatcher.go, pkg/server/server.go
- Removes double call to server `Close`.
- Removes `logrus.Exit(0)` in `runCmd` because it kill Traefik before the end of the server `Close` called in the defer of  `runCmd`.
Have a clean stop of Traefik
=> fix: remove double call to server Close.

docs/check.Dockerfile
Fixes flaky Travis builds due to 'not get uid/gid'
To have a stable CI.
```
Step 4/10 : RUN apk --no-cache --no-progress add     git     nodejs     npm   && npm install --global     markdownlint@0.17.2     markdownlint-cli@0.19.0
---> Running in f06d17604331
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/10) Installing expat (2.2.8-r0)
(2/10) Installing pcre2 (10.33-r0)
(3/10) Installing git (2.22.0-r0)
(4/10) Installing c-ares (1.15.0-r0)
(5/10) Installing libgcc (8.3.0-r0)
(6/10) Installing http-parser (2.9.2-r0)
(7/10) Installing libstdc++ (8.3.0-r0)
(8/10) Installing libuv (1.29.1-r0)
(9/10) Installing nodejs (10.16.3-r0)
(10/10) Installing npm (10.16.3-r0)
Executing …
```
=> fix: flaky Travis builds due to 'not get uid/gid'

docs/content/https/.markdownlint.json, docs/content/https/acme.md, docs/content/https/include-acme-multiple-domains-example.md, docs/content/https/include-acme-multiple-domains-from-rule-example.md, docs/content/https/include-acme-single-domain-example.md, docs/content/index.md, docs/content/routing/providers/marathon.md, docs/mkdocs.yml
- Proposes improvements to the ACME/Let's Encrypt documentation:
- Describes the domain selection mechanism from routers
- Provides more Dynamic Configuration Examples for LE/ACME
- Adapt the table of content structure
- Exclude all the markdown files which names follow the pattern `include-*.md`. This was already implemented, but not working so it's fixed now.
- Fixed a typo on the routing documentation for Marathon.
https://community.containo.us/tags/c/traefik/letsencrypt-acme should be enough :)
Beginners/newcomers might not immediately get "how is that black magic magicking?"
when using Let's Encrypt/ACME.
The goal is to "state what is obvious for us but not for others".
Please note that no links should be broken by the "Table of content" re-struct.
=> Improve documentation for ACME/Let's Encrypt

webui/src/components/_commons/PanelMirroringServices.vue, webui/src/components/_commons/PanelWeightedServices.vue
Fix weighted service provider icon that was incorrect (`undefined.png`)
Fix #5813
=> Fix weighted service provider icon

webui/src/components/_commons/PanelServiceDetails.vue
Use valid condition for the termination delay section in the service details panel.
Have a working service detail panel.
=> Use valid condition in the service details panel UI

pkg/middlewares/accesslog/capture_response_writer.go, pkg/middlewares/accesslog/field_middleware.go, pkg/middlewares/accesslog/logger.go, pkg/middlewares/metrics/metrics.go, pkg/middlewares/metrics/recorder.go
This PR makes sure that the ResponseWriters in accesslog and metrics only implement CloseNotify if their underlying ResponseWriter does so.
Fixes https://github.com/containous/traefik/issues/5953#issuecomment-563933225
=> detect CloseNotify capability in accesslog and metrics

webui/package-lock.json, webui/package.json, webui/src/_mixins/GetTableProps.js, webui/src/components/_commons/Chips.vue, webui/src/components/_commons/MainTable.vue, webui/src/components/_commons/ProviderIcon.vue, webui/src/pages/_commons/MiddlewareDetail.vue, webui/src/pages/_commons/ServiceDetail.vue, webui/src/pages/http/Middlewares.vue, webui/src/pages/http/Routers.vue, webui/src/pages/http/Services.vue, webui/src/pages/tcp/Routers.vue, webui/src/pages/tcp/Services.vue
Take off logic from generic table component
Some display logics are in the generic MainTable vue component (like list of columns based on a type prop).
=> Web UI: Take off logic from generic table component

docs/content/middlewares/passtlsclientcert.md, docs/content/reference/dynamic-configuration/file.toml, docs/content/reference/dynamic-configuration/file.yaml, docs/content/reference/dynamic-configuration/kv-ref.md, pkg/config/dynamic/middlewares.go, pkg/config/label/label_test.go, pkg/middlewares/passtlsclientcert/pass_tls_client_cert.go, pkg/middlewares/passtlsclientcert/pass_tls_client_cert_test.go
The SerialNumber field for a client certificate was not forwarded as a header in the PassTLSClientCert middleware. This PR fixes that issue.
Fixes #5881 
I was unable to completely build the entire project. The fix was tested by running the unit tests.
=> Add serial number certificate to forward headers

pkg/middlewares/accesslog/capture_response_writer.go, pkg/middlewares/accesslog/capture_response_writer_test.go, pkg/middlewares/metrics/metrics_test.go, pkg/middlewares/metrics/recorder.go
In #5985, we added `CloseNotify` specific versions of the `responseWriter` wrappers in
accesslog and metrics.
But the implementer is the pointer, not the value, and we messed up because we returned the value instead of the pointer in the "constructor".
Also, we had forgotten to remove the `CloseNotify` method for the type that is not supposed to implement it.
Therefore this PR fixes the above.
Fixes #6008 
=> CloseNotifier: return pointer instead of value

docs/content/migration/v2.md, docs/mkdocs.yml
Adds a guide on how to migrate Traefik v2.x minor versions.
Have our users do the right things ;-)
=> Add Migration Guide for Traefik v2.1

docs/content/operations/include-api-examples.md
This PR adds a documentation example for dashboard and api for kubernetes CRD.
With the release of Traefik v2.1, Kubernetes CRD `IngressRoute` can now specify the internal service `api@internal` as a type `TraefikService`, which allow a "Secure Dashboard" configuration.
=> add a documentation example for dashboard and api for kubernetes CRD

pkg/provider/kubernetes/crd/kubernetes_http.go
Kubernetes CRD was missing support for ExternalName https backends. It's already added into v2.0 and Kubernetes Ingress in v2.1 has it already included, so, I simply add this into CRDs. 
I need Sticky sessions with Kubernetes CRDs and ExternalName on https backends in an ongoing project, and this feature is going to be implemented anyway.
I made the former pull request to support https backends in ExternalNames for v2.0, as they were hardcoded as "http" backends in the code. 
Related to #5660
Regression from #5711
=> Added ExternalName https support for Kubernetes CRD, as done in v2.0

pkg/config/parser/labels_decode.go, pkg/config/parser/labels_decode_test.go
Throw an error instead of panic when a label/flag name ends with a dot.
Fixes #6024
```
Stack: goroutine 62 [running]:
runtime/debug.Stack(0xc00010c000, 0x2550df9, 0x17)
/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x235a380, 0xc0007e5420)
/go/src/github.com/containous/traefik/pkg/safe/routine.go:160 +0xb1
github.com/containous/traefik/v2/pkg/safe.OperationWithRecover.func1.1(0xc000705d78)
/go/src/github.com/containous/traefik/pkg/safe/routine.go:168 +0x56
panic(0x235a380, 0xc0007e5420)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/containous/traefik/v2/pkg/config/parser.DecodeToNode(0xc0007a7e30, 0x252f8bb, 0x7, 0xc0007053a0, 0x2, 0x2, 0x10, 0x21fd9e0, 0x29f5b01) …
```
=> fix: invalid label/flag parsing.

pkg/server/service/proxy.go
Force `User-Agent` header to `""` if it's not set to avoid it being replaced with `Go-http-client/1.1"`.
https://github.com/golang/go/blob/7d30af8e17d62932f8a458ad96f483b9afec6171/src/net/http/request.go#L614-L619
Fixes #5621, but only for v2.1.
Probably we should add a backport for this to v1.7, since the issue was reported to occur on that version. If the backport is needed, I can create it.
=> Don't set user-agent to Go-http-client/1.1

provider/kubernetes/fixtures/ingressAnnotations_ingresses.yml, provider/kubernetes/kubernetes.go, provider/kubernetes/kubernetes_test.go
This PR:
- Fixes behavior of an edge case with rewrite-target
Fixes #5990 
This edge case was where we trim the trailing slashes on the rewrite-target before appending the contents of the matched path. This behavior was required becuase it ensures that we don't duplicate slashes.
However, it introduced an edge case where if the trailing slash _was_ the leading slash, it could get lost.
This is that edge case. The solution here is to capture the leading slash as part of the path capture group, and append it to the rewrite target.
=> Add edge case for root path with rewrite-target

integration/consul_catalog_test.go, pkg/provider/consulcatalog/consul_catalog.go
Fetches additional health data from consul to detect whether a service is healthy or not.
Fix #5905
=> Query consul for service health separately

integration/testdata/rawdata-ingress.json, pkg/provider/traefik/fixtures/api_insecure_with_dashboard.json, pkg/provider/traefik/fixtures/full_configuration.json, pkg/provider/traefik/internal.go
fix dashboard redirect loop
Fix #6073, #6041
The recommended way to create routing for the dashboard/api is to use `api@internal` and `api.insecure=false`.
https://community.containo.us/t/serving-traefiks-internal-dashboard-behind-traefik-itself/3457/7?u=ldez
=> fix: dashboard redirect loop

docs/content/routing/entrypoints.md
Fix the command for use websecure mode via CLI.
I using with Docker and detect this error [following this doc](https://docs.traefik.io/user-guides/docker-compose/acme-http/). See `websecure` in `command` property.
```
traefik:
command:
- "--entrypoints.websecure.address=:443"
```
```
traefik:
command:
- "--entrypoints.web-secure.address=:443"
```
Using `web-secure` rather than `websecure` the API not response in previous endpoint.
=> Fix command for use websecure via CLI

provider/ecs/ecs.go
Skip ECS container when information are missing instead of panic.
```
Stack: goroutine 70 [running]:
runtime/debug.Stack(0x26cb820, 0x17, 0xc0012ee0f0)
/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/containous/traefik/safe.defaultRecoverGoroutine(0x2246600, 0x4603250)
/go/src/github.com/containous/traefik/safe/routine.go:148 +0x89
github.com/containous/traefik/safe.OperationWithRecover.func1.1(0xc00101be18)
/go/src/github.com/containous/traefik/safe/routine.go:156 +0x56
panic(0x2246600, 0x4603250)
/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/containous/traefik/provider/ecs.(*Provider).listInstances(0xc0004432b0, 0x29eaee0, 0xc000087400, 0xc000423330, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/containous/traefik/provider/ecs/ecs.go:322 +0xe62 …
```
=> fix: skip ECS container when information are missing instead of panic.

cmd/traefik/traefik.go, pkg/server/server_entrypoint_tcp.go, pkg/server/server_entrypoint_tcp_test.go, pkg/tcp/router.go
This PR handles the `RespondingTimeout` options and improve `Shutdown`.
Fixes #5763 
=> Handle respondingtimeout and better shutdown tests.

pkg/provider/kubernetes/crd/kubernetes_http.go
In the Kubernetes CRD provider, log the ignored namespace only when a service namespace is explicitly defined with a cross provider reference.
Fixes #6033
=> Log the ignored namespace only when needed

pkg/middlewares/auth/forward.go, pkg/middlewares/auth/forward_test.go
This PR **fixes** the propagation of tracing headers when using `forwardAuth`
fixes #5774 
close #6009
This PR fixes the problems described in https://github.com/containous/traefik/pull/6009.
**Important Note:** While working on this I realized that tracing propagation will only work if tracing middleware happens before the forwardauth middleware, is this something we can guarantee?
Ping @ldez @aliksend
=> fix(tracing): makes sure tracing headers are being propagated when using forwardAuth

pkg/provider/kubernetes/ingress/fixtures/Ingress-one-rule-host-only_ingress.yml, pkg/provider/kubernetes/ingress/kubernetes.go, pkg/provider/kubernetes/ingress/kubernetes_test.go
Fixes a crash when using the KubernetesIngress Provider if an Ingress has a rule without a `nil` `http` element.
This is a common case if you're using Let's Encrypt `http01` verification to create a certificate for a non-HTTP based service.  Or in my case, the ingress just uses an annotation to HTTP redirect with ingress-nginx (which i'm migrating away from).
Basically, just adds a `nil` check.  Without this `nil` check a single ingress rule that has a `nil` `http` element will make the entire provider not work.
I also added a unit test to verify the change and to avoid it from happening again in the future.
I'm trying to migrate to traefik from ingress-nginx and after hours of searching for why my secrets weren't being found, I finally dug into the nil pointer deference I was also seeing …
=> k8s Ingress: fix crash on rules with nil http

pkg/middlewares/accesslog/capture_request_reader.go, pkg/middlewares/accesslog/logdata.go, pkg/middlewares/accesslog/logger.go
This PR renames a variable which name led to believe it contains a count whereas it contains a size.
I've lost quite a bit of time while debuging thinking that `crr.count` was wrongly incremented.
=> Rename the non-exposed field "count" to "size"

docs/content/middlewares/ratelimit.md, docs/content/reference/dynamic-configuration/docker-labels.yml, docs/content/reference/dynamic-configuration/file.toml, docs/content/reference/dynamic-configuration/file.yaml, docs/content/reference/dynamic-configuration/kv-ref.md, docs/content/reference/dynamic-configuration/marathon-labels.json, pkg/config/dynamic/fixtures/sample.toml, pkg/config/dynamic/middlewares.go, pkg/config/label/label_test.go, pkg/middlewares/ratelimiter/rate_limiter.go, pkg/middlewares/ratelimiter/rate_limiter_test.go, pkg/provider/kv/kv_test.go, script/test-unit
We're getting some user feedback that they would like to be able to specify a rate limit lower than 1 request per second.
One possibility would have been to change the "average" field to a float (e.g. 6 requests / minute would have been average=0.1).
However, that would break the configuration (among other things) as TOML will not decode a value that looks like an int (no decimal point specified) into a Go float64.
Therefore, this PR (re-)introduces the notion of a period, that allows one to (optionally) specify the duration for which the given average applies.
The default value for the period is 1 second, which means if no period is specified, the meaning of the average does not change compared with before this change (it is still in requests/s).
Fixes #5918
=> Add period for rate limiter middleware

docs/content/routing/providers/docker.md
Fixes a link to `service` named `rule` in the routing documentation.
=> Fix typo in docker routing documentation

docs/content/reference/dynamic-configuration/kubernetes-crd.yml, integration/fixtures/k8s/05-ingressroutetcp.yml, pkg/provider/kubernetes/crd/fixtures/tcp/services.yml, pkg/provider/kubernetes/crd/fixtures/tcp/with_different_services_ns.yml, pkg/provider/kubernetes/crd/kubernetes_tcp.go, pkg/provider/kubernetes/crd/kubernetes_test.go, pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroutetcp.go
Add a namespace attribute on `IngressRouteTCP` service.
Allow to specify a namespace to reference a Kubernetes service from `IngressRouteTCP`.
=> Add namespace attribute on IngressRouteTCP service

docs/content/providers/kubernetes-ingress.md, docs/content/routing/providers/kubernetes-ingress.md, docs/mkdocs.yml, integration/testdata/rawdata-ingress.json, pkg/provider/kubernetes/ingress/annotations.go, pkg/provider/kubernetes/ingress/annotations_test.go, pkg/provider/kubernetes/ingress/fixtures/Ingress-with-annotations_endpoint.yml, pkg/provider/kubernetes/ingress/fixtures/Ingress-with-annotations_ingress.yml, pkg/provider/kubernetes/ingress/fixtures/Ingress-with-annotations_service.yml, pkg/provider/kubernetes/ingress/kubernetes.go, pkg/provider/kubernetes/ingress/kubernetes_test.go
Add Ingress annotations support.
Fixes #6074
=> Add Ingress annotations support

docs/content/providers/overview.md, docs/content/routing/entrypoints.md
Update supported providers list.
=> Update supported providers list.

pkg/provider/docker/config.go, pkg/provider/docker/config_test.go
Throw an error instead of panic when the service definition is invalid.
```
Stack: goroutine 38 [running]:
runtime/debug.Stack(0xc0000e8000, 0x25581e1, 0x17)
/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x210c480, 0x3fbcdb0)
/go/src/github.com/containous/traefik/pkg/safe/routine.go:160 +0xb1
github.com/containous/traefik/v2/pkg/safe.OperationWithRecover.func1.1(0xc00022fd78)
/go/src/github.com/containous/traefik/pkg/safe/routine.go:168 +0x56
panic(0x210c480, 0x3fbcdb0)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/containous/traefik/v2/pkg/provider/docker.(*Provider).addServer(0xc00014d2d0, 0x29b4960, 0xc00067cc00, 0xc000616300, 0x40, 0xc000647535, 0xb, 0xc000647535, 0xb, 0xc00067c4b0, ...) …
```
=> fix: invalid service definition.

pkg/provider/docker/config.go, pkg/provider/docker/config_test.go
Fix #6187 
When using `useBindPortIP`, we were using the indicated port instead of the calculated port.
=> Use the calculated port when useBindPortIP is enabled

pkg/provider/kubernetes/ingress/kubernetes.go
This PR moves the call to updateIngressStatus so that it is always called, whereas previously it would not have been called in .e.g some error cases. While we were at it, also added a small refactor to unindent some code.
This should have done (or at least discussed) in https://github.com/containous/traefik/pull/6121, but IMO the review got rushed.
=> systematically call updateIngressStatus

pkg/provider/kv/kv.go
Use the provider name instead of the store name as concrete provider name.
https://github.com/abronan/valkeyrie/blob/1ae9442de16e0751c9bcc51fdb1c8300bf4fa835/store/store.go#L18
Fixes #6209 
=> fix: etcd provider name.

Gopkg.lock, Gopkg.toml, vendor/github.com/decker502/dnspod-go/domains.go
Fix dnspod certificate update.
I have encountered this problem. The certificate cannot be update correctly.
```
acme: error cleaning up: API call failed: json: cannot unmarshal number into Go struct field DomainInfo.share_total of type string
```
Dnspod updated API struct. `DomainInfo.ShareTotal` from `string` to `int`.
=> Fix dnspod update.

pkg/responsemodifiers/response_modifier.go, pkg/server/aggregator.go, pkg/server/middleware/middlewares.go, pkg/server/middleware/middlewares_test.go, pkg/server/provider/provider.go, pkg/server/provider/provider_test.go, pkg/server/router/router.go, pkg/server/router/tcp/router.go, pkg/server/service/service.go, pkg/server/service/service_test.go, pkg/server/service/tcp/service.go, pkg/server/service/tcp/service_test.go
Since the references to middlewares in the config of a chain middleware are not necessarily fully provider-qualified names (i.e. without the trailing "@provider" part), when that is the case, and we want to find the corresponding configuration for each of these references, we have to rely on the provider for the chain itself. This was not handled properly when recursively creating http handlers for the response modifier.
Fixes #5890 
=> use provider-qualified name when recursing for chain

docs/content/https/acme.md
Small documentation fix to change
```
--certificatesResolvers.le.acme.dnsChallenge.resolvers:=1.1.1.1:53,8.8.8.8:53
```
to
```
--certificatesResolvers.le.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53
```
The existing documentation is wrong and results in the syntax error:
> command traefik error: failed to decode configuration from flags: field not found, node: resolvers:
=> Documentation fix for acme.md CLI

pkg/provider/kubernetes/ingress/fixtures/Ingress-with-wildcard-host_endpoint.yml, pkg/provider/kubernetes/ingress/fixtures/Ingress-with-wildcard-host_ingress.yml, pkg/provider/kubernetes/ingress/fixtures/Ingress-with-wildcard-host_service.yml, pkg/provider/kubernetes/ingress/kubernetes.go, pkg/provider/kubernetes/ingress/kubernetes_test.go
Tests the host in an ingress for a wildcard host prefix, and builds a HostRegexp rule instead of a Host rule.
Fixes #6250
=> Allow wildcard hosts in ingress provider

pkg/provider/acme/provider.go, pkg/provider/file/file.go, pkg/provider/kubernetes/crd/kubernetes.go, pkg/provider/kubernetes/ingress/kubernetes.go, pkg/provider/marathon/marathon.go, pkg/safe/routine.go, pkg/safe/routine_test.go, pkg/server/configurationwatcher.go, pkg/server/server.go, pkg/server/server_signals.go, pkg/server/server_signals_windows.go
Change all the old style `pool.Go` to `pool.GoCtx`
Fix stucked go routine in kubernetes providers when `pool.Stop()`
=> Fix kubernetes providers shutdown and clean safe.Pool

pkg/middlewares/auth/forward.go
This PR changes the way to create the http client in the forward auth middleware.
Before this modification, the http client was created for each request. When it was done without configuring tls, it was not a big problem, because we reused the `http.DefaultTransport` but when tls was activated, the` http.Transport` was created in each request, and that automatically creates a new connection to the forward auth server, and since we have not configured an expiration time on the idle connection on these transports, we have kept the connections open forever.
Fixes #6229
=> don't create http client for each request in forwardAuth middleware

middlewares/auth/authenticator.go, middlewares/auth/forward.go
Same as #6267 but for v1.7
This PR changes the way to create the http client in the forward auth middleware.
Before this modification, the http client was created for each request. When it was done without configuring tls, it was not a big problem, because we reused the `http.DefaultTransport` but when tls was activated, the` http.Transport` was created in each request, and that automatically creates a new connection to the forward auth server, and since we have not configured an expiration time on the idle connection on these transports, we have kept the connections open forever.
Fixes #6229
=> don't create http client in each request in forward auth

tls/certificate.go, tls/certificate_test.go
Fixes domain to certificate matching when ACME is enabled and non-acme certificates are provided via configuration.
Currently the domain to certificate matching algorithm [here](https://github.com/containous/traefik/blob/f68b6294693b01fd18fcd1f1dd5818be6d0c2c85/acme/acme.go#L611) fails and the default certificate is served. The result is that if two or more non-ACME certificates are provided, only the first one is used.
HTTPS requests to domains not covered by the default certificate fail.
I am not aware of the project's architecture, or whether the place where I added the call to `BuildNameToCertificate` is the best place for it.
=> Fix finding proper provided certificate when ACME is enabled

go.mod, go.sum, integration/redis_test.go
Update valkeyrie to fix the support of Redis. 
Fixes #6210
-  ~~[ ] Added/updated documentation~~
=> Update valkeyrie to fix the support of Redis.

README.md, docs/content/contributing/submitting-pull-requests.md
This PR fixes in the README file and the contributing guide.
=> Minor readme improvements

pkg/tcp/router.go
Use Debugf logging instead of Errorf for client related error .
My traefik instance is flooded by the following logs:
```json
{
"level": "error",	
"msg": "Error while Peeking first byte: read tcp 10.100.10.107:443->X.X.X.X:49742: read: connection reset by peer",
"time": "2020-01-20T08:58:34Z"
}	
```
This patch will allow to not be bothered by those errors due to clients closing connection while opening connection.
=> Decrease log level for client related error

pkg/server/configurationwatcher.go, pkg/server/configurationwatcher_test.go
The configuration reloading code takes various actions in order to limit the number of reloads that have to be performed.
One of those actions is to check if the new configuration is the same as the current configuration. 
If the new configuration is the same, then there is no need to apply it and it can be safely ignored.
However, the check was performed at the wrong location.
The location assumed that the `c.currentConfiguration`s variable is up to date.
This assumption does not hold given the throttling and asynchronous handling of configuration updates.
The effect of this incorrect assumption is that a configuration update can be thrown away and leave a prior configuration in place.
This resolves the problem by moving the check to the `loadMessage` method.
This is the point where the …
=> Don't throw away valid configuration updates

docs/content/providers/docker.md, pkg/provider/docker/config.go
When traefik cannot identify the ip address of the container, it returns 127.0.0.1 no matter what. This behavior is not desirable in many situations (i.e. exposed container running in network_mode = host while traefik doesn't, docker desktop, ...)
It solves https://github.com/containous/traefik/issues/5559 and https://github.com/containous/traefik/issues/5535 and maybe a few other I didn't catch
For this to work in linux, https://github.com/moby/moby/pull/40007 needs to be merged. In the meantime you need to define "host.docker.internal" using extra_hosts if you want to take advantage of it.
In any case, this won't alter the current behavior. If you are running traefik in network_mode host or on a platform/version that does not provide the dns record its behavior won't change.
=> Fix traefik behavior when network_mode is host

pkg/server/service/managerfactory.go
fix: return an error when ping is not enabled.
Fixes #6297
```
Stack: goroutine 94 [running]:
github.com/containous/traefik/v2/pkg/middlewares/recovery.recoverFunc(0x29c82c0, 0xc000179aa0, 0x29be840, 0xc000424760, 0xc00021ea00)
/go/src/github.com/containous/traefik/pkg/middlewares/recovery/recovery.go:47 +0x1db
panic(0x211bd20, 0x3fd7e30)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/containous/traefik/v2/pkg/ping.(*Handler).ServeHTTP(0x0, 0x29be840, 0xc000424760, 0xc00021ec00)
/go/src/github.com/containous/traefik/pkg/ping/ping.go:31 +0x26
github.com/containous/traefik/v2/pkg/middlewares/tracing.(*forwarderMiddleware).ServeHTTP(0xc000272c60, 0x29be840, 0xc000424760, 0xc00021ec00)
/go/src/github.com/containous/traefik/pkg/middlewares/tracing/forwarder.go:38 +0x610 …
```
=> fix: return an error when ping is not enabled.

docs/content/providers/consul-catalog.md, integration/consul_catalog_test.go, pkg/provider/consulcatalog/consul_catalog.go
Early filter of the catalog services.
Instead of making a request by service and then filtering the service, the services are filtered directly when the list of service is retrieved.
This greatly reduces the number of catalog requests.
Closes #6266
=> Early filter of the catalog services.

docs/content/observability/access-logs.md, integration/simple_test.go, pkg/middlewares/accesslog/logdata.go, pkg/middlewares/accesslog/logger.go, pkg/middlewares/accesslog/logger_test.go
Added to the logger the http request scheme HTTP/HTTPS.
Fixes #6130 
Got solution from https://github.com/golang/go/issues/28940#issuecomment-441749380.
Need to add test for the https scheme, but could not figure it out. If someone could give me some directions please.
=> Add http request scheme to logger

docs/content/providers/kubernetes-ingress.md
Updates a doc page to clarify the format of the value for `providers.kubernetesingress.ingressendpoint.publishedservice`
I used the key=value wrong based on the example. Once I saw the traefik log output saying I needed to enter the value in the format of namespace/service my simple setup worked. I'm assuming for this doc change that it always needs to be in that format for any use of `publishedservice` across TOML/YAML/arg.
=> Docs: Clarifying format of ingress endpoint service name

docs/content/migration/v1-to-v2.md
Removes TLS cipher suites from configuration where TLS minVersion is set to 1.3.
According to the Traefik [cipher suites documentation](https://docs.traefik.io/https/tls/#cipher-suites), cipher suites cannot be configured for TLS 1.3. In the v1 to v2 migration section, they are being configured for TLS 1.3.
=> Remove TLS cipher suites for TLS minVersion 1.3

integration/fixtures/tcp/service_errors.toml, integration/fixtures/udp/service_errors.toml, integration/simple_test.go, pkg/server/router/udp/router.go
Before this PR, if more than one udp services was attached to same entrypoint, we randomly built only one.
After the PR, all services are built and we use the first one (in natural order on the service name).
Fix a flaky test because, sometimes we didn't build the service with an error.
Fixes #6310
=> Build all UDP services on an entrypoint

integration/testdata/rawdata-ingress.json, pkg/provider/kubernetes/ingress/kubernetes.go, pkg/provider/kubernetes/ingress/kubernetes_test.go
Use the namespace and the name of the Ingress to create a more unique router name.
Fixes #6320
=> Improvement of the unique name of the router for Ingress.

docs/content/routing/providers/consul-catalog.md, docs/content/routing/providers/docker.md, docs/content/routing/providers/marathon.md, docs/content/routing/providers/rancher.md, pkg/config/label/label.go, pkg/config/label/label_test.go, pkg/provider/configuration.go, pkg/provider/consulcatalog/config.go, pkg/provider/consulcatalog/config_test.go, pkg/provider/docker/config.go, pkg/provider/docker/config_test.go, pkg/provider/kv/kv_test.go, pkg/provider/marathon/config.go, pkg/provider/marathon/config_test.go, pkg/provider/rancher/config.go, pkg/provider/rancher/config_test.go
This PR handles UDP on all providers with labels .
Being able to define UDP load balancing using labels in rancher, consulcatalog, docker and marathon.
=> Add UDP in providers with labels

pkg/tls/certificate.go
**What does this PR do?**
Fix a typo.
=> Fix typo in the godoc of TLS option MaxVersion

docs/content/routing/providers/kubernetes-crd.md, pkg/provider/kubernetes/crd/kubernetes_http.go, pkg/provider/kubernetes/crd/kubernetes_test.go
This PR allows the same code to determine if an externalName service should use the HTTPS protocol as the non-externalName Service
Fixes #6344 
This also should allow h2c as a backend protocol too!
=> Use consistent protocol determination

pkg/provider/kubernetes/crd/client.go, pkg/provider/kubernetes/ingress/client.go
This PR starts the informer on secrets with the other informers, and before the caches are synched. This allows the listers to have access to secrets on the first informer trigger.
Fixes #3667 
Avoid log on startup
```
level=error msg="Error while reading basic auth middleware: failed to load auth credentials: secret 'traefik/traefik' not found" middlewareName=traefik-auth providerName=kubernetescrd
level=error msg="middleware \"traefik-auth@kubernetescrd\" does not exist" routerName=traefik-traefik-86717a050e7497cf6af6@kubernetescrd entryPointName=traefik
level=error msg="middleware \"traefik-auth@kubernetescrd\" does not exist" entryPointName=web routerName=traefik-traefik-86717a050e7497cf6af6@kubernetescrd
level=error msg="Error while reading basic auth middleware: failed to load auth …
```
=> Fix secret informer load

pkg/server/router/router.go, pkg/server/tcprouterfactory.go
Healthcheck was launch two times at each configuration refresh, and it can create some side effect. Now the healthcheck is launch only one time at each configuration refresh.
Fixes #6096
=> Launch healhcheck only one time instead of two

pkg/tcp/router.go
We consider SSLv2 as TLS in the routing system, by doing this, the SSLv2 request will be forward to the TLS handshake that will be able to refuse the handshake correctly
Fixes #6358
=> Consider SSLv2 as TLS in order to close the handshake correctly

pkg/provider/consulcatalog/config.go, pkg/provider/consulcatalog/config_test.go
fix: consul-catalog use port from label instead of item port.
The label `traefik.http.services.xxx.loadbalancer.server.port` had no effect.
https://community.containo.us/t/override-consul-port-via-tags/4521
=> fix: consul-catalog use port from label instead of item port.

pkg/api/handler_overview.go, pkg/api/testdata/overview-dynamic.json, pkg/api/testdata/overview-empty.json, pkg/api/testdata/overview-features.json, pkg/api/testdata/overview-providers.json, webui/src/_mixins/GetTableProps.js, webui/src/_services/UdpService.js, webui/src/components/_commons/NavBar.vue, webui/src/components/_commons/PanelServers.vue, webui/src/pages/_commons/RouterDetail.vue, webui/src/pages/_commons/ServiceDetail.vue, webui/src/pages/dashboard/Index.vue, webui/src/pages/udp/Routers.vue, webui/src/pages/udp/Services.vue, webui/src/router/routes.js, webui/src/store/index.js, webui/src/store/udp/actions.js, webui/src/store/udp/getters.js, webui/src/store/udp/index.js, webui/src/store/udp/mutations.js, webui/src/store/udp/mutations.spec.js, webui/src/store/udp/state.js
Add UDP pages.
Traefik is now compatible with UDP.
=> WebUI: add udp pages

docs/content/migration/v2.md
Use explicitly the word Kubernetes in the migration guide.
Have better documentation
Fixes #6378
=> Use explicitly the word Kubernetes in the migration guide.

pkg/provider/file/file.go
Watches for delete events on the watched config file, and re-register the watch on the same file.
This allows configmaps to be updated in k8s, and have traefik follow the new updated code.
See:
https://martensson.io/go-fsnotify-and-kubernetes-configmaps/
http://thrawn01.org/posts/2016/03/22/howto-write-configmap-enabled-golang-microservices/
https://medium.com/@xcoulon/kubernetes-configmap-hot-reload-in-action-with-viper-d413128a1c9a
Fixes the original issue in #1188
=> Allow fsnotify to reload config files on k8s (or symlinks)

docs/user-guide/docker-and-lets-encrypt.md
- remove invalid sentence about label and backend
- use "segment label" instead of "service label"
Fixes #6385
=> Fix typo in user guide.

docs/user-guide/kubernetes.md
The rbac and demonset deployment bloc are out of date with the linked yaml files. This PR updates the example bloc with the yaml code linked in the associated URL
if you try to copy those blocs and deploy with "kubectl apply -f local_file" you'll fail with
error: error validating "traefik-ds.yaml": error validating data: ValidationError(DaemonSet.spec): missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec; if you choose to ignore these errors, turn validation off with --validate=false
as the "selector" fields are required in v1 of the API.
=> Updated rbac and demonset example bloc

pkg/provider/file/file.go
This PR revert the PR #5037 
The PR #5037 generates error messaging:
```
ERRO[2020-03-02T23:22:35+01:00] Could not remove watcher for /home/juliens/test: can't remove non-existent inotify watch for: /home/juliens/test/4913  providerName=file
ERRO[2020-03-02T23:23:09+01:00] Could not remove watcher for /home/juliens/test: can't remove non-existent inotify watch for: /home/juliens/test/4913  providerName=file
```
We need to think more about a solution to handle this.
=> Revert "Allow fsnotify to reload config files on k8s (or symlinks)"

pkg/metrics/datadog.go, pkg/metrics/influxdb.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/metrics/prometheus.go, pkg/metrics/statsd.go, pkg/middlewares/metrics/metrics.go
Fixes #5944  
StatsD assumes that duration based metric values are in Milliseconds.
Currently Traefik always calls the `Observe` function converting the `time.Duration` to seconds. With this change we can set the scale in the metric provider implementation, on statsD case Milliseconds, while keeping the current value as the default for those that don't specify it.
=> fix statsd scale for duration based metrics

cmd/traefik/traefik.go, integration/testdata/rawdata-ingress.json, pkg/server/aggregator.go, pkg/server/configurationwatcher.go
Create a copy of the router before cleaning the list of entry points.
The bug is related to the following line:
https://github.com/containous/traefik/blob/99861ac808b66ce44322269c819688d04ff22b6f/pkg/server/configurationwatcher.go#L144
To reproduce:
<details>
<summary>docker-compose.yml</summary>
```yml
version: '3.7'
services:
traefik:
image: traefik:v2.2.0-rc1
command:
- --log.level=DEBUG
- --api
- --entrypoints.web.address=:80
- --entrypoints.web.http.redirections.entrypoint.to=websecure
- --entrypoints.web.http.redirections.entrypoint.scheme=https
- --entrypoints.websecure.address=:443
- --entrypoints.websecure.http.tls=true
- --providers.docker.exposedbydefault=false
- --providers.file.directory=/config/
- --providers.file.watch=true
ports:
- 80:80
- 443:443
volumes:
- …
```
=> Router entry points on reload.

docs/content/routing/providers/kubernetes-crd.md, integration/fixtures/k8s/02-services.yml, integration/fixtures/k8s/05-ingressroutetcp.yml, integration/testdata/rawdata-crd.json, pkg/provider/kubernetes/crd/fixtures/services.yml, pkg/provider/kubernetes/crd/fixtures/tcp/services.yml, pkg/provider/kubernetes/crd/fixtures/tcp/with_externalname.yml, pkg/provider/kubernetes/crd/fixtures/tcp/with_externalname_with_port.yml, pkg/provider/kubernetes/crd/fixtures/tcp/with_externalname_without_ports.yml, pkg/provider/kubernetes/crd/fixtures/with_externalname.yml, pkg/provider/kubernetes/crd/fixtures/with_externalname_with_http.yml, pkg/provider/kubernetes/crd/fixtures/with_externalname_with_https.yml, pkg/provider/kubernetes/crd/fixtures/with_externalname_without_ports.yml, pkg/provider/kubernetes/crd/kubernetes.go, pkg/provider/kubernetes/crd/kubernetes_http.go, pkg/provider/kubernetes/crd/kubernetes_tcp.go, pkg/provider/kubernetes/crd/kubernetes_test.go
Improve kubernetes external name service support by allowing three ways to define port for backends
fixes #6390 
=> Improve kubernetes external name service support

docs/content/providers/docker.md
Fix typo in documentation
The default doesn't have the `s` unit, the example should probably not have it either :)
https://github.com/containous/traefik/blob/09c07f45ee999fad6dc97463b4b825fb08c7c34b/pkg/provider/docker/docker.go#L68
Was reading the documentation, find it confusing :grin: 
You're all incredible people and this is an amazing software! :tada:
=> Fix example values for swarmModeRefreshSeconds

docs/content/routing/routers/index.md
This PR reworks a bit the documentation, to move the passthrough option in its own section.
Perfectionism.
=> Specify passthrough for TCP/TLS in its own section

CHANGELOG.md
Prepare release v2.2.0-rc2
aka `chevrotin`
=> Prepare release v2.2.0-rc2

docs/content/middlewares/basicauth.md
Fix cryptographic-related terminology in documentation.
The term 'encoded' for passwords being hashed (by MD5, SHA1 or BCrypt) is wrong and can be misleading.
=> docs: terminology, replace 'encoded' by 'hashed'

pkg/middlewares/headers/headers.go, pkg/middlewares/headers/headers_test.go
Allow to override the request Host header with the Header middleware.
Fix #6500,  #5966, #6000
=> fix: custom Host header.

docs/content/migration/v2.md, docs/content/routing/providers/kubernetes-ingress.md, integration/testdata/rawdata-ingress.json, pkg/provider/kubernetes/ingress/fixtures/TLS-support_ingress.yml, pkg/provider/kubernetes/ingress/kubernetes.go
Now, the TLS section in a Ingress don't control the activation of the TLS.
To enable TLS:
- use the TLS configuration on the entry point: https://docs.traefik.io/v2.2/routing/entrypoints/#tls
- use annotation `traefik.ingress.kubernetes.io/router.tls: "true"`: https://docs.traefik.io/v2.2/routing/providers/kubernetes-ingress/#on-ingress
Fixes #6501,#6506
Co-authored-by: Julien Salleyron <julien@containo.us>
=> fix: Ingress TLS support

integration/udp_test.go, pkg/server/server_entrypoint_tcp_test.go, pkg/server/server_entrypoint_udp_test.go, pkg/udp/conn.go, pkg/udp/conn_test.go
This PR removes the use of a timer for timeouts, replacing it with a ticker instead.
The timer was wrongly used because:
1) it was being reset concurrently (without any locking).
2) it was being reset in cases where its channel might have not been drained
The situation might have been fixed in various ways while still using a timer, but it seems simpler for now to have a ticker instead.
Fixes #6494 
=> udp: replace concurrently reset timer with ticker

docs/content/routing/entrypoints.md, pkg/config/static/entrypoints.go, pkg/provider/traefik/fixtures/redirection_port.json, pkg/provider/traefik/internal.go, pkg/provider/traefik/internal_test.go
Allows to :
- set `permanent` to false.
- set `priority`
- use a port instead of entry point name.
Fixes #6474
=> Fix entry point redirect behavior

docs/content/https/include-acme-single-domain-example.md
Fix a typo.
No contribution is totally useless. (again!)
=> Doc: fix wrong name of config format

pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/middlewares/metrics/metrics.go
Fix a memory leak in metrics.
Fixes #6520 
=> Fix memory leak in metrics

CHANGELOG.md
Prepare release v2.2.0-rc4
aka `chevrotin`
=> Prepare release v2.2.0-rc4

docs/content/https/include-acme-single-domain-example.md
Fix tab name in sample
In the current docs for the page
https://docs.traefik.io/https/acme/
expanding examples:
there is a mismatch on the tab `File (TOML)`
=> Fix tab name

docs/content/reference/dynamic-configuration/docker-labels.yml, docs/content/reference/dynamic-configuration/file.toml, docs/content/reference/dynamic-configuration/file.yaml, docs/content/reference/dynamic-configuration/marathon-labels.json, docs/content/routing/providers/consul-catalog.md, docs/content/routing/providers/docker.md, docs/content/routing/providers/kubernetes-crd.md, docs/content/routing/providers/marathon.md, docs/content/routing/providers/rancher.md, docs/content/routing/services/index.md, go.mod, go.sum, pkg/config/dynamic/http_config.go, pkg/server/service/service.go
Allow to configure cookie option:
- sameSite
Fixes #6261
~~Waiting for https://github.com/vulcand/oxy/pull/195~~
=> Fix sameSite (Traefik v2)

server/server.go, server/server_configuration.go, server/server_loadbalancer.go, server/smart_roundtripper.go
This PR force the use of http1.1 with the backend when the request is a `Connection:Upgrade` because `Connection: Upgrade` is not valid for http2.
Some kubernetes api server refuse http2 during tls-alpn (like k3s) but some other just don't (like kind) and so, SPDY upgrade fails. This PR fixes this behavior.
Fixes #6527 
=> Force http/1.1 for upgrade (Traefik v1)

build.Dockerfile, docs/content/contributing/building-testing.md, exp.Dockerfile, go.mod, pkg/server/service/roundtripper.go, pkg/server/service/smart_roundtripper.go
This PR forces the use of http1.1 with the backend when the request is a `Connection:Upgrade` because `Connection: Upgrade` is not valid for http2.
Also, this PR fixes the fact that specifying root CAs and specifying insecureskipverify was mutually exclusive.
Some kubernetes api server refuse http2 during tls-alpn (like k3s) but some other just don't (like kind) and so, SPDY upgrade fails. This PR fixes this behavior.
Fixes #6527 
=> Force http/1.1 for upgrade (Traefik v2)

go.mod, go.sum, pkg/middlewares/auth/basic_auth.go, pkg/middlewares/auth/digest_auth.go
This PR adds support for the stale header option, so that the digest auth middleware can use it when replying to a request that is correctly (correct username and password) authenticated, but with a nonce counter that is not the expected one. We distinguish two cases:
- if the nonce counter is the same as the previously seen one, it is still considered a replay attack, and the behaviour stays the same as before.
- if the nonce counter is inferior to the expected one, one of the possible reasons is because requests arrived out of order, and is the cause of the observed issue. In this case, we use the new RequireAuthStale method, which uses the header mentioned above, to signal the client (the browser) that it should retry with the same credentials, without having to prompt the user for the …
=> digest auth: use RequireAuthStale when appropriate

pkg/provider/kubernetes/ingress/client.go
Delete a confusing log when a deprecated apiVersion is used for a Kubernetes Ingress.
How apiVersion is handled depends on the version of Kubernetes and could generate many unnecessary warning logs.
Fixes #6536
=> Delete an unnecessary warning log

docs/content/routing/entrypoints.md
This PR updates the documentation for CLI entrypoint redirects. I believe there was a typo. The CLI config didn't match the TOML/YAML configs. When I used the parameters in the docs, I got the error shown below. Switching my CLI args to match the TOML and YAML representations fixed the issue.
Quarantine.
Traefik rocks :metal:
=> Doc Fix for 2.2 Redirects

pkg/config/static/entrypoints.go
Change the default priority on the router created by the redirect.
Have a better default behavior.
=> Change the default priority on the router created by the redirect.

webui/src/components/_commons/PanelTLS.vue
Correct a typo when no TLS is configured.
Um, grammar?
This is based on the assumption that a router can only have 1 TLS configuration. If not, then the language still needs changing, just in a slightly different way.
=> It's just the one TLS, actually.

docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/routing/services/index.md, pkg/config/static/entrypoints.go
=> Fix documentation

docs/content/observability/tracing/overview.md
- Makes it easier to find page with docs on tracing powered by elastic APM from [overview page](https://docs.traefik.io/observability/tracing/overview/).
- I was looking for documentation on how to enable tracing using elastic. At first glance on the overview page, there is a list of all the supported tracing backends but it leaves out `Elastic` which is included on the side navigation. To save anyone else looking for the page on integrating with elastic some seconds, I have included the link on the overview page.
=> Add link to tracing with elastic

pkg/server/configurationwatcher.go
This PR considers UDP when checking for an empty configuration in the configuration watcher.
Allow UDP only dynamic configurations.
=> fix: consider UDP when checking for empty config

pkg/server/service/proxy.go
Force Sec-WebSocket-Version header case to fix Handshake problem on various Websocket implementations
There are various Websocket implementations out there, which are not case insensitive. This fix makes the Websocket implementation more robust.
=> Fix case-sensitive header Sec-Websocket-Version

docs/content/migration/v1-to-v2.md
Add a hint to the migration documentation, that the default configuration of the access logs in v2 won't log the same details as v1 anymore.
Stumbled across the need of reconfiguration later in my migration path and would loved to get a hint right at the beginning of my configuration adaptions.
-
=> Add Access log chapter for migration v1->v2

docs/content/routing/providers/kubernetes-crd.md
Adds a sentence about the fact, that the namespace of a middleware is internally added automatically, as it's important when you want to reference that middleware from another provider.
Enhance our Docs
Fix #6318
=> Add sentence about the resource namespace and middleware

webui/src/components/_commons/ToolBar.vue
Fix #6610 by polling `getOverview` in the toolbar.
Up to date numbers
=> Add polling for getOverview in toolbar

docs/content/getting-started/install-traefik.md
Fix the helm chart documentation
Sync documentation with the helm hcart
=> Update the documentation for helm chart

pkg/config/dynamic/middlewares.go, pkg/middlewares/extractor.go, pkg/middlewares/inflightreq/inflight_req.go, pkg/middlewares/ratelimiter/rate_limiter_test.go, pkg/provider/consulcatalog/config_test.go, pkg/provider/docker/config_test.go, pkg/provider/marathon/config_test.go
This PR removes ipstrategy being systematically set as the default source
criterion, which was causing any other source criterion provided in the config
to be ignored.
We already take care of setting ipstrategy as the default in the rate limiter
constructor anyway.
Fixes #6687
=> ratelimit: do not default to ipstrategy too early

webui/package.json
It disables the distribution of the WebUI as a PWA, as there is no strong benefit of distributing it as a PWA currently but instead adds some complexity and confuses our users.
Fixes #6514
=> Disable distribution of the WebUI as PWA

pkg/middlewares/forwardedheaders/forwarded_header.go, pkg/middlewares/forwardedheaders/forwarded_header_test.go
If we have two Traefik and the first one put x-forwarded-proto to `wss`, the second one will overwrite with `https`
Fix a bug with wss x-forwarded-proto.
=> Fix wss in x-forwarded-proto

docs/content/https/acme.md, docs/content/https/ref-acme.txt
When reading the current documentation I noticed the Let's Encrypt section shows the acme CLI flags in camelCase format instead of lowercase, which is different from other sections of documentation such as the CLI configuration [reference](https://docs.traefik.io/reference/static-configuration/cli/). Because of that, this PR updates the flags to keep homogeneous documentation. Example:
From: `--certificatesResolvers.<name>.acme.caServer`
To: `--certificatesresolvers.<name>.acme.caserver`
My main motivation is to improve the documentation in a way that avoids newcomers get confused.
=> Improve acme CLI options in Let's Encrypt documentation 

docs/content/providers/kubernetes-ingress.md
Removes redundant paragraph in the Kubernetes Ingress  [doc page](https://docs.traefik.io/providers/kubernetes-ingress/#letsencrypt-support-with-the-ingress-provider_1).
There were two identical paragraphs in the doc page.
=> Remove redundant paragraph in Kubernetes ingress documentation

docs/configuration/entrypoints.md
Improve doc on v1.7 regarding entrypoints whitelisting by adding a brief description of the behavior when enabling `useXForwardedFor` and a warning to users behind another load balancer.
To fix #5816
=> Doc improvement on entrypoints whitelist for v1.7

docs/content/observability/access-logs.md
Updates the access logging docs regarding the field for headers.
The descriptive text above the code sample is incorrect - the value is `headers`.
=> Use "headers" instead of "header" in access log docs

docs/content/routing/providers/docker.md
Fixing "time: missing unit in duration 10"
Because this feature used time.ParseDuration library .
:-)
=> Fix healthcheck.interval in docs

pkg/provider/docker/config.go
When defining a service in the docker provider which is pointing to a container with a networking mode of `host:other-container`, the `traefik.docker.network` was ignored and an arbitrary IP of the `other-container` was used as the upstream.
If that IP is not routable from the Traefik instance, this could cause Gateway Timeouts.
This change adds steps to parse configuration from labels on the connected container from which the service container inherits its network.
My strawman fix prioritises the `traefik.docker.network` label on the network-owning container, but falls back to the network specified on the service container. Perhaps this should be flipped, but the network-owning container is the authoritative source of which networks it is connected to, so this makes sense to me.
I have a …
=> Use specified network for "container" network mode

docs/content/middlewares/headers.md
fix: dead link
fix: dead link
-  ~[ ] Added/updated tests~
=> fix: dead link.

pkg/udp/conn.go
Fix a memory / go routine leak on udp connections, specifically in allocating a new `time.Ticker` under the `Conn` struct.
**No expert here**, but after taking a heap profile in a stress test which created lots of new udp connections it showed that we were leaking memory, and probably go routines (runtime malg), as we allocated a time.Ticker in `udp.(*Listener)newConn`. This is also consistent with the profile sent on #6761.
It could be that the `Ticker`, which was referenced by the `Conn`, was not being collected by the GC, justifying the dead go routines and memory leak.
Changing the implementation to allocate and stop the ticker in the main `readLoop` seems to solve the memory and go routine problems as demonstrated in the new profile taken after running the same stress test:
Issue …
=> Fix mem leak on UDP connections

pkg/udp/conn.go, pkg/udp/conn_test.go
Fix: Avoid overwriting already received UDP messages.
Receiving UDP datagrams in quick succession may overwrite already received data. If the message queue is not empty, another read from the connection into the buffer seems to alter the content of already received packets.
This PR fixes the issue by creating a new read buffer for every datagram to avoid overwriting existing data.
Fix issue with incoming UDP packets overwriting data of already received UDP packets reported in bug #6796.
- Add a test which checks data integrity when receiving multiple, consecutive packets.
Unit tests passed, but integration tests failed (on my machines) with `FAIL: docker_test.go:147: DockerSuite.TestDockerContainersWithTCPLabels` or `FAIL: grpc_test.go:363: GRPCSuite.TestGRPCBufferWithFlushInterval`. …
=> Avoid overwriting already received UDP messages

docs/content/migration/v1-to-v2.md
What does this PR do?
Unify domain name in migration v1->v2 documentation.
Motivation
Have compact and clear examples.
=> Fix v1-> v2 migration: unify domain name in documentation example

docs/content/providers/docker.md
Use a link of an archived version of the Docker Documentation.
Keep valid documentation pending correction on the official doc.
To be updated when the Docker documentation will be fixed.
=> fix a broken link on Docker plugins documentation

integration/testdata/rawdata-consul.json, integration/testdata/rawdata-etcd.json, integration/testdata/rawdata-ingress.json, integration/testdata/rawdata-redis.json, integration/testdata/rawdata-zk.json, pkg/middlewares/redirect/redirect.go, pkg/middlewares/redirect/redirect_scheme.go, pkg/middlewares/redirect/redirect_scheme_test.go, pkg/provider/traefik/fixtures/api_insecure_with_dashboard.json, pkg/provider/traefik/fixtures/full_configuration.json, pkg/provider/traefik/internal.go
This PR fixes the regex used by redirect middleware to handle properly ipv6 in urls
Fixes #5197
See #5197
=> Fix ipv6 handling in redirect middleware

integration/access_log_test.go, pkg/middlewares/auth/basic_auth.go, pkg/middlewares/auth/digest_auth.go
This PR adds the username in the log data, if present, on auth failure for middlewares basic auth and digest auth.
fixes #6722
Providing the user on auth failure in the access log is an expected behavior for some tools, at least fail2ban.
=> Provide username in log data on auth failure

integration/fixtures/headers/secure_multiple.toml, integration/headers_test.go, pkg/middlewares/headers/headers.go, pkg/middlewares/headers/headers_test.go, pkg/responsemodifiers/headers.go, pkg/responsemodifiers/response_modifier.go, pkg/responsemodifiers/response_modifier_test.go
Utilizes the secureContextKey to allow different header middlewares to operate independently, without overwriting the next middleware's context key.
Fixes #5538 
Because `unrolled/secure` uses a private secureContextKey type for storage, we cannot retrieve from this project. Testing this drills down to the base secure project, which is already tested in their repo.
Therefore integration testing I feel is the best option at this point.
=> Allow multiple secure middlewares to operate independently 

docs/content/observability/access-logs.md
Fixes incorrect JSON log field names in the documentation. 
I aligned the table with the keys defined in `pkg/middlewares/accesslog/logdata.go`.
=> Fix log field names in documentation

docs/content/https/acme.md
Lego does not support the `_FILE` variables for everything. For example:
> AWS_ACCESS_KEY_ID	Managed by the AWS client (AWS_ACCESS_KEY_ID_FILE is not supported)
https://go-acme.github.io/lego/dns/route53/
Fix statement about lego _FILE env var: s/Every/Many/ and instruct reader to follow linked documentation.
I trusted the "every" in this doc so thoroughly I failed completely to notice the contradictory statement in lego's doc. I wasted most of a day chasing around `route53: NoCredentialProviders`. I disliked that, and I want future readers to have a better experience.
Traefik is amazing and I love the work y'all are doing!
I suspect the lack of support for `AWS_ACCESS_KEY_ID_FILE` has more to do with the AWS SDK than with lego or Traefik.
=> Fix statement about lego _FILE env var

docs/content/operations/ping.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, integration/fixtures/custom_ping_termination_status_code.toml, integration/simple_test.go, pkg/ping/ping.go
Allow custom http code in ping route when Traefik is terminating (graceful shutdown)
Issue https://github.com/containous/traefik/issues/6688 
Better handling of graceful shutdown with Kubernetes livenessprobe.
=> Add custom ping http code when Traefik is terminating

docs/content/https/include-acme-multiple-domains-from-rule-example.md, docs/content/https/include-acme-single-domain-example.md
This PR fixes a typo at "certresolver" in the Kubernates examples.
Unfortunately, this error took me half a day to find. I hope I spare others the search. ;-)
=> fix certResolver typo

webui/src/components/_commons/PanelMiddlewares.vue
`ACCESS CONTROL ALLOW ORIGIN` section in middleware section of router view doesn't list values from `accessControlAllowOriginList` options, but instead tries to print `accessControlAllowOrigin`. This PR fixes it.
I wanted to see the value set in `accessControlAllowOriginList` option in Traefik dashboard.
I didn't have a chance to run it locally.
=> Add missing accessControlAllowOrigin list to middleware view

pkg/server/configurationwatcher.go, pkg/server/configurationwatcher_test.go
This PR fixes race condition issues with the provided dynamic configuration by:
- Storing a deep copy of the dynamic `Message` in the configuration watcher for later comparisons.
- Providing a deep copy of the dynamic `Message` to the configuration watcher listeners.
Potential fixes: #6566
We discovered that the load balancing was not working anymore on Maesh because unchanged configurations are not skipped by mesh proxy providers, which as a side effect resets the load balancer counters.
=> Fix race condition issues with provided dynamic configuration

docs/content/operations/dashboard.md, docs/content/operations/include-dashboard-examples.md
Move the Dashboard dynamic configuration examples after the Router Rule section and change them to a combined `Host` and `PathPrefix` rule as its the most complete.
Some users get confused when trying to setup a `PathPrefix` rule on their provider. Moving it after the explanation and giving complete examples for each provider may fix this.
Last raised issue: #6872
=> Update Dashboard examples and move it after 'Router Rule' section

cmd/traefik/traefik.go, docs/content/https/tls.md, docs/content/migration/v1-to-v2.md, docs/content/migration/v2.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, docs/content/routing/routers/index.md, integration/fixtures/grpc/config.toml, integration/fixtures/grpc/config_h2c_termination.toml, integration/fixtures/grpc/config_insecure.toml, integration/fixtures/grpc/config_retry.toml, integration/grpc_test.go, pkg/config/static/static_config.go, pkg/rules/rules.go, pkg/rules/rules_test.go, pkg/server/router/router_test.go, pkg/tcp/router.go, traefik.sample.toml
This PR introduces a new default behavior to prevent domain fronting, at the router's level.
With this new behavior, all `Host` rules matchers will try to match **both** the `Host header` value **and** the `Server Name Indication` value from the TLS negotiation.
To fallback to the previous insecure behavior, a global configuration flag has been added: `InsecureSNI` (false by default).
When set to true it enables all `Host` rules matchers to match **only** the `Host header` value.
Furthermore, new rules matcher have been added: 
- `HostHeader` tries to match the `Host header` value
- `HostSNI` tries to match the `Server Name Indication` value from the TLS negotiation
Those new matchers can be used as an advanced feature to fine grain control routing.
Disabling domain fronting capability by …
=> Disable domain fronting

docs/content/https/tls.md, docs/content/migration/v2.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, pkg/config/static/static_config.go
insecureSNI is `true` by default.
related to #7020
=> Change the default value of insecureSNI

cmd/configuration.go, pkg/config/static/static_config.go
This PR fixes the `global.insecureSNI` default value when the `global` is not set.
Changes the default value for insecureSNI.
related to #7020
=> Fix default value for InsecureSNI when global is not set

pkg/provider/kubernetes/crd/kubernetes.go
The Kubernetes CRD does not know how to read in the contentType middleware.
Fixes #7005
=> fix k8s crd to read contentType middleware into dynamic config

cmd/configuration.go, cmd/traefik/traefik.go, docs/content/https/tls.md, docs/content/migration/v2.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, docs/content/routing/routers/index.md, integration/fixtures/grpc/config.toml, integration/fixtures/grpc/config_h2c_termination.toml, integration/fixtures/grpc/config_insecure.toml, integration/fixtures/grpc/config_retry.toml, integration/grpc_test.go, pkg/config/static/static_config.go, pkg/rules/rules.go, pkg/rules/rules_test.go, pkg/server/router/router_test.go, pkg/tcp/router.go, traefik.sample.toml
This PR:
- reverts the domain fronting fix (introduced in v2.2.2)
- keeps the HostHeader rule matcher for routers (introduced in v2.2.2)
This PR fallback to v2.2.1 behavior because of regression issues, notably in case of [connection reuse](https://httpwg.org/specs/rfc7540.html#reuse) with http2
Fixes #7020
=> Revert domain fronting fix

docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, pkg/config/static/entrypoints.go
Fix some typos
Have an homogeneous doc
=> fix: documentation references.

docs/content/routing/entrypoints.md
Show how to bind an entrypoint to a single ip address. Similar as earlyer by #1194.
There is not mentioned anywhere in the doc that an IP address can be set for an entry point. (Except in #1193) 
Started a list showing how to do the address matching for different orchestrators. Instructions for other orchestrators would be handy (as requested in #5059.
I linked to original sources for users can find more details themselves.
=> Add example for entrypoint on one ip address

pkg/provider/traefik/fixtures/redirection_with_protocol.json, pkg/provider/traefik/internal.go, pkg/provider/traefik/internal_test.go
Takes the entrypoints address without the protocol for the entrypoint based redirection.
Fix https://github.com/containous/traefik-helm-chart/issues/208
=> Get Entrypoints Port Address without protocol for redirect

pkg/healthcheck/healthcheck_test.go, pkg/provider/kubernetes/ingress/kubernetes_test.go, pkg/server/middleware/middlewares_test.go, pkg/server/service/tcp/service_test.go, pkg/server/service/udp/service_test.go
replaces calls to require/assert Nil/NotNil to NoError/Error
[NoError](https://godoc.org/github.com/stretchr/testify/require#NoError) is for asserting no error was return
[Error](https://godoc.org/github.com/stretchr/testify/require#Error) is for asserting an error was returned
```golang
return Fail(t, fmt.Sprintf("Received unexpected error:\n%+v", err), msgAndArgs...)
```
```golang
return Fail(t, "An error is expected but got nil.", msgAndArgs...)
```
When these fail their message explicitly calls out that we were or were not expecting an error. This communicates the intent of the assertion.
=> prefer NoError/Error over Nil/NotNil

pkg/provider/kubernetes/ingress/client.go, pkg/provider/kubernetes/ingress/client_mock_test.go, pkg/provider/kubernetes/ingress/kubernetes.go, pkg/provider/kubernetes/ingress/kubernetes_test.go
This PR fixes the parsing of the Kubernetes server version.
Fixes #7061
=> Use semantic versioning to enable ingress class support

docs/content/migration/v2.md, docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml, pkg/tls/certificate_store.go
This PR:
- Adds a migration documentation and updates the Kubernetes RBAC to support the newly introduced `IngressClass`.
- Fix some typos in the certificate store code.
Improve the `IngressClass` documentation.
=> Add migration documentation for IngressClass

docs/content/https/acme.md, docs/content/routing/providers/docker.md
This PR adds one single letter to the docs example about UDP router in docker.
Trying  to get things working, and thinking what's wrong with my config from the example. 
It's really just a single letter, anyone can make mistakes.
=> spelling(docs/content/routing/providers/docker.md)

pkg/api/dashboard.go, pkg/api/dashboard_test.go
Clean X-Forwarded-Prefix header for the dashboard.
Be safe.
=> fix: clean X-Forwarded-Prefix header for the dashboard.

docs/content/https/tls.md
Document which key of the Kubernetes secret is used to retrieve the CA certificate from for client auth.
I had a secret with key `ca.crt` which did not work. Instead of getting this information from the docs, I only saw it in the logs of traefik:
```
the tls.ca entry is missing from secret traefik/client-ca
```
=> doc: add name of used key for kubernetes client auth

docs/content/providers/kubernetes-ingress.md, docs/content/routing/providers/kubernetes-ingress.md, pkg/provider/kubernetes/ingress/client.go, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-empty-pathType_endpoint.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-empty-pathType_ingress.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-empty-pathType_service.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-exact-pathType_endpoint.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-exact-pathType_ingress.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-exact-pathType_service.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-implementationSpecific-pathType_endpoint.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-implementationSpecific-pathType_ingress.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-implementationSpecific-pathType_service.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-ingress-annotation_endpoint.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-ingress-annotation_ingress.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-ingress-annotation_service.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-no-pathType_endpoint.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-no-pathType_ingress.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-no-pathType_service.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-prefix-pathType_endpoint.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-prefix-pathType_ingress.yml, pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-prefix-pathType_service.yml, pkg/provider/kubernetes/ingress/kubernetes.go, pkg/provider/kubernetes/ingress/kubernetes_test.go
This PR introduces the support of the `pathType` property for the Kubernetes Ingress, which is available since version 1.18.
Introducing the support of the new `pathType` property.
fixes #6690
It also fixes the support for the new IngressClass, making not mandatory to use the new IngressClass in cluster of version 1.18+.
Co-authored-by: kevinpollet <pollet.kevin@gmail.com>
=> Support Kubernetes Ingress pathType

docs/content/routing/providers/kubernetes-crd.md
With the whitespace as it was the whole spec would be part of the
resource metadata which obviously won't yield the desired results.
The configuration examples in the kubernetes-crd part contain erroneous whitespace, making the whole spec part of the resource metadata. As such, these examples cannot be used as-is as the desired rules never become effective.
This PR fixes the whitespace so the examples can be used.
Low-hanging fruit to help others taking their first steps with kubernetes-crd.
None.
=> kubernetes-crd: fix whitespace in configuration examples

docs/content/providers/ecs.md, pkg/provider/ecs/ecs.go
This PR improves the automatic `Region` resolution by:
- Querying the EC2 instance metadata only in an EC2 context.
- Using the `AWS_REGION` environment variable added by AWS to the FARGATE container.
Fixes #7096
=> Improve region resolution for ECS provider

cmd/traefik/traefik.go, pkg/metrics/pilot.go, pkg/metrics/pilot_test.go, pkg/pilot/pilot.go, pkg/pilot/pilot_test.go
This PR introduce a new metric provider for the Pilot platform.
This new provider implements the metrics.Registry interface to fit in the chain of metrics provider.
It collects all the current available metrics, from Traefik server, through EntryPoints to Services metrics.
Add the ability to provide metrics to the Pilot platform for a given "Pilot enabled" Traefik instance.
=> Pilot metrics provider

pkg/config/kv/kv_node.go, pkg/config/kv/kv_test.go
Allows slashes in root key of KV-storages.
We've got single KV storage shared across many of teams. Each team have its own directory in it. My team soon to have some separated Traefiks. So it would be cool, if we can separate configurations as:
```
team-a/traefik-1
team-a/traefik-2
```
There is no information about inadmissibility of slashes neither in documentation nor in logs, only message: "invalid root label". I see two possibilities of resolving this situation: add this constraint to documentation or add this feature.
As it's technically not too complex to implement, I chose 2nd variant.
=> Allows multi-level KV prefixes

docs/content/observability/tracing/jaeger.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, go.mod, go.sum, pkg/tracing/jaeger/jaeger.go
This PR updates the `jaeger-client-go` dependency version to `v2.25.0`. 
This update allows the reconnection to the `jaeger-agent` when the connection is lost. As this new behaviour is listed as breaking in [v2.25.0](https://github.com/jaegertracing/jaeger-client-go/releases/tag/v2.25.0) a new tracing option for jaeger named `DisableAttemptReconnecting` defaulting to `true` has been introduced to be backward compatible.
Fixes #6093.
- Diff of `jaeger-client-go` https://github.com/jaegertracing/jaeger-client-go/compare/v2.22.1...v2.25.0
=> Update jaeger-client-go dependency to v2.25.0

docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
This PR updates the documentation to add the missing `networking.k8s.io` `apiGroup` to the Kubernetes RBAC. This `apiGroup` is needed to work with the new `IngressClass` resource available since Kubernetes [v1.18](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/).
I've deployed Traefik `v2.3.0-rc3` on Kubernetes `v1.18` and the `Ingress` discovery was failing because of the missing `apiGroup`.
=> docs: add missing apigroup to Kubernetes RBAC

docs/content/https/tls.md
- Makes minor language improvements in the TLS documentation page
=> doc: Minor language improvement in TLS documentation

contrib/grafana/traefik-kubernetes.json, contrib/grafana/traefik.json
This PR fixes and improves the Grafana dashboards provided as examples.
Some metrics needed to be updated:
- Prometheus metrics `traefik_backend_open_connections`, `traefik_backend_request_duration_seconds_bucket` and `traefik_backend_requests_total` [have been removed](https://github.com/containous/traefik/commit/8e97af8dc34ddd63e5ccc489089c8dbacb73f29e#diff-00c48dd481887b7f1cfa8e0edabe69d6) and replaced by `traefik_services_*`.
- In Kubernetes, label `container_name` for metrics `container_memory_usage_bytes` and `container_cpu_usage_seconds_total` [has been renamed](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.14.md#urgent-upgrade-notes) to `container`
Some panels had `"datasource": null"`, causing Grafana errors.
Some other Grafana dashboards improvements …
=> Fix & improve Grafana dashboards

docs/content/migration/v2.md
This change reorders the migrations for v2 to follow the releases from bottom to top. (Oldest migrations at the bottom, newer ones at the top.)
Currently, the order of migrations is: `2.2.2 -> 2.2.5`.  `2.0 -> 2.1`, `2.1 -> 2.2`
As someone wo is upgrading from 2.0 to 2.2, I can now follow the migrations one by one without checking the whole document, if there are other changes that might be important for the version skips I try to do.
=> Reorder migrations for v2 minor upgrades

docs/content/providers/docker.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, pkg/anonymize/anonymize_config_test.go, pkg/config/dynamic/fixtures/sample.toml, pkg/config/static/static_config.go, pkg/provider/docker/docker.go
This PR adds a new configuration option on the Docker provider setting the HTTP client timeout when a HTTP endpoint is used. It also sets a default of 1 hour, which should probably be debated as there is currently _no_ timeout by default.
Closes #7093.
Let's debate whether it's a good or a bad idea to set a default timeout of e.g. 1 hour.
=> Support configuring a HTTP client timeout in the Docker provider

docs/content/providers/kubernetes-ingress.md
Adds an example how to use the new IngressClass with Traefik
Make better docs
=> Add example for the IngressClass usage

docs/content/reference/dynamic-configuration/file.yaml, pkg/config/dynamic/middlewares.go
This PR:
- Adds a struct tag to the `IPStrategy` option for YAML. Without this tag, the deserialized option name must be `ipstrategy` which is not consistent with TOML, JSON and the documentation.
- Fixes the `IPStrategy` option name case in the file reference documentation.
Fixes #7129 
=> Add missing IPStrategy struct tag for YAML

docs/content/migration/v2.md
This PR fix the documentation to avoid misleading assumptions when reading the HostSNI rule removal section in the migration guide, by specifying the scope of the removal of the HostSNI rule to HTTP routers only.
closes #7229
=> doc: specify HostSNI rule removal only for HTTP routers

pkg/middlewares/headers/responsewriter.go
Adds `Hijack` and `Flush` methods on the response writer of the headers middleware.
Fixes  #7250
-  ~~[ ] Added/updated documentation~~
=> fix: header middleware response writer.

Makefile, webui/Dockerfile
Expose the PLATFORM_URL environment variable that was already used to configure the build of the webUI.
Now, a user can set it to target another Pilot environnement.
```sh
export PLATFORM_URL=https://pilot.traefik.io
```
Then compile as usual.
That helps debugging previews of the next Pilot version.
=> feat: allows to change the Pilot URL in the web UI in dev mode

docs/content/routing/services/index.md
Fix small typo on documentation
=> doc: fix typo in health check options

docs/content/https/tls.md, docs/content/middlewares/overview.md
Provide an example for the usage of a Middleware with Kubernetes Ingress, include the requirements for the annotations in these scenarios, and improve the documentation for the setup of default TLSOptions in k8s.
We had a hard time figuring out, how to setup Middlewares / TLSOptions with the "old" style Kubernetes Ingress after upgrading to v2.x.
As we do have a lot of projects in our clusters, we didn't want to force an update to CRD to function correctly. Therefore we needed the correct annotation-format and a default TLSOption working for all ingresses.
=> Improve documentation for usage of Kubernetes Ingress

pkg/provider/kubernetes/ingress/client.go, pkg/provider/kubernetes/ingress/client_mock_test.go, pkg/provider/kubernetes/ingress/client_test.go, pkg/provider/kubernetes/ingress/kubernetes.go
Traefik now updates Kubernetes Ingresses with all of the load balancer IPs from its `providers.kubernetesIngress.ingressEndpoint.publishedService`
Fixes #6950
I haven't yet updated any tests, but it appears to work properly.
We're running `external-dns` on our ingresses to keep DNS records synced up nicely. Before this change, we'd only get one of our IP records into DNS. Bad for load balancing.
=> feat: update more than one LoadBalancer ip

docs/content/routing/providers/kubernetes-ingress.md
Add the ingressclass resource and the networking.k8s.io apiGroup to the RBAC.
Have an up to date documentation.
related to #7199 and #7083
=> Add the ingressclass resource in the ingress RBAC documentation

cmd/traefik/plugins.go, netlify.toml
Fix the start of Traefik Pilot.
```
main.hasPlugins(...)
/go/src/github.com/traefik/traefik/cmd/traefik/plugins.go:42
main.initPlugins(0xc00021c900, 0xc000280960, 0xc000280900, 0xc00021c980, 0xc000119940, 0xc00079a300)
/go/src/github.com/traefik/traefik/cmd/traefik/plugins.go:12 +0x209
main.setupServer(0xc00021c900, 0xc00047b380, 0x1e, 0xc0007950b0)
/go/src/github.com/traefik/traefik/cmd/traefik/traefik.go:218 +0x566
main.runCmd(0xc00021c900, 0x0, 0x0)
/go/src/github.com/traefik/traefik/cmd/traefik/traefik.go:117 +0x3b6
main.main.func1(0xc00004c170, 0x14, 0x15, 0x15, 0xc00021ca00)
/go/src/github.com/traefik/traefik/cmd/traefik/traefik.go:58 +0x2c
github.com/traefik/paerser/cli.run(0xc00021ca00, 0xc00004c170, 0x14, 0x15, 0x18, 0xc000119300) …
```
=> fix: start of Traefik Pilot

pkg/metrics/pilot.go
pilot metrics unit for req duration.
use `ms` instead of `s`
=> fix: pilot metrics unit for req duration.

middlewares/ip_whitelister.go
Avoids setting `error=true` on the tracing span for requests that pass through the whitelist middleware that are allowed through.
I also checked the rest of the codebase, and other calls to `SetErrorAndDebugLog` seem to log actual errors. Only the call in the whitelist middleware seemed wrong.
Currenly, all requests that pass a whitelist middleware are traced as an error. This prevents any real use out of these traces, because real errors are masked.
I could not find relevant documentation or tests.
I haven't checked the code in this PR, hoping the CI/CD will catch any errors :innocent: .
=> Do not SetError on tracing event when whitelist allowed request

docs/content/providers/docker.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, pkg/config/static/static_config.go, pkg/provider/docker/docker.go
This PR fixes the default value of the docker client timeout. By default, timeout is now set to `0` which means no timeout. This is also the value defined in the docker client [here](https://github.com/moby/moby/blob/ecdb0b22393bb669325099320d26d18687425e5f/client/client.go#L158).
Fixes the wrong default value which leads to `ERROR` in the logs:
```
ERRO[2020-09-24T15:32:21+02:00] Provider connection error context deadline exceeded (Client.Timeout or context cancellation while reading body), retrying in 552.330144ms  providerName=docker
```
=> Fix default value of docker client timeout

pkg/healthcheck/healthcheck.go, pkg/healthcheck/healthcheck_test.go, pkg/server/service/service.go
This PR re-adds the server up metric to traefik 2.x
The server up metric is necessary for our setup
=> Re-add server up metrics

docs/content/https/acme.md, pkg/provider/acme/provider.go
fix: use provider keytype instead of account keytype.
adds missing keytype documentation
=> fix: use provider keytype instead of account keytype.

pkg/tls/tlsmanager.go
Restrict protocol for TLS Challenge.
Improve TLS Challenge.
During the renew of the certificate, avoid serving an invalid certificate.
=> fix: restrict protocol for TLS Challenge.

docs/content/https/tls.md
TLS options named `default` have special treatment in the code, this is not mentioned in the documentation and can be confusing. This PR updates documentation, to clarify that TLS options named `default` do not belong to a provider namespace (even though you can define them with a file provider), and that provider namespace should not be used with them.
https://community.traefik.io/t/inconsistent-provider-marker-file/8021
=> Adding details about the default TLS options to the documentation

docs/content/middlewares/overview.md, docs/content/providers/overview.md
"Provider Namespace" topic is located under "Middlewares" heading. However, this concept is not limited to Middlewares, we can also see it used with Services, TLSOptions, and ServersTransports. This PR moves out this topic from the Middlewares section, and adjusts the wording to make it clear that this concept is not related _just_ to Middlewares.
https://community.traefik.io/t/inconsistent-provider-marker-file/8021
=> Moving Provider Namespace documentation topic to Configuration Discovery section

docs/content/observability/access-logs.md
Clarifies the access-logs documentation for;
- the `minDuration` filter units
- the `OriginDuration` and `Overhead` time-based field value units.
"Enhancing clarity is always a good thing..." - geraldcroes
Contributing in some small way to the hackathon.
Related to  #4402
=> Clarify time-based field units

pkg/middlewares/accesslog/logger_formatters_test.go
This PR replace the timezone `US/Alaska` in favor of `Etc/GMT+9` to set a `TZ` timezone environment variable in logger formatter tests.
Fix the logger formatter unit tests for specific platforms.
Co-authored-by: jbdoumenjou <925513+jbdoumenjou@users.noreply.github.com>
=> Use timezone without daylight saving time for logger formatter tests

docs/scripts/verify.sh
Add www.namesilo.com and youtube to the urls ignored list for the doc verify script
Having a working CI.
=> fix: exclude protected link from doc verify

docs/content/middlewares/headers.md, docs/content/reference/dynamic-configuration/docker-labels.yml, docs/content/reference/dynamic-configuration/file.toml, docs/content/reference/dynamic-configuration/file.yaml, docs/content/reference/dynamic-configuration/kv-ref.md, pkg/config/dynamic/middlewares.go, pkg/config/label/label_test.go, pkg/middlewares/headers/header.go, pkg/middlewares/headers/header_test.go, pkg/middlewares/headers/headers.go, pkg/provider/kv/kv_test.go
This PR allows to use regular expressions to be used as `AccessControlAllowOriginList` value.
Regular expressions brings more flexibility to the configuration. We're working on a SOA environment that requires temporary hosts to be spun for development and demo purposes. Having a fixed list of hosts requires to frequently update Traefik configuration.
See also https://github.com/containous/traefik/issues/6851
Because `AccessControlAllowOriginList` is of type `[]string`, I leveraged `regexp.MatchString(pattern string, s string)` (the utility function from the `regexp` package) instead of `Regexp.MatchString(s string)` (the exported function from `Regexp` type).
In this way the configuration can define regular expressions as strings. This works with the current code type structure. It also …
=> Allow to use regular expressions for `AccessControlAllowOriginList`

docs/content/middlewares/forwardauth.md, docs/content/reference/dynamic-configuration/docker-labels.yml, docs/content/reference/dynamic-configuration/file.toml, docs/content/reference/dynamic-configuration/file.yaml, docs/content/reference/dynamic-configuration/kv-ref.md, docs/content/reference/dynamic-configuration/marathon-labels.json, pkg/config/dynamic/fixtures/sample.toml, pkg/config/dynamic/middlewares.go, pkg/middlewares/auth/forward.go, pkg/middlewares/auth/forward_test.go, pkg/provider/kubernetes/crd/kubernetes.go, pkg/provider/kubernetes/crd/traefik/v1alpha1/middleware.go
adds new field `authResponseHeadersRegex` to `forwardAuth` middleware
fixes #6823 
update of outdated pr #6828
=> Middlewares: add forwardAuth.authResponseHeadersRegex

cmd/traefik/traefik.go, pkg/provider/acme/challenge_http.go, pkg/provider/acme/challenge_tls.go, pkg/provider/acme/local_store.go, pkg/provider/acme/provider.go, pkg/provider/acme/store.go, pkg/provider/traefik/internal.go, pkg/server/aggregator.go, pkg/server/aggregator_test.go, pkg/server/routerfactory_test.go, pkg/server/service/internalhandler.go, pkg/server/service/managerfactory.go, pkg/tls/tlsmanager.go
New HTTP and TLS challenges implementations.
- HTTP challenge: use a classical Traefik router/service like for the API, the ping, Prometheus, etc.
- TLS challenge: an implementation that uses the Traefik TLS store mechanism
In summary, uses Traefik to handle Traefik internals :smile:
A positive effect is the suppression of the `ChallengeStore` and the `LocalChallengeStore`.
Co-authored-by: Julien Salleyron <julien@traefik.io>
=> acme: new HTTP and TLS challenges implementations.

cmd/traefik/traefik.go, docs/content/contributing/data-collection.md, pkg/config/static/static_config.go
This PR enables stats collections when Pilot is used.
We activate anonymous usage when using pilot to better understand the community's need, and also to get information about plug-ins popularity
=> Enable stats collection when pilot is enabled

docs/content/routing/providers/ecs.md, docs/mkdocs.yml
This PR adds the missing ECS menu to the dynamic configuration reference.
Enhance documentation.
=> Add ECS menu to dynamic config reference

pkg/config/dynamic/zz_generated.deepcopy.go
This PR updates the CRD generation for the new `AccessControlAllowOriginListRegex` field introduced in #6881.
Adds the `AccessControlAllowOriginListRegex` field to the generated `deepcopy` function.
=> Add AccessControlAllowOriginListRegex field to deepcopy

docs/theme/partials/company-header.html
When you choose Traefik Proxy from the Product pull-down on the Traefik Proxy docs page, it mistakenly takes you to the Traefik Proxy docs page. It should take you to the Traefik Proxy product page.
My passion for consistent menus.
Many Bothans died to bring you this change.
=> Fix Traefik Proxy product nav in docs

go.mod, go.sum
update Yaegi to v0.9.5
https://github.com/traefik/yaegi/compare/v0.9.4...v0.9.5
=> Update Yaegi to v0.9.5

pkg/provider/ecs/config.go, pkg/provider/ecs/config_test.go
Fixes #7470: ecs `getPort` function now checks the exposed/mapped ports for services to correctly handle dynamic allocated ports.
=> fix: translate configured server port into correct mapped host port

docs/content/https/tls.md
fix doc: [Certificates Stores](https://doc.traefik.io/traefik/https/tls/)
I found this error when I tried to use Traefik TLS and read the docs and corrected it
=> Fix docs for TLS

docs/content/middlewares/forwardauth.md
Add headers that the middleware provides to the target forward-auth address.
These headers contain certain request properties from the initial request that
is subject for authentication.
Without this information it is not clear, what a forward-auth target application 
may expect to receive. Having this in the docs helps application developers 
for targets of this middleware.
=> Forwardauth headers

script/crossbinary-default, script/update-generated-crd-code.sh
Change shebang from '/bin/bash' to '/usr/bin/env bash' to match other scripts.
All shell scripts in 'scripts/' using bash shell to have the '/usr/bin/env bash' shebang.
=> /bin/bash replaced with /usr/bin/env bash to match other scripts

pkg/provider/consulcatalog/consul_catalog.go
It fixes the behavior of the consul catalog provider w.r.t. how it polls Consul. It currently waits the refreshing interval before doing its first pull which causes many 404 for too long.
A colleague thinks that Traefik v2 is not ready yet for us, currently on Traefik v1. He'll highly motivated to fix all the remaining issues we may encounter.
:heart:
=> fix: consulcatalog to update before the first interval

docs/content/providers/ecs.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, pkg/config/static/static_config.go, pkg/provider/ecs/ecs.go
This PR fixes the definition of the ECS and Consul Catalog providers in the static configuration so they can be enabled without options. This PR also improves logs messages and factorize the ECS provider and stay consistent with the Consul Catalog provider.
Allow the use of:
- `--providers.ecs=true`
- `--providers.consulcatalog=true`
=> Fix missing allow-empty tag on ECS and Consul Catalog providers

pkg/provider/kubernetes/crd/client.go, pkg/provider/kubernetes/crd/client_test.go, pkg/provider/kubernetes/ingress/client.go, pkg/provider/kubernetes/ingress/client_test.go
This PR updates the Kubernetes CRD and Ingress providers to prevent storing Helm secrets in their informer's cache. This fix reduces Traefik memory usage.
Fixes #7384
Fixes #7406
=> Filter out Helm secrets from informer caches

go.mod, go.sum
Update Yaegi to v0.9.7
https://github.com/traefik/yaegi/compare/v0.9.5...v0.9.7
=> Update Yaegi to v0.9.7

go.mod, go.sum
Update go-acme/lego to v4.1.2
Fixes:
- **[lib]** fix: preferred chain support.
- **[dnsprovider]** otc: select correct zone if multiple returned
- **[dnsprovider]** azure: fix target must be a non-nil pointer
- ~~[] Added/updated documentation~~
=> Update go-acme/lego to v4.1.2

go.mod, go.sum
It fixes invalid slice parsing (mainly during labels parsing)
To reproduce, use the slice of struct syntax on a slice of string field.
Example:
```yaml
traefik.http.middlewares.Middleware1.basicauth.users: one,two
traefik.http.middlewares.Middleware1.basicauth.users[0].bug: one
```
Fixes #7582
```
Error in Go routine: reflect: NumField of non-struct type string
Stack: goroutine 41 [running]:
runtime/debug.Stack(0xc0001dc000, 0x34c674a, 0x17)
/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x2cc5ae0, 0xc000aa79d0)
/go/src/github.com/traefik/traefik/pkg/safe/routine.go:66 +0xb4
github.com/traefik/traefik/v2/pkg/safe.OperationWithRecover.func1.1(0xc000a89db8)
/go/src/github.com/traefik/traefik/pkg/safe/routine.go:74 +0x56 …
```
=> fix: invalid slice parsing.

pkg/middlewares/redirect/redirect.go, pkg/middlewares/redirect/redirect_regex_test.go
This PR fixes a bug in the `redirectRegex` middleware where template actions were evaluated in the request URL. 
Fixes #7513
=> Do not evaluate templated URL in redirectRegex middleware

docs/content/providers/ecs.md
Add plurial to cluster{s} keyword for toml script. Doesn't work if missing "s" in keyword
=> Fix clusters option in ECS provider documentation

webui/src/components/_commons/PanelServiceDetails.vue
This PR adds an indication in the web dashboard of the Proxy Protocol status for a backend service.
The recently merged PR #7320 added support for Proxy Protocol to backend services, but there's no visual clue in the dashboard about whether such protocol is enabled or not for a service. Showing in the dashboard the version of the Proxy Protocol used by a backend service (if any) might be useful to quickly diagnose communication problems between Traefik and the proxied services.
=> Display Proxy Protocol version for backend services in web dashboard.

docs/content/routing/providers/docker.md
Adds a configuration example explaining how to configure more than one service port and router on a single docker container using the docker provider.
While the documentation isn't misleading or explicitly obfuscates this information, it also doesn't give an example of a real-world use case for utilizing the `service` parameter on an HTTP router in the context of the Docker provider. 
In addition, this PR addresses #7605
=> Add example for multiple service per container

go.mod, go.sum
Update go-acme/lego to v4.1.3
Fixes:
- **[dnsprovider]** azure: fix error handling.
fixes #7623
- ~~[] Added/updated documentation~~
=> Update go-acme/lego to v4.1.3

webui/src/components/_commons/PanelMiddlewares.vue, webui/src/components/_commons/PanelMirroringServices.vue, webui/src/components/_commons/PanelRouterDetails.vue, webui/src/components/_commons/PanelWeightedServices.vue, webui/src/css/sass/app.scss
The service name can become very long and it can overflow the section as described in issue #5702.
The fix uses overflow functionality to visually cut the text that does not fit in the screen, avoiding covering over nearby visual elements.
It fixing a visual glitch when using weighted or mirrored services.
Fixes #5702
How it looks after the fix.
*updated image*
=> Fix UI bug on long service name

docs/content/assets/styles/menu.css
This PR adds some spacing at the bottom of the sidebar menus on the documentation, which is sufficient to make the last item visible when there are many items and we scroll all the way down.
The documentation as we have today, depending on which menus are opened, the last item of the sidebar menu in the documentation (both left or right), might not be visible, because it's covered by the footer bar.
So the next time we export the doc, it will be correct.
=> Documentation: Add spacing to sidebars so the last item is always visible

pkg/server/router/tcp/router.go, pkg/server/router/tcp/router_test.go
This PR fixes a bug on the TCP Router when multiple HTTP routers specifies the same domains and TLS options. Fallback on the `default` TLS options should be done only when multiple routers use the same domain with different TLS options.
Fixes #7385
=> Fix TLS options fallback when domain and options are the same 

docs/content/providers/kubernetes-crd.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, integration/fixtures/k8s/07-ingressroute-cross-namespace.yml, integration/fixtures/k8s_crd.toml, integration/k8s_test.go, integration/testdata/rawdata-crd.json, pkg/provider/kubernetes/crd/client.go, pkg/provider/kubernetes/crd/client_mock_test.go, pkg/provider/kubernetes/crd/fixtures/services.yml, pkg/provider/kubernetes/crd/fixtures/tcp/services.yml, pkg/provider/kubernetes/crd/fixtures/tcp/with_cross_namespace.yml, pkg/provider/kubernetes/crd/fixtures/udp/services.yml, pkg/provider/kubernetes/crd/fixtures/udp/with_cross_namespace.yml, pkg/provider/kubernetes/crd/fixtures/with_cross_namespace.yml, pkg/provider/kubernetes/crd/fixtures/with_middleware_cross_namespace.yml, pkg/provider/kubernetes/crd/kubernetes.go, pkg/provider/kubernetes/crd/kubernetes_http.go, pkg/provider/kubernetes/crd/kubernetes_tcp.go, pkg/provider/kubernetes/crd/kubernetes_test.go, pkg/provider/kubernetes/crd/kubernetes_udp.go
This PR adds the `allowCrossNamespace` option on the Kubernetes provider configuration to allow/disallow cross-namespace routing.
The `allowCrossNamespace` is defaulted to `true`.
When set to `false` it's not possible for an IngressRoute to reference a service in another namespace than its namespace.
fixes #7353
=> IngressRoute: add an option to disable cross-namespace routing

go.mod, go.sum
Update Yaegi to v0.9.8
https://github.com/traefik/yaegi/compare/v0.9.7...v0.9.8
=> Update Yaegi to v0.9.8

go.mod, go.sum
This PR updates Logrus from v1.4.2 to v1.7.0. 
No breaking changes between these versions.
Fixes since our last update:
- The dependency toward a windows terminal library has been removed
- End of line cleanup
- Revert the entry concurrency bug fix whic leads to deadlock under some circumstances
- Add mutex for hooks concurrent access on Entry data
- Caller function field for go1.14
- Fix build issue for gopherjs target
https://github.com/sirupsen/logrus/compare/v1.4.2...v1.7.0
Fixes #7425
In v1.7.0, `konsorten/go-windows-terminal-sequences` has been removed, which solves this issue.
=> Update Logrus to v1.7.0

docs/content/user-guides/marathon.md, pkg/provider/marathon/builder_test.go, pkg/provider/marathon/config.go, pkg/provider/marathon/config_test.go
Every marathon port has a name attached. Currently the "index:" prefix is supported to select a marathon port by it's index.
Extend this lookup to search for the port name if the label prefix is "name:".
Extend marathon port discovery to allow the "name:" prefix to select a port.
We at [ESL](https://about.eslgaming.com/) use marathon, mesos-dns and nginx to discover our microservices via DNS. mesos-dns uses the port names in it's DNS payload. We are currently evaluating traefik to replace this setup.
=> Extend marathon port discovery to allow port names as identifier

docs/content/middlewares/errorpages.md
Fix docs
Adding quotations prevents the error:
```
v1alpha1.ErrorPage.Status: []string: ReadString: expects " or n, but found 4, error found in #10 byte of ...|status":[401]}}},{"a|..., bigger context ...|ice":{"name":"XXXX","port":80},"status":[401]}}},{"apiVersion":"traefik.containo.us/v1alpha1|...
```
=> Add missing quotes in errorpages k8s example yaml

pkg/rules/rules.go, pkg/rules/rules_test.go, pkg/server/router/router_test.go
Disable router when a rule has an error.
Fix #7679
<details>
<summary>To reproduce:</summary>
```yml
version: '3.7'
services:
traefik:
image: traefik:v2.3.5
command:
- --log.level=INFO
- --api
- --providers.docker.exposedbydefault=false
- --entrypoints.web.address=:80
ports:
- 80:80
volumes:
- /var/run/docker.sock:/var/run/docker.sock:ro
labels:
traefik.enable: 'true'
traefik.http.routers.traefik.rule: Host(`traefik.localhost`)
traefik.http.routers.traefik.entrypoints: web
traefik.http.routers.traefik.service: api@internal
whoami:
image: containous/whoami:v1.5.0
command:
- --name=🧀whoami
labels:
traefik.enable: 'true'
traefik.http.routers.whoami.rule: (Host(``) && PathPrefix(`/hammered`))
traefik.http.routers.whoami.entrypoints: web
app:
image: …
```
=> Disable router when a rule has an error

docs/content/providers/docker.md, docs/content/routing/providers/docker.md
This PR fixes broken links to the `docker-compose` documentation.
=> docs: fix broken links to docker-compose documentation

docs/content/providers/overview.md
Documentation fixes:
- for Traefik v2.3
* Add ECS to supported providers list
* Change Redis position in providers list table to be consistent with sidebar navigation
Aim is to make providers table consistent with sidebar menu
=> Add ECS to supported providers list

pkg/tracing/datadog/datadog.go
Adds support to usage of configuration environment variables of Datadog tracer, following Datadog best practices of using environment variables to setup values of Datadog tracer host and port.
The issue #7628 alerted this topic, it is a good enhancement to have.
Resolves #7628
=> Use Datadog tracer environment variables to setup default config

docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, docs/content/routing/entrypoints.md, docs/content/routing/routers/index.md, pkg/config/static/entrypoints.go, pkg/config/static/static_config.go, pkg/server/server_entrypoint_udp.go, pkg/server/server_entrypoint_udp_test.go, pkg/udp/conn.go, pkg/udp/conn_test.go, pkg/udp/proxy_test.go
Fixes issue #6859 
The UDP endpoint feature is rather useless if traefik closes the session after 3 seconds. My particular use case is to route mumble voip packets through traefik and having the server break after 3 seconds of inactivity is not useful.
If there is a recommended alternative for creating a dummy ticker, that might be a better solution for the implementation of timeout values of 0.
=> Feature: add udp timeout configuration

pkg/provider/kubernetes/ingress/annotations.go
Saves (in certain cases a lot of) memory allocations by compiling a ingress annotation regex once, instead of once per ingress per reload.
I inspected the heap pprof and noticed a large amount of allocated_space coming from this call to `MustCompile`.
=> Compile kubernetes ingress annotation regex only once

pkg/middlewares/customerrors/custom_errors.go
This PR fixes issue #7722 .
The current logs for customerrors middleware generates too much non relevant error logs.
By decreasing the log level, traefik is now more cohesive in its log level.
=> Discrepancy in Traefik log levels

.github/workflows/documentation.yml, .travis.yml
Replace Travis CI by GitHub Action to build and publish the documentation.
Have a stable publication process.
Co-authored-by: Michael <michael.matur@gmail.com>
=> Use GitHub Action to publish documentation.

docs/content/routing/providers/kubernetes-crd.md, integration/fixtures/k8s/05-ingressrouteudp.yml, integration/testdata/rawdata-crd.json, pkg/provider/kubernetes/crd/fixtures/udp/services.yml, pkg/provider/kubernetes/crd/fixtures/udp/with_externalname.yml, pkg/provider/kubernetes/crd/fixtures/udp/with_externalname_with_port.yml, pkg/provider/kubernetes/crd/fixtures/udp/with_externalname_without_ports.yml, pkg/provider/kubernetes/crd/kubernetes_test.go, pkg/provider/kubernetes/crd/kubernetes_udp.go
This PR changes how the service port is resolved for UDP services to be consistent with TCP and HTTP. As a side note, the service port retrieval algorithm for `externalName` services si now consistent for `IngressRoute`, `IngressRouteTCP` and `IngressRouteUDP`.
To be consistent.
=> Improve kubernetes external name service support for UDP

docs/check.Dockerfile, docs/content/providers/kubernetes-gateway.md, docs/docs.Dockerfile
This PR fixes a YAML syntax in the Kubernetes Gateway provider docs.
Keep Traefik properly documented.
=> fix: YAML syntax in providers docs

pkg/api/handler.go, pkg/api/handler_test.go
This PR fixes a bug on the `/api/http/middlewares/{middlewareID}` endpoint when the requested middleware is a plugin. In this case the response didn't return the plugin type but instead an empty string.
Fixes #7778
=> Fix plugin type on middleware endpoint response

docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, pkg/provider/consulcatalog/consul_catalog.go
Updates the annotation for the default value of Refresh Interval. Based on documentation on the website and https://github.com/traefik/traefik/pull/7810/files#diff-c3e25341e36d91fba700c36777fee7b575bb7004a9521a76ec17d2fb3f748364R83 it looks like it is 15s instead of 100ms
=> Fix refresh interval option description in consulcatalog provider

integration/resources/compose/tlsclientheaders.yml, integration/tls_client_headers_test.go, pkg/provider/aggregator/aggregator.go, pkg/provider/aggregator/aggregator_test.go
This PR fixes a concurrency issue between the ACME provider and the internal provider.
The HTTP challenge could have started before the internal provider has run and created the HTTP challenge router.
To fix this, the internal provider will be the first provider to be started.
Fix #7784
=> Fix HTTP challenge router unexpected delayed creation

pkg/provider/aggregator/aggregator.go, pkg/provider/aggregator/aggregator_test.go
This PR fixes `servers transport not found default@internal`. 
Fixes #7809
=> Fix servers transport not found

pkg/pilot/pilot.go
This PR increases the backoff retry interval and thus, pressure on Pilot service.
If an outage occurs on Pilot this is not necessary to over-stress the service with excessive retries and consequently increase the probability of an over-incident.
Before the PR:
```
$ go build && ./test_retry 
retry failed
```
with the PR:
```
$ go build && ./test_retry 
retry failed
```
=> fix: reduce pressure of pilot services when errors occurs

pkg/middlewares/forwardedheaders/forwarded_header.go, pkg/middlewares/forwardedheaders/forwarded_header_test.go
fix: infinite loop in forwarded header middleware.
Fixes #7845
Co-authored-by: kevinpollet <pollet.kevin@gmail.com>
=> fix: infinite loop in forwarded header middleware.

docs/content/reference/static-configuration/env-ref.md, internal/gendoc.go
Use `_n_` instead of `[n]` in environment variables generation.
Update the static configuration reference documentation accordingly.
Fixes #7834
Having valid documentation.
=> Fix the static configuration generation for environment variables

pkg/config/static/entrypoints.go
Fix the redirect entry point default priority.
Avoid priority issues between internal routers.
Fixes #7825
=> Fix the redirect entrypoint default priority

docs/content/reference/dynamic-configuration/kubernetes-gateway-resource.yml, docs/content/routing/providers/kubernetes-gateway.md, pkg/provider/kubernetes/gateway/fixtures/simple_cross_provider.yml, pkg/provider/kubernetes/gateway/fixtures/simple_to_api_internal.yml, pkg/provider/kubernetes/gateway/kubernetes.go, pkg/provider/kubernetes/gateway/kubernetes_test.go
Enhance the `HTTPRoute` object with the `BackendRef` property.
This allows a reference to a Traefik service that could be an internal service or a service from another provider. 
* Allows cross provider reference
* Allows access to the Traefik internal service such as `api@internal`
Fixes #7731
The Traefik dashboard can now be exposed in the HTTPRoute thanks to the `api@internal` service.
You can use our [test project](https://github.com/jbdoumenjou/k8s-api-gateway-dashboard) to play with this PR :)
Co-authored-by: Harold Ozouf <harold.ozouf@gmail.com>
=> Allow crossprovider service reference

docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md
Update the default priority value of the internal redirection router in static reference documentation.
Having documentation up to date. :nerd_face:
=> Fix the static reference documentation for the internal redirection router.

integration/consul_catalog_test.go
Fixes a small typo in a consul test case. The test registered two services with id `whoami` but the teardown used `whoami1` and `whoami2` instead.
=> Fixed typo in consul catalog tests.

cmd/traefik/traefik.go, pkg/provider/acme/challenge_tls.go, pkg/provider/acme/provider.go
- Increasing the internal timeout for the TLS challenge to be at least 2 times of duration of the ProvidersThrottleDuration.
```
level=error msg="Unable to obtain ACME certificate for domains \"traefik.localhost\": unable to generate a certificate for the domains [traefik.localhost]: error: one or more domains had a problem:\n[traefik.localhost] [traefik.localhost] acme: error presenting token: timeout 2021-02-09 09:36:09.994505266 +0000 UTC m=+6.642410137\n" routerName=traefik@docker rule="Host(`traefik.localhost`)" providerName=leresolver.acme
```
- When a challenge fails, cleaning the certificates related to the TLS challenge
```
level=error msg="Unable to obtain ACME certificate for domains \"traefik.localhost\": unable to generate a certificate for the domains [traefik.localhost]: …
```
=> Fix TLS challenge timeout and validation error

docs/content/providers/consul-catalog.md, docs/content/providers/consul.md, docs/content/providers/docker.md, docs/content/providers/ecs.md, docs/content/providers/etcd.md, docs/content/providers/file.md, docs/content/providers/http.md, docs/content/providers/kubernetes-crd.md, docs/content/providers/kubernetes-gateway.md, docs/content/providers/kubernetes-ingress.md, docs/content/providers/marathon.md, docs/content/providers/overview.md, docs/content/providers/rancher.md, docs/content/providers/redis.md, docs/content/providers/zookeeper.md
This PR is a follow-up to #7808 which in much the same way, proposes many fixes to the provider documentation pages.
It introduces multiple grammar, phrasing and formatting improvements to the middleware documentation pages. It seeks to improve consistency and not introduce any changes that would make the pages inconsistent with other ones. It does not change things across all documents, but some changes might come in another PR (like introducing a standard for describing default values for options and whether they are optional or required.)
Among the most frequent changes you will find in this PR:
* Removal of future tense (`will do` -> `does`)
* Replacement of passive voice with active voice
* Removal of contractions (`it's` -> `it is`)
* Makes admonitions more consistent (title should …
=> Provider documentation fixes

docs/content/middlewares/compress.md, go.mod, go.sum, pkg/middlewares/compress/compress.go, pkg/middlewares/compress/compress_test.go
Apply excludedContentTypes on response Content-Type Header.
fixes #6810
Co-authored-by: kevinpollet <pollet.kevin@gmail.com>
=> Apply content type exclusion on response

pkg/api/dashboard.go, pkg/api/dashboard_test.go, pkg/server/service/managerfactory.go
Only allows iframes to be loaded from our domain
Be more secure :)
=> Only allow iframes to be loaded from our domain

docs/content/providers/kubernetes-gateway.md, docs/content/routing/providers/kubernetes-gateway.md
This PR fixes the links to the Kubernetes Gateway API documentation.
The Kubernetes Gateway documentation has its own domain, see https://github.com/kubernetes-sigs/gateway-api/pull/559.
This means that the documentation URL https://kubernetes-sigs.github.io/gateway-api/ has to be changed to https://gateway-api.sigs.k8s.io/.
Fix broken links. 
=> Fix Kubernetes Gateway API documentation links

docs/content/providers/file.md
Fixes a reflink format typo in `file.md`  
Found it while reading docs
=> Fix reflink typo in file provider documentation

go.mod, go.sum
Update Yaegi to v0.9.13
https://github.com/traefik/yaegi/compare/v0.9.8...v0.9.13
=> Update Yaegi to v0.9.13

docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, internal/gendoc.go
Update the doc as the default value for `CheckNewVersion` is `true`: 
https://github.com/traefik/traefik/blob/438eec720a01476d2af699272d7fc3a22cb9356d/cmd/configuration.go#L22
Fixes #7878
=> Fixing doc for default value of checknewversion

script/deploy.sh
This fixes all shellcheck warnings as reported by ‘make validate’ on a
fresh Git checkout of the master branch.
The actual changes are simple:
- Add quotes around some variables to avoid ‘word splitting’
- Ensure some ‘$encrypted_...’ variables (coming from CI apparently) are
actually set.
=> Address all shellcheck warnings

go.mod, go.sum
This version bump paerser to the [v0.1.2](https://github.com/traefik/paerser/releases/tag/v0.1.2)
https://github.com/traefik/paerser/compare/v0.1.1...v0.1.2
Be up to date.
=> Bump paerser to v0.1.2

docs/content/routing/providers/consul-catalog.md, docs/content/routing/providers/docker.md, docs/content/routing/providers/ecs.md, docs/content/routing/providers/kubernetes-crd.md, docs/content/routing/providers/kv.md, docs/content/routing/providers/marathon.md, docs/content/routing/providers/rancher.md
This PR fixes the documentation regarding `ServersTransport` configuration.
It adds the `ServersTransport` kind in the reference table for Kubernetes IngressRoute.
It also clarifies, in all label providers pages, the usage of the reference to a `ServersTransport` when defining a service loadbalancer. 
Better documentation.
Co-authored-by: mpl <mathieu.lonjaret@gmail.com>
=> Fix ServersTransport documentation

pkg/server/service/roundtripper.go
Set default `http.Transport` read and write buffer size  to increase performance.
Performance optimisation.
The gain is measured using a load test consisting of:
- a dedicated machine simulating 200 intensive simultaneous clients (16  intel CPUs, 32 GB ram)
- a dedicated machine running `traefik` (8 intel CPUs, 16 GB ram)
- 5 machines simulating backend servers load-balanced by traefik (5 x 8 intel CPUs )
The test measure the throughput in transaction per seconds. RES is the resident memory size (number of 4k pages) of the traefik process during the test (the cost of this change).
|                               | Traefik-master   |   Traefik-perf     |
| ----------------  | ---------------- | ---------------- |
| requests/s            | 59074                 | 66960                |
| …
=> feature: tune transport buffer size to increase performance

go.mod, go.sum
This pull request remove usage of replace directive for Docker dependency.
According to this (source: https://github.com/testcontainers/testcontainers-go/issues/127#issuecomment-571616048):
> Adding a replace works if you want to use a version that matches a tagged release of docker (for which tags can be found in the docker/engine repository), but if that's the reason, it's probably most most logical to pick a tag (but pin by commit, because Go doesn't accept the YY.MM tags)
> Unfortunately, the replace won't help for consumers of this project though (only for the project itself); the replace is not inherited by those projects, so everyone using this package would need to add the same replace rule to their go.mod.
And this (source: …
=> Use Docker dependency directly without replace directive

pkg/metrics/metrics_test.go, pkg/middlewares/ratelimiter/rate_limiter_test.go, pkg/provider/aggregator/aggregator_test.go, pkg/server/configurationwatcher_test.go, pkg/server/server_entrypoint_tcp_test.go
Fix some flaky tests.
I hate flaky tests.
<details>
<summary>TestProviderAggregator_Provide</summary>
```
--- FAIL: TestProviderAggregator_Provide (0.03s)
aggregator_test.go:36: 
Error Trace:	aggregator_test.go:60
aggregator_test.go:36
Error:      	elements differ
extra elements in list A:
([]interface {}) (len=1) {
(string) (len=4) "file"
}
listA:
([]string) (len=1) {
(string) (len=4) "file"
}
listB:
([]string) <nil>
Test:       	TestProviderAggregator_Provide
FAIL
```
</details>
<details>
<summary>TestShutdownHTTP</summary>
```
--- FAIL: TestShutdownHTTP (5.10s)
server_entrypoint_tcp_test.go:42: 
Error Trace:	server_entrypoint_tcp_test.go:127
server_entrypoint_tcp_test.go:42
Error:      	Received unexpected error:
unexpected EOF
Test:       	TestShutdownHTTP
time="2021-03-04T15:35:46Z" …
```
=> Fix flaky tests.

go.mod, go.sum
Update go-acme/lego to v4.3.1
Fixes:
- **[dnsprovider]** exoscale: fix dependency.
related to https://github.com/exoscale/egoscale/issues/482
=> Update go-acme/lego to v4.3.1

go.mod, go.sum
security bug described in issue:
https://github.com/pires/go-proxyproto/issues/69
this affects traefik 2.4 with enabled proxy protocol support
https://github.com/pires/go-proxyproto/compare/v0.3.1...v0.5.0
=> server: updating go-proxyproto with security bugfix from upstream

.travis.yml, Makefile, docs/Makefile
Travis sometimes fails because it fails to pull docker images when building docs.
This PR allows trying to pull images 10 times instead of once.
It removes fails that look like this:
```bash
$ if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make docs; fi
make -C ./docs docs
make[1]: Entering directory '/home/travis/build/traefik/traefik/docs'
rm -rf /home/travis/build/traefik/traefik/docs/site
docker build -t traefik-docs -f docs.Dockerfile ./
Sending build context to Docker daemon  6.612MB
Step 1/6 : FROM alpine:3.13
3.13: Pulling from library/alpine
age configuration: unexpected EOF
make[1]: *** [docs-image] Error 1
make[1]: Leaving directory '/home/travis/build/traefik/traefik/docs'
make: *** [docs] Error 2
The command "if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make docs; fi" …
```
=> Fix travis docker image pulling for docs

docs/content/middlewares/basicauth.md
Don't use the `-b` switch to promt for the password and force Bcrypt with `-B`
Logging a password in cleartext is never a good idea
=> Doc: improve basic auth middleware httpasswd example

cmd/traefik/traefik.go, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, pkg/config/static/pilot.go, pkg/config/static/static_config.go, pkg/version/version.go, webui/src/App.vue, webui/src/components/_commons/NavBar.vue
This PR adds an option (`--pilot.dashboard` or `TRAEFIK_PILOT_DASHBOARD`) to remove pilot usage in the dashboard.
When set to false, it removes both the buttons in the navigation bar and the side panel.
It will allow the use of the traefik dashboard without pilot ever being called.
Closes #7360
=> Adding an option to (de)activate Pilot integration into the Traefik dashboard

docs/content/migration/v2.md, docs/content/routing/routers/index.md, pkg/rules/rules.go, pkg/rules/rules_test.go, pkg/server/router/tcp/router.go, pkg/server/router/tcp/router_test.go
This PR introduces a new check on domain names used in HTTP router rule `Host` and `HostRegexp` expressions,
and in TCP router rule `HostSNI` expression.
This check ensures that provided domain names don't contain non-ASCII characters. 
If not, an error is raised, and the associated router will be shown as invalid in the dashboard.
This new behavior is intended to show what was failing silently previously and to help troubleshooting configuration issues.
It doesn't change the support for non-ASCII domain names in routers rules, which is not part of the Traefik feature set so far.
Provide errors to better troubleshoot bad configuration and document the correct use for non-ASCII domains (Punycode format) in routers rules.
fixes #7494
=> Raise errors for non-ASCII domain names in a router's rules

pkg/tcp/proxy.go, pkg/tcp/proxy_test.go
Previously `ResolveTCPAddr` has always been used. But as stated in go's
docs this is not recommended:
> The address parameter can use a host name, but this is not
> recommended, because it will return at most one of the host name's
> IP addresses.
For host names `ResolveTCPAddr` in combination with `DialTCP` has now
been replaced with a single call to `Dial`.
The added advantage is that `Dial` tries all IPs the host name resolves
to:
> When using TCP, and the host resolves to multiple IP addresses, Dial
> will try each IP address in order until one succeeds.
The reason why I stumbled over this is that one of the IPs a host name resolves to is invalid and I tried to figure out how to get traefik to use the valid one.
- Removed `TestLookupAddress` as it feels like it is only testing …
=> Improve host name resolution for TCP proxy

pkg/types/metrics.go
Apply same env var mechanism used for datadog tracer endpoint for datadog metrics endpoint.
Ease configuration when using datadog on kubernetes.
Related to #7721
=> Allow to define datadogs metrics endpoint with env vars

docs/content/reference/dynamic-configuration/file.toml, docs/content/reference/dynamic-configuration/file.yaml, docs/content/reference/dynamic-configuration/kubernetes-crd-resource.yml, docs/content/reference/dynamic-configuration/traefik.containo.us_serverstransports.yaml, docs/content/routing/services/index.md, integration/fixtures/k8s/01-traefik-crd.yml, pkg/config/dynamic/http_config.go, pkg/provider/kubernetes/crd/traefik/v1alpha1/serverstransport.go, pkg/server/service/roundtripper.go, pkg/server/service/roundtripper_test.go, pkg/server/service/smart_roundtripper.go
Adds the ability to disable HTTP/2 in dynamic serverstransport configuration.  This is required when using Windows-based authentication for downstream sites.
#6608 
- Unsure of appropriate area to place tests and/or if they apply to this change
This PR resolves #6608 and is related to #7179 .  The comments in that PR suggest moving the configuration from static to dynamic, which is what this PR does.
=> Add ability to disable HTTP/2 in dynamic config

pkg/provider/kubernetes/gateway/client.go
This PR replaces an error with a log when no HTTProute is provided.
Fixes #8022
=> Remove error when HTTProutes is empty

docs/content/routing/providers/kubernetes-ingress.md
The annotation traefik.ingress.kubernetes.io/service.serversscheme must be on the service and not on the ingress.
This pull request modifies the documentation to make the placement of the annotation traefik.ingress.kubernetes.io/service.serversscheme more clear.
I struggled getting a https backed service to work.
=> correct annotation option

metrics/prometheus.go
Fixing Prometheus Handler to use the custom registry.
Fixes #8039.
=> prometheus: fixing prom Handler to use the custom registry

docs/check.Dockerfile
Add a dependency for `html-proofer` compilation.
Fixes docs image when doing `make docs`.
=> Docs: installing deps for html-proofer

docs/content/migration/v2.md, pkg/tracing/tracing.go
Generates error spans on `5xx` errors rather than `>= 400` errors.
A client generating hundreds of 401s every few minutes.
Generating error spans for client-side errors creates a lot of noise on high-volume systems when the problem is not addressable by the server operator.
Most tracers implement similar logic, only generating an error when the response code is 500 or greater. Examples:
https://github.com/opentracing-contrib/go-stdlib/blob/v1.0.0/nethttp/client.go#L191-L193
https://github.com/opentracing-contrib/nginx-opentracing/blob/v0.14.0/opentracing/src/request_tracing.cpp#L64-L67
=> Error span on 5xx only

pkg/provider/kubernetes/ingress/fixtures/Ingress-with-port-invalid-for-one-service_endpoint.yml, pkg/provider/kubernetes/ingress/fixtures/Ingress-with-port-invalid-for-one-service_ingress.yml, pkg/provider/kubernetes/ingress/fixtures/Ingress-with-port-invalid-for-one-service_service.yml, pkg/provider/kubernetes/ingress/kubernetes.go, pkg/provider/kubernetes/ingress/kubernetes_test.go
…bsets was searched
Fix kubernetes ingress provider to return error only if slice endpoints.Subsets was searched
fix https://github.com/traefik/traefik/issues/7991
=> Kubernetes ingress provider to search via all endpoints

go.mod, go.sum
Upgrade quic-go to v0.20.1 which according to @marten-seemann [contains a lot of improvements](https://github.com/caddyserver/caddy/pull/4075#issue-597193701).
https://github.com/lucas-clemente/quic-go/compare/v0.19.3...v0.20.1
=> Upgrade github.com/lucas-clemente/quic-go

docs/content/providers/kubernetes-gateway.md
Removes a dead link in the [gateway api](https://gateway-api.sigs.k8s.io) doc.
Fix Doc
=> fix: k8s gateway api link

go.mod, go.sum
Update Yaegi to v0.9.17
https://github.com/traefik/yaegi/compare/v0.9.13...v0.9.17
=> Update Yaegi to v0.9.17

docs/scripts/verify.sh
It removes [linode](https://linode.com) url health check in the CI since it might not be used by users.
Fix CI
=> fix: remove linode link health check

pkg/provider/kubernetes/gateway/fixtures/with_two_hosts_one_wildcard.yml, pkg/provider/kubernetes/gateway/fixtures/with_two_hosts_wildcard.yml, pkg/provider/kubernetes/gateway/kubernetes.go, pkg/provider/kubernetes/gateway/kubernetes_test.go
closes #7874
Allows a kubernetes gateway api httproute definition to include wildcard hostnames (ie. `*.foo.com`). As mentioned in #7874 per [the spec](https://gateway-api.sigs.k8s.io/spec/#networking.x-k8s.io/v1alpha1.Hostname) this is an allowed usage but was originally badly rendered by their documentation renderer (which has now been fixed) so as to properly render the `*` character, which had previously been interpreted as markdown markup). 
I've been enjoying using the gateway api via traefik but this became a blocker for rolling it out in what should otherwise be a simple deployment.
I did not add documentation but as it is documented in the gateway-api spec and the traefik documentation refers to that, I think it isn't incorrect to omit it.
I'm not a go developer (I'm a Perl dev …
=> Add wildcard hostname rule to kubernetes gateway

docs/content/routing/services/index.md, go.mod, go.sum, pkg/server/service/service.go, pkg/server/service/service_test.go
This PR bump [vulcand/oxy](https://github.com/vulcand/oxy) version to [v1.3.0](https://github.com/vulcand/oxy/releases/tag/v1.3.0) which add cookie value hashing among other things.
https://github.com/vulcand/oxy/compare/v1.2.0...v1.3.0
It will make all sticky cookies values to be hashed while still being backward compatible by allowing to cookies set by the old version of oxy to remain sticky until they expire. 
Fixes #7297
Fixes #2299
=> Add a mechanism to format the sticky cookie value

cmd/traefik/traefik.go, docs/content/observability/metrics/datadog.md, docs/content/observability/metrics/influxdb.md, docs/content/observability/metrics/prometheus.md, docs/content/observability/metrics/statsd.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, integration/resources/compose/base.yml, integration/simple_test.go, pkg/metrics/datadog.go, pkg/metrics/datadog_test.go, pkg/metrics/influxdb.go, pkg/metrics/influxdb_test.go, pkg/metrics/metrics.go, pkg/metrics/pilot.go, pkg/metrics/pilot_test.go, pkg/metrics/prometheus.go, pkg/metrics/prometheus_test.go, pkg/metrics/statsd.go, pkg/metrics/statsd_test.go, pkg/middlewares/metrics/metrics.go, pkg/server/router/router.go, pkg/server/router/router_test.go, pkg/server/routerfactory.go, pkg/server/routerfactory_test.go, pkg/types/metrics.go
Adds router metrics with service and router name as dimensions with the objective of proper incoming traffic monitoring and "mirroring" v1 metric behaviour. 
Disabled by default to prevent current users from having an unexpected memory usage increase.
Fixes #6495, #7007
I've tons of sites served by traefik v1 that points to the same service. This service renders a different page depending of the domain the user comes in. With v1 I can split the service traffic by `rule` aka backend. That's not possible in v2 service metric.
=> Add router metrics

docs/content/routing/providers/kubernetes-crd.md
This PR removes an unsupported example in the `IngressRouteTCP` documentation.
Fixes #8112
=> Fix ingressRouteTCP external name service examples in documentation

pkg/plugins/client.go
Fix the unzip call for plugins when running on windows, or any other platform that does not use a *nix path separator.
It seems that the zip.FileHeader does not care about os specific file separator and instead always uses forward slashes. So to run on windows or other platforms with different path separators we cannot rely on os.PathSeparator when using its file name reference.
=> Fix plugin unzip call on windows

docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml
This adds the recently added option to (de)active Pilot integration into the Traefik dashboard (#7994) to the static configuration `yml` and `toml` example files.
The flag for this option has already been added to the env variables at the time of the PR but was missing from the static configuration example files.
N/A
=> docs: add pilot dashboard flag to static configuration file reference

pkg/provider/kubernetes/ingress/fixtures/Ingress-with-a-named-port-matching-subset-of-service-pods_endpoint.yml, pkg/provider/kubernetes/ingress/fixtures/Ingress-with-a-named-port-matching-subset-of-service-pods_ingress.yml, pkg/provider/kubernetes/ingress/fixtures/Ingress-with-a-named-port-matching-subset-of-service-pods_service.yml, pkg/provider/kubernetes/ingress/kubernetes.go, pkg/provider/kubernetes/ingress/kubernetes_test.go
Fixes an incorrect behaviour when the Endpoints generated for Service pods contain two distinct subsets for two different ports.
The bug had broken down one of our production services for a while and we had to revert to Traefik 1.7.
The bug caused some (third in our case) of HTTP requests to be forwarded to pods that hadn't had the port exposed.
=> Fix incorrect behaviour with multi-port endpoint subsets

.golangci.toml, docs/content/middlewares/headers.md, docs/content/migration/v2.md, docs/content/reference/dynamic-configuration/traefik.containo.us_middlewares.yaml, integration/fixtures/k8s/01-traefik-crd.yml, pkg/config/dynamic/middlewares.go, pkg/middlewares/headers/headers.go
Deprecates `sslRedirect`, `sslTemporaryRedirect`, `sslHost` and `sslForceHost`.
Prepare the removal of support of these options.
For simple HTTP to HTTPS redirection, one should use [EntryPoints redirections](https://doc.traefik.io/traefik/routing/entrypoints/#redirection)
For more advanced use cases, you can use either the [RedirectScheme middleware](https://doc.traefik.io/traefik/middlewares/redirectscheme/) or the [RedirectRegex middleware](https://doc.traefik.io/traefik/middlewares/redirectregex/).
=> Deprecates ssl redirect headers middleware options

docs/content/migration/v2.md, docs/content/reference/dynamic-configuration/docker-labels.yml, docs/content/reference/dynamic-configuration/file.toml, docs/content/reference/dynamic-configuration/file.yaml, docs/content/reference/dynamic-configuration/kv-ref.md, docs/content/reference/dynamic-configuration/marathon-labels.json, docs/content/reference/dynamic-configuration/traefik.containo.us_middlewares.yaml, integration/fixtures/k8s/01-traefik-crd.yml, pkg/anonymize/anonymize_config_test.go, pkg/anonymize/testdata/anonymized-dynamic-config.json, pkg/config/dynamic/fixtures/sample.toml, pkg/config/dynamic/middlewares.go, pkg/config/label/label_test.go, pkg/middlewares/headers/headers.go, pkg/provider/kv/kv_test.go
Removes deprecated headers middleware option `accessControlAllowOrigin`.
Removing a deprecated option that was supposed to be removed on v2.2.
=> Removes  headers middleware options 

webui/Dockerfile
Bump node version to the latest LTS version based on the docker-hub tag
The v12 release of Node entered a maintenance status. As a good practice, the base image should be moved to the next active LTS version
https://nodejs.org/en/about/releases/
=> Upgrade Node version to LTS on webui folder

docs/content/routing/routers/index.md, pkg/ip/checker.go, pkg/rules/rules.go, pkg/rules/rules_test.go
This PR adds IP routing based on the client IP.
You can now write your rules: ```ClientIP(`10.0.0.0`, `192.168.0.0/24`, `80fe::1`, `::1/64`)```
It supports both IPv4 and IPv6 with and without CIDR.
Fixes #7138.
`ClientIP` matcher only tries to match the request client IP and does not rely on the `X-Forwarded-For` header.
Could be nice to add a rule example in an appropriate section of the documentation.
=> Add routing IP rule matcher

docs/content/contributing/documentation.md, docs/content/middlewares/errorpages.md
1. The `make` commands for building and serving the documentation seemed out of date to me so I briefly updated them.
2. The [current documentation on error pages](https://doc.traefik.io/traefik/middlewares/errorpages/#status) was a bit brief for my taste which caused me to [ask for clarification on the discussion board](https://community.traefik.io/t/how-do-i-define-the-error-middleware-for-multiple-status-codes/10786). I have expanded it to describe the full range of possible status combinations.
[This comment](https://community.traefik.io/t/how-do-i-define-the-error-middleware-for-multiple-status-codes/10786/6?u=midnighter) on my question.
=> Elaborate on possible use of status codes with the errors middleware

pkg/provider/acme/provider.go, pkg/provider/kubernetes/crd/kubernetes.go, pkg/server/aggregator.go, pkg/server/router/tcp/router.go, pkg/tls/certificate_store.go, pkg/tls/tlsmanager.go
The changes in this PR are two-fold:
1) It makes sure that when initializing the TLS store for the ACME challenges certificates, it does not generate a (useless) default certificate (as opposed to with the other TLS stores). This solves the initial problem reported, as it won't uselessly burn CPU anymore for that on configuration reload.
2) While we were at it, we cleaned up the mutex lockings and the related writes/initialization on the Manager struct. The end result is that UpdateConfig method is now the only one actually mutating to the struct, while the Get and GetStore methods are now read-only (as their names suggested).
On slower hardware generating certificates can cause noticeable delays when configuration changes. …
=> tls Manager: do not build a default certificate for ACME challenges store

Makefile
Really small PR that fixes the bind mount to actually have `dist` as bind_dir and not `"dist"`
=> Fixed BIND_DIR quoting

docs/content/https/tls.md, docs/content/middlewares/http/forwardauth.md, docs/content/routing/providers/kubernetes-crd.md, pkg/provider/kubernetes/crd/fixtures/with_servers_transport.yml, pkg/provider/kubernetes/crd/fixtures/with_tls_options.yml, pkg/provider/kubernetes/crd/kubernetes.go, pkg/provider/kubernetes/crd/kubernetes_test.go
Instead of relying on an exact number of entries in a secret for use as a root ca or mTLS certificate set, we check for the presence of specific names.
For the rootCA's field we keep backwards compatibility with the previous behavior of just picking the first entry but only after an explicit check for `ca.crt` and `tls.ca` fails.
fixes #7788
=> Improve CA certificate loading from kubernetes secret

docs/content/observability/tracing/jaeger.md, go.mod, go.sum, pkg/tracing/jaeger/jaeger.go
This PR upgrades the jaeger client to version 2.29.1
Be able to override tracing configuration with env variables
=> Override jaeger configuration with env variables

docs/content/routing/providers/kubernetes-gateway.md
While trying out the Gateway API alpha support with the v0.1.0 CRDs, I found out that the example given in the Traefik documentation is invalid with respect to the `httproutes.networking.x-k8s.io/v1alpha1` endpoint. The last line "values" should be a `map[string]string`, instead of an array of map[string]string.
Before:
```yaml
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
spec:
rules:
- matches:
- headers:
values:
- foo: bar
```
After:
```yaml
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
spec:
rules:
- matches:
- headers:
values:
foo: bar
```
I used Traefik 2.4.8.
=> gateway-api: fix the "values" field in the example of httproute

pkg/tcp/router.go
Use a dynamic buffer to handle client Hello SNI detection.
Fixes #7644
=> Use a dynamic buffer to handle client Hello SNI detection

pkg/provider/kubernetes/crd/fixtures/tcp/with_bad_tls_options.yml, pkg/provider/kubernetes/crd/fixtures/tcp/with_tls_options.yml, pkg/provider/kubernetes/crd/fixtures/tcp/with_tls_options_and_specific_namespace.yml, pkg/provider/kubernetes/crd/fixtures/with_bad_tls_options.yml, pkg/provider/kubernetes/crd/fixtures/with_default_tls_options.yml, pkg/provider/kubernetes/crd/fixtures/with_default_tls_options_default_namespace.yml, pkg/provider/kubernetes/crd/fixtures/with_servers_transport.yml, pkg/provider/kubernetes/crd/fixtures/with_tls_options.yml, pkg/provider/kubernetes/crd/fixtures/with_tls_options_and_specific_namespace.yml, pkg/provider/kubernetes/ingress/fixtures/TLS-support_ingress.yml, pkg/provider/kubernetes/ingress/fixtures/TLS-support_secret.yml
This PR fixes malformed Kubernetes resource names in test fixtures.
Be consistent with [Kubernetes validation constraints](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names).
It follows PR #8212 which was focused on documentation.
This PR does not affect the tests in practice, since the fixtures impacted are used in unit tests and are loaded through the mock client which is not making validation against resources, and so tolerate any string value as a name inside a resource.
Therefore, the goal of this PR is only to sanitize fixtures, so it will hopefully prevent using malformed names later on.
=> Fix: malformed Kubernetes resource names and references in tests

.gitignore, cmd/traefik/plugins.go, cmd/traefik/traefik.go, go.mod, go.sum, pkg/anonymize/anonymize_config_test.go, pkg/anonymize/testdata/anonymized-static-config.json, pkg/config/static/experimental.go, pkg/plugins/builder.go, pkg/plugins/plugins.go, pkg/plugins/types.go
Adds support for local private plugins.
The plugins must be placed in `./plugins-local` directory, ex:
```
./plugins-local/
└── src
└── github.com
└── traefik
└── plugindemo
├── demo.go
├── demo_test.go
├── go.mod
├── LICENSE
├── Makefile
└── readme.md
```
Fixes  #7088
How to test it:
<details>
<summary>traefik.yml</summary>
```yml
entryPoints:
web:
address: :8081
api:
insecure: true
log:
level: DEBUG
providers:
file:
filename: ./dyn.yml
watch: true
experimental:
localPlugins:
example:
moduleName: github.com/traefik/plugindemo
```
</details>
<details>
<summary>dyn.yml</summary>
```yml
http:
routers:
my-router:
rule: host(`demo.localhost`)
service: service-foo
entryPoints:
- web
middlewares:
- my-plugin
services:
service-foo:
loadBalancer:
servers:
- …
```
=> Local private plugins.

pkg/middlewares/accesslog/logger.go, pkg/middlewares/accesslog/logger_test.go
An HTTP header can have only one value, but a header can be repeated several times.
Put all the values related to a header name in the access logs fields
Be able to show all the header values in the access log.
=> accesslog: multiple times the same header name.

Makefile
This PR adds two new targets to the makefile:
- One to run only the container integration tests (`test-integration-container`)
- One to run only the host integration tests (`test-integration-host`)
Release pressure on CI by having two targets that can be run in separate jobs.
=> Fix: Add dedicated integration tests targets for CI

Makefile, docs/content/migration/v2.md, docs/content/providers/kubernetes-crd.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, pkg/provider/kubernetes/crd/kubernetes.go, pkg/provider/kubernetes/crd/kubernetes_http.go, pkg/provider/kubernetes/crd/kubernetes_test.go
Disables the `allowCrossNamespace` by default for IngressRoute provider
Security
=> Disable Cross-Namespace by default for IngressRoute provider

docs/content/migration/v2.md, docs/content/providers/kubernetes-crd.md, docs/content/providers/kubernetes-ingress.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, integration/fixtures/k8s_crd.toml, pkg/provider/kubernetes/crd/fixtures/udp/services.yml, pkg/provider/kubernetes/crd/fixtures/udp/with_externalname_service.yml, pkg/provider/kubernetes/crd/kubernetes.go, pkg/provider/kubernetes/crd/kubernetes_http.go, pkg/provider/kubernetes/crd/kubernetes_tcp.go, pkg/provider/kubernetes/crd/kubernetes_test.go, pkg/provider/kubernetes/crd/kubernetes_udp.go, pkg/provider/kubernetes/ingress/fixtures/Ingress-with-IPv6-endpoints-externalname-enabled_ingress.yml, pkg/provider/kubernetes/ingress/fixtures/Ingress-with-IPv6-endpoints-externalname-enabled_service.yml, pkg/provider/kubernetes/ingress/fixtures/Ingress-with-service-with-externalName-enabled_ingress.yml, pkg/provider/kubernetes/ingress/fixtures/Ingress-with-service-with-externalName-enabled_service.yml, pkg/provider/kubernetes/ingress/kubernetes.go, pkg/provider/kubernetes/ingress/kubernetes_test.go
This PR:
- Disables ExternalName services by default in the KubernetesCRD provider
- Disables ExternalName services by default in the KubernetesIngress provider
- Exposes a flag to allow ExternalName services on both providers
- Adds documentation to explain the flag
- Does not create a router for invalid services (aka ExternalName services when not allowed) to maintain current behavior, as this is a bugfix, and not a PR to change core server behavior.
Security
=> Disable ExternalName Services by default on Kubernetes providers

docs/content/getting-started/faq.md, pkg/provider/file/file.go, pkg/provider/file/file_test.go, pkg/provider/file/fixtures/toml/tls_file_key.cert, pkg/server/configurationwatcher.go
It forces the content of the certificates to be loaded so it will be taken into account during the configuration update check.
It was previously only working for TLS certificates, and will now work with this PR in addition for:
* TLS store
* ServersTransport
* TLS options
Allow detection of content modification for all certificates in the configuration.
Related to #5495 
=> Detect certificates content modifications

pkg/rules/rules.go
This PR verifies the HTTP version before logging an error about a missing host header.
Fixes #5501.
- ~[ ] Added/updated tests~ None needed, bugfix
- ~[ ] Added/updated documentation~ None needed, bugfix
Interestingly the mandatory `Host` header was implemented in HTTP 1.1, so systems that don't require any host checking etc often use HTTP 1.0 where it is optional, and can save space/bandwith.
=> Ignore http 1.0 request host missing errors

CHANGELOG.md, script/gcg/traefik-bugfix.toml
Prepare release v2.4.11
aka `livarot`
=> Prepare release v2.4.11

go.mod, go.sum, pkg/middlewares/compress/compress.go, pkg/middlewares/compress/compress_test.go
This PR changes the use of [github.com/traefik/gziphandler](https://github.com/traefik/gziphandler) (based on [https://github.com/nytimes/gziphandler](https://github.com/nytimes/gziphandler)) to [github.com/klauspost/compress/gzhttp](https://github.com/klauspost/compress/tree/master/gzhttp).
According to some simple [bench test](https://github.com/klauspost/compress/tree/master/gzhttp#performance), this lib change allows for a huge performance boost.
<details><summary>Benchmark of library change</summary>
```bash
> benchcmp bench/old.txt bench/newlib.txt
benchmark                      old ns/op     new ns/op     delta
BenchmarkCompress_S2k-12       73087         34939         -52.20%
BenchmarkCompress_S20k-12      133451        42235         -68.35%
BenchmarkCompress_S100k-12     401413 …
```
=> Library change for compress middleware to increase performance

go.mod, go.sum, pkg/plugins/providers.go
- downgrade yaegi to v0.9.19
- fix mapping
Fix regression with v0.9.20
```
DEBU[2021-07-19T18:10:50+02:00] loading of plugin: example: github.com/traefik/pluginproviderdemo@v0.2.0 
12:6: panic
panic: reflect.Set: value of type *struct { Xname string; XpollInterval time.Duration; Xcancel func() } is not assignable to type func() error [recovered]
panic: reflect.Set: value of type *struct { Xname string; XpollInterval time.Duration; Xcancel func() } is not assignable to type func() errorgoroutine 1 [running]:
github.com/traefik/yaegi/interp.runCfg.func1(0xc000ed7e40, 0xc000120d00, 0xc000b72d68)
/home/ldez/sources/go/pkg/mod/github.com/traefik/yaegi@v0.9.20/interp/run.go:185 +0x253
panic(0x304ec80, 0xc000efb030)
/home/ldez/.gvm/gos/go1.16.6/src/runtime/panic.go:965 +0x1b9 …
```
=> Downgrade yaegi to v0.9.19

pkg/provider/kubernetes/ingress/client.go, pkg/provider/kubernetes/ingress/client_mock_test.go, pkg/provider/kubernetes/ingress/client_test.go, pkg/provider/kubernetes/ingress/kubernetes.go, pkg/provider/kubernetes/ingress/kubernetes_test.go
This PR modifies the kubernetes ingress provider to allow API failures without removing all routers and content.
The `GetServerVersion()` method does not use a lister, and will fail when connectivity is lost.
Fixes #8066 
- ~~[ ] Added/updated tests~~ Bugfix, manual testing
- ~~[ ] Added/updated documentation~~ Bugfix
This PR was tested by:
- Running a Kubernetes cluster (1.19.7) and deploying Traefik with the kubernetes ingress provider accessing the kubernetes cluster via `kubectl proxy`
- Deploying a whoami pod and exposing it using Ingress
- Verifying that the http router is created
- Kill the `kubectl proxy` command to make the Kubernetes API unreachable
- Wait until the resync period elapses (~10')
- Confirm that the router is still present in the dashboard/api
This PR currently:
- …
=> Don't remove ingress config on API call failure

webui/src/components/_commons/PanelMiddlewares.vue
This PR solves an issue where the dashboard does not show middlewares details.
It's a bug that was introduced by #7794 that fetched a provider's name by `middleware.provider.name` instead of `middleware.provider`.
Have a working dashboard.
Fixes #8276 
=> Fix dashboard to display middleware details

go.mod, go.sum, pkg/plugins/providers.go
Update yaegi to v0.9.21
https://github.com/traefik/yaegi/compare/v0.9.20...v0.9.21
=> Update yaegi to v0.9.21

pkg/middlewares/ratelimiter/rate_limiter.go, pkg/middlewares/ratelimiter/rate_limiter_test.go
This change fixes two issues that were sort of canceling each other:
1) the ttlSeconds argument that was given to TtlMap.Set was previously
based on a value in nanoseconds instead of seconds. That was not only
incorrect, but also potentially an integer overflow on some platforms.
(Not actually reproduced, but most likely the cause for issue 8235).
2) we were only calling TtlMap.Set when initially creating the rate
limiter for a given source. That was wrong, because the expiryTime
(now + ttlSeconds) for a given source must be updated everytime there is
any activity for a given, which is what TtlMap.Set does.
We should have observed sources getting expired and garbage collected by
ttlmap because of 2), but since we were setting an incorrect, huge,
ttlSeconds because of 1), the symptom of 2) …
=> ratelimiter: use correct ttlSeconds value, and always call Set

integration/resources/compose/k8s.yml
This PR upgrades the k3s version to fix the following issue: https://k3d.io/faq/faq/#solved-nodes-fail-to-start-or-get-stuck-in-notready-state-with-log-nf_conntrack_max-permission-denied
Stable integration tests
=> fix: upgrade k3s version

pkg/middlewares/auth/forward.go, pkg/middlewares/connectionheader/connectionheader.go, pkg/middlewares/connectionheader/connectionheader_test.go, pkg/middlewares/headers/headers.go
Clean connection header added by the header and the forward auth middleware.
Don't allow to drop a header by spoofing the `Connection` header.
=> fix: remove hop-by-hop headers define in connection header beore some middleware

pkg/provider/kubernetes/k8s/event_handler.go, pkg/provider/kubernetes/k8s/event_handler_test.go
This PR fixes the resources changes detection inside the Kubernetes event handler.
Be able to detect changes for all resources and generate a new configuration accordingly.
=> Kubernetes: detect changes for resources other than endpoints

pkg/provider/kubernetes/crd/fixtures/with_middleware_cross_namespace.yml, pkg/provider/kubernetes/crd/kubernetes_http.go, pkg/provider/kubernetes/crd/kubernetes_test.go
Disallows the 'namespace-name@kubernetescrd' middleware reference format in kubernetes crd provider to avoid cross namespace when it is not allowed.
Avoids unauthorized cross namespace reference.
=> Avoid unauthorized midlleware cross namespace reference 

pkg/config/kv/kv_node.go, pkg/config/kv/kv_test.go
Remove any trailing "/" from any key sent by a KV provider, that is about Traefik configuration.
Avoid the creation of an empty node by the parser that leads to an error like:
```
KV connection error: field not found, node: , retrying in 9.148251988s" providerName=consul
```
=> Remove unwanted trailing slash in key

.semaphore/semaphore.yml, pkg/config/kv/kv_node.go, pkg/config/kv/kv_test.go, pkg/provider/kubernetes/crd/fixtures/with_middleware_cross_namespace.yml, pkg/provider/kubernetes/crd/kubernetes_http.go, pkg/provider/kubernetes/crd/kubernetes_test.go
Merge current v2.4 branch into v2.5
Be sync.
=> Merge current v2.4 into v2.5

pkg/middlewares/redirect/redirect.go, pkg/middlewares/redirect/redirect_regex.go, pkg/middlewares/redirect/redirect_regex_test.go, pkg/middlewares/redirect/redirect_scheme.go, pkg/middlewares/redirect/redirect_scheme_test.go
~~If a request includes a port in the req.Host (forced in via the Host header), the redirect middleware should not include it when comparing old and new URLs for redirect purposes.~~
Fix comparison when explicit port request and implicit redirect port
Fixes #8345
~~I'm not 100% sure if this is a complete fix, it feels like there is variation on this that may still cause problems.~~
=> redirect: fix comparison when explicit port request and implicit redirect port

webui/src/pages/_commons/RouterDetail.vue
traefik v2.5.0-rc5 shows tcp middlewares as HTTP Middlewares in ui, see screenshot
This PR should fix it.
=> Fix dashboard title for TCP middlewares

pkg/middlewares/headers/responsewriter.go, pkg/middlewares/tracing/status_code.go
This PR adds a conditional CloseNotify in the response modifier of the header middleware to avoid a panic.
Fixes #8373 
=> Conditional CloseNotify in header middleware

docs/check.Dockerfile, docs/docs.Dockerfile, exp.Dockerfile
This PR bumps alpine docker images version to v1.14.1.
FIx [CVE-2021-36159](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-36159) for the experimental docker images: `traefik/traefik:experimental-{branch}`.
It also bumps alpine docker images version to v1.14.1 for documentation build and checks.
=> Bumps alpine docker images to v1.14.1

docs/check.Dockerfile, docs/content/routing/providers/kubernetes-gateway.md, docs/docs.Dockerfile, exp.Dockerfile
This PR pins the alpine docker image version to v3.14.
Having all released v3.14 bug fixes.
=> Fix alpine docker image to version 3.14

go.mod, go.sum
This PR bumps `go.elastic.co/apm` version from v1.11.0 to v1.13.1:
- v1.12.0 release changelog: https://github.com/elastic/apm-agent-go/releases/tag/v1.12.0
- v1.13.0 release changelog: https://github.com/elastic/apm-agent-go/releases/tag/v1.13.0
- v1.13.1 release changelog: https://github.com/elastic/apm-agent-go/releases/tag/v1.13.1
This bump brings a fix for issue #8158.
The fix https://github.com/elastic/apm-agent-go/pull/931 (release v1.12.0) allows spans without "context.destination.service.name" value (https://github.com/elastic/apm/issues/180) to be validated by APM server.
It will prevent request validation errors as the following:
```
DEBU[2021-08-24T12:13:23+02:00] request failed: request failed with 400 Bad Request: {"accepted":3,"errors":[{"message":"validation error: span: …
```
=> Bump go.elastic.co/apm version to v1.13.1

docs/content/providers/kubernetes-ingress.md, docs/content/routing/providers/kubernetes-ingress.md
This PR adds the missing `pathType` attribute for `networking.k8s.io/v1` Ingresses examples in documentation.
fixes #8379
=> Adds pathType for v1 ingresses examples

go.mod, go.sum
v0.22.1 fixes a race condition and v0.23.0 is the latest release.
https://github.com/lucas-clemente/quic-go/compare/v0.22.0...v0.23.0
=> Upgrade github.com/lucas-clemente/quic-go to v0.23.0

docs/content/middlewares/tcp/ipwhitelist.md
Fixes error in example (YAML) for TCP middleware whitelist
=> docs: fix error in example (YAML) for TCP middleware whitelist

docs/content/providers/consul-catalog.md, docs/content/providers/docker.md, docs/content/providers/ecs.md, docs/content/providers/file.md, docs/content/providers/marathon.md, docs/content/providers/rancher.md, pkg/tls/cipher.go, pkg/tls/version.go
Replaces https://golang.org/pkg by https://pkg.go.dev in documentation and comments.
Avoid doc lint errors due to URLs redirections.
=> Fix golang doc URLs

docs/content/migration/v2.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, docs/content/routing/entrypoints.md, pkg/config/static/entrypoints.go, pkg/config/static/static_config.go, pkg/server/server_entrypoint_tcp_http3.go, pkg/server/server_entrypoint_tcp_http3_test.go
* moves an EntryPoint's enableHTTP3 flag into a HTTP3Config struct under the http3 key
* adds option to configure what to advertise as the http3 authority
#8130 
I saw that the Docker integration tests are failing, but I can't figure out what is causing the issue. If someone could provide some feedback I'll fix it...
=> Add HTTP3Config

docs/content/contributing/maintainers.md
This PR adds Tom Moulard [@tommoulard](https://github.com/tommoulard) to the maintainers' team.
Tom is recognized for outstanding and valiant actions carried out lately.
=> Add Tom Moulard in maintainers team

docs/content/middlewares/http/basicauth.md, go.mod, pkg/provider/kubernetes/crd/fixtures/basic_auth_secrets.yml, pkg/provider/kubernetes/crd/kubernetes.go, pkg/provider/kubernetes/crd/kubernetes_test.go
Provides support for `basic-auth` type secrets in the kubernetes basicAuth middleware.
Fixes #7867 
- This PR keeps the same behavior for digestAuth, only basic-auth has additional secret format options.
- This PR takes the SHA1 of the secret to pass to the auth middleware. It really doesn't matter as the secret contains un-encrypted data.
=> Support Kubernetes basic-auth secrets

pkg/provider/consulcatalog/consul_catalog.go
Fixes the initialization of the `certChan` chan.
It was not supposed to be in `SetDefaults`.
Have a proper code base.
=> Fix certChan defaulting on consul catalog provider

docs/content/getting-started/faq.md, docs/content/middlewares/http/headers.md, docs/content/routing/services/index.md
Adds documentation around which headers are automatically added to proxied requests.
Users should be able to figure out what headers are added to proxied requests by default.
fixes: #8294
Happy to move this to another section of the docs if there is a better place for this information!
=> docs: add default proxy headers

docs/content/routing/providers/kubernetes-crd.md, pkg/provider/kubernetes/crd/fixtures/with_servers_transport.yml, pkg/provider/kubernetes/crd/kubernetes.go, pkg/provider/kubernetes/crd/kubernetes_test.go
This PR ensures that disabling http2 works when using the kubernetes `ServersTransport` CRD. I have added a test verifying that it works now. Previously setting the `disableHTTP2` field in the CRD did not change that configuration option.
We host traefik as an ingress loadbalancer for a number of application servers running on k8s that do not support http2 - when trying to disable http2 we kept seeing errors on our application servers indicating that http2 had not been disabled.
From my review of the code when implementing this change it looks like the `PeerCertURI` option in the CRD is also not being translated into a proper configuration of traefik. However I have not functionally verified this as we do not utilize this feature.
=> Ensure disableHTTP2 works with k8s crd

docs/content/routing/providers/kubernetes-crd.md, docs/content/routing/services/index.md, pkg/provider/kubernetes/crd/fixtures/with_servers_transport.yml, pkg/provider/kubernetes/crd/kubernetes.go, pkg/provider/kubernetes/crd/kubernetes_test.go
This PR:
- Fixes the configuration of the `PeerCertURI` configuration in the Kubernetes CRD provider.
- Clarify the `ServersTransport` documentation.
Fixes a bug and have a better documentation.
=> fix: add peerCertURI config to k8s crd provider 

docs/content/observability/metrics/influxdb.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, pkg/metrics/influxdb.go, pkg/metrics/influxdb_test.go, pkg/types/metrics.go
This allows users to set additional influxdb tags on their traefik instances so they can distinguish different traefik instances in the influxdb. For users with existing influxdb changes, this PR changes nothing during an update and the old configuration functions identically, except that they can improve it afterwards.
We have a certain fleet of traefik instances across different production environments and with different specializations. When I enabled the influxdb metric collection, it was an easy experience to do so, but it resulted in a bit of a mess on the influxdb side. With this pull request, I can add different tags to my traefik instances, so I can distinguish them.
There also is an issue about this, #6997. However, I don't think introducing default tags is a good strategy. …
=> Add configurable tags to influxdb metrics

pkg/provider/kubernetes/crd/fixtures/tcp/with_tls_options_cross_namespace.yml, pkg/provider/kubernetes/crd/fixtures/with_cross_namespace.yml, pkg/provider/kubernetes/crd/fixtures/with_servers_transport.yml, pkg/provider/kubernetes/crd/fixtures/with_servers_transport_cross_namespace.yml, pkg/provider/kubernetes/crd/fixtures/with_tls_options_cross_namespace.yml, pkg/provider/kubernetes/crd/kubernetes_http.go, pkg/provider/kubernetes/crd/kubernetes_tcp.go, pkg/provider/kubernetes/crd/kubernetes_test.go
It filters out `ServersTransport` and `TLSOptions` from namespaces that are
not in the current IngressRoute namespace and when the option
`allowCrossNamespace` is not set.
Here's a chart representing the support for each Ingress Route Types (irt):
|irt |`ServersTransport`|`TLSOptions`|
|----|------------------|------------|
|HTTP|X                 |X           |
|TCP |                  |X           |
|UDP |                  |            |
Since `TLSStore` is not used, its behavior has not changed.
Remove the access of resources from routes that should not access them.
Fixes #8415.
=> Add cross namespace verification in Kubernetes CRD

docs/content/middlewares/http/compress.md, docs/content/reference/dynamic-configuration/docker-labels.yml, docs/content/reference/dynamic-configuration/file.toml, docs/content/reference/dynamic-configuration/file.yaml, docs/content/reference/dynamic-configuration/kv-ref.md, docs/content/reference/dynamic-configuration/marathon-labels.json, docs/content/reference/dynamic-configuration/traefik.containo.us_middlewares.yaml, integration/fixtures/k8s/01-traefik-crd.yml, pkg/config/dynamic/middlewares.go, pkg/config/label/label_test.go, pkg/middlewares/compress/compress.go, pkg/middlewares/compress/compress_test.go, pkg/provider/kv/kv_test.go
This pull request aims to implement a way to customize the minimum body size for the [compress middleware](https://doc.traefik.io/traefik/middlewares/compress/) to apply.
According to the documentation, this minimum size should currently be hardcoded to **1400 bytes**, however, after some skimming through the code, I cannot find the part where that happens. Is this an issue in the documentation or is it an issue on my side?
1. I wanted to get into contributing to other, bigger projects and I really like traefik, so I chose to give it a try.
2. This feature was requested (#8197)
Fixes #8197
I would be happy about any constructive criticism as this is my first PR to traefik.
I may make some mistakes, like forgetting to change something in another area, because I don't know the complete …
=> Implement customizable minimum body size for compress middleware

docs/content/reference/dynamic-configuration/traefik.containo.us_tlsoptions.yaml, integration/fixtures/k8s/01-traefik-crd.yml, pkg/provider/kubernetes/crd/traefik/v1alpha1/tlsoption.go
This PR adds the missing `RequireAnyClientCert` value to the TLSOption CRD.
Related to https://github.com/traefik/traefik-helm-chart/issues/503
=> fix: add missing RequireAnyClientCert value to TLSOption CRD

docs/content/middlewares/http/errorpages.md, docs/content/migration/v2.md, pkg/middlewares/customerrors/custom_errors.go, pkg/middlewares/customerrors/custom_errors_test.go
This PR fixes the Host header value forwarded to the configured service in the Errors middleware.
Previously when the service was configured with the `PassHostHeader` value set to `true` the forwarded Host header value was `0.0.0.0`. Now, in that case, the forwarded value is the client request Host value. 
Allows the Errors middleware service to be aware of the client request Host.
Related to https://github.com/traefik/traefik/issues/8267 and https://github.com/traefik/traefik/pull/8433.
=> fix: forward request Host to errors middleware service

cmd/internal/gen/main.go, docs/content/user-guides/grpc.md, integration/healthcheck_test.go, pkg/middlewares/tcp/ipwhitelist/ip_whitelist_test.go
Move from deprecated `ioutil` to `os` and `io` packages.
Replace deprecated functions.
Since Traefik is currently using Go 1.16 and CI using Go 1.17, so it is safe to remove deprecated `ioutil` package, ref https://golang.org/doc/go1.16#ioutil.
Associated with traefik/traefik#8471.
=> Move from deprecated ioutil to os and io packages

docs/content/migration/v2.md, docs/content/reference/dynamic-configuration/kubernetes-gateway-rbac.yml, docs/content/routing/providers/kubernetes-gateway.md, pkg/provider/kubernetes/gateway/client.go, pkg/provider/kubernetes/gateway/client_mock_test.go, pkg/provider/kubernetes/gateway/fixtures/httproute/with_namespace_all.yml, pkg/provider/kubernetes/gateway/fixtures/httproute/with_namespace_same.yml, pkg/provider/kubernetes/gateway/fixtures/httproute/with_namespace_selector.yml, pkg/provider/kubernetes/gateway/fixtures/mixed/simple.yml, pkg/provider/kubernetes/gateway/fixtures/mixed/with_multiple_protocol_using_same_port.yml, pkg/provider/kubernetes/gateway/fixtures/mixed/with_namespace_all.yml, pkg/provider/kubernetes/gateway/fixtures/mixed/with_namespace_same.yml, pkg/provider/kubernetes/gateway/fixtures/mixed/with_namespace_selector.yml, pkg/provider/kubernetes/gateway/fixtures/services.yml, pkg/provider/kubernetes/gateway/fixtures/tcproute/with_namespace_all.yml, pkg/provider/kubernetes/gateway/fixtures/tcproute/with_namespace_same.yml, pkg/provider/kubernetes/gateway/fixtures/tcproute/with_namespace_selector.yml, pkg/provider/kubernetes/gateway/fixtures/tlsroute/with_multiple_routes_kind.yml, pkg/provider/kubernetes/gateway/fixtures/tlsroute/with_namespace_all.yml, pkg/provider/kubernetes/gateway/fixtures/tlsroute/with_namespace_same.yml, pkg/provider/kubernetes/gateway/fixtures/tlsroute/with_namespace_selector.yml, pkg/provider/kubernetes/gateway/kubernetes.go, pkg/provider/kubernetes/gateway/kubernetes_test.go, pkg/provider/kubernetes/k8s/parser.go
This PR adds support for the `namespace` directive in a {HTTP,TCP,TLS}Route.
It allows routes [filtering](https://gateway-api.sigs.k8s.io/concepts/security-model/#route-namespaces) based on namespaces.
Close #8246
=> gateway api: support RouteNamespaces

docs/content/middlewares/http/forwardauth.md, docs/content/middlewares/http/headers.md, docs/content/middlewares/http/redirectregex.md, docs/content/middlewares/http/replacepathregex.md, docs/content/middlewares/http/stripprefixregex.md
This warning box advises the user that any escape characters within the regular expression, must then be escaped again for parsing with YAML.
A desire to help other users from encountering the same issue.
This pull request may be considered general knowledge for YAML and not specific to Traefik, and therefore not appropriate for merging.
=> Mention escaping escape characters in YAML for regex usage

docs/content/observability/metrics/datadog.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, pkg/metrics/datadog.go, pkg/metrics/datadog_test.go, pkg/metrics/metrics.go, pkg/metrics/statsd.go, pkg/metrics/statsd_test.go, pkg/types/metrics.go
add prefix configuration for datadog metric sink, similar to statsd
we are using datadog but what to change the prefix similar to statsd sink type. This change is to mirror the same behavior over to datadog sink.
=> Add prefix to datadog metrics

docs/content/middlewares/http/forwardauth.md, docs/content/providers/consul-catalog.md, docs/content/providers/consul.md, docs/content/providers/docker.md, docs/content/providers/etcd.md, docs/content/providers/http.md, docs/content/providers/kubernetes-crd.md, docs/content/providers/kubernetes-ingress.md, docs/content/providers/marathon.md, docs/content/providers/redis.md, docs/content/providers/zookeeper.md, pkg/types/tls.go, pkg/types/tls_test.go
This PR fixes the built `tls.Config` by the `ClientTLS.CreateTLSConfig` method to use the host's system root CA set when the `tls.ca` option is not defined. As described in the `tls.Config` documentation:
> RootCAs defines the set of root certificate authorities that clients use when verifying server certificates. If RootCAs is nil, TLS uses the host's root CA set. 
Being able to use the system root CA set in the `ForwardAuth` middleware and in the `Consul`, `Consul Catalog`, `HTTP`, `Marathon`, `Redis`, `ZooKeeper`, `Docker` and `Etcd` providers
=> fix: use host's root CA set if ClientTLS ca is not defined

.gitignore
It makes git ignore `webui/static/`.
When going from the master branch to the v2.5 one, this generated folder is not ignored by git.
=> fix: git ignore webui/static/

docs/content/routing/routers/index.md
I have added a small section of text that explains that in the `HostRegexp` and `Path` router rules the 'name' in named groups (`{name:pattern}`) can be any arbitrary variable.
When I initially looked at the example I did not think it was as clear that the part before the colon could be anything, the original text before a recent update said:
In order to use regular expressions with `Host` and `Path` expressions, you must declare an arbitrarily named variable followed by the colon-separated regular expression, all enclosed in curly braces.
This made it clear that 'name' could be anything so I thought adding a similar note to the current wording would be helpful.
updated documentation
=> docs: add named groups details to Regexp Syntax section

docs/content/observability/metrics/datadog.md, docs/content/observability/metrics/influxdb.md, docs/content/observability/metrics/prometheus.md, docs/content/observability/metrics/statsd.md
This PR fixes the `addRoutersLabels` option name to be consistent with `addEntryPointsLabels` and `addServicesLabels`.
Be consistent.
=> docs: fix typo in addRoutersLabels option title

pkg/tcp/wrr_load_balancer.go, pkg/tcp/wrr_load_balancer_test.go, pkg/udp/wrr_load_balancer.go
This PR fixes a panic when all TCP/UDP services of a WRR have a weight set to 0.
It also forbids unwanted connections forwarding when all services of a WRR have weight set to 0
Fix WRR behavior when all services have a weight of 0.
=> fix: TCP/UDP wrr when all servers have a weight set to 0

.gitignore
It makes git ignore `autogen/`.
When going from the v2.5 branch to the master one, this generated folder is not ignored by git.
=> fix: git ignore autogen/

pkg/udp/conn.go, pkg/udp/conn_test.go, pkg/udp/proxy.go, pkg/udp/proxy_test.go
This PR increase the buffer length used to read a UDP datagram received by Traefik and by the proxied server. When reading from a `SOCK_DGRAM` if the length of the buffer is lower than the datagram data size, the excess bytes are discarded.
As it is not possible to know the buffer length before reading the datagram data (without using `RAW` sockets), the buffer length is now initialized to the maximum datagram size (65535 bytes).
Fixes https://github.com/traefik/traefik/issues/8547
=> fix: increase UDP read buffer length to max datagram size

docs/content/routing/routers/index.md
Fixes a very minor spelling error
New text was added to the Regexp Syntax section but a small spelling error was introduced
=> fixed minor spelling error in Regexp Syntax section

docs/content/https/acme.md, docs/content/https/ref-acme.toml, docs/content/https/ref-acme.txt, docs/content/https/ref-acme.yaml, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, pkg/anonymize/anonymize_config_test.go, pkg/anonymize/testdata/anonymized-static-config.json, pkg/provider/acme/provider.go, pkg/provider/acme/provider_test.go
Before this PR, when there were less than 30 days remaining before an ACME-obtained certificate expired, Traefik would attempt to renew it automatically. Now that value of 30 days is configurable (but it's still the default value). This setting is per `certResolver`. The new setting is called `renewBeforeExpiry`.
Also, Traefik would perform this check every 24 hours. That interval was reduced to once every hour per certificate.
Closes #8042 
This is useful when using an ACME server that issues short-lived certificates (e.g. 24 hours).
=> feat: allow configuration of ACME certificates duration

docs/content/routing/services/index.md
Change link to the kubernetes documentation regarding Health check behaviour.
The kubernetes liveness probe status should not be used by load balancer. Traffic should be redirected to 'ready' Pods, not 'live' Pods.
From the k8s doc: 
`The kubelet uses readiness probes to know when a container is ready to start accepting traffic.`
https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md?plain=1#L17-L18
=> docs: health check use readiness probe in k8s

pkg/middlewares/ratelimiter/rate_limiter.go
Closes #8573 
I faced inconsistent results comparing `Retry-After` and `X-Retry-In` headers when using the `rate-limit` Middleware
=> feat: rate-limit ceil Retry-After to superior integer

go.mod, go.sum
Update yaegi to v0.11.1
https://github.com/traefik/yaegi/compare/v0.11.0...v0.11.1
=> Update yaegi to v0.11.1

docs/content/providers/consul-catalog.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, pkg/provider/consulcatalog/consul_catalog.go
This pull request brings the partial support of [Consul Enterprise Namespaces](https://www.consul.io/docs/enterprise/namespaces).
Today, the Traefik resource identifiers (routers, services, ...) defined with consul catalog service tags are not namespaced (the name match the ones defined in the tags). As a side effect, allowing to discover services in multiple namespaces could lead to Traefik resource name collision (e.g. the same router could be defined in a `production` and `staging` environment). Therefore, with this pull request, it is only possible to define one namespace.     
Superseeds https://github.com/traefik/traefik/pull/8174
Fixes https://github.com/traefik/traefik/issues/8171
=> Support consul enterprise namespaces in consul catalog provider

go.mod, go.sum
Update go-acme/lego to v4.5.3
https://github.com/go-acme/lego/compare/v4.5.0...v4.5.3
The `preferredChain` parameter is currently only considered for initial issuance of certs but not for renewals. This is fixed in https://github.com/go-acme/lego/pull/1502 with [v4.5.3](https://github.com/go-acme/lego/releases/tag/v4.5.3). I updated the go package accordingly.
=> Update go-acme/lego to v4.5.3

provider/kubernetes/fixtures/tLSSecretLoad_ingresses.yml, provider/kubernetes/fixtures/tLSSecretLoad_secrets.yml, provider/kubernetes/kubernetes.go, provider/kubernetes/kubernetes_test.go
If a user creates a secret with binary encoded key and certificate data (DER), it will cause `p.loadConfig` to fail to parse the template configuration generated from `p.loadIngresses`.
I have not verified if the k8s provider in traefik-2 is susceptible to this behavior, but will be happy to submit a new PR for 2.x if the issue exist there as well. Another option would be to support DER format, and either encode it properly; or convert to PEM format. 
Closes #8142
This PR is a duplicate of https://github.com/traefik/traefik/pull/8143 done by @jr0d.
A new PR had to be created because the original one cannot be merged as-is (because it was created by an organization).
Co-authored-by: Jared Rodriguez <jared@blacknode.net>
=> require that secret is a valid PEM

go.mod, go.sum
This PR updates the golang.org/x/net dependency version to `v0.0.0-20211209124913-491a49abca63`
https://github.com/golang/net/compare/04defd469f4e...491a49abca63
Be up to date.
=> chore: update golang.org/x/net dependency version

docs/content/middlewares/http/overview.md
I am very new to Traefik and start by trying to understand the documentation. In this code snippet, I didn't see a way how the router configuration would point to any existing service, so I updated the reference from "myService" (not defined in the services section) to "service1" (as defined in the services section).
I hope I understood the concept right...
I didn't understand the doc and figured there might be an error in it.
none
=> Correct documentation in middleware overview

.semaphore/semaphore.yml, CHANGELOG.md, CODE_OF_CONDUCT.md, docs/content/middlewares/http/basicauth.md, docs/content/middlewares/http/overview.md, docs/content/middlewares/http/passtlsclientcert.md, go.mod, go.sum, pkg/middlewares/forwardedheaders/forwarded_header.go, pkg/middlewares/forwardedheaders/forwarded_header_test.go, pkg/plugins/builder.go, pkg/plugins/providers.go, script/gcg/traefik-bugfix.toml
Merge current v2.5 branch into master.
Be synced.
=> Merge back v2.5 into master

.semaphore/semaphore.yml, build.Dockerfile
Since the recent release of [goreleaser](https://goreleaser.com) [v1.2.1](https://github.com/goreleaser/goreleaser/releases/tag/v1.2.1), the script to install it was removed.
This PR update the script to install goreleaser to use a gist instead.
Have a working CI.
=> fix: update goreleaser install link to use gist

build.Dockerfile
This PR updates the [golangci-lint](https://github.com/golangci/golangci-lint) installation script URL to use GitHub instead of [goreleaser](https://github.com/goreleaser/goreleaser).
This is due to the recent deprecation of [godownloader](https://github.com/goreleaser/godownloader) used by goreleaser.
Have a working CI.
=> Update golangci-lint install script

.semaphore/semaphore.yml
This PR rolls back a change from #8651 that added by mistake the script to install go-bindata back into semaphore.
Have a proper setup script for semaphore.
=> Remove go-bindata from semaphore

docs/content/providers/kubernetes-crd.md, docs/content/providers/kubernetes-ingress.md
Fix a small typo in `Provider` documentation (`Ingress` & `IngressRoute`):
`labelselector` in the **File (YAML)** example should be camel case, `labelSelector`
Copy'n'pasted without checking the example properly 🤦
=> Remove typo in Kubernetes providers labelSelector examples

docs/content/routing/routers/index.md
This PR should make the use of regular expressions in Traefik clearer. I wasted multiple hours (and found multiple issues and posts from others who had struggled the same) because I expected that the parameter of `HostRegexp(...)` was, well ... a regex... 🤷‍♂️ 
I hope the explicit statement, that values are interpreted verbatim and not as regex outside of curly braces will help others
=> Improve regexp matcher documentation

go.mod, go.sum
This PR update github.com/instana/go-sensor version to v1.38.3
github.com/instana/go-sensor has v1.38.3 has many improvements in comparison to the previous version. The most important is the improvement of the announcement process: reduce a discovery time for containerized environments for a sensor agent version >= 1.3.1.
https://github.com/instana/go-sensor/compare/v1.31.1...v1.38.3
=> Upgrade Instana tracer dependency

webui/src/components/_commons/PanelMiddlewares.vue
This PR fixes text overflow in the dashboard.
It provides a better readability to middleware REGEXP panel by hiding the overflow with ellipsis and display a tooltip when the mouse hovers the regexp(e.g. see screenshots).
This PR re-uses the overflow functionality introduced in #7535.
Fix a visual problem when using middlewares
Fixes #6947
|From|To|
|:--:|:--:|
|![Screenshot from 2022-01-13 11-25-35](https://user-images.githubusercontent.com/10183798/149314070-89fbfd03-b645-493a-8e97-1d9de3cf35fa.png)|![Screenshot from 2022-01-13 11-32-20](https://user-images.githubusercontent.com/10183798/149314103-8242247a-5326-43a1-9cf6-41d65d2a8821.png)|
|![Screenshot from 2022-01-13 …
=> Fix middleware regexp's display

pkg/plugins/builder.go, pkg/plugins/middlewares.go, pkg/plugins/providers.go
Evaluate all functions at the start of Traefik instead of during the reload of the dynamic configuration.
Before:
After:
Fix https://github.com/traefik/plugin-log4shell/issues/4
=> fix: middleware plugins memory leak

go.mod, go.sum
This PR bumps the mux dependency version, because it contains a work-around to mitigate a memory leak.
To fix a memory leak, which might be the one observed at #7964 for example.
#8044, #7533
=> Mitigate memory leak

docs/content/providers/consul.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, pkg/provider/kv/kv.go
This pull request fixes the missing token configuration. This token is used to connect/authenticate with Consul KV.
Support token authentication for Consul KV.
=> Support token authentication for Consul KV 

docs/content/providers/http.md
This pull request fixes the endpoint config example for the HTTP provider. The config example is working, but using an array is misleading as one could think that the HTTP provider supports multiple endpoints (see https://community.traefik.io/t/multiple-http-providers/13102).
Fix the misleading HTTP provider endpoint config example.
=> Fix HTTP provider endpoint config example 

pkg/server/configurationwatcher.go
It changes the log level of the message `"Skipping same configuration"` from `info` to `debug`.
Supersedes #8709
Co-authored-by: rhtenhove <rhtenhove@users.noreply.github.com>
=> Adjust log level from info to debug

docs/content/observability/metrics/overview.md
Correct the "InfluxDB" tab name typo, from "InfluDB", on the metrics overview page.  
Same as #8317, but based on the correct branch.
Noticed there a typo while browsing the docs.
N/A
=> Fix typo in metrics overview page

docs/content/providers/consul-catalog.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, integration/consul_catalog_test.go, integration/fixtures/consul_catalog/simple_watch.toml, pkg/provider/consulcatalog/connect_tls.go, pkg/provider/consulcatalog/consul_catalog.go
It allows the configuration to be reloaded on Consul events.
To be able to only reload the configuration when it is actually necessary, and decrease the frequency of requests to the Consul server.
=> Watch for Consul events to rebuild the dynamic configuration

docs/content/observability/metrics/datadog.md, docs/content/observability/metrics/influxdb.md, docs/content/observability/metrics/overview.md, docs/content/observability/metrics/prometheus.md, docs/content/observability/metrics/statsd.md
This PR corrects the documentation examples to remove superfluous quotes (`"`) in YAML.
It also fixes the order of some example tabs.
This PR also remove documentation for `Configuration reload failures` and `Last Configuration Reload Failure` metrics that are not used.
Finally, this PR adds documentation for the `TLS certificates expiration` metric that was missing.
Have proper documentation.
=> Fix mixups in metrics documentation

docs/content/migration/v2.md, docs/content/observability/metrics/overview.md, pkg/middlewares/metrics/metrics.go, pkg/middlewares/metrics/metrics_test.go
Adds a validation mechanism when adding metrics to buckets.
Prevent each new verb used to add memory usage and metrics cardinality.
See https://github.com/prometheus/client_golang/blob/main/prometheus/promhttp/instrument_server.go#L374-L409
=> Fix metrics bucket key high cardinality

.goreleaser.yml
Add s390x arch support 
Increasing usage of Kubernetes on s390x.
Fixes #8728
=> Add s390x arch support

go.mod, go.sum
Upgrade quic-go to v0.25.0.
First release to support upcoming go 1.18.
https://github.com/lucas-clemente/quic-go/compare/v0.23.0...v0.25.0
=> Upgrade quic-go to v0.25.0

pkg/config/static/entrypoints.go, pkg/server/server_entrypoint_tcp.go, pkg/server/server_entrypoint_tcp_http3.go
This pull request removes the http3 server used to set the Quic headers, to use the new exposed `Port` option.
=> Configure advertised port using h3 server option

.github/workflows/documentation.yml
Update `seo` tool and use the flag `product`
Currently, all the documentation tiles contain `Site` instead of `Traefik`
=> docs: fix product name

.github/workflows/build.yaml, .github/workflows/test-unit.yaml, .github/workflows/validate.yaml, .gitignore, .semaphore/semaphore.yml, Makefile, docs/content/contributing/building-testing.md, webui/.gitignore, webui/dev/scripts/transfer.js, webui/readme.md, webui/static/DONT-EDIT-FILES-IN-THIS-DIRECTORY.md
This PR makes the WebUI static assets directory always contains a file. So that the go embed directive to load those assets never fails.
This PR fixes the empty WebUI static assets directory issue when using the Traefik v2 module which uses go embed as a dependency.
A rework of the `build-image` makefile goal is also brought by this PR. It should ensure that each execution produces the same behavior.
=> Fix empty WebUI static assets directory

.github/workflows/build.yaml, .github/workflows/test-unit.yaml, .github/workflows/validate.yaml, .semaphore/semaphore.yml, Makefile, build.Dockerfile, debug.Dockerfile, docs/content/contributing/building-testing.md, exp.Dockerfile
This PR adds new targets in order to build faster (especially on Mac) docker images, for easier iteration while debugging on e.g. Kubernetes. The generated image is also alpine-based, with tools, instead of being from scratch.
It also cleans up a few things to ease maintainability/readability.
To ease the debugging workflow on Kubernetes.
=> Add simpler and faster debug Makefile target

docs/content/routing/routers/index.md
This pull request fixes the `HostRegexp` examples which do not use the right syntax.
https://github.com/traefik/traefik/pull/8686#issuecomment-1058617275
=> Fix HostRegexp examples

docs/content/routing/routers/index.md
This PR adjusts rule length in HostRegex matcher routers documentation.
=> Adjust rule length in routers documentation

docs/content/providers/kubernetes-crd.md, docs/content/providers/kubernetes-ingress.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, integration/testdata/rawdata-crd.json, pkg/provider/kubernetes/crd/fixtures/services.yml, pkg/provider/kubernetes/crd/fixtures/tcp/services.yml, pkg/provider/kubernetes/crd/fixtures/tcp/with_empty_services.yml, pkg/provider/kubernetes/crd/fixtures/udp/services.yml, pkg/provider/kubernetes/crd/fixtures/udp/with_empty_services.yml, pkg/provider/kubernetes/crd/fixtures/with_empty_services.yml, pkg/provider/kubernetes/crd/kubernetes.go, pkg/provider/kubernetes/crd/kubernetes_http.go, pkg/provider/kubernetes/crd/kubernetes_tcp.go, pkg/provider/kubernetes/crd/kubernetes_test.go, pkg/provider/kubernetes/crd/kubernetes_udp.go
This PR adds an option to set `allowEmptyServices` like `--providers.kubernetesingress.allowEmptyServices=true`.
If true, returns 503 instead of 404 if no endpoints are available.
Fix #8708
=> Allow empty services in Kubernetes CRD

docs/content/routing/routers/index.md, pkg/muxer/tcp/mux.go, pkg/muxer/tcp/mux_test.go
This PR adds the support of a new `HostSNIRegexp` rule matcher to the TCP muxer.
fixes https://github.com/traefik/traefik/issues/7266
=> Add HostSNIRegexp rule matcher for TCP

docs/content/https/tls.md
Documentation enhancements:
- for Traefik v2: use branch v2.6
Add Kubernetes documentation tab to 'Default Certificate' section
Missing documentation
=> Add default certificate definition example for Kubernetes

docs/content/https/acme.md
Corrects inconsistent usage of "Certificates Resolver(s)" in the docs and adds a documentation note about the difference in the key name.
Confusing `certificatesResolvers` with `certificateResolvers` or `certificateResolver` seems to be a common issue. Cite:
* https://github.com/traefik/traefik/issues/7414
* https://community.traefik.io/t/a-solution-to-the-incredibly-unhelpful-the-router-uses-a-non-existent-resolver-letsencrypt-message/3859
I ran into the same issue when trying to get my Let'sEncrypt setup working -- a note would have been helpful.
=> Fix certificates resolver typo

cmd/traefik/plugins.go
A Pilot token is now not required to use plugins.
Move to the future
=> Plugins and token

docs/requirements.txt
This PR sets the version of Jinja to `3.0.0` to build the documentation.
Have a working CI / documentation.
=> Fixing dependency to build doc

docs/content/traefik-hub/index.md
This PR fixes a bad configuration example in the Traefik Hub documentation.
Having correct documentation.
=> Fix hub tls documentation

pkg/plugins/middlewares.go, pkg/plugins/plugins.go, pkg/plugins/plugins_test.go, pkg/plugins/providers.go
Trying to use the right separator for parsing slices for the plugins configuration.
related to #8850
Fixes #8885
The solution is not perfect because if the slice contains only one value with a comma the parsing will split on this character.
A workaround, for slices with only one value, is to add the character `║` at the beginning of this value.
=> Fix slice parsing for plugins

.goreleaser.yml, .semaphore/semaphore.yml
This PR create some free space on semaphore before creating a release and it also add `-trimpath` option during the build
Be able to do a release
=> fix: CI release

pkg/tls/tlsmanager.go
This PR removes the returned errors from the `GetCertificate` func in TLSConfig on the server side and replaces them with a log.
This will allow the private `getCertificate` from `crypto/tls` package to return the correct `errNoCertificates` error (see crypto/tls [common.go](https://cs.opensource.google/go/go/+/dev.boringcrypto.go1.17:src/crypto/tls/common.go;l=1058))
when no certificate can be found.
Fixes #8888
=> Return TLS unrecognized_name error when no certificate is available

docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, docs/content/routing/entrypoints.md, pkg/config/static/entrypoints.go, pkg/server/server_entrypoint_tcp.go, pkg/server/server_entrypoint_tcp_http3_test.go, pkg/server/server_entrypoint_tcp_test.go
This PR allows configuring the max concurrent stream value of HTTP/2 entrypoint.
Fixes #8768
=> Allow HTTP/2 max concurrent stream configuration

Makefile, build.Dockerfile, docs/content/contributing/maintainers-guidelines.md, docs/content/contributing/submitting-issues.md, docs/scripts/verify.sh, exp.Dockerfile
To mitigate [CVE-2022-24765](https://github.blog/2022-04-12-git-security-vulnerability-announced/), `git` introduced the [`safe.directory`](https://git-scm.com/docs/git-config/2.35.2#Documentation/git-config.txt-safedirectory) configuration.
This PR sets an argument in the docker building process to take advantage of such mitigation.
<details>
<summary markdown="span">Here is an example of the encountered error on semaphore</summary>
```
---> Making bundle: binary (in /home/semaphore/go/src/github.com/traefik/traefik/script)03:20
fatal: unsafe repository ('/home/semaphore/go/src/github.com/traefik/traefik' is owned by someone else)03:20
To add an exception for this directory, call:03:20
git config --global --add safe.directory /home/semaphore/go/src/github.com/traefik/traefik
``` …
=> Add safe.directory to the build image

docs/content/observability/access-logs.md
It brings the example syntax for `[accessLog.fields]` from its place above the YAML/TOML code blocks into the TOML code block.
I saw the rendered documentation on the website and spotted some oddly-formatted text in the access log filtering examples. I wanted to help! 😉
I really enjoy using Traefik. 🫂
=> Move accessLog.fields example to TOML section

docs/content/observability/access-logs.md
Fixed documentation formatting for default values of access log fields.
I found out that documentation was formatted incosistently.
=> docs: add default mode for fields.names to access log

script/codegen.Dockerfile
Enhancements:
* Dockerfile: fix for users with large uids
see https://github.com/moby/moby/issues/5419 for details
On ubuntu large UIDs won't work. If we use `useradd` with the option...
```
-l, --no-log-init
Do not add the user to the lastlog and faillog databases.
```
things work. I doubt that we need the user to be added to the lastlog or faillog database.
---
[Mathias Zeller](mailto:mathias.zeller@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)).
=> codegen: fix for users with large uids

pkg/middlewares/redirect/redirect.go, pkg/middlewares/redirect/redirect_regex.go, pkg/middlewares/redirect/redirect_scheme.go
This PR changes the way regexp is handled by the redirect middleware.
It changes from being compiled for every request to being compiled when Traefik is launched.
To have a potentially faster redirect middleware.
=> Fix regexp handling in redirect middleware 

docs/content/middlewares/http/buffering.md, docs/scripts/verify.sh, go.mod, go.sum, pkg/middlewares/buffering/buffering_test.go
This pull request fixes the default value of `MemResponseBodyBytes` option to `1048576` by updating the dependency to github.com/containous/multibuf (see https://github.com/containous/multibuf/pull/1). Because of a bug, it used to be `0` which means that there was nothing buffered in memory (everything on disk).
It also fixes the documentation accordingly.
To address this comment: https://github.com/traefik/traefik/issues/4580#issuecomment-1098530051.
=> Fix default for buffering middleware 

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature-request.yml
This pull request replaces the old Traefik community links (https://community.containo.us) with the new ones (https://community.traefik.io) in the GitHub templates.
To have the traefik.io community links.
=> Fix Traefik community links in GitHub templates

go.mod, go.sum
Update Yaegi to v0.11.3
https://github.com/traefik/yaegi/compare/v0.11.2...v0.11.3
=> Update Yaegi to v0.11.3

pkg/middlewares/customerrors/custom_errors.go
This PR re-adds a missing writeheader call (that was removed in #8932 ) in Flush that is needed in case Flush is called before anything else.
This PR also simplifies the Write(header) methods of the codeCatcher.
Readability and maintainability.
=> Re-add missing writeheader call in flush

pkg/provider/acme/provider.go, pkg/provider/acme/provider_test.go
Fixes typos in ACME provider getCertificateRenewDurations and test comments:
- There are actually 365 days in a year
- Renew period for 1 year certificates is actually 4 months (the test comment says 2)
This aligns the code with the documentation
First commit adds a test for 90d < certificateDuration  < 1y to highlight issue
Second commit actually fixes it to make the new and existing tests pass
=> Fix RenewInterval computation in ACME provider

go.mod, go.sum
This PR upgrades the `jaeger-client-go` package to v2.30.0.
The upgrade fixes b3 span id format to always be 16 characters long.
Fixes https://github.com/traefik/traefik/issues/8949
https://github.com/jaegertracing/jaeger-client-go/compare/v2.29.1...v2.30.0
=> Update jaeger-client-go to v2.30.0

docs/content/middlewares/http/errorpages.md, pkg/middlewares/customerrors/custom_errors.go, pkg/middlewares/customerrors/custom_errors_test.go
This PR adds the `{url}` variable in the `query` option of the ErrorPages middleware.
This PR fixes #3420.
=> Support URL replacement in errors middleware

docs/content/contributing/maintainers-guidelines.md
=> Fix typo in maintainers guidelines

docs/scripts/verify.sh, pkg/provider/kubernetes/crd/kubernetes.go
When an IngressRoute and an ExternalName do not have matching ports, a
warning is printed to the log. However, it was not formatted so it ended
up looking like:
> time="2022-05-10T07:23:09Z" level=warning msg="The port %d from
IngressRoute doesn't match with ports defined in the ExternalName
service %s/%s.{0 8080 }mynsmyservice"
I saw this error crop up in my Traefik logs. It was helpful, so I thought I'd fix it.
=> Fix log statement for ExternalName misconfig

pkg/provider/hub/hub.go
skip Provide when TLS is nil
```
time="2022-05-19T12:28:42Z" level=error msg="Error in Go routine: runtime error: invalid memory address or nil pointer dereference"
time="2022-05-19T12:28:42Z" level=error msg="Stack: goroutine 91 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine({0x314da80, 0x60a2d40})\n\t/go/src/github.com/traefik/traefik/pkg/safe/routine.go:66 +0xa5\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1()\n\t/go/src/github.com/traefik/traefik/pkg/safe/routine.go:56 +0x36\npanic({0x314da80, 0x60a2d40})\n\t/usr/local/go/src/runtime/panic.go:1038 +0x215\ngithub.com/traefik/traefik/v2/pkg/provider/hub.createAgentClient(0x37edb5e)\n\t/go/src/github.com/traefik/traefik/p …
```
=> fix: skip Provide when TLS is nil

pkg/tcp/proxy.go, pkg/tcp/proxy_test.go
Fix #8347
since we probably missed that use case in #7370
When initializing a TCP proxy the code was failing fast if the initial address was not resolvable, meaning it would never get refreshed or attempt a new lookup until the dynamic configuration is reloaded to rebuild the router.
This is especially problematic when you're starting both the proxy and the target service at the same time without any guarantee that the target service name will be ready when Traefik builds the router/proxy.
=> Fix initial tcp lookup when address is not available

pkg/tls/tlsmanager.go, pkg/tls/tlsmanager_test.go
This PR adds a validation before returning the default certificate.
If the certificate store is nil, it closes the connection.
Fixes #9016
=> Fix panic when getting certificates with non-existing store

go.mod, go.sum
Update Yaegi to v0.12.0
https://github.com/traefik/yaegi/compare/v0.11.0...v0.12.0
There's an API change, but it is a non-breaking one (new `FileSet` and `Globals` methods on the interpreter type). It is only for debugging purposes, and should not affect traefik plugins themselves.
=> Update Yaegi to v0.12.0

docs/content/routing/providers/kubernetes-gateway.md
This PR updates TCPRoute and TLSRoute documentation links.
This PR also removes useless EOL whitespaces.
As this PR updates documentation links, it fixes CI issues on dead links. 
=> Update Gateway API links

docs/content/routing/routers/index.md
fix rule expression render.
Before:
After:
=> docs: fix rule expression render

pkg/server/router/tcp/router.go
use `%v` instead of `%w`
```
Error while adding route for host: %!w(*errors.errorString=&{invalid value for \"HostSNI\" matcher, \"foo_bar.example.com\" is not a valid hostname})
```
=> fix: invalid placeholder in log message

docs/content/routing/services/index.md, pkg/server/service/service.go
This PR adds a log to help users understand their health check configuration is missing the `path` argument.
When the health check does not have a path, the configuration is omitted and not effective. There is no indication and everything looks like working properly.
=> Add log when missing path in health check

docs/content/middlewares/http/passtlsclientcert.md
info.serialNumber : true does not pass serial number in 'X-Forwarded-Tls-Client-Cert-Info' header.
Added documentation for info.serialNumber which passes serial number in 'X-Forwarded-Tls-Client-Cert-Info' header.
=> docs: add missing info.serialNumber option to PassTLSClientCert middleware

go.mod, go.sum
Update Yaegi to v0.13.0
https://github.com/traefik/yaegi/compare/v0.12.0...v0.13.0
=> Update yaegi to v0.13.0

pkg/healthcheck/healthcheck.go, pkg/healthcheck/healthcheck_test.go
This PR makes sure that the health check routine does not hammer a poor remote server with a ton of requests during the health check routine if the URL to check is the same.
Fixes #7043
I'm not sure if this is the best approach. I don't think we should have the same URLs multiple times in a load balancer but on the other hand removing one URL from a load balancer should not impact others?
=> Do not make multiple requests to the same URL for balancer healthcheck 

docs/content/middlewares/http/redirectscheme.md, pkg/middlewares/redirect/redirect_scheme.go, pkg/middlewares/redirect/redirect_scheme_test.go
This PR allows the RedirectScheme middleware to redirect a request based on the `X-Forwarded-Proto` header.
Fixes https://github.com/traefik/traefik/issues/9112
=> RedirectScheme redirects based on X-Forwarded-Proto header

pkg/provider/http/http.go
This PR makes the HTTP provider start polling on start up.
Fixes https://github.com/traefik/traefik/issues/9110
Co-authored-by: Jason Quigley <jason@onecha.net>
=> Start polling HTTP provider at the beginning

CHANGELOG.md, script/gcg/traefik-rc-new.toml
Prepare release v2.8.0-rc2
aka `vacherin`
=> Prepare release v2.8.0-rc2

pkg/metrics/datadog.go
Ensures that the Datadog client is cleanly stopped.
To fix a life cycle issue with the Datadog client.
=> Ensure that the Datadog client is cleanly stopped

pkg/provider/consulcatalog/consul_catalog.go
This PR drops the usage of the Catalog API within the Consul Catalog provider and switches to only using the Health API(s).  This is nicely compatible with the Connect endpoints as they live under the same API and output exactly the same types.
The Health API, with the cache query parameter set to `true`, uses the streaming health check system. This means that if streaming is enabled in a Consul cluster, Traefik is now effectively 'free' to run, going so far as an operator can set the refresh interval down to 1 second and likely not notice anything in their Consul cluster.
Even if streaming is disabled, this still cuts the request rate in half, meaning $\approx\frac{1}{2}$ bandwidth usage on top of that which is helpful in really large clusters.
Supersedes #8834
Co-authored-by: Charles …
=> Move consulcatalog provider to only use health apis

script/binary
This PR removes the `-a` option when building the binary.
According to https://pkg.go.dev/cmd/go#hdr-Calling_between_Go_and_C
> The build cache correctly accounts for changes to Go source files,
compilers, compiler options, and so on: cleaning the cache explicitly
should not be necessary in typical use. However, the build cache does
not detect changes to C libraries imported with cgo. If you have made
changes to the C libraries on your system, you will need to clean the
cache explicitly or else use the -a build flag (see 'go help build') to
force rebuilding of packages that depend on the updated C libraries.
Traefik does not use cgo, thus C libraries changes does not impact
Traefik.
<details>
<summary markdown="span">It also improves the binary building time of Traefik by a factor of …
=> Remove `-a` when building binary

docs/content/middlewares/http/redirectscheme.md, pkg/middlewares/forwardedheaders/forwarded_header.go, pkg/middlewares/redirect/redirect_regex.go, pkg/middlewares/redirect/redirect_scheme.go, pkg/middlewares/redirect/redirect_scheme_test.go
This pull request fixes the RedirectScheme middleware to support the forwarded websocket protocol, through the `X-Forwarded-Proto` header. Therefore, the `ws` and `wss` values are converted to the corresponding `http` and `https` values.
Fixes https://github.com/traefik/traefik/issues/9155
=> Support forwarded websocket protocol in RedirectScheme

pkg/tls/certificate_store.go
This PR refactors the `MatchDomain` function used to match certificate domains against the server name from the TLS client hello.
It also adds comments regarding the trailing dots for FQDNs and the TLS SNI extension.
While passing by this code portion it appears that the function could be unexported.
=> Refactor certificate domains matching func

pkg/metrics/prometheus.go, pkg/metrics/prometheus_test.go
This PR force the computation of all the service endpoints.
Old endpoints were not removed when the service came back in the configuration with new endpoints.
This PR fixes #9194 
~- [] Added/updated documentation~
=> Fix service up gauge for Prometheus metrics

docs/content/providers/docker.md, pkg/provider/docker/config.go
This PR adds support for reaching containers using host networking on systems using podman by allowing traefik to correctly detect the podman gateway.
On docker traefik detects the gateway by looking up `host.docker.internal`. Podman doesn't support the `host.docker.internal` domain, but added support for `host.containers.internal` in https://github.com/containers/podman/pull/9972 instead.
Without this PR podman users would have to manually set `host.docker.internal` using add-host/extra_hosts.
I'm using traefik on a server running podman and ran into this issue.
Related to #5730
It would also be possible so solve this using a loop, but because there are only two domains I think that it is more readable without one. Should more domains be needed in the future I would recommend using a …
=> Add support for reaching containers using host networking on Podman

docs/content/routing/providers/consul-catalog.md, docs/content/routing/providers/nomad.md, pkg/provider/consulcatalog/config.go, pkg/provider/consulcatalog/config_test.go, pkg/provider/consulcatalog/consul_catalog.go, pkg/provider/consulcatalog/label.go, pkg/provider/nomad/config.go, pkg/provider/nomad/config_test.go, pkg/provider/nomad/nomad.go, pkg/provider/nomad/nomad_test.go
This PR adds support for [Nomad canary deployment](https://learn.hashicorp.com/tutorials/nomad/job-blue-green-and-canary-deployments#deploy-with-canaries).
When Nomad orchestrator is a provider (of service registration) for Traefik,
one might have the need to distinguish within Traefik between a [Canary](https://learn.hashicorp.com/tutorials/nomad/job-blue-green-and-canary-deployments#deploy-with-canaries) instance of a service, or a production one.
For example if one does not want them to be part of the same load-balancer.
Therefore, this option, which is meant to be provided as one of the values of the `canary_tags` field in the Nomad [service stanza](https://www.nomadproject.io/docs/job-specification/service#canary_tags), allows Traefik to identify that the associated instance is a …
=> Support Nomad canary deployment

integration/testdata/rawdata-ingress-label-selector.json, integration/testdata/rawdata-ingress.json, integration/testdata/rawdata-ingressclass.json, pkg/provider/kubernetes/ingress/kubernetes.go, pkg/provider/kubernetes/ingress/kubernetes_test.go
This PR fixes #9214, placing namespace before name in router key for Kubernetes Ingress. This behaviour is consistent with the naming convention for services and other resources.
Names of routers for `Ingress` and `IngressRoute` are not consistent on dashboard.
=> Place namespace before name in router key for Ingress

pkg/metrics/prometheus.go
This PR makes the `labelNamesValues` type method `With' not mutate the original slice, by doing an explicit copy.
Avoid potential metrics overlapping.
This change needs to be benchmarked.
=> Control allocation and copy of labelNamesValues type

go.mod, go.sum
https://github.com/traefik/paerser/compare/v0.1.6...v0.1.7
The new version returns an error instead of panic when a string is used instead of a slice.
Fixes #9249
=> fix: update paerser to v0.1.7

pkg/provider/marathon/marathon.go
This PR is only refactoring the backoff declaration to add the context shared with the operation.
It will prevent the operation from backing off if the context has been canceled.
To be consistent with what is done in other providers' implementations.
=> Add missing context in backoff for Marathon

docs/content/migration/v2.md, go.mod, go.sum
https://github.com/traefik/paerser/compare/v0.1.7...v0.1.8
**Temporarily** allows an invalid configuration.
I personally disagree with this change.
Fixes #9249
=> Update paeser to v0.1.8

CHANGELOG.md, script/gcg/traefik-bugfix.toml
Prepare release v2.8.3
aka `vacherin`
=> Prepare release v2.8.3

pkg/provider/kubernetes/crd/generated/clientset/versioned/fake/register.go, pkg/provider/kubernetes/crd/generated/clientset/versioned/scheme/register.go, script/codegen.Dockerfile
This PR updates the codegen docker image to use `golang:1.19`. It removes deprecated `go get` in favor of `go install`.
I chose to install all of those binary (`defaulter-gen,client-gen,lister-gen,informer-gen,deepcopy-gen`), to reflect what as been done [here](https://github.com/kubernetes/kubernetes/blob/d5fdf3135e7c99e5f81e67986ae930f6a2ffb047/staging/src/k8s.io/code-generator/generate-groups.sh#L53).
This PR's motivation is to update the codegen infrastructure.
=> Update codegen docker image to golang:1.19

go.mod, go.sum
This PR updates [paerser](https://github.com/traefik/paerser) to [`v0.1.9`](https://github.com/traefik/paerser/releases/tag/v0.1.9).
https://github.com/traefik/paerser/compare/v0.1.8...v0.1.9
This PR fixes #9269.
=> chore: update paerser to v0.1.9

docs/content/routing/services/index.md
It fixes a configuration example which doesn't match documentation.
The `rootCAs` (for `serversTransport`) secret data used the key `tls.crt`, but it must be either `ca.crt` or `tls.ca` according to the docs at https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-serverstransport.
I was wondering if a `cert-manager.io/Certificate` secret could be used to provide the CA. It didn't appear so from the example, since the leaf certificate would be used, but when I looked at the docs, it became clear that it would work as expected.
=> Fix k8s for example for rootCAs serversTransport

pkg/middlewares/retry/retry.go
don't retry on panic
Fixes #9188
Closes #9204
=> fix: don't retry on panic

pkg/provider/docker/docker.go
This PR fixes a memory leak that would occur when the Docker provider operation retries, because old connections were not closed properly.
Fixes #8872
=> Fix Docker provider mem leak on operation retries

cmd/traefik/traefik.go, pkg/plugins/client.go, pkg/server/middleware/middlewares.go
Allow starting Traefik even if plugin services have an issue.
Be able to start Traefik even if plugin services are down.
=> fix: allow starting Traefik even if plugin services have an issue

docs/content/getting-started/quick-start-with-kubernetes.md, docs/content/migration/v2.md, docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml, docs/content/routing/providers/kubernetes-ingress.md
Improve the kubernetes ingress configuration example. RBAC updated so traefik can set the ingress status.
With the documented example I got an rbac error when traefik tried to update the ingress status.
=> Add missing networking apiGroup in Kubernetes RBACs examples and references

docs/content/routing/providers/docker.md
As in [health check](https://doc.traefik.io/traefik/routing/services/#health-check) described the timeout has the unit specified.
This is also already the case for `interval`:
https://github.com/traefik/traefik/blob/32e44816c9445f722fdcd01d9a06bde162a1d57c/docs/content/routing/providers/docker.md?plain=1#L331
Fix the documentation to the health check default
=> doc: add healthcheck timeout seconds to value

docs/content/deprecation/features.md, pkg/server/aggregator_test.go, pkg/server/configurationwatcher_test.go, pkg/tls/tlsmanager.go, pkg/tls/tlsmanager_test.go
Change the default TLS Options for more security while maintaining compatibility with most clients
https://github.com/golang/go/issues/45428
Fixes #6756 
Go will remove support for TLS 1.0 and 1.1 soon, so I think it's better if we prepare in advance by changing the default values and then adding a notice on the deprecations page.
**Plus** lots of complaints about Traefik not being secure enough out of the box, from the TLS perspective.
On this PR I trust that Go will keep an up to date list of secure ciphers during its lifecycle, then the tests with static values will ensure we notice when things change so we don't break compatibility without notice.
=> Change default TLS options for more security

pkg/middlewares/requestdecorator/request_decorator.go, pkg/middlewares/requestdecorator/request_decorator_test.go
Fix the function `parseHost` got different result from the host `[ipv6Address]` and the host `[ipv6Address]:8000`
I have set the entryPoint on the port 80. And a router rule set as `Host(`ipv6address`)`.  
Send a request by curl : `curl http://[ipv6address]/`，I found the `RequestDecorator` parse the host to `[ipv6address]`. 
I try to set the port to 8080, and do `curl http://[ipv6address]:8080/`.  The `RequestDecorator` parse the host to `ipv6address`.
=> fix: IPv6 addr in square brackets

pkg/api/handler_http.go, pkg/api/handler_http_test.go, pkg/api/testdata/router-baz-custom-tls-options.json, pkg/api/testdata/router-baz-default-tls-options.json
This PR allows the Dashboard to properly display the default TLS options set on HTTP routers.
=> Display default TLS options in the dashboard

docs/content/observability/tracing/datadog.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, pkg/tracing/datadog/datadog.go
This PR adds a new `GlobalTags` option for Datadog tracing.
The previous `GlobalTag` option has been deprecated.
=> Add Datadog GlobalTags support

go.mod, go.sum
Update Yaegi to v0.14.2
https://github.com/traefik/yaegi/compare/v0.14.1...v0.14.2
Fix #8682
Related to #8808
=> Update Yaegi to v0.14.2

pkg/tcp/proxy.go, pkg/tcp/proxy_unix.go, pkg/tcp/proxy_windows.go
This PR decreases the log level for some errors in the TCP proxy.
It changes to debug level errors due to the reception of an RST packet during a read operation.
It also quiets completely further errors on connection closing if the socket is already disconnected.
The PR avoids confusion, when one peer is shutting down the connection abruptly with an RST packet, by having the related error logged as debug only.
Fixes #8737
=> Quiet down TCP RST packet error on read operation

Dockerfile, docs/content/providers/ecs.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, pkg/provider/ecs/config.go, pkg/provider/ecs/ecs.go, pkg/redactor/redactor_config_test.go, pkg/redactor/testdata/anonymized-static-config.json
Add support for self-managed on-premise infrastructure with ECS Anywhere.
Extend ECS provider.
Fixes #8795
make validate fails with the following error:
```
docker run -v "/var/run/docker.sock:/var/run/docker.sock"   -e OS_ARCH_ARG -e OS_PLATFORM_ARG -e TESTFLAGS -e VERBOSE -e VERSION -e CODENAME -e TESTDIRS -e CI -e CONTAINER=DOCKER		 -v "/home/jgaspar/Documents/repos/traefik/dist:/go/src/github.com/traefik/traefik/dist" "traefik-dev:feature-ecs-anywhere" ./script/make.sh generate validate-lint validate-misspell validate-vendor
---> Making bundle: generate (in /go/src/github.com/traefik/traefik/script)
---> Making bundle: validate-lint (in /go/src/github.com/traefik/traefik/script)
pkg/provider/ecs/ecs.go:210: Function 'listInstances' is too long (249 > 230) (funlen)
func (p *Provider) …
```
=>  Add support for ECS Anywhere

pkg/plugins/middlewares.go, pkg/server/middleware/plugins.go
Allows using of an empty config for a plugin.
Fixes #9337
=> plugins: allow empty config

docs/content/getting-started/faq.md
This PR adds documentation to the FAQ, about [json schema](https://www.schemastore.org/json/) usage to validate the configuration (static and dynamic).
To give some hints to help with malformed configuration issues.
=> Add documentation for json schema usage to validate config in the FAQ

docs/content/routing/routers/index.md
This pull request adds one example to use with the Path or PathPrefix rule for a case-insensitive backend.
Fix https://github.com/traefik/traefik/issues/4180
=> Add a note on case insensitive regex matching

docs/content/migration/v2.md
fix link to RouteNamespaces
Be able to validate the doc.
=> docs: fix link to RouteNamespaces

docs/content/providers/ecs.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, pkg/provider/ecs/ecs.go
~Allow specification of ECS Services to monitor for tasks to add
when it's unnecessary or undesirable to scan the entire cluster.~
Add checking the health state of a task and require it to have a Healthy status before configuring a route for it
~I deploy Traefik in ECS to handle requests for other services in ECS, however, we don't want Traefik scanning every task in the cluster(s) so I needed a way to tell each Traefik service to only handle the tasks of specific services, yet still maintain the ability to scan every task if none specified.~
Sometimes adding a task to the route before it's healthy according to the ECS health checks is undesirable as there is a possibility that the task is not ready to handle connections and is still having traffic routed to it.
~None~
After more …
=> Add option to keep only healthy ECS tasks

docs/content/reference/dynamic-configuration/docker-labels.yml, docs/content/reference/dynamic-configuration/file.toml, docs/content/reference/dynamic-configuration/file.yaml, docs/content/reference/dynamic-configuration/kv-ref.md, docs/content/reference/dynamic-configuration/marathon-labels.json, docs/content/routing/services/index.md, pkg/config/dynamic/fixtures/sample.toml, pkg/config/dynamic/http_config.go, pkg/config/label/label_test.go, pkg/healthcheck/healthcheck.go, pkg/healthcheck/healthcheck_test.go, pkg/healthcheck/mock_test.go, pkg/provider/kv/kv_test.go, pkg/server/service/service.go
Add gRPC support to healthcheck (using "grpc" scheme in the backend config option). It's based on [GRPC Health Checking Protocol v1](https://pkg.go.dev/google.golang.org/grpc/health/grpc_health_v1)
We need to deploy gRPC apps that will not be immediately ready to serve data (populating caches, ...). This will allow Traefik to not route request to a "unhealthy" container.
See also https://github.com/traefik/traefik/issues/6027
This is probably a naive implementation, any help / comment is welcome !
PS: most changes are related to tests (192+ / 2-)
=> Support gRPC healthcheck

pkg/provider/consulcatalog/config.go, pkg/provider/consulcatalog/config_test.go
Fixes an issue of loadbalancer tags being used in Nomad jobs for Consul Catalog not picking up the port in the Consul Catalog addServerUDP. I used a lot of the addServerTCP code to realize the difference and correct for those differences.
We recently ran into an issue of Traefik not picking up the port for our service written in Nomad using Consul Catalog (https://community.traefik.io/t/traefik-showing-port-0-for-service/15796). The port that Traefik would establish for the service was always 0. I was able to get it working by using a file configuration but that was insufficient for our use case as Nomad was in play.
=> fix: UDP loadbalancer tags not being used with Consul Catalog

pkg/provider/acme/provider.go
=> fix: acme panic

docs/content/observability/metrics/overview.md
Rework the metrics overview page without adding or removing content.
Better readability and ease of use for when you want to scroll or search for the available metrics in one of the supported backends. This is the list of changes:
- The name of the metric should reflect the representation on the backend to avoid confusion. Ex: HTTP Request Total Count -> Requests total (prometheus: `traefik_<entrypoint|router|service>_requests_total`)
- The type of the metric is removed from the name and added into a dedicated column
- Labels are now displayed on a column
- The description of the metric is now displayed in a column
- All backend representations are grouped after the overview table
I always struggled with the layout of this page in particular and I feel this is better for quick lookups and …
=> Rework metrics overview page

pkg/muxer/http/mux.go, pkg/muxer/http/mux_test.go
query parameter with equals
Related to #9368
=> fix: query parameter matching with equal

docs/content/providers/kubernetes-ingress.md
Makes it more clear what the kubernetes-ingress options actually do. like ip and publishedService.
Hackaeton and the long-lasting issue #8406.
Fixes #8406
=> Improve documentation for publishedService and IP options

go.mod, go.sum, integration/helloworld/helloworld.pb.go, pkg/server/server_signals_windows.go
Signed-off-by: Thomas Spear <tspear@conquestcyber.com>
Patches CVE-2022-27664 and run `go mod tidy` and `go fmt`
Found the CVE during vulnerability scans while making a configuration update to our traefik instance
=> Update golang.org/x/net to latest version

docs/content/providers/docker.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, pkg/provider/docker/docker.go
Signed-off-by: Boris HUISGEN <bhuisgen@hbis.fr>
Update docker provider doc.
Small fix about the watch parameter, used too in classic mode (non swarm).
=> Fix watch option description for Docker provider

docs/content/providers/ecs.md
This PR aims to clarify the documentation regarding the relationship between `autoDiscoverClusters` and `clusters` in the ECS provider.
Fix https://github.com/traefik/traefik/issues/9385
Received feedback from @kevinpollet on my initial issue , and was asked to update the documentation -- as this was the intended functionality.
=> Fix autoDiscoverClusters option documentation for ECS provider

cmd/traefik/traefik.go, docs/content/https/tailscale.md, docs/content/reference/static-configuration/cli-ref.md, docs/content/reference/static-configuration/env-ref.md, docs/content/reference/static-configuration/file.toml, docs/content/reference/static-configuration/file.yaml, docs/mkdocs.yml, go.mod, go.sum, pkg/config/static/static_config.go, pkg/provider/tailscale/provider.go, pkg/provider/tailscale/provider_test.go, pkg/tls/certificate.go
This pull request adds Tailscale as a certificate resolver, as publicized in https://tailscale.com/blog/tls-certs/. 
To support Tailscale TLS certificate resolution.
=> Add Tailscale certificate resolver

docs/requirements.txt
Bump PyYAML version from 6.0 to 6.0.1
Be able to build the documentation. 
```
Collecting PyYAML==6.0
Downloading PyYAML-6.0.tar.gz (124 kB)
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
ERROR: Command errored out with exit status 1:
command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpo9nxejup
cwd: /tmp/pip-install-x11rlt3g/pyyaml_868c62dd565a43a3ad6dc27a48136919
Complete output (48 lines):
running egg_info
writing lib/PyYAML.egg-info/PKG-INFO
writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
writing top-level names to …
```
=> chore: fix PyYAML version

docs/content/routing/providers/kubernetes-crd.md
Remove optional `namespace` option of middleware.
Shows that `Middleware` in the same namespace that `IngressRoute` can be used without specifying it.
Just above, the other example show how to specify namespace on middleware when `IngressRoute` is using a different namespace:
=> docs: improve middleware example

docs/content/providers/docker.md, docs/content/routing/providers/docker.md, go.mod, pkg/provider/configuration.go
It improve the situation described in #10258 by:
1. Provides _only_ complete examples in the doc
2. Improve wording in the doc on this matter
3. Improve error message (with the router name when it's possible).
Improve UserXP without breaking change, since many users faced it in the last four years. Detailed in #10258.
This PR aims to improve User XP with the current behavior of Docker provider.
Introducing a new Convention over configuration (aka _magic_) way for configuring Traefik Proxy is not the purpose of this PR.
=> This PR does not supersede #10252. 
Thanks to @joshka and @bluepuma77 who can be credited for my motivation on this PR.
=> Improve error and documentation on the needed link between router and service
